### ISSUE TITLE
Restrict -g matching to certain parts of the read

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#102]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on December 09, 2014 18:21:07_

That is, if the adapter is too far to the right, it isn't removed.

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=92_

**Comment by guilleUTALCA** [comment]
how many nt is considered too far. In my case i have found some adapter about 20 or less nt from the right.

**Comment by marcelm** [comment]
As of now, this is just a suggestion and not implemented. Adapters specified via `-g` can currently occur anywhere. They can even be rightmost in the read (with no base following).

**Comment by guilleUTALCA** [comment]
I did some tests to understand the behavior -b option in critical points, where the contaminant is in the middle of the sequence, in the image uploaded were removed the colored part of the sequence+contaminant(yellow) , but i can not see a cutting pattern in Examples 4 and 5 of the image. If is possible an explanation to this behavior, i would appreciate enormously this contribution.

![screenshot](https://cloud.githubusercontent.com/assets/12203407/7441655/c91339aa-f0c7-11e4-9a1a-c5b511f6af60.png)

**Comment by marcelm** [comment]
Does [the explanation in the documentation](http://cutadapt.readthedocs.org/en/stable/guide.html#or-3-adapters) help? Perhaps [the illustration of the adapter types](http://cutadapt.readthedocs.org/en/stable/guide.html#trimming-reads) is also helpful.

You counted the nucleotides before and after the adapter in your screenshot, but please note that cutadapt does not care about that. Whereever the adapter occurs, the adapter itself and the sequence following it is removed. There is one exception when using `-b`: If the adapter occurs in the beginning of the read (that is, zero nucleotides preceding it), then only the adapter is removed, not the sequences following it.

The `-b` option is usually not what you want. If you had used `-a` instead in your example, you would get the same result - except for case 1, where the read would be empty after trimming.

**Comment by guilleUTALCA** [comment]
Thank you so much,  That was very helpful and sorry for the inconvenience. 
cutadapt is a very useful tool.

**Comment by marcelm** [comment]
Glad I could help!

**Comment by marcelm** [comment]
Forgot to close this.
