### ISSUE TITLE
Add found adapter as comment to output FASTA/FASTQ

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#104]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on December 18, 2014 14:22:45_

may be useful when we are not demultiplexing but still want to know which adapter/primer was found.

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=94_

**Comment by dkoppstein** [comment]
+1, it would be really nice to have the output in the FASTA/FASTQ header, especially if using file:FILE so you know which adapter was trimmed off (if specifying the primer on the command line, you can use --prefix or --suffix). One idea is that you could specify the format; for example --header-format '|PRIMER={id}|' could append that information and substitute id for the found fasta/fastq header in the FILE. 

I'd be happy to help if pointed in the right direction =)

**Comment by marcelm** [comment]
The [documentation](http://cutadapt.readthedocs.org/en/latest/guide.html#modifying-read-names) contains more info.
