### ISSUE TITLE
"Pairs that were too long" in the report

### ISSUE THREAD

**Issue by alexey-larionov** [marcelm/cutadapt#110]
After using cutadapt with --minimum-length (-m) option, the Summary section of the report shows “Pairs that were too long: …” information (supposedly: the number of reads in question).  

It seems that when using cutadapt with --minimum-length (-m) option, the number refers to “Pairs with too short read(s)”.  

This issue does not affect the validity of results, just may be confusing for users reading reports.  Please check.

**Comment by marcelm** [comment]
You are absolutely right. That’s a slightly embarrassing mistake I have now fixed.

Regarding your remark in parentheses: Please tell me if the wording should be changed. I tried to make it concise and therefore omitted "Number of ..." in front of every line. If it gets unclear, I have to re-think.
