### ISSUE TITLE
5' quality filtering doesn't seem to be taken into account for R2 reads

### ISSUE THREAD

**Issue by timflutre** [marcelm/cutadapt#111]
First of all, thanks a lot for providing your software under an open-source license! (Even though I have to admit that I'd have preferred a free-software license such as the GPL.)

I launched Cutadapt v1.8 with `-q 20,20` on paired-end data. Then I launched FastQC on the output files. The R1 reads all have a quality above 20 (in 5' and 3'), but some R2 reads still have a quality below 20 in 5', even though they all have a quality above 20 in 3'. I hope I'm clear...

Edit: I wonder if the problem comes from the fact that, for R2 reads, the very first few bases in 5' have a good quality, but the ones just after have a lower one, and then the quality goes up again, before going down in 3' (see images below).

R1 reads before Cutadapt:
![quality_r1](https://cloud.githubusercontent.com/assets/607508/6705862/2539ff26-cd59-11e4-8e29-c9b21eeb5220.png)

R1 reads after Cutadapt:
![quality_r1_after](https://cloud.githubusercontent.com/assets/607508/6705919/8172379a-cd59-11e4-8500-6964325a1772.png)

R2 reads before Cutadapt:
![quality_r2](https://cloud.githubusercontent.com/assets/607508/6705861/25364566-cd59-11e4-974c-b3148f6508fc.png)

R2 reads after Cutadapt:
![quality_r2_after](https://cloud.githubusercontent.com/assets/607508/6705918/81713c32-cd59-11e4-9789-805ea742fa49.png)

**Comment by marcelm** [comment]
Thanks for the report. Are you using any of the new `-A`/`-B`/`-G`/`-U` paired-end trimming options introduced with cutadapt 1.8? Then it should work as intended.

I believe what you wrote in your edit is correct: The base quality of the first few bases is too good. If you follow the [description of the quality-trimming algorithm](http://cutadapt.readthedocs.org/en/stable/guide.html#quality-trimming), you will see that the algorithm makes a very local decision of where to trim. So if the very first base is already above the quality threshold, the remaining ones won’t even be considered.

Perhaps you could try to "forcefully" remove the first two (or perhaps three) bases from every R2 read by adding `-U 2` to your options. This is done before quality trimming, so the quality trimming algorithm won’t even see the good quality bases.

**Comment by timflutre** [comment]
Yes, I am using `-a ... -A ...` (thanks a lot for this by the way).

Ok, so we have the same interpretation. Indeed, I will use `-U 3`. But maybe, for the future (?), it could be a good idea to have a quality filter working with a sliding window.

**Comment by marcelm** [comment]
Great, thanks for closing. Let’s see whether I can incorporate a better quality trimming algorithm in the future.
