### ISSUE TITLE
Using '--trim-n' with '-p'

### ISSUE THREAD

**Issue by skazakoff** [marcelm/cutadapt#115]
Hi,

I love the recent changes that have been made to cutadapt, especially the interleaved output stream. However, when I use both '--trim-n' and '-p' together, only the N's on the end of R1 are trimmed. Trailing N's on the end of R2 remain in the output stream. Would somebody be able to confirm and/or fix this?

My cmd line:

cutadapt --trim-n -a file:adapters1.fa -A file:adapters2.fa <R1.fastq.gz> <R2.fastq.gz> -p -

**Comment by marcelm** [comment]
Hi, you’re absolutely right, and I can also confirm that this behavior is not intentional.

**Comment by skazakoff** [comment]
Excellent! Thank you!
