### ISSUE TITLE
problem with paired read trimming

### ISSUE THREAD

**Issue by dleopold** [marcelm/cutadapt#117]
I love the updates to cutadapt since I last used it, but I have noticed some strange behaviour when trimming forward and reverse reads at the same time. The call to cutadapt I am using is:

cutadapt -a GCATCGATGAAGAACGCAGC -A TTACTTCCTCTAAATGACCAA -q 20 -e 0.2 -O 8 -m 50 -o R1_trim.fastq -p R2_trim.fastq R1_concat.fastq R2_concat.fastq

The input files have ~4.6million sequences each and only 60% of these are written to the output. It looks like they are mostly being filtered as too long (Pairs that were too long: 1,832,388 (39.8%)), which is strange because I did not set a max length. If I run cutadapt individually on the forward and reverse reads I end up with ~98% of the reads passing through into the output for both. Seems like there is something odd going on with the way both files are handled at the same time. Unless I am missing something...

**Comment by marcelm** [comment]
Hi, sorry for the misleading message: The text for too short and too long reads is actually swapped in version 1.8. I’ve fixed it for the next release. I’m not sure why you get 60% when trimming pairs, but 98% when trimming individual files. Note that a pair is discarded when *any* of the two reads are too short. So in the worst case, you can have 98% filtered in one file, 98% in the other, but 96% when filtering in paired-end mode. You won’t get down to 60%, however. Are you using identical options when trimming individually? If you cannot figure it out, it would be helpful if you could post the exact command line for the individual trimming runs and the log output.

**Comment by marcelm** [comment]
Probably fixed, closing.
