### ISSUE TITLE
Paired End Demultiplexing

### ISSUE THREAD

**Issue by davmlaw** [marcelm/cutadapt#118]
This is not currently supported, and displays "Demultiplexing not supported for paired-end files, yet."

I started writing this feature, but I think it's not obvious how it should work - so perhaps we can spec out a design, so it can be implemented properly?

Here is a command line I'd like to work:

`cutadapt -b file:barcodes.fasta -o trimmed-{name}_R1.fastq.gz --paired-output trimmed-{name}_R2.fastq.gz ${READ1} ${READ2}`

So, if you specify {name} in R1 (demultiplexing), you need it in paired-output as well. (otherwise error?)

The easy case is if you are demultiplexing on only 1 end - then you just use the same {name} for both outputs.

If you specify different barcodes for read 1 and read 2 (ie -b foo=GATC -A foo=GATC) complicated things can happen. If both are specified and both match, it makes sense to write them out with that name. If they don't agree - what do you do?

**Comment by marcelm** [comment]
I assume this is the same as issue #113? If so, then I’m working on that right now.

**Comment by davmlaw** [comment]
Sorry I pressed enter too early and it submitted, I'm writing up a proper issue now.

**Comment by marcelm** [comment]
I think cutadapt should always write out correctly paired data (the two files should be in sync). From that it follows that `{name}` would need to be in both file name patterns, as you said. Then the other issue is what to do when adapters for the first and also for the second read are given. I think the only solution that makes sense to me now is to have the `{name}` always refer to the set of adapters that are removed from the first read. That is, even if you provide `-A foo=ACGT`, the name would be ignored.

I haven’t had a use case for paired-end demultiplexing myself, so I think the most important question is to ask what is useful for a user.

If you are interested in implementing this, you could also ignore the issues arising when a second set of adapters is given. Cutadapt has two paired-end trimming modes. For backwards compatibility, a "legacy" mode is enabled when none of the uppercase adapter options are given (`-A`/`-B` etc). With the command you give above, cutadapt runs in legacy mode (which mainly means that the second read is ignored for length filtering and is unaffected by quality trimming). It seems it would be sufficient for you if demultiplexing worked in legacy mode.

**Comment by jrderuiter** [comment]
Any news on this?

**Comment by marcelm** [comment]
It seems @davmlaw did not pursue this further, but I can give it a try this week.

**Comment by marcelm** [comment]
This is now implemented. Please see [the updated section in the documentation](https://cutadapt.readthedocs.io/en/latest/guide.html#demultiplexing).

**Comment by jrderuiter** [comment]
This is great, thanks!
