### ISSUE TITLE
cutadpt for PacBio CCS reads?

### ISSUE THREAD

**Issue by pengchy** [marcelm/cutadapt#120]
Hi martin,
For PacBio CCS sequence, there exists several categories concatemers related adaptor and primers, as explained in cDNA_primer wiki: 
https://github.com/PacificBiosciences/cDNA_primer/wiki/Artificial-concatemers%2C-PCR-chimeras%2C-and-fusion-genes.

This concatemers can be detected by:
1. using "-b" parameter of cutadapt, then deal with the "--info-file="
2. run cutadapt two times iteratively.

Because the PacBio become more and more popular, the need will grow or a specific tool should be developed.

Best,
pengcheng

**Comment by marcelm** [comment]
Sorry, forgot about this. Is this still relevant?
