### ISSUE TITLE
shorter read name in error message makes difficult to spot the wrong line

### ISSUE THREAD

**Issue by lpantano** [marcelm/cutadapt#123]
Hi,

I had a problem with a fastq file that had some weird characters `^@` in the middle of the quality values (amazed)

`cutadapt` gives the short version of the read name: https://github.com/marcelm/cutadapt/blob/e16ba3f9b2843102da0b887dfb0b7b5fa65da82b/cutadapt/seqio.py#L38 which is not useful because all reads start with that. Do you think that it would be good to use 100 instead of 20 for that function?, so It gives you exactly the read that fails.

thanks so much!

**Comment by marcelm** [comment]
Good point! I’ve changed the default length to 100. I cannot remove the shortening entirely since some weirdly/incorrectly formatted files could fill up the screen otherwise. Thanks for the suggestion!
