### ISSUE TITLE
Empty read in output although only partially matches an adapter

### ISSUE THREAD

**Issue by kmavrommatis** [marcelm/cutadapt#127]
Hi,

I run cutadapt v 1.8.1 on PE reads
**cutadapt-1.8.1/bin/cutadapt --format=fastq -o cutadapt.1.fq -p cutadapt.2.fq -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT --info-file info.txt read.1.fq read.2.fq**

I get an empty read in the output file for the 1st mate read.
However, checking the info file it shows that the read has a match to the adapter in its first 33 bases so I would expect that the remaining of the read appears in the output file:

**Info.txt**
HWI-ST1382:217:HCMKMADXX:1:1101:10705:3339 1:N:0:GATCAG 1       0       33              GATCGGAAGAGCACACGTCTGAACTCCAGTCAC       GATCAGATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAATTACACGTAGTAGCTGCCGTTGCCGTT     1

**Input files:**

**read.1.fq**
@HWI-ST1382:217:HCMKMADXX:1:1101:10705:3339 1:N:0:GATCAG
GATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAATTACACGTAGTAGCTGCCGTTGCCGTT
+
@@@BDDFDAHFDFIIGIFGHIIEHGH@GH?DDFBGHEAEB?;@DFGHGDGGEG@EG@DAEEEE=?###################################

**read.2.fq**
@HWI-ST1382:217:HCMKMADXX:1:1101:10705:3339 2:N:0:GATCAG
GACCGGAAGAGCGGCCCGTCGGGGAAAAGGGGAGGTGTCGGGGGGGGCCCGATCTTTAAAAAAAAAAAAAAGTCGGTCGAAGCCGACGGGGACGGACGCT
+
####################################################################################################

**Output files
**cutadapt.1.fq
@HWI-ST1382:217:HCMKMADXX:1:1101:10705:3339 1:N:0:GATCAG
__NOTE THIS IS AN EMPTY LINE__
+
__NOTE THIS IS AN EMPTY LINE__
**cutadapt.2.fq
@HWI-ST1382:217:HCMKMADXX:1:1101:10705:3339 2:N:0:GATCAG
GACCGGAAGAGCGGCCCGTCGGGGAAAAGGGGAGGTGTCGGGGGGGGCCCGATCTTTAAAAAAAAAAAAAAGTCGGTCGAAGCCGACGGGGACGGACGCT
+
####################################################################################################

Any help/insight would be greatly appreciated
Thanks in advance for your help

**Comment by marcelm** [comment]
If you use the `-a` parameter, the specified adapter is assumed to be a 3' adapter, and everything that follows it is removed from the read. It does not matter where the adapter occurs in the read: If it appears in the beginning, as in your case, the read will be empty after trimming. See also the [section in the documentation](http://cutadapt.readthedocs.org/en/stable/guide.html#adapters) (last paragraph) and the description of `-a` when you run `cutadapt --help`.

Note that this is probably the correct behavior here: You seem to have an adapter dimer (a 5' adapter connected to a 3' adapter) in that read. The sequence following the 3' adapter is likely just random noise.

**Comment by kmavrommatis** [comment]
Thanks, 
I should have read the documentation more closely :(

**Comment by marcelm** [comment]
No problem, I’m always happy if reported bugs turn out not to be bugs at all :-).
