### ISSUE TITLE
cutadapt in paired-end did not trim the sequence

### ISSUE THREAD

**Issue by AdrienneTin** [marcelm/cutadapt#130]
When I ran cutadapt in paired-end mode with this command:
--overlap=10 -e 0.1 --minimum-length 1 -G GATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG 
-o file1_out.bz2  -p file2_out.bz2 file1.bz2  file2.bz2

cutadapt did not trim any sequence in read 1
Total read pairs processed:           42927459
  Read 1 with adapter:                       0 (0.0%)
  Read 2 with adapter:                    9697 (0.0%)
Pairs that were too short:                   0 (0.0%)
Pairs written (passing filters):      42927459 (100.0%)

When I use single end mode:
 --overlap=10 -e 0.1 --minimum-length 1 -g GATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG 
-o file1_out.bz2 file1.bz2
cutadapt trimmed many:
Total reads processed:                42927459
Reads with adapters:                    119230 (0.3%)
Reads that were too short:                 941 (0.0%)
Reads written (passing filters):      42926518 (100.0%)

Was my paired-end mode command specified correctly?

Thanks

**Comment by marcelm** [comment]
In the first command line you give, the `-G` option specifies the adapter to remove from the second read. No adapters are searched for in the first read (and therefore not removed). In the second command line, you use `-g` and remove adapters from the first read only.

It looks like you are removing a TruSeq adapter. If that is the case, are you sure that you want to remove it from the 5' end of your reads? (That is what the `-g` and `-G` options do.) Typically, you would want to remove TruSeq adapters from the 3' end of each read. Perhaps have a look at the [section in the documentation about Illumina TruSeq](http://cutadapt.readthedocs.org/en/stable/guide.html#illumina-truseq). Get back to me if you have more questions!

**Comment by marcelm** [comment]
No reply, so closing.
