### ISSUE TITLE
Cutadapt doesn't print out trimming metrics for R2 arguments 

### ISSUE THREAD

**Issue by gpratt** [marcelm/cutadapt#133]
Not much else to say, I'll try to figure out how to fix it if you don't get to it first.

**Comment by marcelm** [comment]
Not sure what you mean ... perhaps slightly more detail would be good (I believe it does print out those metrics).

**Comment by gpratt** [comment]
Sorry, I was working on an out of date dev version and some stuff was broken.  I updated to master and everything appears to be working fine.  

Thanks for making such a great piece of software!

**Comment by marcelm** [comment]
Yeah :-)
