### ISSUE TITLE
cutadapt in paired-end quality trimming option did not trim the read 2

### ISSUE THREAD

**Issue by FrankLee-1987** [marcelm/cutadapt#134]
Dear Marcel Martin,

I would like to 
bin/cutadapt -q 25,25 -o S00298E_r1_trimmed.fastq -p S00298E_r2_trimmed.fastq S00298E_r1.fastq S00298E_r2.fastq

![cutadapt screenshot scenario 1](https://cloud.githubusercontent.com/assets/11964645/8504376/84d59136-219e-11e5-9b8d-473136cc8a13.png)

Why the read 2 shows as 0 bp.

**Comment by marcelm** [comment]
If you want to trim adapters, then you have to specify which adapter sequence you would like to remove. Cutadapt does not detect that automatically. The call to cutadapt you ran only did quality trimming, but did not remove any adapters.

If Illumina TruSeq adapters were used, you can [read the TruSeq section in the documentation](http://cutadapt.readthedocs.org/en/stable/guide.html#illumina-truseq).

**Comment by PEHGP** [comment]
Modify first read only, keep second in sync (-p given, but not -A/-G/-B/-U).
This exists for backwards compatibility ('legacy mode').
Full paired-end trimming when both -p and -A/-G/-B/-U given.
Also the read modifications (such as quality trimming) are applied to second read.

**Comment by marcelm** [comment]
Closing, feel free to re-open if my answer didn’t help.

**Comment by RCWilliams** [comment]
I'm running cut adapt on paired end reads, but I cannot get -u to apply to read 2. It remains full length. Please can anybody offer any help? Am I missing something obvious?

**Comment by marcelm** [comment]
Hi, could you please open a new issue? When you do, post also your command line, please.
