### ISSUE TITLE
unexpected results when cut 5' and 3' adaptors simultaneously

### ISSUE THREAD

**Issue by mt1022** [marcelm/cutadapt#140]
the fastq file is:
```
cat tmp.txt 
@D2SV54V1:272:HFJTWADXX:1:1203:2161:94514 1:N:0:ACAGTG
TCTACAGTCCGACGATCATCCAACCGAATTTGGCTCGGCTGGAATTCTCGG
+
@@CFDDFDHDHDFFHHIGGIEHHGIDGGIHIJJGIEGBEEGI@CECC=AHD
```

when I cut 3' and 5' adaptor using following command:
```
cat tmp.txt | cutadapt -m 18 -a TGGAATTCTCGGGTGCCAAGG -g GTTCAGAGTTCTACAGTCCGACGATC -
This is cutadapt 1.8 with Python 2.7.6
Command line parameters: -m 18 -a TGGAATTCTCGGGTGCCAAGG -g GTTCAGAGTTCTACAGTCCGACGATC -
Trimming 2 adapter(s) with at most 10.0% errors in single-end mode ...
@D2SV54V1:272:HFJTWADXX:1:1203:2161:94514 1:N:0:ACAGTG
ATCCAACCGAATTTGGCTCGGCTGGAATTCTCGG
+
GGIEHHGIDGGIHIJJGIEGBEEGI@CECC=AHD
Finished in 0.10 s (100000 us/read; 0.00 M reads/minute).

=== Summary ===

Total reads processed:                       1
Reads with adapters:                         1 (100.0%)
Reads that were too long:                    0 (0.0%)
Reads written (passing filters):             1 (100.0%)

Total basepairs processed:            51 bp
Total written (filtered):             34 bp (66.7%)

=== Adapter 1 ===

Sequence: TGGAATTCTCGGGTGCCAAGG; Type: regular 3'; Length: 21; Trimmed: 0 times.

=== Adapter 2 ===

Sequence: GTTCAGAGTTCTACAGTCCGACGATC; Type: regular 5'; Length: 26; Trimmed: 1 times.

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20-26 bp: 2

Overview of removed sequences
length	count	expect	max.err	error counts
17	1	0.0	1	1

```
the 3' adaptor is not removed as you can see.  When I cut only 3' or 5' adaptor, It worked correctly. Why this happens?

**Comment by marcelm** [comment]
Cutadapt trims only one of the given adapters from each read by default. If you want to remove more than one adapter, use the option `--times`, such as `--times=2`. See also the [section in the documentation](http://cutadapt.readthedocs.org/en/stable/guide.html#trimming-more-than-one-adapter-from-each-read).

**Comment by mt1022** [comment]
Thanks for your answer.

I compare the follow two ways:
a. trim 3' and 5' adaptor simultaneously with `-n 2` following your suggestion:
```
zcat $fq | cutadapt -m 18 -n 2 -a TGGAATTCTCGGGTGCCAAGG -g GTTCAGAGTTCTACAGTCCGACGATC - 2>$outdir/${prefix}-trim.log >$outdir/${prefix}-trim.fq
```
b. cut 3' adaptor first then cut 5' adaptor:
```
zcat $fq | cutadapt -m 18 -a TGGAATTCTCGGGTGCCAAGG - 2>$outdir/${prefix}-trim3p.log | cutadapt -m 18 -g GTTCAGAGTTCTACAGTCCGACGATC - 2>$outdir/${prefix}-trim5p.log >$outdir/${prefix}-trim.fq
```

when I process a fastq file with the above two methods, the final trimmed fastq files have different number of lines:
`31459376` for a, `31708012` for b

what do you think is possible reason?

**Comment by marcelm** [comment]
These two variants of trimming a 5' and 3' adapter are not exactly equivalent. Using the `-n 2` option tells cutadapt that it may remove up to two adapters from each read, but it is possible that it will remove one of the adapters twice. I’ve been planning a while to add support for 'linked adapters' which would solve this specific use case.

Note also that you should [very likely use an *anchored 5' adapter*](http://cutadapt.readthedocs.org/en/stable/guide.html#five-prime-adapters) by prefixing the 5' adapter sequence with the `^` character: `-g ^GTTCAGAGTTCTACAGTCCGACGATC`. If you do that, I assume the numbers above will be less different from each other.

If you want to, run the two commands above again, but without the `-m 18` option and send me the output of `diff -u trimmedfile1.fastq trimmedfile2.fastq | head -n 100`.

Also note that cutadapt supports gzipped input, no need to run zcat yourself.

**Comment by mt1022** [comment]
Hi,

I ran the two commands without `-m 18` and got two fastq files with same numbers of lines, but there are still differences between the two output files.

the results of
```
diff -u trimmedfile1.fastq trimmedfile2.fastq | head -n 100
```
can be downloaded from https://github.com/mt1022/tmp/blob/master/head_diff.txt

**Comment by marcelm** [comment]
Please use unified diff (`diff -u`).

**Comment by mt1022** [comment]
sorry about that. I have updated the file.

**Comment by marcelm** [comment]
Sorry for the late reply. Looking at the diff, one can see that the extra sequence that you get in the second file is `TGGAAT`, which is the beginning of your 3' adapter sequence. I would guess that these are the cases where the 3' adapter was removed twice in the version using `--times=2`. I’m not quite sure what the correct way to deal with this would be. Either those `TGGAAT` ends are contamination or random matches. I would guess that it does not matter that much in practice which of the two commands you mentioned you use. In the future, having an option of explicitly working with linked adapters would be best (which I already mentioned above). Please watch issue #44 for updates if you want to be notified if this gets implemented.
