### ISSUE TITLE
Could cutadapt write the rest file in fastq file format?

### ISSUE THREAD

**Issue by kepbod** [marcelm/cutadapt#143]
The rest file now only contains read name and sequence information with omitting quality information. Could cutadapt write the rest file in fastq file format? Thanks very much!

**Comment by marcelm** [comment]
I’m planning to add quality information as additional columns to the [`--info-file` format](http://cutadapt.readthedocs.org/en/stable/guide.html#format-of-the-info-file). Would that be sufficient? That solution would require a one-line awk script to turn the info file into a FASTQ file.

**Comment by kepbod** [comment]
It's excellent! Thanks!

**Comment by marcelm** [comment]
Tracking this in issue #144.
