### ISSUE TITLE
Installation issues: "ERROR: Cython is not installed."

### ISSUE THREAD

**Issue by robsyme** [marcelm/cutadapt#145]
I'm trying to install cutadapt in an environment where pip is not available. I have the dependencies listed [in the documentation](https://cutadapt.readthedocs.org/en/stable/installation.html#dependencies):

```
> python --version
Python 2.7.6
> gcc --version
gcc (GCC) 4.9.0 20140422 (Cray, Inc.)
...
```
But the installation step suggests that I also need Cython:
```
> wget https://github.com/marcelm/cutadapt/archive/v1.8.3.tar.gz
> tar -xvf *.tar.gz
> cd cutadapt-1.8.3
> python setup.py install --user
At least one C source file is missing or out of date
ERROR: Cython is not installed. Install at least Cython version 0.17
```

Is Cython a dependency, or am I doing something wrong?

**Comment by marcelm** [comment]
The package that can be downloaded from Github is a developer version that does not contain all necessary files. The "official" package is [the one available on PyPI](https://pypi.python.org/pypi/cutadapt/). If you use that one, the C files that Cython generates are already included.

**Comment by robsyme** [comment]
Aha. That makes sense. Sorry for my confusion.
