### ISSUE TITLE
discard-untrimmed broken with paired-end reads

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#146]
This was reported by @akshayparopkari in issue #126. When exactly one of the two reads is trimmed, the entire pair should be discarded, but is kept instead.

**Comment by marcelm** [comment]
This is fixed in master now.

**Comment by akshayparopkari** [comment]
Hi Marcel,

Thank you for replying back so soon. I appreciate your help!

I was wondering, it could be beneficial to keep reads with either adapter 1 or adapter 2 but not both. In essence, we are throwing away data, and perhaps, someone might need this mismatched data for downstream analysis. You may provide an optional parameter for either keeping or discarding mismatched trimmed pair end reads.
