### ISSUE TITLE
quality trimming on paired-end data

### ISSUE THREAD

**Issue by nicolasnzt** [marcelm/cutadapt#147]
Hi,
When I performed quality trimming without adapter trimming on paired-end data, cutadapt doesn't trim read 2.
Can you help me to solve this issue?
Thanks

cutadapt --minimum-length=50 --quality-cutoff=10 -o S1_cleaned.R1.fq.gz -p S1_cleaned.R2.fq.gz S1.R1.fq.gz S1.R2.fq.gz

=== Summary ===

Total read pairs processed:          1,193,862
  Read 1 with adapter:                       0 (0.0%)
  Read 2 with adapter:                       0 (0.0%)
Pairs that were too short:                   6 (0.0%)
Pairs written (passing filters):     1,193,856 (100.0%)

Total basepairs processed:   693,231,732 bp
  Read 1:   345,631,127 bp
  Read 2:   347,600,605 bp
Quality-trimmed:                 553,756 bp (0.1%)
  Read 1:       553,756 bp
  Read 2:             0 bp
Total written (filtered):    692,677,524 bp (99.9%)
  Read 1:   345,077,180 bp
  Read 2:   347,600,344 bp

**Comment by marcelm** [comment]
That’s (unfortunately) intended behavior required for backwards compatibility with older versions. When the ability to work with paired-end data was first added, cutadapt would need to be run twice, and it would modify the first read in the first round and the second read in the second round. Cutadapt only switches to the new behavior where it modifies both reads when you use any of the uppercase switches `-A`/`-B`/`-G`/`-U`. The most recent version from Git will print a warning to make this more clear.

To work around the issue, add the `-A` option with a dummy adapter sequence, such as `-A XXX`.

Please don’t close the report as I would like to have it here as a reminder that I need to solve this some other way, perhaps by adding an uppercase `-Q` option.

**Comment by nicolasnzt** [comment]
Thank for your response.
I run successfully cutadapt using a dummy adapter sequence (-A XXX).
