### ISSUE TITLE
multi-threading speedups

### ISSUE THREAD

**Issue by avilella** [marcelm/cutadapt#148]
I was wondering any efforts are being consider to speed-up cutadapt
for large fastq.gz files? 

Would multithreading at the level of reading/writing the compressed
fastq files speed things up? Maybe externally calling a tools like
http://zlib.net/pigz/ and pipe the results back into cutadapt?

Another more mapreduce-style approach for a machine with N cores would
be to first divide big fastq.gz files into N chunks, run the cutadapt
trimming on each of them, then merge the resulting files back.

**Comment by marcelm** [comment]
Hi, my reply to your mail which you sent earlier with a similar question overlapped with this issue. I’m copying the relevant parts of my reply below.

> I’ve done some timings and at least on my test data, if you trim a single adapter only, then cutadapt trims reads about as fast as gzip can compress and write them to the output file. Even if trimming were faster, gzip would be the bottleneck (for this use case).
>
> I did try to make the tool use multiple CPUs some time ago. However, it turns out that the methods I tried (multithreading, multiprocessing) require too much overhead and running in parallel was actually slower than in serial. It should be better when doing more complicated things, such as trimming multiple adapters or doing additional filtering. I recently came across an idea of how some of the overhead could be avoided, so I may give it another try.
>
> Note that you get some parallelization for free when you read from or write to compressed FASTQ files since this is done in a separate gzip process.

Because you also mention pigz, I’d like to add that you’re right that using pigz would shift the bottleneck to cutadapt again. That is also one of the reasons I haven’t given up on finding a solution.

**Comment by avilella** [comment]
cp+paste from email:

> Thanks, I think having a wrapper like this is the way to go. I’ll see what I can do with it. I would like to also have an aggregate report in the end, which is probably the most difficult part.

Yes, at the moment an external mapreduce approach produces separate summary reports for
each separate cutadapt execution, so having this approach integrated into cutadapt would be great.

**Comment by Chris7** [comment]
I have actually implemented a multi-threaded cutadapt here:

https://github.com/BarasLab/miRge/blob/master/trim_file.py

It is significantly faster, but I don't know enough about all the internals of cutadapt to implement it everywhere other than the specific use case I had.

**Comment by marcelm** [comment]
Thanks! I guess I should implement something like this in cutadapt itself. As I wrote above, in my experiments so far I’ve tried to speed up the case where a single adapter is being removed, but there’s just to much overhead. I realize now that many people are actually using cutadapt with more complicated processing pipelines, in which case it does become faster.

**Comment by avilella** [comment]
Is @Chris7 's code something that could be included into cutadapt's main branch? This is, using python multiprocessing module within each read or read pair of the looping over the input files?

**Comment by marcelm** [comment]
Yes, something like this could be integrated. The code isn’t usable as a patch for cutadapt, but it should be possible to re-use some parts of it.

**Comment by Chris7** [comment]
It should be possible to move all cutadapt's code that decides what and how to trim to the Worker class and likewise all the writing bits to the Writer class. Because we're not going to get any better with I/O, the main thread can still handle the reading/queue population.

**Comment by marcelm** [comment]
It’s been quite a long time since this issue was opened, and the idea to make cutadapt use multiple cores is even older, so I’m happy to report that cutadapt now supports parallel execution when running under Python 3.

It’s currently limited to the case when there is just a single input and a single output file, but all the necessary refactoring is done, so it’ll be straightforward to make this work for paired-end data (and other cases with multiple output files such as `--too-short-output`). I’ll do so before the next release.

The original comment contained the suggestion to use `pigz` (parallel gzip). I actually implemented this some time ago without mentioning it here, so this is actually done.

Thanks to all for the suggestions, and in particular code (although I ended up implementing everything myself in the end)!

**Comment by avilella** [comment]
This sounds great. I am going to test in on my end and report back under
our conditions.

Is this in master branch or one of the releases?

**Comment by marcelm** [comment]
Thanks, it definitely needs testing. It’s in the master branch at the moment. I hope to get it working on paired-end data within the next week or so, in case you need that.

**Comment by sk-bioinfo** [comment]
Hi Marcel,
I ran an earlier version of cutadapt (1.14) and the latest build with the multithreading on a single end fastq with ~25M reads. The former took 30 minutes to run on one thread and the latter took 3 minutes running 8 threads. The trimmed fastq files from both versions were identical and so were the stdouts.
Great job! Many thanks!
Waiting for the paired-end support and the release.
SK

**Comment by marcelm** [comment]
Wow, that is impressive, sounds like I did something right :-). I’m developing this on a two-core machine and have run only a couple of tests on bigger ones, so it’s great to know that it scales up so well!

**Comment by sk-bioinfo** [comment]
Hi Marcel,
I also ran a Hiseq dataset (~550M reads) single end file through. The zipped file (.gz) took 18 hrs to run, so I unzipped it and that completed in 1.5 hrs (which is great). Does pigz have to be installed for seeing the same speed in the zipped version?
Thanks for the improvements.
SK

**Comment by marcelm** [comment]
I am fixing this at the moment. There are two problems coming together: In Python 3, cutadapt does not use `pigz`, but the normal Python compression library, and that library has the default compression level set to 9, which is really slow (gzip/pigz have 6 as the default).

**Comment by marcelm** [comment]
This should be mostly fixed now. You need to update the `xopen` library to get the improvements. The easiest way to upgrade would probably be to just re-install the developer version.

**Comment by marcelm** [comment]
Paired-end support should also work now. See progress in issue #270.

**Comment by marcelm** [comment]
And finally, this can be closed! [Cutadapt 1.15 is now released](https://twitter.com/marcelm_/status/933688295749570560). Thanks again for feedback and tips.
