### ISSUE TITLE
bugreport

### ISSUE THREAD

**Issue by catkira** [marcelm/cutadapt#151]
Hi,

when I do the following command:

cutadapt -a AGATCGGAAGAGCACA -n 2 -e 0.2 -O 4 -o out.fastq ../in.fastq

the sequence GCCTCGCACTCCCACTAGCTGGGGAATGGGTATCTGATAGTC becomes trimmed to
                        GCCTCGCACTCCCACTAGCTGGGGAATGGGTATCTGAT

This shoud not happen, because I allowed only 1 mismatch, but there are 2. Am I right?

**Comment by catkira** [comment]
No. of allowed errors:
0-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-16 bp: 3

Bases preceding removed adapters:
  A: 22.9%
  C: 15.8%
  G: 20.8%
  T: 17.8%
  none/other: 22.6%

Overview of removed sequences
length	count	expect	max.err	error counts
4	19296	3372.9	0	12570 6726
5	22133	843.2	1	9633 12500
6	13701	210.8	1	9122 4579
7	10387	52.7	1	9092 1295
8	10420	13.2	1	9316 472 632
9	9734	3.3	1	8504 375 855
10	10759	0.8	2	9732 190 837
11	8318	0.2	2	7740 245 333
12	8356	0.1	2	8015 167 161 13
13	7821	0.0	2	7517 219 54 31
14	7432	0.0	2	7096 205 91 40

**Comment by marcelm** [comment]
Cutadapt allows insertions and deletions when matching adapters. The overlap alignment between read and adapter looks like this:
```
GCCTCGCACTCCCACTAGCTGGGGAATGGGTATCTGATAG-TC
                                      AGATCGGAAGAGCACA
```
Which has only one error (a deletion). The error rate of 0.2 is relative to the number of bases of the adapter that were used in the alignment. In this case, five bases are used, so 0.2*5 = 1 error is allowed.

If you don’t want to allow indels, use the `--no-indels` option.
