### ISSUE TITLE
Inconsistent -- error: at line 1, expected a line starting with '@'

### ISSUE THREAD

**Issue by doliv071** [marcelm/cutadapt#155]
Hi, I've had this error with both 1.8.2 and 1.9.dev6 (I upgraded when I started getting this error). The problem is that out of ~100 files some 25ish give the error listed in the title while the rest work fine. They are all processed identically prior to cutadapt input. Below is the error and the head of one of the files with the error. I've checked multiple files and they all look fine and I cannot tell the difference between files that work and those that don't. 

This is cutadapt 1.9.dev6 with Python 2.7.10
Command line parameters: -g TTTGGCAATGGTAGAACTCA -o ~/OutDir/miR_182_5p.fastq ~/miR_182_5p.fastq
Trimming 1 adapter with at most 10.0% errors in single-end mode ...
cutadapt: error: at line 1, expected a line starting with '@'

$ head ~/miR_182_5p.fastq
@HWI-M02584R:43:000000000-AG02Y:1:1102:23933:12068 2:N:0:GCCAAT
TGAGTTCTACCATTGCCAAAGGTCGTCGGACTGTAGAACTCTGAACGTGTA
+
CCCCCGGGGGGGGGGGGGGGGGGGGG8FGGGGGGGGFGGGGGGGGGGGGGF
@HWI-M02584R:43:000000000-AG02Y:1:1104:15406:11714 2:N:0:GCCAAT
TGAGTTCTACCATTGCCAAAGATCGTCGGACTGTAGAACTCTGAACGTGTA
+
CCCCCGGGGGGGGGGGGGCFGGGGGEEEGGEGGGGGGGGGGGGAFFGFGGC
@HWI-M02584R:43:000000000-AG02Y:1:1107:5166:19184 2:N:0:GCCAAT
TGAGTTCTACCATTGCCAAAGATCGTCGGACTGTAGAACTCTGAACGTGTA

Thanks for the help,
-Dave

**Comment by doliv071** [comment]
As usual, once I wrote up the problem I saw the error. It appears that some of my reads are not read 1 in the pair and this is what is causing cutadapt to spit out the error above. I check and all files that were successfully processed were read 1 in pair and the error files were read 2 (although file names somehow don't reflect that...not a cutadapt problem obviously). 

If it's possible to have a more meaningful error report for this particular situation, that would be helpful otherwise, feel free to close this issue.

thanks,
-Dave

**Comment by marcelm** [comment]
Hi, I’d like to improve the error reporting here, but I’m not sure I understand the problem exactly. You are using cutadapt in single-end trimming mode where it doesn’t care whether the reads are paired or not (and it doesn’t care about the file names anyway). The message is written only when the very first character in the input FASTQ file is not an `@` symbol. You could try to run `hexdump -C ~/miR_182_5p.fastq|head` to see if there are any strange characters in there. If you find out what it is, I would be interested.

I have also just changed cutadapt to print out what it sees. The error message will now look like this:
```
cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but found '\x1f\x8b\x08\x00;5,U\x00\x03'
```

**Comment by doliv071** [comment]
What I think caused the error was that the header line showed that the file contained the second in pair reads (I should have just done paired end mode but only needed to trim from the first read and got lazy).

For read 1 file you get...
@HWI-M02584R:43:000000000-AG02Y:1:1107:5166:19184 1:N:0:GCCAAT
_________________________________________________^___________
For read 2 file you get...
@HWI-M02584R:43:000000000-AG02Y:1:1107:5166:19184 2:N:0:GCCAAT
_________________________________________________^___________

So when I tried single end trimming on the second read file, cutadapt (rightly) spit out an error. 

Thanks again,
Dave

**Comment by marcelm** [comment]
Hm, cutadapt doesn’t actually check that digit ... anyhow, I’m closing this now since the next time the error occurs, the error message will be more helpful. Thanks for reporting!
