### ISSUE TITLE
where does read 2 go for too-short-output?

### ISSUE THREAD

**Issue by john-calley** [marcelm/cutadapt#156]
I'm trimming paired-end reads and using --too-shortoutput. The result file does contain all the read 1 content when ever either read 1 or read 2 was removed as too short but I can't find the read 2 content nor any way to specify where to put it. Am I missing something? I am using cut adapt 1.8.1 but I didn't see anything about this in the change log.

ThankS!

John

**Comment by marcelm** [comment]
No mistake on your part, the appropriate option was simply not implemented, yet.

I have now added the options `--too-short-paired-output` and `--too-long-paired-output`. If you are still interested, I’d be happy if you could test it. Do you know how to get the most recent version from the Git repository?

**Comment by john-calley** [comment]
I have tested this and it works fine. Thanks for the prompt response!

John

**Comment by marcelm** [comment]
Great! I’ve also just released cutadapt 1.9.1 with the changes.
