### ISSUE TITLE
cutadapt with gnu parallel - output issues

### ISSUE THREAD

**Issue by multicode** [marcelm/cutadapt#157]
Hi, 

When I try to parallelize cutadapt using gnu parallel, I face a problem where the cutadapt finishes successfully, but the `*_matched.fq.gz` files that are produced, are only a few kilobytes (~80kb). But if I don't run parallel cutadapt operations in the same folder, I get the `*_matched.fq.gz` files in Megabytes (~300MB). I suspect that it has something to do with the temporary file storage and processing.

Could you please clarify on this topic ? Thanks!

Here is the script that I've used to parallelize my cutadapt code for multiple files.

```bash
ls -1 *_F3.fq.gz *_F5-RNA.fq.gz | \
sed 's/_F3.fq.gz//;s/_F5-RNA.fq.gz//' | uniq | sort | \
parallel --dry-run -u -j24 --env PATH,PYTHONPATH \
-S server01,server02 --workdir $PWD '
cutadapt \
--max-n 0 \
-q 20,20 \
-a CGCCTTGGCCGTACAGCAG \
-a GCGGAACCGGCATGTCGTC \
-g TCTATGGGCAGTCGGTGAT \
-a "A{10}" -a "T{10}" -g "A{10}" -g "T{10}" \
-A ATCACCGACTGCCCATAGA \
-A TAGTGGCTGACGGGTATCT \
-G TCTATGGGCAGTCGGTGAT \
-A "A{10}" -A "T{10}" -G "A{10}" -G "T{10}" \
--overlap 5 --times 5 \
--minimum-length 25 \
--output {}_F3_trimmed_matched.fq.gz \
--paired-output {}_F5-RNA_trimmed_matched.fq.gz \
{}_F3.fq.gz {}_F5-RNA.fq.gz
 
fastqc {}_F3_trimmed_matched.fq.gz {}_F5-RNA_trimmed_matched.fq.gz
'
```

**Comment by multicode** [comment]
Apparently, the previous code has the problem with the following lines where `{}` conflicts with gnu parallel. The problem is now solved using the bash function.
```
-a "A{10}" -a "T{10}" -g "A{10}" -g "T{10}" \
-A "A{10}" -A "T{10}" -G "A{10}" -G "T{10}" \
```

##### Modified code using the bash function

```bash
function cutadapt_parallel {
basename=$1
 
cutadapt \
--max-n 0 \
-q 20,20 \
-a CGCCTTGGCCGTACAGCAG \
-a GCGGAACCGGCATGTCGTC \
-g TCTATGGGCAGTCGGTGAT \
-a "A{10}" -a "T{10}" -g "A{10}" -g "T{10}" \
-A ATCACCGACTGCCCATAGA \
-A TAGTGGCTGACGGGTATCT \
-G TCTATGGGCAGTCGGTGAT \
-A "A{10}" -A "T{10}" -G "A{10}" -G "T{10}" \
--overlap 5 --times 5 \
--minimum-length 25 \
--output ${basename}_F3_trimmed_matched.fq.gz \
--paired-output ${basename}_F5-RNA_trimmed_matched.fq.gz \
${basename}_F3.fq.gz ${basename}_F5-RNA.fq.gz
 
fastqc ${basename}_F3_trimmed_matched.fq.gz ${basename}_F5-RNA_trimmed_matched.fq.gz
 
}
 
export -f cutadapt_parallel
 
ls -1 *_F3.fq.gz *_F5-RNA.fq.gz | \
sed 's/_F3.fq.gz//;s/_F5-RNA.fq.gz//' | uniq | sort | \
parallel -u -j24 --env PATH,PYTHONPATH,cutadapt_parallel \
-S server01,server02 --workdir $PWD cutadapt_parallel {}
```

**Comment by marcelm** [comment]
I believe GNU parallel allows you to escape the `{` and `}` characters with `\{` and `\}`, but using a function is a nicer solution in any case.

**Comment by multicode** [comment]
Yeah, I tried `\{` and `\}` but the escape characters are showing up on a dry run. That is when I dropped to the solution that uses function.
