### ISSUE TITLE
Ability to do more than one round of quality trimming

### ISSUE THREAD

**Issue by john-calley** [marcelm/cutadapt#159]
There is an issue with at least some NextSeq data that results in apparently high base quality reads 'protecting' low quality bases, including adaptor sequence. To address this, I'd like to be able to do one round of adaptor trimming, then quality trim, and finally do another round of adaptor trimming. Currently I address this with multiple calls to cutadapt, but it would be nice if this was not necessary.

This issue arises because NextSeq has two fluorescent tags rather than the four used in previous Illumina machines. One tag is T, one is C, the two together mark A and absence of either marks G. When the fragment to be sequenced is short relative to the read length, the NextSeq runs off the end of the fragment and you get uniform blackness which is interpreted as high quality polyG.

Thanks,

John

**Comment by marcelm** [comment]
That is very interesting since I’ve always wondered what the Illumina machines report if they reach the end of the fragment. For HiSeq, I always suspected that one simply gets random bases (because all four colors should be at very low intensity). That you get a polyG on a NextSeq is a nice insight.

I’m not sure whether it’s really worth adding another option to cutadapt for this since there already are so many ... But NextSeq isn’t so uncommon, so perhaps I should do it. Is it correct that the first round of adapter trimming is the removal of the poly-G end? Do you perhaps have a read that you could send me or copy into this report so I can test?

**Comment by john-calley** [comment]
Yes it is correct that the first round would be removal of polyG. I'd be happy to send you a bigger example set but just to get you started here's 10 PE reads directly. If you send me an email address I could send you a bigger set.
Read#1:
@NS500350:251:HLM7JBGXX:1:11101:17219:1049 1:N:0:TACAGC
GATCGNAAGAGCACACGTCTGAACTCCAGTCACTACAGCATCTCGTATGCCGTCTTATGCTTGAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGNNNNNNNNNNNGGNGG
+
AAAAA#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAA//EAEE//A6///E//A//EA/EEEEEEAEA//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE###########EE#EA
@NS500350:251:HLM7JBGXX:1:11101:2251:1052 1:N:0:TACAGC
GATCGNAAAGAGCACACGTCTGAACTCCAGTCACTACAGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGNNNNNNNNNNNGGGGG
+
AAAAA#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAA<//E/AE6/E6///E/////E/EEEEEEEEEA/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE###########EEEEA
@NS500350:251:HLM7JBGXX:1:11101:7098:1071 1:N:0:TACAGC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTACAGCATCTCGTATGCCGTCTTATGCTTGAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
/AAAAEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEAEEA/A////////EE/A/E///////EEEEE6EEEE/6EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEA
@NS500350:251:HLM7JBGXX:1:11101:3860:1081 1:N:0:TACAGC
GATCGGAAGAGCAACACGTCTGAACTCCAGTCACTACAGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEAEEEA///A//E//EA6//E//E6/E/AEEEEEEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAA
@NS500350:251:HLM7JBGXX:1:11101:6587:1089 1:N:0:TACAGC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTACAGCATCTCGTATGCCGTCTTATGCTTGAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/E/////E//E6A//E/////EEAEEEEEEEE///EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEA
@NS500350:251:HLM7JBGXX:1:11101:18997:1091 1:N:0:TACAGC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTACAGCATCTCGTATGCCGTCTTATGCTTGAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
AAAAAEEEEAEEEEEEEEEEEEAEAEEEEEEEEEEEEEEE/E////EE//A6///E//EE/E//EEEEEEEEE////EEEEEEAEEAEEEAEEEAEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEAEEE
@NS500350:251:HLM7JBGXX:1:11101:5995:1113 1:N:0:TACAGC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTACAGCATCTCGTATGCCGTCTTCTGGTTGAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
AAAAAEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEA////EAAE//EE///E//E//E//EAEEEEEEE/AEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEA
@NS500350:251:HLM7JBGXX:1:11101:4347:1114 1:N:0:TACAGC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTACAGCATCTCGTATGCCGTCTTATGCTTGAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEA///AEEEEAEA6//AE//E//E/AEEEEEEEEE//AEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEE
@NS500350:251:HLM7JBGXX:1:11101:12075:1120 1:N:0:TACAGC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTACAGCATCTCGTATTCCGTCTTCTGCTTGAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
AAAAAEEEEEEAEEEEAEAEEEEEEAEEEEEEEEEEEEEEE///E/EE////AAEE/E//////EEEEEEE6///////E6EEA/AEAEAE6EEEEEEEEEEEEAEAA/E/EEEEA//EEEEEAEAEE/EEEAEEEE<E/AEEEEE/EEE
@NS500350:251:HLM7JBGXX:1:11101:22452:1121 1:N:0:TACAGC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTACAGCATCGCGTATGCCGTCTTATGCTTGAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/////E/EE//E6///E//A//E//EEEEEEEE6//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE<EEEEEEEE

Read #2:
@NS500350:251:HLM7JBGXX:1:11101:17219:1049 2:N:0:TACAGC
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
######################################################################################################################################################
@NS500350:251:HLM7JBGXX:1:11101:2251:1052 2:N:0:TACAGC
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
######################################################################################################################################################
@NS500350:251:HLM7JBGXX:1:11101:7098:1071 2:N:0:TACAGC
NGGGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAAATAAAANNNNNNNNNNNNNGNGNGGGGGGNGNGGGGGNGGGGGNNGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
#AAA###################################################/////E/A#############A#<#EEEEEE#E#EEEEE#EEEEE##E###############################################
@NS500350:251:HLM7JBGXX:1:11101:3860:1081 2:N:0:TACAGC
NGGGGGGGGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGGGGAAAAAAAANNNNNNNGNGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGNGNNGNNGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
#AAAAEE6E############################################//////////66#######/#A/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#E##E##E###############################
@NS500350:251:HLM7JBGXX:1:11101:6587:1089 2:N:0:TACAGC
NGGGGGGGGGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNANNNNNNNNNGGGGGAGAATAAAAAAANANNAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGNGGNNNNNNNNNNGNNNNNNNNNNNNN
+
#AAAAEE66E#############################/#########/E///////////////#6##//////A<EEEEEEEEEEEEEE<EEEEEEEEEEEEEEEEEEEEEEAEEEEEEE#EE##########E#############
@NS500350:251:HLM7JBGXX:1:11101:18997:1091 2:N:0:TACAGC
NGGGGGGGGGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGNNNNNNNNGGGGGGGGGTAAAAAAAANANNAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGNGGNNNNNNGNNGGNNNNNNNNNNNNN
+
#AAAAE666E#############################/########//EE//////////A//E#A##//////6E/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE#EE######E##EE#############
@NS500350:251:HLM7JBGXX:1:11101:5995:1113 2:N:0:TACAGC
GGGGGGGGGGGGGGGGGGGGGGGGGATTGGGTTGGATAAGGGGGGGGGGGGGGGAGTGATAAAAAAAAAATGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
AAA/AEE666E66E66//66//EE//////////////////AE//////EE//////////E/E//////////E/E/EEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEAEEEEEAEA<EEEEEEAEEAAA<AEAEAA
@NS500350:251:HLM7JBGXX:1:11101:4347:1114 2:N:0:TACAGC
GGGGGGGGGGGGGGGGGGGGGGGGGAGAGTGGGGGTTGGGGGGGGGGGGGGGGGAGGAAAAAAAAAAAAGAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
AAAAAE6666666E6EE6A6//E6////////////////66////AE//A///////////////E//////E/E/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEE<AEEEEEEEEEAAEE/
@NS500350:251:HLM7JBGXX:1:11101:12075:1120 2:N:0:TACAGC
GGGGGGGGGAGCTGCGGGGAAGGGTTAATAGGTAATGTAAAAAGAAGGGGCGGAAAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
A//A///////////////////////////////A/A6////////////////6/E/6EEEE/EE/AA////////EE/<<EE/AA/<AE/EE/AAAEEEAE/E/EE/6EEEEEEEA/AEEAE/E/AAEEEEEEE/EEEEEEEAEE<E
@NS500350:251:HLM7JBGXX:1:11101:22452:1121 2:N:0:TACAGC
GGGGGGGGGTGGGGTGGGGTGGGTGAATAATTTTTATAAGGGGGGGGGGGGGGGAGAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
AA66666///////////////////////////////////////////66///////////A///////////</<//EE/AE/EAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEAEEAEEEEEEAEAAAEEAAAAA<

**Comment by john-calley** [comment]
I should note that the above is selected to illustrate the problem. Not a random sample at all.

**Comment by marcelm** [comment]
Thanks for the example! Not sure whether I need more, but you can run `cutadapt --help | head -n2` to see my e-mail address.

Could you tell me what your expected output is? Looking at read 1 only, all sequences start with the "TruSeq Adapter, Index 5". It therefore seems that they are all adapter dimers: The sequencing primer is followed immediately by the 3' adapter, without any actual sequence in between. I am guessing that the correct way to trim those reads would be to run `cutadapt -a GATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG` and then all of them would be trimmed to a length of zero. Note that cutadapt removes the adapter itself and everything following it, so you remove the poly-G run also. Quality trimming wouldn’t be relevant here.

What have I missed?

**Comment by john-calley** [comment]
Marcel,   The problem is when the adaptor sequence is low quality. It is 'protected' by the nominally high quality polyG so no quality trimming occurs, and the Illumina adaptor is not recognized. I think there are some examples of this in read 2 but I might not have included any that actually look like this.
John

**Comment by marcelm** [comment]
I understand. I’m wondering what the best way to handle this is. A second round of adapter trimming would work, but it may be better to add a modified quality trimming routine instead. As a test, I modified the quality trimming to treat `G` bases in the end of the read as low quality, and it seems to work on your data. It definitely needs more testing, though, so it would be great if you could send me a larger set of reads.

**Comment by john-calley** [comment]
I've sent you an invitation so that I can send you bigger examples.

**Comment by marcelm** [comment]
Hi, and sorry for taking so long. I’ve just added a new option to cutadapt called `--nextseq-trim`. It works similar to the already existing quality trimming option `-q`, but ignores the actual quality assigned to `G` bases and treats them as having low quality. I used the data files you provided to test it, but since I don’t know what the result should be, I’m still not 100% sure that it does what you need. Please test it if you are still interested.

**Comment by john-calley** [comment]
I'm definitely still interested. I've go some other issues to deal with first, so it may be a while but I will definitely test it. Thanks for your great responsiveness!
John

**Comment by marcelm** [comment]
The option has been in cutadapt for a while now, so some people must have tested it.
