### ISSUE TITLE
Output write error

### ISSUE THREAD

**Issue by Protitor** [marcelm/cutadapt#160]
Hej,

I have rather a question than a real problem. I wonder if it is possible to redirect every read which is filtered to an extra file, along with the trimmed output files? I wanted to keep data loss at a minimum to go back and look into the filtered sequences at a later time point if I have to. But if I use something like:

    cutadapt -a ADAPTER1 -A ADAPTER2 -m 20 -o out1.fastq -p out2.fastq --too-short-output tooshort.fastq input1.fastq input2.fastq

I get the following Python error:
```
Traceback (most recent call last):
  File "/home/jan/Programs/cutadapt-1.9/bin/cutadapt", line 10, in <module>
    cutadapt.main()
  File "/home/jan/Programs/cutadapt-1.9/cutadapt/scripts/cutadapt.py", line 856, in main
    stats = process_paired_reads(reader, modifiers, modifiers2, filters)
  File "/home/jan/Programs/cutadapt-1.9/cutadapt/scripts/cutadapt.py", line 287, in process_paired_reads
    if filter(read1, read2):
  File "/home/jan/Programs/cutadapt-1.9/cutadapt/filters.py", line 68, in __call__
    self.writer.write(read1, read2)
TypeError: write() takes exactly 2 arguments (3 given)
```

If this is not possible at all, please try to implement an error message, so that the user can easily identify the problem (took me some while).

Thanks in advance,
Jan

**Comment by marcelm** [comment]
Thanks for the report. That you’re getting an unfriendly error message is definitely a bug and I’ve just fixed it. The second problem is that cutadapt 1.9 doesn’t actually allow you to use `--too-short-output` with paired-end data. I have fixed this a few days ago and there is now an option `--too-short-paired-output`, which you will need to use in order to specify where the second read in a pair that is too short should be written.

I’ve just released cutadapt 1.9.1 which includes the new option. Could you install it and see if it works?

**Comment by Protitor** [comment]
Cool, thanks for the prompt reply. I will install and try the options as soon as possible and will let you know whether it worked.

**Comment by Protitor** [comment]
Hej,

seems like you changed something in the way you import your packages. I got this error when I try to use cutadapt:
```
jan@ZIBOSCH409-03:~/Downloads/cutadapt-master$ bin/cutadapt 
Traceback (most recent call last):
  File "bin/cutadapt", line 9, in <module>
    from cutadapt.scripts import cutadapt
  File "/home/jan/Downloads/cutadapt-master/cutadapt/scripts/cutadapt.py", line 62, in <module>
    check_importability()
  File "/home/jan/Downloads/cutadapt-master/cutadapt/__init__.py", line 9, in check_importability
    import cutadapt._align
ImportError: No module named _align
```
Hope that helps.
Jan

**Comment by marcelm** [comment]
If you check out from Git, then you’ll need to compile the extension modules. Easiest is to just run `python setup.py build_ext -i`. Then it should work.

**Comment by marcelm** [comment]
Ah, or did you use the zip file that is available via Github? Either do what I said above or use the file from PyPI instead: https://pypi.python.org/pypi/cutadapt/

**Comment by Protitor** [comment]
Hej,
tried the new version and it worked fine for me. Nice job and thank you very much. Never had such a fast response including the solution for my problem ;-).

**Comment by marcelm** [comment]
:-)
