### ISSUE TITLE
Documentation bug for pair ends

### ISSUE THREAD

**Issue by Poshi** [marcelm/cutadapt#163]
Hello,

in the help of cutadapt, you can read the following:
>    -u LENGTH, --cut=LENGTH
>                        Remove LENGTH bases from the beginning or end of each
>                        read. If LENGTH is positive, bases are removed from
>                        the beginning of each read. If LENGTH is negative,
>                        bases are removed from the end of each read. This
>                        option can be specified twice if the LENGTHs have
>                        different signs.
This description lies terribly and can cause some time loses (like for me yesterday). The point is that it says that the option "Remove LENGTH bases from the beginning or end of each read." But it does not remove anything from "each read", only from the first read!
If you continue reading the help you can find the "-U" option, but it is easy to bypass the contradiction in the help.
Solution is really simple, change "each read" by "the first read".

**Comment by marcelm** [comment]
Sorry for your frustration, but saying that it *lies terribly* is an exaggeration, which is also not very polite.

The help for many options was written while cutadapt was still not paired-end aware, and the help text for `--cut` was kept consistent with that when I added it. The idea is that you have to read the section about the paired-end options when you start trimming paired-end data.

**Comment by marcelm** [comment]
And yes, of course I will fix it.

**Comment by Poshi** [comment]
Oh! Sorry, I didn't intended to be rude. When I said that it "lies terribly" I was exagerating on purpose to magnify a small typo and to cause some laughts, not to cause ofence. My apologies.
And thanks for you work!

**Comment by marcelm** [comment]
Great, was a bit worried for a minute ... I’m unfortunately busy with other things right now, will reply to your other reported issues later.

**Comment by marcelm** [comment]
This is the new help text for `--cut`:
```
    -u LENGTH, --cut=LENGTH
                        Remove bases from each read (first read only if
                        paired). If LENGTH is positive, remove bases from the
                        beginning. If LENGTH is negative, remove bases from
                        the end. Can be used twice if LENGTHs have different
                        signs.
```
I’ve changed the other help texts as well to make it clear to which read in a pair it applies.
