### ISSUE TITLE
Minimum length

### ISSUE THREAD

**Issue by Poshi** [marcelm/cutadapt#165]
Another suggestion. As you know, reads can be very short after trimming. You have parameters to control the minimum and maximum read length, and if something is outside the limits, you can discard them or save them to another file. I'd like to propose an extra option: keep a minimum number of bases in the read instead of discarding it.
The rational is: maybe you are interested in keeping all the data in the output, but if you keep too short reads, you can run into trouble with some aligners (aligning a single base against a genome could potentially return a huge number of hits, as many as times appear that base in the reference). If you allow the code to keep a minimum number of bases, the aligner won't cause any trouble (it will just output the sequence unaligned, probably).
In fact, this is our case.

**Comment by marcelm** [comment]
Hi, thanks for the suggestion and sorry for the delay. It seems to me this would be something that is rarely needed, but perhaps I don’t understand correctly. Could you elaborate on why you would want to keep all data in the output?

**Comment by Poshi** [comment]
Mainly due to "client requirements".
The rational is that we intend to keep only the final bam file. And this file should have all the information needed for everything: doing analyses on the alignments, but also recovering the original FastQ file from the bam file. If we discard reads (and bases), we are no longer able to regenerate the FastQ file, which forces us to keep a copy of the FastQ files somewhere else (and this means a lot of disk space used).
The reasons to be able to have the FastQ files available is that we can start any analysis with different trimming parameters from them and that in cases where Illumina requests the FastQ files generated by the sequencer to diagnose and replace some flowcell.
By being able to regenerate the original FastQ files from the bam files we can save a lot of space while keeping the whole functionality.
All of this is related to the cliping-instead-of-trimming issue: being able to regenerate the original file.

**Comment by marcelm** [comment]
Keeping all the information necessary to re-generate the FASTQ file makes sense. However, since this would basically be a workaround for a badly behaving aligner, I’d like to assign this issue a lower priority for now. Feel free to send in a patch though.

**Comment by marcelm** [comment]
I’m trying to clean up the issue list a bit. For this particular feature, it appears that only very few people would find it useful, and taking into account that any feature added to Cutadapt increases the maintenance burden for me, I’ve decided not to implement it. Still, thanks a lot for your feedback! I do appreciate learning how the tool is or could be used.
