### ISSUE TITLE
piping to stdout but message "Trimming 2 adapters with at most 10.0% errors in paired-end mode ..." printed on stdout

### ISSUE THREAD

**Issue by lindenb** [marcelm/cutadapt#167]
Hi, I'm not sure it's a bug. I'm trying to pipe the outpout of cutadapt 1.9.1 into bwa.

```bash
cutadapt   -a ${P1} -A{P2} --quiet   -o - --paired-output - R1.fastq.gz R2.fastq.gz  2> /dev/null
```
however some logs are written to stdout:

```bash
Trimming 2 adapters with at most 10.0% errors in paired-end mode ...
@HWI-1KL149:101:C8410ACXX:8:1101:1402:2226 1:N:0:GAGAGGC
(...)
```

is it me or is it a bug ?

thanks ?

PS: cross-posted: https://www.biostars.org/p/171372/

**Comment by marcelm** [comment]
See also my answer on Biostars. The problem that I can fix is that `--quiet` does not make cutadapt quiet.

**Comment by lindenb** [comment]
@marcelm thank you for your quick answer. I'll work with intermediate fastq files for now instead of piping :-)

**Comment by marcelm** [comment]
If you know how to install from Git, you could test the changes I made. Otherwise, you’ll need to wait for the next release. Feel free to re-open this issue if the problem is still there with the new version.

**Comment by lindenb** [comment]
:+1: thanks, I'll wait for the next release.
