### ISSUE TITLE
Typo in doc/guide

### ISSUE THREAD

**Issue by frederic-mahe** [marcelm/cutadapt#168]
Hi,

I am not sure about that, but I think there is a markup problem in the section *Reducing random matches*. The text renders like this:

The minimum overlap length can be changed with the --overlap``(short: ``-O) parameter. Shorter matches are simply ignored, and the bases are not trimmed.

I guess it should be rendered ``--overlap (-O)``?

Thanks,

**Comment by marcelm** [comment]
Yes, thanks for finding!
