### ISSUE TITLE
Question regarding match priority

### ISSUE THREAD

**Issue by frederic-mahe** [marcelm/cutadapt#170]
Hi @marcelm,

I may have missed it in the documentation, but cutadapt's matching priorities are unclear to me. When searching for adapters in 5' (option `-g`), if a given sequence contains two exact copies of the adapter, which one of the copies will be trimmed?
```
fluffADAPTERfluffADAPTERfluffflufffluff...
```
Will the trimming be applied up to the leftmost copy (leaving `fluffADAPTERfluffflufffluff...`) or up to the rightmost copy (leaving `fluffflufffluff...`)?

I think cutadapt trims the leftmost copy (hence the `--times` option), but I need to be sure it is the intended behavior.

Thanks,

**Comment by marcelm** [comment]
Yes, that’s the intended behavior. There is an exception when inexact matches are involved, see the commit for an explanation.
