### ISSUE TITLE
Feature request - select output format

### ISSUE THREAD

**Issue by davidmartinad200** [marcelm/cutadapt#171]
Hi ,
From the documentation it says that the output format is the same as the input format

_> "The output format is the same as the input format, except for the FASTA/QUAL pairs – those will always be converted to FASTQ. Also, cutadapt does not check the output file name: If you input FASTQ data, but use -o output.fasta, then the output file will actually be in FASTQ format."_

Would it be possible to convert from fastq to fasta directly so that the following command will work:
cutadapt -a AACCGGTT -o output.**fasta** input.fastq

It saves some time......
thanks

**Comment by marcelm** [comment]
Good idea, why not. Give me some time, however, since I’d like to work on some other issues first.

**Comment by marcelm** [comment]
This is now implemented. The file format is detected from the name of the output file. `.fa`, `.fna`, `.fasta` are recognized as FASTA.
