### ISSUE TITLE
Failed building wheel for cutadapt

### ISSUE THREAD

**Issue by GreetDB** [marcelm/cutadapt#173]
Hi All,

I'm unable to install cutadapt. I always get the following error:

`cutadapt/_align.c:1316:16: warning: implicit declaration of function 'PyByteArray_CheckExact' is invalid in C99 [-Wimplicit-function-declaration]
      if (!(likely(PyByteArray_CheckExact(__pyx_t_2))||((__pyx_t_2) == Py_None)||(PyErr_Format(PyExc_TypeError, "Expected %.16s, got %.200s", "bytearray", Py_TYPE(__pyx_t_2)->tp_name), 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                   ^
    cutadapt/_align.c:436:43: note: expanded from macro 'likely'
      #define likely(x)   __builtin_expect(!!(x), 1)
                                              ^
    cutadapt/_align.c:8407:18: warning: implicit declaration of function 'PyByteArray_GET_SIZE' is invalid in C99 [-Wimplicit-function-declaration]
            length = PyByteArray_GET_SIZE(string);
                     ^
    cutadapt/_align.c:8410:13: warning: implicit declaration of function 'PyByteArray_AS_STRING' is invalid in C99 [-Wimplicit-function-declaration]
                PyByteArray_AS_STRING(string)[i] = (char) v;
                ^
    cutadapt/_align.c:8410:42: error: subscripted value is not an array, pointer, or vector
                PyByteArray_AS_STRING(string)[i] = (char) v;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
    cutadapt/_align.c:8417:38: error: subscripted value is not an array, pointer, or vector
            PyByteArray_AS_STRING(string)[i] = (char) v;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
    3 warnings and 2 errors generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
`
Python is up to date (Python 2.7.11 :: Anaconda 2.4.1 (x86_64)) and my gcc as well (Apple LLVM version 7.0.2 (clang-700.1.81)).

Does somebody has an idea what's going wrong? This would be a very useful tool for my research so I hope somebody can help!

Thanks a lot,
Greet

**Comment by marcelm** [comment]
I see you are using conda. Cutadapt is available [from the "bioconda" channel](https://anaconda.org/bioconda/cutadapt), so you should be able to install it with `conda install -c bioconda cutadapt`. I’m not using OS X myself, so I can probably not help with the compilation problem.

**Comment by GreetDB** [comment]
installing it using bioconda seems to work! Thanks a lot!

**Comment by marcelm** [comment]
Great, glad I could help!
