### ISSUE TITLE
Parameter for minimum adapter lenght

### ISSUE THREAD

**Issue by ulbivin** [marcelm/cutadapt#177]
When I trim 5' adaptors with the -g option I experience that adaptors down to the length of 3 bases are removed. Such a tri-mer of course exists multiple times over the reference sequence and hence in my reads, and therefore my results are tainted.

Is there a way to set a minimum adaptor length to trim or will you consider including this option in a future version?

**Comment by marcelm** [comment]
See the [section in the documentation about how to reduce the number of random matches](http://cutadapt.readthedocs.org/en/stable/guide.html#reducing-random-matches). You may also want to use an [anchored 5' adapter instead](http://cutadapt.readthedocs.org/en/stable/guide.html#anchored-5-adapters).

**Comment by ulbivin** [comment]
A RTFM case so. Thank you!

**Comment by marcelm** [comment]
I did not use those words explicitly, but yes ;-)
