### ISSUE TITLE
Cannot run cutadapt

### ISSUE THREAD

**Issue by Kamya24** [marcelm/cutadapt#180]
I am not able to run comaandsin cutadapt1.9.1. the error is cutadapt command not found. but when I type cut --h it works. With the commandcutadapt -a CAGGTATACGA -o output.fastq input.fastq cutadapt: command not found . Same with ths. But with cut cut -a CAGGTATACGA -o output.fastq input.fastq cut: invalid option -- 'a' Try `cut --help' for more information.

**Comment by marcelm** [comment]
Hi, the "cut" command is pre-installed on most Linux systems, but it does something completely different from cutadapt. How did you (or try to) install cutadapt? Have you seen the [installation instructions](http://cutadapt.readthedocs.org/en/stable/installation.html)?
