### ISSUE TITLE
cutadapt 

### ISSUE THREAD

**Issue by Kamya24** [marcelm/cutadapt#182]
I tried installing cutadapt and it is shown that the installation is complete. 

kamya@kamya-MS-7357:~/cutadapt-1.9.1$ python setup.py install --user
running install
running build
running build_py
running build_ext
building 'cutadapt._align' extension
i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c cutadapt/_align.c -o build/temp.linux-i686-2.7/cutadapt/_align.o
i686-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-i686-2.7/cutadapt/_align.o -o build/lib.linux-i686-2.7/cutadapt/_align.so
building 'cutadapt._qualtrim' extension
i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c cutadapt/_qualtrim.c -o build/temp.linux-i686-2.7/cutadapt/_qualtrim.o
i686-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-i686-2.7/cutadapt/_qualtrim.o -o build/lib.linux-i686-2.7/cutadapt/_qualtrim.so
building 'cutadapt._seqio' extension
i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c cutadapt/_seqio.c -o build/temp.linux-i686-2.7/cutadapt/_seqio.o
i686-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-i686-2.7/cutadapt/_seqio.o -o build/lib.linux-i686-2.7/cutadapt/_seqio.so
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/cutadapt -> build/scripts-2.7
changing mode of build/scripts-2.7/cutadapt from 664 to 775
running install_lib
creating /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/filters.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/modifiers.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/xopen.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/colorspace.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/qualtrim.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/__main__.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/adapters.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/seqio.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
creating /home/kamya/.local/lib/python2.7/site-packages/cutadapt/scripts
copying build/lib.linux-i686-2.7/cutadapt/scripts/cutadapt.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt/scripts
copying build/lib.linux-i686-2.7/cutadapt/scripts/__init__.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt/scripts
copying build/lib.linux-i686-2.7/cutadapt/_seqio.so -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/_qualtrim.so -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/report.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/_align.so -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/__init__.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/compat.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
copying build/lib.linux-i686-2.7/cutadapt/align.py -> /home/kamya/.local/lib/python2.7/site-packages/cutadapt
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/filters.py to filters.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/modifiers.py to modifiers.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/xopen.py to xopen.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/colorspace.py to colorspace.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/qualtrim.py to qualtrim.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/__main__.py to __main__.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/adapters.py to adapters.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/seqio.py to seqio.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py to cutadapt.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/scripts/__init__.py to __init__.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/report.py to report.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/__init__.py to __init__.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/compat.py to compat.pyc
byte-compiling /home/kamya/.local/lib/python2.7/site-packages/cutadapt/align.py to align.pyc
running install_scripts
creating /home/kamya/.local/bin
copying build/scripts-2.7/cutadapt -> /home/kamya/.local/bin
changing mode of /home/kamya/.local/bin/cutadapt to 775
running install_egg_info
Writing /home/kamya/.local/lib/python2.7/site-packages/cutadapt-1.9.1.egg-info
kamya@kamya-MS-7357:~/cutadapt-1.9.1$ cutadapt -a AACCGGTT -o output.fastq input.fastq
cutadapt: command not found
kamya@kamya-MS-7357:~/cutadapt-1.9.1$ cutadapt -help
cutadapt: command not found
kamya@kamya-MS-7357:~/cutadapt-1.9.1$ cutadapt -h
cutadapt: command not found

I have gone through the instruction manual. Still I am getting the error cutadapt command not found. Can you please tell me if the installation is not done properly or i am using it in a wrong way and  how to use the command.

**Comment by marcelm** [comment]
Hi, thanks for trying cutadapt. It seems that the installation has succeded. The only problem is that the shell does not know where the program is when you type in `cutadapt`. The program was installed into `~/.local/bin/` (the `~` character is an abbreviation for your home directory `/home/kamya/`). This means that when you want to run the program, you need to do one of two things:
* Either use the full path to the program every time you want to run it, like this: `~/.local/bin/cutadapt --help`
* Or add `~/.local/bin/` to your `PATH` environment variable before running `cutadapt`. Use this command to do so: `export PATH=$HOME/.local/bin:$PATH`. This setting is not permanent and only affects the current shell session you have open. To make it permanent, add the command to the file `~/.bashrc`.

Let me know how it goes.

**Comment by Kamya24** [comment]
Thank you so much. I will try and let you know how it goes.

**Comment by Kamya24** [comment]
Hi,
I tried the commands using the path and it worked. I have around 13 GB of
data . Do I have to keep the data in same folder as the cutadapt.I tried
doing that but it gave the error

kamya@kamya-MS-7357:~$ ~/.local/bin/cutadapt -a TGGAATTCTCGGGTGCCAAGG -o
output.fastq CL_NS_Run18_0815.fastq.gz
gzip: CL_NS_Run18_0815.fastq.gz: No such file or directory
This is cutadapt 1.9.1 with Python 2.7.6
Command line parameters: -a TGGAATTCTCGGGTGCCAAGG -o output.fastq
CL_NS_Run18_0815.fastq.gz
Trimming 1 adapter with at most 10.0% errors in single-end mode ...
cutadapt: error: gzip process returned non-zero exit code 1. Is the input
file truncated or corrupt?


On Wed, Mar 2, 2016 at 4:32 PM, Kamya Singh <kamyasingh90@gmail.com> wrote:

> Thank you so much. I will try and let you know how it goes.
> On Mar 2, 2016 4:06 PM, "Marcel Martin" <notifications@github.com> wrote:
>
>> Hi, thanks for trying cutadapt. It seems that the installation has
>> succeded. The only problem is that the shell does not know where the
>> program is when you type in cutadapt. The program was installed into
>> ~/.local/bin/ (the ~ character is an abbreviation for your home
>> directory /home/kamya/). This means that when you want to run the
>> program, you need to do one of two things:
>>
>>    - Either use the full path to the program every time you want to run
>>    it, like this: ~/.local/bin/cutadapt --help
>>    - Or add ~/.local/bin/ to your PATH environment variable before
>>    running cutadapt. Use this command to do so: export
>>    PATH=$HOME/.local/bin:$PATH. This setting is not permanent and only
>>    affects the current shell session you have open. To make it permanent, add
>>    the command to the file ~/.bashrc.
>>
>> Let me know how it goes.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/marcelm/cutadapt/issues/182#issuecomment-191177505>.
>>
>


-- 
Kamya Singh

**Comment by marcelm** [comment]
Hi, no, the data does not need to be kept in the same folder as the program. Also, if you have such big files, I strongly recommend that you compress also the output files. Just add the `.gz` extension to the output file name (write `-o output.fastq.gz` instead of just `-o output.fastq`). And I suggest to choose a more descriptive file name, such as `CL_NS_Run18_0815.trimmed.fastq.gz`. (Less confusion in the long run.)

Regarding the 'no such file or directory' error, you will need to make sure that you provide the proper path names to the program. You need to get familiar with some basic Unix command-line knowledge in order to solve this - it has nothing to do with cutadapt itself. I suggest that you get someone who sits down with you and explains the basic commands, or that you take an introductory Unix/Linux course. The basics are not difficult and it will help you with many other bioinformatics tools as well.

**Comment by Kamya24** [comment]
Thank you so much. It worked well. I would definitely take lessons
regarding the basics of linux command as i would require them more
frequently with bioinformatics tools.

On Thu, Mar 3, 2016 at 5:59 PM, Marcel Martin <notifications@github.com>
wrote:

> Hi, no, the data does not need to be kept in the same folder as the
> program. Also, if you have such big files, I strongly recommend that you
> compress also the output files. Just add the .gz extension to the output
> file name (write -o output.fastq.gz instead of just -o output.fastq). And
> I suggest to choose a more descriptive file name, such as
> CL_NS_Run18_0815.trimmed.fastq.gz. (Less confusion in the long run.)
>
> Regarding the 'no such file or directory' error, you will need to make
> sure that you provide the proper path names to the program. You need to get
> familiar with some basic Unix command-line knowledge in order to solve this
> - it has nothing to do with cutadapt itself. I suggest that you get someone
> who sits down with you and explains the basic commands, or that you take an
> introductory Unix/Linux course. The basics are not difficult and it will
> help you with many other bioinformatics tools as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcelm/cutadapt/issues/182#issuecomment-191740206>.
>



-- 
Kamya Singh

**Comment by marcelm** [comment]
Great! Closing this issue then.
