### ISSUE TITLE
How it happened： length of quality sequence (17) and length of read (99) do not match

### ISSUE THREAD

**Issue by Shicheng-Guo** [marcelm/cutadapt#192]
It is very interesting. I download the SRA files and then transfer them to fastq and then I want to cut-adaptors use cutadapt. The question is I get one of such error. 

cutadapt: error: In read named 'SRR949197.215195112 D1JR8ACXX130107:2:2203:10919:71639 length=99': length of quality sequence (17) and length of read (99) do not match

How it can happen? SRA file's problem? fastq-dump problem? It is really interesting. What I should do now？ filter out this reads? 

Thanks You So Much

Best regards,

This is cutadapt 1.9.1 with Python 2.6.6
Command line parameters: -f fastq -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC SRR949197_1.fastq.gz
Trimming 1 adapter with at most 10.0% errors in single-end mode ...

gzip: SRR949197_1.fastq.gz: unexpected end of file
cutadapt: error: In read named 'SRR949197.215195112 D1JR8ACXX130107:2:2203:10919:71639 length=99': length of quality sequence (17) and length of read (99) do not match

Cutadapt terminated with exit signal: '256'.
Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

**Comment by marcelm** [comment]
Hi, in the middle of the log output that you pasted is the crucial message: `gzip: SRR949197_1.fastq.gz: unexpected end of file`. Your gzip file is incomplete for some reason. Perhaps fastq-dump was cancelled? Maybe the disk was full?

**Comment by marcelm** [comment]
No reply, closing.

**Comment by Yinglei1** [comment]
> It is very interesting. I download the SRA files and then transfer them to fastq and then I want to cut-adaptors use cutadapt. The question is I get one of such error.
> 
> cutadapt: error: In read named 'SRR949197.215195112 D1JR8ACXX130107:2:2203:10919:71639 length=99': length of quality sequence (17) and length of read (99) do not match
> 
> How it can happen? SRA file's problem? fastq-dump problem? It is really interesting. What I should do now？ filter out this reads?
> 
> Thanks You So Much
> 
> Best regards,
> 
> This is cutadapt 1.9.1 with Python 2.6.6
> Command line parameters: -f fastq -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC SRR949197_1.fastq.gz
> Trimming 1 adapter with at most 10.0% errors in single-end mode ...
> 
> gzip: SRR949197_1.fastq.gz: unexpected end of file
> cutadapt: error: In read named 'SRR949197.215195112 D1JR8ACXX130107:2:2203:10919:71639 length=99': length of quality sequence (17) and length of read (99) do not match
> 
> Cutadapt terminated with exit signal: '256'.
> Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

Hello, I meet the same question, if you figure it out?

**Comment by marcelm** [comment]
You commented on issue #96 already. See my reply there.

**Comment by Yinglei1** [comment]
Hi， I re-download the new data, but the new problem arise. but the line 1 started with @. Thanks in advance!
<img width="727" alt="9533e229d51ba96a9648850559f6844" src="https://user-images.githubusercontent.com/59709147/72155449-772fb800-33b3-11ea-956f-73d7c9d057b9.png">
<img width="952" alt="87f01dde52382d820f07ce16ed7e78e" src="https://user-images.githubusercontent.com/59709147/72155454-78f97b80-33b3-11ea-99d6-8d019a8eac1a.png">

**Comment by marcelm** [comment]
Please do not write the same thing in two different issues. It will not give you a faster answer.

Again, see my reply in #96.
