### ISSUE TITLE
Too few 3' adaptor can be removed

### ISSUE THREAD

**Issue by dawnmy** [marcelm/cutadapt#194]
I am working on a amplicon sequencing data, and trying to remove the forward and reverse primers from the merged paired end reads. But I could not get all 3' primer removed. The 5' primer is fine. For the 3' primer I converted it to the reverse complementary sequence of the original primer sequence as the instruction of cutadapt. 

I counted the 3' primer from the end of the reads using grep -Ec 'TCCTACGGGAGGCAGCA$', and 11394396 3' primer seqs are there. But only 16696 were detected and trimed by cutadapt. I also check the output fastq file of the cutadapt, most of the 3' primers are still there. Did I do something wrong, or I misunderstand something? Hope you can help me out. Thank you!

## **The output log is as follows:**

Command line parameters: -g ^AGAGTTTGATCMTGGCTCAG -a TCCTACGGGAGGCAGCA$ -e 0.06 -f fastq --trimmed-only -o vag.merged.cutprim.fastq vag.merged.fastq
Trimming 2 adapters with at most 6.0% errors in single-end mode ...
Finished in 253.51 s (22 us/read; 2.76 M reads/minute).

=== Summary ===

Total reads processed:              11,673,347
Reads with adapters:                11,673,049 (100.0%)
Reads written (passing filters):    11,673,049 (100.0%)

Total basepairs processed: 4,212,570,352 bp
Total written (filtered):  3,979,104,819 bp (94.5%)

=== Adapter 1 ===

Sequence: TCCTACGGGAGGCAGCA; Type: anchored 3'; Length: 17; Trimmed: 16696 times.

No. of allowed errors:
0-15 bp: 0; 16-17 bp: 1

Bases preceding removed adapters:
  A: 0.3%
  C: 99.5%
  G: 0.0%
  T: 0.1%
  none/other: 0.0%
WARNING:
    The adapter is preceded by "C" extremely often.
    The provided adapter sequence may be incomplete.
    To fix the problem, add "C" to the beginning of the adapter sequence.

Overview of removed sequences
length	count	expect	max.err	error counts
16	75	0.0	0	0 75
17	16606	0.0	1	16276 330
18	15	0.0	1	0 15

=== Adapter 2 ===

Sequence: AGAGTTTGATCMTGGCTCAG; Type: anchored 5'; Length: 20; Trimmed: 11656353 times.

No. of allowed errors:
0-15 bp: 0; 16-20 bp: 1

Overview of removed sequences
length	count	expect	max.err	error counts
19	72931	0.0	1	0 72931
20	11564389	0.0	1	11266512 297877
21	19033	0.0	1	0 19033

WARNING:
    One or more of your adapter sequences may be incomplete.
    Please see the detailed output above.
Reading fastq file 100%
11057918 sequences kept (of which 0 truncated), 615131 sequences discarded.

**Comment by marcelm** [comment]
Cutadapt by default trims only at most one adapter from each read. If you provide multiple adapter sequences, it will trim only the best matching one. If you want to remove up to two, then you need to use the option `--times=2` or the short form `-n 2`.

The next cutadapt version will have support for "linked adapters" for exactly your use case (I implemented it because I myself have merged paired-end data with primers at both ends). It will allow you to specify that two adapter sequences belong together:
```
cutadapt -a AGAGTTTGATCMTGGCTCAG...TCCTACGGGAGGCAGCA$ [further options]
```
The first is treated as an (anchored) 5' adapter and the second as a 3' adapter, but both must occur together in order to be removed. Since this counts as just one adapter match, it would also solve your problem.

**Comment by dawnmy** [comment]
Thank you so much! That would be great. Looking forward to the next version. So when is the release of the new version?

**Comment by marcelm** [comment]
Not sure, yet, but I hope within the next two or three weeks. Using `-n 2` should work fine until then.

**Comment by dawnmy** [comment]
I will try out `-n 2` as you suggested. Thank you for your prompt reply.

**Comment by marcelm** [comment]
Sure!
