### ISSUE TITLE
how to trim anchored multiple sequences

### ISSUE THREAD

**Issue by danshu** [marcelm/cutadapt#200]
Hello,

I want to trim 3' anchored adapter sequences of different length, e.g.
>f1
AGATCGGAAGAGCACA$
>f2
AGATCGGAAGAGCAC$
>f3
AGATCGGAAGAGCA$
>f4
AGATCGGAAGAGC$

I saved the adapter sequences in fasta files and used -a file:forward_adapters.fasta -A file:reverse_adapters.fasta in the command since I was trimming paired end data. I added "$" at the end of adapter sequences to only trim anchored 3' adapter sequences. 

I tested it on some sample data, however, I found that the "$" seems didn't work, i.e. reads with internal adapter (***ADAPTER****) will also be trimmed. So it it because that "$" is not supported in the file?
Any one can help?

Best,
Quan

**Comment by danshu** [comment]
Sorry, I found that this may not be related with "$".
Actually I found that reads that end with ADAPTERN will also be trimmed, and this should be due to the default error rate 0.1 and default seting that allows indel.
My further question would be: is there any smarter method to trim multiple anchored adapter sequences (they are actually the same adapter but lengths vary among different reads) without listing each prefix one by one?

**Comment by marcelm** [comment]
Hi, yes, the `$` is supported even if you use the `file:` syntax. You are right, the error rate and indels being allowed by default explains what you saw.

There is [a trick mentioned in the 'recipes' section of the documentation](http://cutadapt.readthedocs.io/en/stable/recipes.html#forcing-matches-to-be-at-the-end-of-the-read) that you can use: Just specify `-a ADAPTERXXX` with a few `X` characters in the end. These do not match any base, and in this way you can avoid internal matches. Just make sure that there are more `X` characters than the length of the adapter times the error rate.

**Comment by danshu** [comment]
This is exactly what I need! Thanks for you answer!

**Comment by marcelm** [comment]
Alright! Glad I could help.
