### ISSUE TITLE
cutadapt v1.10 '--length-tag' option does not work as expected

### ISSUE THREAD

**Issue by bli25wisc** [marcelm/cutadapt#202]
Hi, 

I have tried cutadapt v1.10 with the --length-tag option. It only modifies the first line of a FASTQ record. For example:

@SRR955864.17 DDLZ38V1:292:D2756ACXX:1:1101:6658:2167 length=42
TTCACCGTGGAGACCGGGGTTCGACTCCCCGTATCGGAGCCA
+SRR955864.17 DDLZ38V1:292:D2756ACXX:1:1101:6658:2167 length=50
CCCFFFFFHHHHHJIJJJJFHJJIJJIIJJJEHHIIJJGHFB

It does not change the 'length=50' at the third line.

**Comment by marcelm** [comment]
Thanks for the report, this is definitely a bug. It’s now fixed in the master branch.

**Comment by bli25wisc** [comment]
Hi @marcelm, thanks for your quick response. Can you let me know if this bug will influence other parts of the program?  For example, if I turn off the --length-tag option, will I get correct results?

Thanks,
Bo

**Comment by marcelm** [comment]
This bug affects only the options that change read names. They are: `--length-tag`, `-x`, `-y` and `--strip-suffix`. If you do not use any of these options, you will be fine.

**Comment by ShanSabri** [comment]
Using v.1.10 and notice that the --length-tag 'length=' is not working. 

command is posted below: 

`/usr/local/bin/cutadapt -a TGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGAT --length-tag 'length=' --minimum-length 15 --too-short-output /Users/shansabri/Dropbox/PlathLab/Analyses/Martina_Roos/2016-08-12/fastq/AGA.trim.too.short.length.update.fq -o /Users/shansabri/Dropbox/PlathLab/Analyses/Martina_Roos/2016-08-12/fastq/AGA.trimmed.length.update.fq.gz /Users/shansabri/Dropbox/PlathLab/Analyses/Martina_Roos/2016-08-12/fastq/AGA.fq.gz
`
Any thoughts?

**Comment by marcelm** [comment]
Version 1.10 still has the problem. I’ve just released 1.11, which includes the fix. Please update, and it should work!
