### ISSUE TITLE
TypeError: quality_trim_index() takes at most 3 arguments (4 given)

### ISSUE THREAD

**Issue by cookersjs** [marcelm/cutadapt#203]
Hello, I have been attempting to use cutadapt in conjunction with another program, trim_galore on a unix cluster. After installing both and attempting to submit a paired end job using this command:

**trim_galore --paired Forward_read.fastq Reverse_read.fastq**

The error message that is output looks like this: 

Quality Phred score cutoff: 20
Quality encoding type selected: ASCII+33
Adapter sequence: 'AGATCGGAAGAGC' (Illumina TruSeq, Sanger iPCR; auto-detected)
Maximum trimming error rate: 0.1 (default)
Minimum required adapter overlap (stringency): 1 bp
Minimum required sequence length for both reads before a sequence pair gets removed: 20 bp
Running FastQC on the data once trimming has completed

Writing final adapter and quality trimmed output to Forward_read_trimmed.fq

  >>> Now performing quality (cutoff 20) and adapter trimming in a single pass for the adapter sequence: 'AGATCGGAAGAGC' from file Forward_read.fastq <<<
This is cutadapt 1.10 with Python 2.6.6
Command line parameters: -f fastq -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC Forward_read.fastq
Trimming 1 adapter with at most 10.0% errors in single-end mode ...
Traceback (most recent call last):
  File "/home/jcook/.local/bin/cutadapt", line 10, in <module>
    cutadapt.main()
  File "/home/jcook/.local/lib/python2.6/site-packages/cutadapt/scripts/cutadapt.py", line 696, in main
    stats = process_single_reads(reader, modifiers, filters)
  File "/home/jcook/.local/lib/python2.6/site-packages/cutadapt/scripts/cutadapt.py", line 115, in process_single_reads
    read = modifier(read)
  File "/home/jcook/.local/lib/python2.6/site-packages/cutadapt/modifiers.py", line 258, in __call__
    start, stop = quality_trim_index(read.qualities, self.cutoff_front, self.cutoff_back, self.base)
TypeError: quality_trim_index() takes at most 3 arguments (4 given)

Is there any potential solutions to this problem? I know both trim_galore and cutadapt work when I use their respective functions as a test, but during the actual analysis this is the farthest I get, usually lasting under 10 seconds.

Thanks!

**Comment by marcelm** [comment]
I changed the `quality_trim_index()` function a while back from 3 to 4 arguments, so I think this is some kind of installation issue where two versions of cutadapt are (perhaps partially) installed at the same time. Try using cutadapt directly, it has had support for proper paired-end trimming for quite a while:
```
cutadapt -q 20 -a AGATCGGAAGAGC -A AGATCGGAAGAGC -o out.1.fastq -p out.2.fastq in.1.fastq in.2.fastq
```
(Or use `fwd` and `rev` instead of `1` and `2` if you want.) See also [the documentation](http://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq).

I do not understand what you mean by this:
> I know both trim_galore and cutadapt work when I use their respective functions as a test

**Comment by cookersjs** [comment]
Thanks I will try it out! And I just meant typing 'trim_galore' or 'cutadapt' to check that the software is actually accessible so that I knew the problem wasn't my PATH or something similar. Thanks again

**Comment by cookersjs** [comment]
So I am able to get cutadapt to perform adaptor trimming, but when I include the -q quality trimming component, I get the same error message. I tried uninstalling cutadapt but didnt have any luck.

**Comment by marcelm** [comment]
Ok, I’m still convinced this is some kind of installation issue. How did you uninstall cutadapt? If you used `pip uninstall`, please try to run it multiple times - if there are multiple versions of a program installed, it will remove only one of them. Just run `pip uninstall cutadapt` until it tells you that the package is not installed. When you have uninstalled it, try to run `cutadapt`, just to make sure that it is really gone. Then re-install it. (Do not use `sudo` unless you know what you are doing.)

You could also [use conda](https://cutadapt.readthedocs.io/en/stable/installation.html#installation-with-conda) instead, this is more reliable and you get access to lots of other software from the bioconda channel as well.
