### ISSUE TITLE
paired-end trimming of reads with short inserts

### ISSUE THREAD

**Issue by germaximus** [marcelm/cutadapt#204]
Hello,

When I trim adapters from paired-end reads, each read is treated independently. This creates rare instances where the read #1 would have zero length (sequenced adapter dimer of some sort), but the read #2 would have a non-zero length (because the number of mismatches exceeded allowed value and adapter was not recognized despite being there). This behavior breaks paired end output files, because an empty line is introduced and some aligners would stuck on them with error. To avoid this I used to specify --minimum-length, but is there a more elegant way? Closely related to it, output paired-end files after trimming are not equal in size, due to the fact that sometimes the adapter is found in one read, but not found in another read. However, logically, if we reach the adapter on one side, we have to reach another adapter no the other side as well. Is there a way to enforce read lengths (forward and reverse) to be equal after trimming? I couldn't find an answer to it in the manual, perhaps this option is already implemented?

Sincerely,

**Comment by marcelm** [comment]
You’re using the `--minimum-length` option in the way it is intended to be used. If you see this type of unbalanced trimming quite often (adapter found in one read but not the other), you may also want to consider increasing the maximum error rate a bit.

Regarding the other type of unbalanced trimming, where an adapter is found in both reads, but the reads still end up having different lengths after trimming, there is no way to enforce equal lengths in cutadapt at the moment. I planned to do this a while back, also using the information that the remaining parts of the reads should be reverse complements of each other (a bit similar to how paired-end read mergers work), but never got around to implementing it. No promises I will do this soon, but could you perhaps share a few examples of such an imbalanced read pair?

**Comment by germaximus** [comment]
Here is a self-explanatory example:
>forward
AATGCGCAGATGACAGGGCGGAACTTGCCAAGTACATGTGTGAAAACCAGGCGACTATCTCCAGCAAACTGC
>reverse
GGAAGACNTCCTTGGCNTCAGCATAGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

And the more real-life relevant:
before trimming
>forward
TTTAATGTAGAAAAGATTAATGGGGAATGGCATACTATTATCCTGGCCTCTGACAAAAGAGAAAAGATAGAAGAT 
>reverse
CATCTCTTACAGTATGGAATTTAAGAACTAAGGAATTCTCCAAGACATGGATTTGCTCCAGAAAAAGTCTAAAGT
after trimming:
>forward
TTTAATGTAGAAAAGATTAATGGGGAATGGCATACTATTATCCTGGCCTCTGACAAAAGAGAAAAGATAGA
>reverse
CATCTCTTACAGTATGGAATTTAAGAACTAAGGAATTCTCCAAGACATGGATTTGCTCCAGAAAAAGTCTAAAGT

I guess it occurs when the partial adapter is found (first few nucleotides), which could happen simply by chance and, therefore, be a false positive detection. In theory, specifying the minimal length of the adapter should help, say at least 6 nucleotides. However it seem better to require adapter verification by the opposing read and, if it does not agree, undo the trimming of the first read.

**Comment by marcelm** [comment]
Thanks for the examples. As I said, it will take some time, but please leave the issue open.

**Comment by FrickTobias** [comment]
I'm running into similar problems where I'm trimming read one for a handle structure and not read two whilst getting both longer and shorter sequences that I should. So something like a r1/r2-specific trimming option would be amazing, at least for the -M option.

**Comment by marcelm** [comment]
I’m closing this issue in favor of #332. Implementing the suggestion there would solve the problem of unbalanced read pairs.

**Comment by FrickTobias** [comment]
Awesome, thanks!
