### ISSUE TITLE
Allowing More Than One Adapter Sequence Removed

### ISSUE THREAD

**Issue by DarioS** [marcelm/cutadapt#209]
Currently, only the best matching adapter is removed. Would support for multiple adapters be feasbile? For example,

![adapters](https://cloud.githubusercontent.com/assets/631218/18577527/9f518de0-7c2d-11e6-93fd-eb6ab61e397f.png)

I guess that it's a rare event, so it depends on how much effort it is to code.

**Comment by marcelm** [comment]
Please see <http://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq>: You also need to remove the `A` preceding the index adapter.

One solution is to pretend that the two adapters are a single adapter. Use a single `-a` option and give cutadapt the sequence of the index adapter (also add a `A` before it) followed by the universal adapter.

Another option is to give cutadapt *only* the index adapter (again, preceded by `A`). Cutadapt removes the adapter *and everything that follows* anyway, so it will also work.

Finally, [there actually is already an option to remove more than one adapter](http://cutadapt.readthedocs.io/en/stable/guide.html#trimming-more-than-one-adapter-from-each-read), which you could also use.

**Comment by DarioS** [comment]
Good ideas.
