### ISSUE TITLE
Missing 1.11 tag

### ISSUE THREAD

**Issue by andrewjrobinson** [marcelm/cutadapt#210]
You have a release on pypi for 1.11 but there is no tag to your source for this version in here.  Presumably it belongs to the following commit (given the commit/upload dates).  Please add tag (and/or push --tags) for this release.

https://github.com/marcelm/cutadapt/commit/a00e63b8b3b9bae5d3b508087dccf6c3f4f32ea8

**Comment by marcelm** [comment]
Thanks, forgot to `push --tags` indeed. Note the corect commit is actually one later at 46bab597.
