### ISSUE TITLE
question, will temporary files be generated during paired end trimming

### ISSUE THREAD

**Issue by lidaof** [marcelm/cutadapt#211]
from the legacy paired end trimming, I see we need to remove temporary files like tmp.1.fastq and tmp.2.fastq, I am using it with current way:

`cutadapt -a ADAPTER_FWD -A ADAPTER_REV -o out.1.fastq -p out.2.fastq reads.1.fastq reads.2.fastq`

will temporary files also being generated during paired end trimming by this way?
I am asking this because I am running cutadapt in parallel (say run 3 trimming at same folder) in one folder has many pairs of fastq files...if tmp.1.fastq and tmp.2.fastq are being generated...probably will mess up the data because you don't know cutadapt is writing tmp.1.fastq......

Thanks a lot.

**Comment by marcelm** [comment]
Cutadapt does not create any temporary files of its own, so running it on multiple files in parellel will work fine. If in the future cutadapt ever needs to create temporary files, I will make sure that it chooses a random file name each time, so even then it will work fine.

**Comment by lidaof** [comment]
​Thank you very much ​Marcel.
That's very helpful for this confirmation.

Daofeng

**Comment by marcelm** [comment]
Glad I could help!
