### ISSUE TITLE
Demultiplex output files missing

### ISSUE THREAD

**Issue by angelinaceballos** [marcelm/cutadapt#213]
I am a beginner in bioinformatics and I am trying to demultiplex my reads from Illumina data with cutadapt.
I want to split my files in folders according to 5 different tags. The file A1_S1_R1.fq correspond with the forward read of my sample in fastq format. I use the commands as in the documentation example:

**cutadapt -a one=CCTATGT -a two=CGTAGAGT -a three=CTGAGAAGT -a four=GATGGTCAGT -a five=AGGATCCAAGT -o trimmed-A1_S1_R1.fq.gz A1_S1_R1.fq**

It analyses the data without showing any problem:
Finished in 2.72 s (80 us/read; 0.75 M reads/minute).

**=== Summary ===

Total reads processed:                  34,253
Reads with adapters:                    32,396 (94.6%)
Reads written (passing filters):        34,253 (100.0%)

Total basepairs processed:     9,059,279 bp
Total written (filtered):        577,157 bp (6.4%)**

 
I should get one file for each tag and other for unknown, but the only thing I get is a file called trimmed-A1_S1_R1.fq.gz  and nothing more. When I remove the -o output I get the same output file but the analysis text seems different.

What I am doing wrong? How can I get my demultiplexed output files?

Thank you very much

**Comment by marcelm** [comment]
Hi, from the example you give, it looks as if you have [read the demultiplexing section in the docs](https://bitbucket.org/whatshap/phasing-comparison-experiments) already. Perhaps it has not become clear enough in that section, but you must have the text `{name}` in the output file name! That is, a literal opening curly brace, then `name`, then a closing curly brace. It may also be a good idea to add quotes around the file name, just to prevent the shell from interpreting the name in any special way (if you use bash, then it would also work without the quotes). It should look like this (of course you can put the `{name}` somewhere else in the file name):
```
cutadapt -a one=CCTATGT -a two=CGTAGAGT -a three=CTGAGAAGT -a four=GATGGTCAGT -a five=AGGATCCAAGT -o "trimmed-A1_S1_R1-{name}.fq.gz" A1_S1_R1.fq
```
The `{name}` will be replaced with the name of the adapter. Thus, five files will be created named `trimmed-A1_S1_R1-one.fq.gz`, `trimmed-A1_S1_R1-two.fq.gz` etc. (If an output file is missing, then no read containing the corresponding adapter was found.)

Please close this issue if that helped you!

**Comment by angelinaceballos** [comment]
Thank you very much, I didn't understand well the example from the docs demultiplexing section but with this clarification I do! I close the topic because now it perfectly works.

**Comment by jlsovaz** [comment]
Hello marcelm,

I am a beginner using cutadapt and I have an issue referring to demultiplex. I have **paired end reads** from 5 different amplicons, so I finally decided to do a cutadapt adding as "adapters" the 5 pairs of primers that flank the five regions of interest. This step was done perfectly without any problem, I finally got my trimmed reads. But I would want to ask you if there is any possibility to obtain a demultiplex output, for example:

cutadapt -text file with 5 pairs of adapters (named: a, b, c, d, e). 
I want to obtain at the end the **output a** with **all reads trimmed for a adapters**, the **output b** with **all reads trimmed for b adapters**...and so on. Now I have a general trimmed output with all the trimmed reads (mix between a, b, c, d and e).

 I hope I've explained my issue correctly.

Thank you in advance,

Jose Luis

**Comment by marcelm** [comment]
Cutadapt 1.14 supports [demultiplexing of single-end reads (see documentation)](https://cutadapt.readthedocs.io/en/stable/guide.html#demultiplexing). The development version of cutadapt also supports [demultiplexing of paired-end reads](https://cutadapt.readthedocs.io/en/latest/guide.html#demultiplexing). (This link goes to the documentation for the development version.)

> I want to obtain at the end the output a with all reads trimmed for a adapters, the output b with all reads trimmed for b adapters...and so on.

Yes, this is exactly what cutadapt will allow you to do!

If you want to demultiplex paired-end data right now, you will have to use the development version of cutadapt. I have just [added a section to the documentation](https://cutadapt.readthedocs.io/en/latest/installation.html#installing-the-development-version) that describes how to do so. Otherwise, you will need to wait until I make a new release, which I plan to do this month.

**Comment by jlsovaz** [comment]
Perfect. Thank you very much for your response.

Although I can wait for the new release, I will try with de development version. So in this develop version, what would be the usage or parameter to perform the demultiplex trimming for paired reads? Using the {name} like in single strand?

Thank you

Jose

**Comment by marcelm** [comment]
Yes, you need to use `{name}` in both output file names. See the second link I posted above.

**Comment by jlsovaz** [comment]
Finally I tried demultiplexing paired ends in my data with the development version and it worked perfectly!

Thank you for your attention,

Jose Luis

**Comment by marcelm** [comment]
Great, I’m glad it helped!
