### ISSUE TITLE
Misleading overview of removed sequences

### ISSUE THREAD

**Issue by AngryMouser** [marcelm/cutadapt#218]
Dear Author,

This is the part of my summary file:

> === Second read: Adapter 2 ===
> 
> > Sequence: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTA; Type: regular 3'; Length: 65; Trimmed: 2252705 times.
> > 
> > No. of allowed errors:
> > 0-9 bp: 0; 10-19 bp: 1; 20-29 bp: 2; 30-39 bp: 3; 40-49 bp: 4; 50-59 bp: 5; 60-65 bp: 6
> > 
> > Overview of removed sequences
> > length	count	expect	max.err	error counts
> > 3	33613	44371.8	0	33613
> > 4	2951	11093.0	0	2951
> > 5	224	2773.2	0	224
> > 6	52	693.3	0	52
> > 7	411	173.3	0	411
> > 8	184	43.3	0	184
> > 9	1020	10.8	0	988 32

So I understand that the number of allowed errors is based on the length of the adapter-read match but in the first column I got the length of the whole removed sequence - not just the match-length but with the suffix as well?
Regardless of that - the main problem is that in the last row the max.err. is set to zero, yet I have two values in the last column. This happens many times though all my results. This is completely misleading. I am totaly confused - how is that possible?

Kind Regards!
M

**Comment by marcelm** [comment]
Hi, sorry for the confusion. The `length` is indeed the length of the whole removed sequence, including the part after the adapter. The `count` column represents how often a sequence of that length was removed, which is probably also quite clear.

The reason why you see a value for one error in the 9 bp row although zero errors should be allowed is that cutadapt allows indels in adapter matches. So in those 32 cases, it must be that the first 10 bp of the adapter match the final 9 bp of a read, so there must be one deletion (relative to the adapter sequence). 

Here is an example:
```
Adapter         CTGTCTCTTATACACATCTGAC...
Read ...AAGGAATTCTGTCTCT-A
```
You can disallow indels with `--no-indels`.

For completeness, I should mention that the `expect` column is an estimate of the count that one would expect if both sequence and adapter were just random. The model is very simple and does not take indels or wildcards into account, so it is better to merely see this as a hint.
