### ISSUE TITLE
concatenated bz2 files are considered differently depending the way that they where concatenated although same md5sum

### ISSUE THREAD

**Issue by rcosentino** [marcelm/cutadapt#222]
Hi,

I had the following issue.

I have several fastq files bz2 compressed, named for example "file1.fq.bz2", "file2.fq.bz2" and "file3.fq.bz2"

I merge them using:

cat file1.fq.bz2 file2.fq.bz2 file3.fq.bz2 > cat_merged_file.fq.bz2

when I ran cutadapt with "cat_merged_file.fq.bz2" to trim the adapter from the reads, I realized that only the reads from the first file concatenated file ("file1.fq.bz2") were being considered ( it took me a while to see it).

then I try merging the reads using:

bzcat file1.fq.bz2 file2.fq.bz2 file3.fq.bz2 | bunzip > bzcat_merged_file.fq.bz2

now, with "bzcat_merged_file.fq.bz2", cutadapt ran as expected considering all the reads.

and the interesting thing to me is that both merged files have the same md5 value as assesed by:

bzcat cat_merged_file.fq.bz2 | md5sum

bzcat bzcat_merged_file.fq.bz2 | md5sum

[Here](https://www.biostars.org/p/81924/) I read that somebody had an issue like this with FastQC and concatenated gzipped files.

**Comment by marcelm** [comment]
This is a limitation of Python 2. See the note in [the Python 2 documentation](https://docs.python.org/2/library/bz2.html):
> This class does not support input files containing multiple streams

I was not aware of this limitation, nor have I tested cutadapt explicitly with concatenated bz2 files, so I have never noticed this. The easiest solution is to use cutadapt under Python 3. That is, when installing, use `pip3 install --user cutadapt` (best to remove the Python 2 version first with `pip uninstall cutadapt`).

Concatenated gzip files *are* supported in both versions, however.

Please leave this report open. It will remind me to update the documentation. Or perhaps I could use the bzip2file module even under Python 2, as described in the note I linked to above.

**Comment by rcosentino** [comment]
thank you very much for the quick answer and help! :)
