### ISSUE TITLE
Different versions, different results !

### ISSUE THREAD

**Issue by davidechiarugi** [marcelm/cutadapt#223]
I have used cutadapt 1.3 and 1.11 on the same bacterial dataset. The results obtained differ markedly in terms of number of output reads (with the version 1.3 I obtain many more reads after the trimming). I kept the same parameters in both versions. Any idea of the reason(s) why ? 

https://www.biostars.org/p/225564/#225987

**Comment by DarioS** [comment]
Consider the read IDs that are unique to a particular version of the software. Then, look at the read sequences and manually identify the adapters. Which version gives more correct results? Different may be better or it may be worse.

**Comment by marcelm** [comment]
I replied on biostars. No reply neither here nor there, so I assume the issue is resolved.
