### ISSUE TITLE
Allow Different Error Tolerance for Sequences

### ISSUE THREAD

**Issue by DarioS** [marcelm/cutadapt#225]
Currently the `-e` option can only be one number. It'd allow more fine control if two numbers could be provided, one for the 5' sequence and one for the 3' sequence.

**Comment by marcelm** [comment]
Thanks for the suggestion, but this has low priority for me since you can usually just leave the error rate at a relatively high setting and it should work fine.

**Comment by marcelm** [comment]
This is finally implemented, but the syntax may appear a bit clunky at first. Use `-a "ADAPTER1;e=0.2" -g "ADAPTER2;e=0.35"` to specify different maximum error rates for the two adapters.
