### ISSUE TITLE
Problem trimming 3' primer

### ISSUE THREAD

**Issue by omeras** [marcelm/cutadapt#229]
Hey,
I'm trying to trim the PCR primers from my barcode-contatining reads. the entire amplicon has the form of
CAATGAAAAGCTTAGTCATGGCGCGCCC...(91-94bp)...CATATGCGTAAAGGCGAAGAGCTGT.

Following demultiplexing I got F reads that look like 
CAATGAAAAGCTTAGTCATGGCGCGCCC...CATATGCG
and R reads
ACAGCTCTTCGCCTTTACGCATATG...GGCGCGCCAT

The trimming of the 5' for both F and R reads is done perfectly, but I get many off-targets for the 3' primer (see attached files for summaries of runs with linked and separated primers).

Is there something that I'm doing wrong? Can I improve the yield of the 3' trimming?

Thanks,
Omer

[linked.txt](https://github.com/marcelm/cutadapt/files/748197/linked.txt)
[separated.txt](https://github.com/marcelm/cutadapt/files/748198/separated.txt)

**Comment by marcelm** [comment]
Since these are PCR primers, you could try to anchor the 3' primer by appending `$` to it. You then need to give the full sequence, so you would use `-a CAATGAAAAGCTTAGTCATGGCGCGCCC...CATATGCGTAAAGGCGAAGAGCTGT$` (and a corresponding `-A` option for the reverse read).

**Comment by marcelm** [comment]
No feedback, closing.
