### ISSUE TITLE
Problem removing reads with adapters

### ISSUE THREAD

**Issue by thorellk** [marcelm/cutadapt#241]
Hi!

I am usually using cutadapt for whole genome sequencing datasets and have never experienced any problems with it but now when I used it for a 16S amplicon dataset I have a problem. The thing is that Cutadapt removes basically all the reads with for me no apparent reason and it feels like I am missing something. 

The dataset is 2*300 bp MiSeq reads and I am running

```
cutadapt -b CCTACGGGNGGCWGCAG -B GACTACHVGGGTATCTAATCC -e 0.15 -q 15 --trimmed-only --trim-n --max-n=3 -m 120 -O 15 -o $fwd_out -p $rev_out $fwd $rev
```
It seems from the logfile that the reads are removed due to being too short after trimming but the quality score per base is not so low that it should trigger removal of > 180 bp. Instead it seems like that the R1 adapters are af some reason not detected in the 3' end of the read but some bp in (I think it is due to that there are 5 random bp inserted in the R1 read during the library prep) but I thought that the -b together with the -O 15 should allow for the detection and correct trimming of these adapters too. I attact the output log file, a multiQC summary of the dataset and a R1 and R2 fastq file of the first 25 reads of the first file. Please let me know if you have any suggestions.

Best wishes,

Kaisa

[troubleshooting_cutadapt.zip](https://github.com/marcelm/cutadapt/files/958907/troubleshooting_cutadapt.zip)

**Comment by marcelm** [comment]
I can look at this in more detail later, but a comment already now: The `-b` and `-B` options are very often not the right ones to choose. You should use it only when your adapter occurs sometimes at the 5' end and sometimes at the 3' end of a read, and this is rarely the case. When you know where an adapter occurs, it is much safer to use the proper `-a` or `-g` option. Also, if you have adapters/primers at both ends, then you may want to use [linked adapters](http://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters-combined-5-and-3-adapter).

**Comment by thorellk** [comment]
Yes, I would also prefer to use -a and -A (I do that for my WGS analyses). The problem is that the R2 adapter always occurs in the 3' end but the R1 adapter can occur > 5 bp into the read since some libraries have random basepairs included in the beginning of the read to increase the diversity of the libraries when running them on the MiSeq, so I thought the -b option could be an alternative to keeping track of which files have the 5 bp insertion and treating them differently. But this might not be the way it works...

**Comment by marcelm** [comment]
But then you can use a regular `-g`. By default, it is not anchored, and the occurrence can be anywhere within the read. Or am I misunderstanding? Perhaps you can sketch how your DNA fragment looks.

**Comment by thorellk** [comment]
Ah, I had missed that -g was not anchored. That worked much better :) Thank you for really fast replies!

**Comment by marcelm** [comment]
Great, glad I could help!
