### ISSUE TITLE
Quality trimming with --nextseq-trim not applied to second read?

### ISSUE THREAD

**Issue by flo-compbio** [marcelm/cutadapt#244]
I'm working with paired-end reads. In the second FASTQ file (containing the second mates of the pairs), I have the following read: 
```
@XYZ
AAANAAAAAAAAAAAAAAAAAAAAAAAAAAGAGGGGAAAGCGGGGGTGGGGGGAAGGGGGGAAGGGAGGGGGGGGGGCGAAAA
+
/FF#FFFFFFFFFFFAFF/FAF//FF/A///////////////F/F////F///////////////////F/AAA//6/////
```
The quality scores of this read are low. The end of the read is all ```/``` = ASCII character 47 - 33 = Phred score 14. However, when I run cutadapt with --nextseq-trim=20, the read is not quality-trimmed at all, while the first read (not shown) is trimmed properly. 

In contrast, when I run cutadapt with -q 20, the second read is trimmed properly:
```
@XYZ
AAANAAAAAAAAAAAAAAAAAAAAAAAAAAGAGGGGAAAGCGGGGGTGGGGGGAAGGGGGGAAGGGAGGGGGGGG
+
/FF#FFFFFFFFFFFAFF/FAF//FF/A///////////////F/F////F///////////////////F/AAA
```
(I know that in this case, it would probably make sense to trim more aggressively. This is just an example to demonstrate this particular behavior of cutadapt.)

If this is the desired behavior, then the documentation should be updated to reflect that. Currently, it [incorrectly states](https://cutadapt.readthedocs.io/en/stable/guide.html#quality-trimming-of-reads-using-two-color-chemistry-nextseq):

> This works like regular quality trimming (where one would use -q 20 instead), except that the qualities of G bases are ignored.

**Comment by marcelm** [comment]
Can you please provide the full command-line that you are using?

**Comment by marcelm** [comment]
Ok, I think I found it. You are correct, Nextseq trimming was only done on the first read - I had not tested it on paired-end data. Should be fixed now. Thanks for reporting!

**Comment by flo-compbio** [comment]
Great, thanks for fixing it!

**Comment by kkanger** [comment]
Hi,
I seem to have the same problem as described above using cutadapt v.1.16 and paired-end data. Poly-G tails in reverse reads were not removed although I  specified the --nextseq-trim=20 option. My full command was:
 cutadapt --nextseq-trim=20 --max-n 0 --minimum-length 35 -o trimmed/sample.R1_trimmed.fastq -p trimmed/V0.R2_trimmed.fastq V0.R1.fastq V0.R2.fastq
