### ISSUE TITLE
Having trouble in generating the info-file

### ISSUE THREAD

**Issue by kingdynasty** [marcelm/cutadapt#248]
` cutadapt --no-indels --no-trim -e 0.05 --minimum-length 20 --maximum-length 150 --max-n 7 -a frm_validated=GT{4}AGAGCTAGAAATAGCAAGTTA{4}TAAGGCTAGTCCGTTATCAACTTGA{5}GTGGCACCGAGTCGGTGCT{6}GCCAC --info-file default_info.txt --untrimmed-output default_untrimmed.fastq -o default_trimmed_{name}.fastq sample_esp_re2.fastq`
After executing the aforementioned command, I inspect the `default_info.txt`,but found some of the fields were not correctly displayed.
some of the reads were perfectly matched with the adapter, however, the `start coordinate of the adapter match` and `end coordinate of the adapter match` was not right.
![image](https://cloud.githubusercontent.com/assets/2476594/26621444/6fad2b6a-4619-11e7-9b96-6afc0ede1cba.png)

Meanwhile, the summary information when finishing executing the command was not correct either.
![image](https://cloud.githubusercontent.com/assets/2476594/26621816/ab47f5be-461a-11e7-8436-2af0fb3a4e00.png)

Total reads processed:                   2,500
Reads with adapters:                       574 (23.0%)
Reads that were too short:                   0 (0.0%)
Reads that were too long:                    0 (0.0%)
Reads with too many N:                   1,883 (75.3%)
**Reads without too many N and passed the adapter trimming** should be the final passing filters which should be  346, not 617.(The actually written reads was correct.)

[sample_esp_re2.fastq.zip](https://github.com/marcelm/cutadapt/files/1040616/sample_esp_re2.fastq.zip)

**Comment by marcelm** [comment]
Thanks for the nice test dataset! This has made it easy to reproduce the behavior you are seeing.

> some of the reads were perfectly matched with the adapter, however, the start coordinate of the adapter match and end coordinate of the adapter match was not right.

Can you explain what you were expecting? Those marked rows contain very short adapter matches - only the first three characters `GTT` of the adapter matched the read. The `-a` adapter type allows these partial matches. You can specify the `--minimum-overlap` option (or `-O` for short) to make sure that only full-length matches are found. Is that it?

> Meanwhile, the summary information when finishing executing the command was not correct either.

617 is the total number of written reads. 346 reads were written to the `default_trimmed_frm_validated.fastq` file and 271 to the `default_untrimmed.fastq` file.

**Comment by kingdynasty** [comment]
@marcelm Thank you for your explanation. I understand the second question.
For the first question, I think it was caused by the partial match. I reset `--overlap 5`, it didn't give the unexpected result anymore.

I changed my command to `cutadapt --no-indels --no-trim -e 0.05 --overlap 5 --minimum-length 20 --maximum-length 150 --max-n 7 -a frm_validated=GTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGAAAAAGTGGCACCGAGTCGGTGCTTTTTTGCCACC --info-file default_info.txt --untrimmed-output default_untrimmed.fastq -o default_trimmed_{name}.fastq sample_esp_re2.fastq`

The total length of the read is 150, the adapter starts from the 21 bp ends with the 108bp, it should be left with 20bp in the 5' end, right? However,  there exist a lot of reads which is shorter than 20bp in the `default_info.txt`.
The adapter length is right. But I set `--minimum-length 20`. I think the selected cells should be `-1` and not being exported to the `efault_trimmed_frm_validated.fastq` file.
![image](https://cloud.githubusercontent.com/assets/2476594/26626287/5a3d0bdc-4629-11e7-837c-3bea175211cf.png)

**Comment by marcelm** [comment]
This is a good point, and I should explain this in the documentation: The info file does not reflect any of the filtering options (such as `--minimum-length'). It simply shows where the adapters were found in the original read. This is a good thing as it allows you to find out *why* a read was filtered (as you did above!). If it had said `-1` in these rows, you wouldn’t be able to distinguish, for example, whether the read was trimmed and then considered to be too short or no adpter was found and it had too many `N` bases.

Note also that `-1` is defined as "no adapter found", so writing a `-1` for filtered reads would be incorrect.

Since it’s a tabular format, you can process it further easily with an `awk` script or similar. This way, you can filter it exactly the way you want.

However, I agree this should be pointed out in the documentation.

**Comment by marcelm** [comment]
Thanks, I’ve updated the documentation.
