### ISSUE TITLE
cutadapt hangs

### ISSUE THREAD

**Issue by tommycarstensen** [marcelm/cutadapt#249]
I'm running cutadapt with these settings `-a "A{75}"`. It seems to run to completion, but it hangs with this message at the end:

```Trimming 1 adapter with at most 10.0% errors in single-end mode ...```

**Comment by marcelm** [comment]
It’s not hanging, it’s working! Cutadapt does not print any messages while it processes the input. Just wait until it is done. When `-a A{75}`, it trims about 4 million reads per minute on my machine, which should give you an idea of how long it will take.

**Comment by tommycarstensen** [comment]
Thanks! It does indeed run to completion (as confirmed by a line count), but the process doesn't exit. Very odd. Anyway, it's not an error, because it works. I'm closing.

**Comment by marcelm** [comment]
Ok, then that could actually be a bug somewhere. I think I fixed a bug related to hanging a while ago. If you see this again, please make sure you update to the most recent cutadapt version. If you still see it, please tell me! (You can re-open this bug report.)

**Comment by tommycarstensen** [comment]
I did `pip install`, so I might not have the latest version. I'll let you know. All jobs ran to completion.
