### ISSUE TITLE
pair-filter doesn't affect if cmdline only with `-m` option with paired data

### ISSUE THREAD

**Issue by lpantano** [marcelm/cutadapt#250]
Hi!

Thanks for keep this awesome tool alive.

I work on Harvard Chan School and we teach a course in NGS. We teach cutadapt, and we have noticed that maybe there was an unexpected behavior. We were filtering empty lines in a paired fastq files, and the only way to get it done in a way that if any of the file had empty sequence was to add the parameter to the command line: `pair-filter=any`.

I think this is maybe because only `-m` parameter was used and the tool setup the legacy mode where `paired=first` inside the code.  Maybe an extra line in the help pages saying that you need to setup `pair-filter` if only using some options, for instance when only using `-m` options that won't turn off the legacy mode.

I can send a tiny example. I don't know if this is desired output, but I think a hint in that specific parameter will help people in case they wanted to remove only empty lines from any of the paired files (specifically if they are in the second file).

Thanks!

**Comment by marcelm** [comment]
Hi, great to hear you are teaching your students how to use cutadapt :-). Your analysis is correct: When "legacy mode" is in effect, the `-m` option looks only at the first read in a pair. I know this is a bit unfortunate, but so far I have wanted to keep this behavior for compatibility with older versions of cutadapt.

I had added a warning message to cutadapt a while ago to make this clear, but I see now that it is not triggered in all cases it should be. I have fixed this now. This is the message that you will get:

```
Trimming 0 adapters with at most 10.0% errors in paired-end legacy mode ...
WARNING: Legacy mode is enabled. Read modification and filtering
options *ignore* the second read. To switch to regular paired-end
mode, provide the --pair-filter=any option or use any of the
-A/-B/-G/-U/--interleaved options.
```
Do you think this is sufficient?

If I ever release a new major version of cutadapt, I will definitely get rid of this behavior.

**Comment by lpantano** [comment]
thanks a lot!
