### ISSUE TITLE
keep primers in assembled reads

### ISSUE THREAD

**Issue by Gian77** [marcelm/cutadapt#251]
Hello,
I have a simple (maybe stupid) question as I was not able to find a solution in the cutadapt manual. Is there a way to keep primers in assembled illumina reads but trimming off all the illumina adapters?
I would like to obtain a situation like this example:

pre-trim:    ...adapter - primer1 - target fragment - primer2 - adapter...
post-trim:                     primer1 - target fragment - primer2

Thank you so much in advance,
Gian

**Comment by marcelm** [comment]
Do I understand correctly that you would like to trim sequences that were obtained from merging paired-end reads? You can use a [non-anchored linked adapter](https://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters-without-anchoring):
```
cutadapt -g adapter1...adapter2 (further options)
```
I believe you can use the sequences mentioned in the [TruSeq trimming section in the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq) except that you need to use the not-reverse-complementedTruSeq Universal Adapter. So potentially this works: `-g AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC...AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT`. This may be wrong though, better test it for yourself.

**Comment by Gian77** [comment]
Hello Marcel,
thank you very much for your quick answer. Yes, my reads are assembled R1 and R2 Illumina MiSeq 16S reads and yes, I want to remove everything is "outside" the primers but I want to keep the primers in my reads :)
Gian

**Comment by marcelm** [comment]
Forgot to close this, I hope this is solved.
