### ISSUE TITLE
Cutadapt files not working in mothur

### ISSUE THREAD

**Issue by alfbiome** [marcelm/cutadapt#259]
Hi,
I have a MiSeq run for 16s but my PI is curious about how the data might look in if we ran it in HiSeq. So I shortened my reads using Cutadapt to simulate how this might look. However when I did this I could not run the make.contigs command in mothur. I tried it with my files that were not cut, and I could run the command just fine, but as soon as I use cutadapt I can't get my files to work in mothur. 
This is the code I used to cut sequences in cutadapt:
`import os

target_dir='AndrewHiSeqTest/'
results_dir='cutadapt_out100/'
files=os.listdir(target_dir)

os.system('mkdir '+results_dir)

for file in files:
	filename=file.split('.')[0]
	fileending=file.split('.')[-1]
	if fileending == 'fastq':
		target=target_dir+file
		output='-o '+results_dir+filename+'.output.fastq'
		if '_R1_' in file:
			length='-u 100'
		elif '_R2_' in file:
			length='-u 100'

		os.system('cutadapt '+length+' '+output+' '+target)`

The error that I keep getting in mothur is
[WARNING]: reading @M04398:45:000000000-B8765:1:1103:26828:9594 expected a name with + as a leading character, ignoring.
[WARNING]: names do not match. read + for fasta and @M04398:45:000000000-B8765:1:1103:26828:9594 for quality, ignoring.[WARNING]: reading + expected a name with @ as a leading character, ignoring read.
I also get
[WARNING]: reading @M04398:45:000000000-B8765:1:1117:11399:20938 expected a name with + as a leading character, ignoring.[WARNING]: names do not match. read + for fasta and @M04398:45:000000000-B8765:1:1117:11399:20938 for quality, ignoring.[WARNING]: Lengths do not match for sequence +. Read 176 characters for fasta and 1 characters for quality scores, ignoring read.
quitting command..
I know my process for simulating MiSeq to HiSeq so I might be beyond the scope of what is possible in cutadapt, but I thought I'd ask just in case.
Thank you!

**Comment by marcelm** [comment]
Can you please post the actual cutadapt command that you are running?

How long are the MiSeq reads and how long do you want the HiSeq reads to be? Do you want to remove bases from the 5' end or from the 3' end?

**Comment by marcelm** [comment]
It would also be helpful to see the part of the FASTQ file around the read that mothur complains about. It seems that mothur ends up in the wrong lines in the file while reading the FASTQ file.

Assuming your command is `cutadapt -u 100 -o out.fastq in.fastq`, I’m certain that cutadapt will produce a correct FASTQ file in which each read is shortened by 100 bases. So in principle, the command should work.

One wild guess: If some of your input reads are 100 bases or less, then cutadapt trims those reads down to a length of zero, producing empty lines in the output file. Perhaps mothur has problems with those?

**Comment by marcelm** [comment]
No reply, closing.
