### ISSUE TITLE
Min Overlap Issues When Trimming 3' Adapters

### ISSUE THREAD

**Issue by Daniel-Liu-c0deb0t** [marcelm/cutadapt#260]
I'm not sure if this is an actual issue, or if it is a feature and I'm just misunderstanding, but on some reads, the trimmed portion has a smaller length than the minimum overlap.
Here are 2 examples (bolded part should be where the adapter match appeared):

Sequence: ...CGTCGGCCGGGCGAACCTGCAGTAGTGGCATAGGTGTTCCAT**GGATCGG**
Trimmed: ...CGTCGGCCGGGCGAACCTGCAGTAGTGGCATAGGTGTTCCAT
Adapter: **AGATCGG**AAGAGCGGTTCAGCAGGAATGCCG

Sequence: ...TAATCCCTAGGATTATCACAGTTTAGCGGCAAGGTGGTTGCATT**AGATGG**
Trimmed: ...TAATCCCTAGGATTATCACAGTTTAGCGGCAAGGTGGTTGCATT
Adapter: **AGATCGG**AAGAGCGGTTCAGCAGGAATGCCG

The beginning of the reads is omitted so it isn't too long. The min overlap (-O) is 8 and the edit threshold (-e) is 0.25.
I took a look at the code and added some print statements. For both reads, I got 8 as the length of the overlaps and 2 as the number of edits (indels and mismatches). Unless I am mistaken, the trimmed regions of the two sequences both has less than 8 bp (overlap). I know that insertions and deletions will change the length of the sequence, but that still does not explain the results of these two sequences. Also, the edit distance between the trimmed portion and the first few bp of the adapter is 1, instead of 2. These two reads should have not been trimmed, but for some reason they had.
If I'm wrong about this, please tell me what I misunderstood.
Thanks.

**Comment by marcelm** [comment]
I’m traveling and will have more time to later, but I believe that an alignment like this is found in the first example:
```
...GGATCG-G
   AGATCGGA AGAGC...
```
Note that the overlap is counted in terms of overlapping adapter bases. The algorithm prefers alignments with fewer edits, but if is not possible to find one within the given constraints, it choses suboptimal ones (two edits, but eight overlapping bases such as in this example). One the one hand, this could be seen as a bit unexpected, but in this case, it is an artifact of the relatively high error rate that is allowed. Saying that 25% errors are ok implies that things like the above are ok. And in fact, if the sequencing error rate actually *is* 25%, then I would say that the above is totally fine.

**Comment by Daniel-Liu-c0deb0t** [comment]
Ok thanks, that makes some sense now.

**Comment by marcelm** [comment]
Closing as we discussed and solved this via private e-mail.
