### ISSUE TITLE
need advice Stagger Sequence Adapter Trimming

### ISSUE THREAD

**Issue by mortunco** [marcelm/cutadapt#261]
Hi,

First I would like to thank developer group for coming up with a convenient and easily usable tool. I would like to ask a question rather than a issue regarding the software.

**Background:**
We are working on crispr screen analysis. Simply, we have small guide RNA (sgRNA) which are targeting specific locations on genes and we are looking for if the loss of a gene effects specific phenotype. In our library we have a stagger sequence in addition to the 5'prime-3'prime adepters. So our adapter sizes on the 5'prime-3'prime are dynamic. Therefore I cannot use fixed base trimming. So far I have come up with different solutions so I would like to hear what would be your solution to this kind of problem.

In ex:
The red highlighted part is the sgRNA part of the read and as you can see two adjacent sequences at 5' and 3' are same. The sequences on the both ends however are stagger sequences which has variable size.

<img width="1183" alt="screen shot 2017-09-25 at 14 04 30" src="https://user-images.githubusercontent.com/12833865/30921610-8ccd6aae-a3af-11e7-9443-b22c8a72472c.png">

**My Attempts:**

1) By using "Trim a fixed number of bases after adapter trimming" option in the wiki. I removed both of the adapters in two steps. My mappability was %60 percent.

2) I was thinking to remove 5' prime adaptor, then extract first 20 bases from the read ( all of my sgRNAs are 20 bp). I couldn't do this solely using cut adapt because "Removing a fixed number of bases" doesn't not keep the removed part so I have to use another tool. With this method my mappability was %50

**My questions:**
1) Is there a standard procedure for this kind of a problem? 
2) What do you think about my initial attempt ? Do you think I can get rid of those staggers sequences by using "Trim a fixed number of bases after adapter trimming" method ?
3) How can I modify cut adapt to extract specific regions. Say I removed the 5' prime adaptor and I would like to pick only 1-20 bp and remove the rest of the read?
4) Is there an easy way to just remove everything on the upstream of 5' prime adaptor and downstream of 3'prime to leave sgRNA seqeuce alone in a read without considering those stagger sequences ?

Thank you very much for your help and sorry for the long post.

Best regards,

Tunc.

**Comment by marcelm** [comment]
Hi, before I can reply, can you clarify a bit how you would like your sequence to be transformed? So how does a single sequence look, and how should it look after cutadapt is done with it? (And what are the sequences that you have highlighted in the screenshot?)

**Comment by mortunco** [comment]
Thank you for the fast reply.

Our aim is to leave sgRNA sequence alone after trimming. Because in the next step we map them with bowtie2 to index files based on our custom made library.

In the given example, I highlighted sgRNA sequence couple reads. Our aim is to remove everything on the 5' and 3' sides and leave sgRNA alone. As I stated in my first post, adjacent sequences of the reads are same. However the ends are different because of the stagger sequences. Stagger sequences are addition to the 5' and 3' adapters.

I am more than happy to give more information to explain the problem. Thanks for your help.

**Comment by marcelm** [comment]
I don’t know too much about CRISPR screening, so you need to be even more specific. I will try to explain what I don’t understand.

[As far as I know](https://www.nature.com/nprot/journal/v8/n11/fig_tab/nprot.2013.132_F3.html), the sequences you highlighted in the image are the "spacer" part of the sgRNA (the base-pairing region), and the full sgRNA actually extends further towards the 3' end. Using that terminology, your reads seem to look like this:
```
5' - some_sequence - spacer - rest_of_sgrna - some_other_sequence - 3'
```
I don’t understand which part of the read you want to retain. You said:
> In the given example, I highlighted sgRNA sequence couple reads. Our aim is to remove everything on the 5' and 3' sides and leave sgRNA alone.

Is it correct that you want to remove everything from each read except for the spacer? That is, get rid of "some_sequence", "rest_of_sgrna" and "some_other_sequence" such that it looks like this:
```
5' - spacer - 3'
```
This would only make sense if you have many different sgRNAs.

**Comment by mortunco** [comment]
For sgRNAs we have 1683 unique RNA which cover ~300 genes. All of the genes have 5-7 sgRNA which are targetting different part of the same gene but each one is unique. 

I am not sure about the spacer part but let me explain what I know with your shematic representation.

```
5'- (stagger in my) - 5' Adapter- Unique SgRNA Sequence (1683) - 3' Adapter - stagger sequence - 3' 
```
These stagger sequences does not let me make a fixed cuts because their sizes varies. So if 5' stagger is one base than 3' is 6 base. Thefore they always add up to 7 bp.
There is nothing after 5' and 3' they just represent directionality.

**Comment by marcelm** [comment]
So is it correct that all you want to keep is the unique sgRNA sequence? Then you should be able to use a [linked adapter without anchoring](https://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters-combined-5-and-3-adapter) (read also the subsequent section when you follow the link):
```
cutadapt -g MY_5PRIME_ADAPTER...MY_3PRIME_ADAPTER -o out.fastq.gz in.fastq.gz
```
Where of course you replace the `MY_5PRIME_ADAPTER` and `MY_3PRIME_ADAPTER` with the correct sequence. The three dots are literal dots, they stay as they are.

This will work even in the presence of a "staggered sequence" before the 5' adapter or after the 3' adapter.

**Comment by mortunco** [comment]
Dear Marcel,

Thank you very much for your help and especially for your patience. I will report the results asap.
