### ISSUE TITLE
Installation Fails if Operating System is Windows

### ISSUE THREAD

**Issue by DarioS** [marcelm/cutadapt#263]
Although the Visual C++ dependency is installed, the output of `pip install cutadapt` can't find it

```
running build_ext
building 'cutadapt._align' extension
error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
```

The Microsoft Visual C++ Compiler for Python 2.7 installer doesn't have any option for choosing the installation directory, so installs into a directory the user has write access to, which is probably unknown to the Python installer.

Also, `cutadapt`'s documentation doesn't specify which operating systems it is intended to work with.

**Comment by marcelm** [comment]
I don’t use Windows myself, so I cannot help unfortunately. I would guess that the problem you are having is one that does not only apply to cutadapt, so you may be able to find a solution somewhere if you leave out 'cutadapt' from the search terms.

While I don’t support usage of cutadapt on Windows myself, I’d be willing to update the documentation with some instructions if you do find a solution to this.

I’ll mention which operating systems are supported in the documentation and then close this issue.

**Comment by DarioS** [comment]
The office computer I couldn't get it to run on has a mix of directories on the network and the computer's hard drive. On my laptop computer, where everything is on the hard disk, I only needed to install [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266) and cutadapt (and other Python installations) worked.

**Comment by marcelm** [comment]
Thanks! I’ve added this to the docs in 04e3af02c6c1ef3e8bb7fcd8c0c2b82644ce19d0
