### ISSUE TITLE
All trimmed reads seem to be discarded

### ISSUE THREAD

**Issue by kosapa** [marcelm/cutadapt#264]
Hi,
 I have paired-end reads and I try to remove the adapters. And I want to keep the reads from which the adapters are chopped off, rather than trimming and then discarding all of them.
The program (v. 1.14) seems working fine except that it discards all my reads. I have even attempted using --trimmed-only option as it should be mutually exclusive to --discard-trimed, but still it seems to run as if --discard were active.
pls let me know how to proceed.

My command line looks like:

 cutadapt -a GGATAGTCAAGGTCAGGTGG -A GACGCTGGAATGTAACAATGG --trimmed-only -o NR05_S21_R1trimmedonly.fastq -p NR05_S21_R2_trimmedonly.fastq  NR05_S21_L001_R1_001.fastq  NR05_S21_L001_R2_001.fastq
 
The report it gives looks like:

This is cutadapt 1.14 with Python 2.7.9
Command line parameters: -a GGATAGTCAAGGTCAGGTGG -A GACGCTGGAATGTAACAATGG --trimmed-only -o NR05_S21_R1trimmedonly.fastq -p NR05_S21_R2_trimmedonly.fastq NR05_S21_L001_R1_001.fastq NR05_S21_L001_R2_001.fastq
Trimming 2 adapters with at most 10.0% errors in paired-end mode ...
Finished in 1.18 s (36 us/read; 1.67 M reads/minute).

=== Summary ===

Total read pairs processed:             32,969
  Read 1 with adapter:                  32,920 (99.9%)
  Read 2 with adapter:                  32,799 (99.5%)
Pairs written (passing filters):        32,754 (99.3%)

Total basepairs processed:    16,539,683 bp
  Read 1:     8,274,854 bp
  Read 2:     8,264,829 bp
Total written (filtered):          1,780 bp (0.0%)
  Read 1:           285 bp
  Read 2:         1,495 bp

=== First read: Adapter 1 ===

Sequence: GGATAGTCAAGGTCAGGTGG; Type: regular 3'; Length: 20; Trimmed: 32920 times.

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20 bp: 2

Bases preceding removed adapters:
  A: 0.0%
  C: 0.0%
  G: 0.1%
  T: 0.0%
  none/other: 99.9%

Overview of removed sequences
length  count   expect  max.err error counts
3       1       515.1   0       1
239     1       0.0     2       1
241     1       0.0     2       1
247     3       0.0     2       2 1
248     45      0.0     2       38 6 1
249     24      0.0     2       21 3
250     179     0.0     2       153 24 2
251     32666   0.0     2       29961 2552 153

=== Second read: Adapter 2 ===

Sequence: GACGCTGGAATGTAACAATGG; Type: regular 3'; Length: 21; Trimmed: 32799 times.

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20-21 bp: 2

Bases preceding removed adapters:
  A: 0.0%
  C: 0.0%
  G: 0.0%
  T: 0.0%
  none/other: 99.9%

Overview of removed sequences
length  count   expect  max.err error counts
3       5       515.1   0       5
4       1       128.8   0       1
246     2       0.0     2       2
248     6       0.0     2       5 1
249     583     0.0     2       516 46 21
250     9088    0.0     2       8470 579 39
251     23114   0.0     2       22398 684 32

**Comment by marcelm** [comment]
It seems you are not using the correct adapter type. From the report, it appears that both adapter sequences you gave are found at the 5' end of the R1 and R2 reads. If you use `-a` to provide an adapter sequence, you are saying that the sequence is a 3' adapter. If cutadapt finds the sequence, it will trim the adapter and everything that follows. If the adapter is found in the 5' end of a read, this means that everything will be removed and you get a read of length zero (an empty read).

I believe you should use an [anchored 5' adapter](https://cutadapt.readthedocs.io/en/stable/guide.html#anchored-5-adapters) instead. That is, specify your adapter sequences in this way: `-g ^GGATAGTCAAGGTCAGGTGG` and `-G ^GACGCTGGAATGTAACAATGG`.

I believe that then also `--trimmed-only` should work in the way you expect it.

**Comment by kosapa** [comment]
You are right.
I was blind, sorry for the stupid question.
U R a genius, 
Thanks a lot for the help.

**Comment by marcelm** [comment]
No question is stupid. Glad I could help!
