### ISSUE TITLE
--minimum-length on paired-end data doesnt remove READ2

### ISSUE THREAD

**Issue by YanaMa** [marcelm/cutadapt#267]
Hi,
Im using cutadapt to shorten my paired-end reads to a fixed length (65bp) before downstream analysis and using a minimum lenght of 20 as follows:

cutadapt --length 65 -a ${ADAPTOR1} -A ${ADAPTOR2} --minimum-length 20 --pair-filter=both -o ${FASTQ_OUTPUT_1} -p ${FASTQ_OUTPUT_2} ${READ1} ${READ2}

When aligning the fastq with STAR it complains that one of the matched read pairs have a zero value. 
I can see that trimmed_READ1 has a sequence however there is no sequence on trimmed_READ2 (the adaptor sequence was found in the beginning of the read and thus the whole READ2 was removed).

How can I make sure that BOTH paired reads are removed if one read is less than 20?
I thought --minimum-length 20 --pair-filter=both would do the trick but apparently not.

Thank you in advance for any help and apologies if it's obvious!

**Comment by marcelm** [comment]
Hi, have you tried this without `--pair-filter=both`? That is likely the problem. I will make this clearer in the documentation and get back to you shortly.

**Comment by YanaMa** [comment]
Hi, 
Thanks for quick reply!

Your suggestion to run without "--pair-filter=both" worked fine this time, and STAR was able to successfully finish its run.
Thank you for your help!

**Comment by marcelm** [comment]
I’ve updated the documentation slightly. Have a look at <http://cutadapt.readthedocs.io/en/latest/guide.html#filtering-paired-end-reads> if you want to know why it worked to remove `--pair-filter=both` from your options.
