### ISSUE TITLE
cutadapt trimming bad quality ends

### ISSUE THREAD

**Issue by iadamo1** [marcelm/cutadapt#268]
Hi
I am new cutadapt user and I have a question on trimming the bad quality ends. 
I have followed the manual on the use of the -q command.
I have a question which might be a very basic one: is it possible to translate the error probability limit of 0.02 used to trim the bad quality ends e.g in Geneious in the numbers that follow the command -q? 
thanks a lot for any help

**Comment by marcelm** [comment]
Can you clarify: Is it correct that Geneious allows you to specify a number such as 0.02 for quality trimming? And that you would like to know whether that number can be converted to a number that cutadapt’s `-q` option understands?

If so, then no, I don’t know how to do so. I assume that Geneious’ trimming algorithm works differently than the one in cutadapt and that it is therefore not possible (cutadapt uses the same algorithm as the one in BWA. Might help when you search the web).

**Comment by iadamo1** [comment]
thanks for your answer! I will look at BWA, because my doubt is how to choose the number to use when trimming the ends.

**Comment by marcelm** [comment]
I think a good start would be `-q 20`, but I haven’t evaluated this systematically.
