### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sk-bioinfo** [marcelm/cutadapt#269]
Dear author,

I tried to install cutadapt current version using following command, but getting the below error. Can you please help? (replaced my working directory with ./)

python3 -m venv ./cutadapt-venv ./cutadapt-venv/bin/pip install Cython ./cutadapt-venv/bin/pip install git+https://github.com/marcelm/cutadapt.git/
Error: Unable to create directory './cutadapt-venv/bin/pip'

I'm trying to test your latest addition of multi-threading :)

**Comment by marcelm** [comment]
Thanks for testing! You seem to have typed this as one single command, but it is actually three different ones that you need to run one after the other. First:
```
python3 -m venv ./cutadapt-venv
```
Then:
```
./cutadapt-venv/bin/pip install Cython
```
Finally:
```
./cutadapt-venv/bin/pip install git+https://github.com/marcelm/cutadapt.git/
```

**Comment by sk-bioinfo** [comment]
Gosh! Embarrassing error :) Sorry about that and thanks for the quick reply.

Tried running the commands and am getting this error:
./cutadapt-venv/bin/pip install git+https://github.com/marcelm/cutadapt.git/
Collecting git+https://github.com/marcelm/cutadapt.git/
  Cloning https://github.com/marcelm/cutadapt.git/ to /tmp/pip-9uy4xoje-build
fatal: https://github.com/marcelm/cutadapt.git//info/refs not found: did you run git update-server-info on the server?
Command "git clone -q https://github.com/marcelm/cutadapt.git/ /tmp/pip-9uy4xoje-build" failed with error code 128 in None

**Comment by marcelm** [comment]
Weird, I don’t get this error with the exact same command. Can you retry to check whether it was a transient error on GitHub? If that still does not work, use this command instead:
```
./cutadapt-venv/bin/pip install https://github.com/marcelm/cutadapt/archive/master.zip
```

**Comment by sk-bioinfo** [comment]
Thanks a lot Marcel. The zip archive worked!

**Comment by marcelm** [comment]
Great! I’ll update the instructions. Seems to be the safer option.
