### ISSUE TITLE
Finish multi-core support

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#270]
Cutadapt now has most of the infrastructure in place to run on multiple cores if running under Python 3. It works, but is currently limited to processing a single input and output file. If necessary, it automatically falls back to the previous single-core code. For the next release, some things remain to do. This issue is meant to track progress.

# Next release

* [x] Support `--interleaved` for FASTQ files (when both input and output is interleaved).
* [x] Support interleaved input and non-interleaved output.
* [x] Support paired-end FASTQ input and output.
* [x] Support paired-end FASTA input and output. Alternatively, make the code that automatically downgrades to single-core aware of the file format and be able to detect this.
* [x] Correctly handle malformatted input (the process hangs at the moment since the exception from the reader process is not propagated to the main process).
* [x] Run tests with a smaller buffer size (to test the code that splits up FASTA/FASTQ into multiple chunks)
* [x] Ensure reading data from stdin works.
* [x] Prevent automatic fallback to single-core mode when executing tests that should actually run in parallel.
* [x] Detect and error out if a FASTA or FASTQ record is bigger than the buffer size (making the buffer size dynamic is for later).
* [x] The `--cores` option defaults to the number of available cores at the moment. Decide whether that is the right behavior (or whether running on a single core should be the default).
* [x] Figure out whether `xopen` should spawn a subprocess or use an in-process `gzip.open()`.
* [x] Measure speedups.
* [x] Add a section to the documentation.

# Later

* Ensure that error messages referring to line numbers in the input FASTA/FASTQ are correct.
* Support for `--info-file`, `--rest-file`, `--wildcards-file`, `--untrimmed-output`, `--too-short-output`, `--too-long-output` (and the `...-paired-output` versions of these options)
* Support `--interleaved` for FASTA files. Alternatively, make the code that automatically downgrades to single-core aware of the file format and be able to detect this.
* Multi-core demultiplexing.
* Add tests for statistics (this has been on my to-do list for a while, it can wait a bit longer)

# Not planned

* Multi-core processing of colorspace data. Doable, but for anyone who is stuck processing SOLiD data, this is probably just a minor nuisance.
* Multi-core support on Python 2. Patches that are not too intrusive are welcome, but I cannot spend time on this myself.

**Comment by avilella** [comment]
Would a command-line like this be multithreaded with current master branch?

```
cutadapt --cores 4 --no-trim --overlap 40  -b TACGATCACGGCGAATCCGATCGAATCAGTCAAGCGCTTTACGAAGTGCGACAGCCTTAG -b ATGCTAGTGCCGCTTAGGCTAGCTTAGTCAGTTCGCGAAATGCTTCACGCTGTCGGAATC -b TACGATCACGGCGAATCCGATCGAATCCTTGTAGCGCTTTACGAAGTGCGACAGCCTTAG -b ATGCTAGTGCCGCTTAGGCTAGCTTAGGAACATCGCGAAATGCTTCACGCTGTCGGAATC -b TACGATCACGGCGAATCCGATCGAATCACAGTGGCGCTTTACGAAGTGCGACAGCCTTAG -b ATGCTAGTGCCGCTTAGGCTAGCTTAGTGTCACCGCGAAATGCTTCACGCTGTCGGAATC  -B TACGATCACGGCGAATCCGATCGAATCAGTCAAGCGCTTTACGAAGTGCGACAGCCTTAG -B ATGCTAGTGCCGCTTAGGCTAGCTTAGTCAGTTCGCGAAATGCTTCACGCTGTCGGAATC -B TACGATCACGGCGAATCCGATCGAATCCTTGTAGCGCTTTACGAAGTGCGACAGCCTTAG -B ATGCTAGTGCCGCTTAGGCTAGCTTAGGAACATCGCGAAATGCTTCACGCTGTCGGAATC -B TACGATCACGGCGAATCCGATCGAATCACAGTGGCGCTTTACGAAGTGCGACAGCCTTAG -B ATGCTAGTGCCGCTTAGGCTAGCTTAGTGTCACCGCGAAATGCTTCACGCTGTCGGAATC CEG73-8-1PC_S1_L002_R1_001.fastq.gz CEG73-8-1PC_S1_L002_R2_001.fastq.gz --untrimmed-output /home/dnanexus/temp/CEG73-8-1PC_S1_L002_R1_001.SQmf.fq.gz --untrimmed-paired-output /home/dnanexus/temp/CEG73-8-1PC_S1_L002_R2_001.SQmf.fq.gz -o /home/dnanexus/temp/CEG73-8-1PC_S1_L002_R1_001.tmp.fq.gz -p /home/dnanexus/temp/CEG73-8-1PC_S1_L002_R2_001.tmp.fq.gz 1>/home/dnanexus/temp/CEG73-8-1PC_S1_L002_R1_001.SQmf.log 
```

**Comment by marcelm** [comment]
No, `--untrimmed-output` and `--untrimmed-paired-output` are not supported, yet.

**Comment by avilella** [comment]
Gotcha, I was going mad trying to understand why it was only using 1 core.
I will keep an eye for this. Thanks!

**Comment by marcelm** [comment]
Hm, sorry about that. I thought I had changed it such that it would print an error when you try to use `--cores` but one of the command-line parameters doesn’t support it. I’ll look into it.

**Comment by marcelm** [comment]
Regarding the `--cores` option, I’ve decided to make `--cores=1` the default in this release. This will allow anyone who knows about the option to test it, and anyone else will get the stable single-core code paths. When I’ve fixed any reported issues and am sure it’s stable, multi-core can be made the default.

**Comment by marcelm** [comment]
[Cutadapt 1.15 is now released](https://twitter.com/marcelm_/status/933688295749570560)

**Comment by eboyden** [comment]
Wondering if multicore support for the options below is still being actively worked on (particularly --untrimmed-output and --untrimmed-paired-output).

ERROR: Running in parallel is currently not supported for the given combination of command-line parameters.
These options are not supported: --info-file, --rest-file, --wildcard-file, --untrimmed-output, --untrimmed-paired-output, --too-short-output, --too-short-paired-output, --too-long-output, --too-long-paired-output, --format
Also, demultiplexing is not supported.
