### ISSUE TITLE
read name modification when using cutadapt

### ISSUE THREAD

**Issue by ctekellogg** [marcelm/cutadapt#271]
Hello,
I recently used cutadapt to trim primers from merged MiSeq reads.  In the process of doing this the sequence name was modified. For instance:

@M01170:40:000000000-APGB7:1:1101:10000:11703 1:N:0:AGACTATTTCAT 
becomes
@M01170:40:000000000-APGB7:1:1101:10000:11703

Is there a way to stop this from happening?  Or away to manually do this to my index file, which I need to match my reads file.

Thank you so much! 

colleen

**Comment by ctekellogg** [comment]
In the end I was able to use sed to remove the string beginning with 1:N:0: from files not processed by cutadapt.

**Comment by marcelm** [comment]
Cutadapt should never modify read names in this way. Perhaps it was actually the read merger that did this? If you are sure it was cutadapt, please re-open this issue.

**Comment by gabriella-quinn** [comment]
I just figured out this happens if you run cutadapt through "Trim galore!". Hopefully that helps someone
