### ISSUE TITLE
Running in parallel incompatible arguments

### ISSUE THREAD

**Issue by jma1991** [marcelm/cutadapt#274]
Using this command:
```cutadapt -a AGATCGGAAGAGC -f fastq -e 0.1 -O 3 -q 20 -m 20 -o output.fastq.gz input.fastq.gz > cutadapt.log```
I get this error:
`ERROR: Running in parallel is currently not supported for the given combination of command-line parameters.`
None of the options listed as incompatible with parallel processing in the README are in my command?

**Comment by marcelm** [comment]
Just omit the `-f fastq` option. The input file format can be auto-detected anyway.

**Comment by jma1991** [comment]
Working now, thank you for the quick reply!

**Comment by marcelm** [comment]
:-)
