### ISSUE TITLE
trouble with --cores=N on mac - cutadapt reverts to using python 2 when I want it to use python 3

### ISSUE THREAD

**Issue by sxrastogi** [marcelm/cutadapt#277]
I have been trying to use the --cores=N feature of cutadapt 1.15 on my mac machine.  My computer came pre-installed with python 2.7.  I installed the latest version of python, 3.6, to try and use multiple cores while running my job.  However, cutadapt defaults to using python 2.7.  I am not computer savvy, so I may be missing something completely obvious.  How can I get cutadapt to start using python 3.6 instead of 2.7?  Thanks!!

**Comment by marcelm** [comment]
I don’t have access to a macOS machine, but I’ll try to help. How did you install Python? How did you install cutadapt? If you are not using it, yet, I can really recommend [bioconda](https://bioconda.github.io/) to make things as simple as possible.

**Comment by marcelm** [comment]
No reply, so closing for now. Feel free to re-open.
