### ISSUE TITLE
Some seemingly untrimmed reads are still in the trimmed output

### ISSUE THREAD

**Issue by ETaSky** [marcelm/cutadapt#278]
Hello, I found this strange behavior as described in the title. The command I used is:
cutadapt --debug -j 1 -g GTGCCAGCMGCCGCGGTAA -g CCTACGGGNGGCWGCAG -G GACTACHVGGGTATCTAATCC -e 0.05 -n 1 -O 15 -o t_trim_R1.fastq.gz --untrimmed-output=t_untrim_R1.fastq.gz -p t_trim_R2.fastq.gz --untrimmed-paired-output=t_untrim_R2.fastq.gz --pair-filter=both t_R1.fastq.gz t_R2.fastq.gz

So given this command, if a read was not trimmed, it should go into untrimmed output. But I found in my trim output, there are a lot of sequences have the same length as before they were trimmed. I checked one of the sequences that stay in the trimmed output but untrimmed. It turned out, it did have the adapter sequence, but with mismatch more than -e 0.05 tolerance. I am not sure if this is the reason it stays. But the adapter was not trimmed either.
Thanks!

**Comment by marcelm** [comment]
This could be because of the `--pair-filter` setting. Can you please have a look at the section about [Filtering paired-end reads in the documentation](https://cutadapt.readthedocs.io/en/latest/guide.html#filtering-paired-end-reads)? With setting `--pair-filter=both`, a read is sent to `--untrimmed-output`/`--untrimmed-paired-output` only if *both* reads do *not* contain an adapter.

**Comment by marcelm** [comment]
The `--untrimmed-output`/`--untrimmed-paired-output` options are not explicitly listed in the table in that section, but they work the same as `--discard-untrimmed`, except that the reads are not discarded, but written to files. If that is your problem, I’ll make this clearer in the documentation.

**Comment by ETaSky** [comment]
Thank you so much! Apparently, I misunderstood the documentation. Sorry for the ignorance. The document is clear and thanks for your time.

**Comment by marcelm** [comment]
Great, glad I could help!

**Comment by ETaSky** [comment]
Not sure if it is appropriate to discuss this issue here, but it appears that many of my 5' primers do have 1 or 2 mismatches, which is a little bit surprising. I may have misunderstood the Illumina error rate but isn't it in general that the quality for the 5' end is pretty good, usually >Q30 or even Q20, then I could expect in a 19bp primer, on average there shouldn't be more than 1 mismatch, right? Therefore, I set the -e to be 0.05 (~Q15), I am assuming the mismatch is occurred due to sequencing errors. I wonder if you could give me some thoughts on this issue. Thanks!

**Comment by marcelm** [comment]
Yes, 5' ends should have pretty low error rates on average. However, the `-e` setting is a hard cutoff and you should set it well higher than the average error rate. Actually, if you set `-e 0.05` and have a primer of length 19, then cutadapt allows 0.05*19=0.95 errors over the length of the adapter - which is then rounded down to 0 errors per adapter match. That is, with `-e 0.05`, you allow no mismatches at all! Cutadapt even tries to tell you this in the report, which should contain these lines in your case:
```
No. of allowed errors:
0-19 bp: 0
```
I’m not saying you should, but you could on the contrary even raise the maximum error rate a bit (15-20% perhaps), just to make sure you get those adapter occurrences where there happen to be two mismatches. Overtrimming will not be a problem as it is quite unlikely to have a sequence that looks like a 19-bp adapter even when you allow two or even three mismatches.

Feel free to ask further questions, but I won’t have time to answer them right now.

**Comment by ETaSky** [comment]
Thanks a lot! This is very helpful.
