### ISSUE TITLE
link adapters when demultiplexing in paired-end mode using fasta files for respective 5' and 3' barcodes

### ISSUE THREAD

**Issue by jack1120** [marcelm/cutadapt#282]
I tried to use a command such as

cutadapt -g file:5'_barcodes.fasta...file:3'_barcodes.fasta -G file:5'_barcodes.fasta...file:3'_barcodes.fasta -o {name}_R1.fastq.gz -p {name}_R2.fastq.gz R1_001.fastq R2_001.fastq

but it fails with an error related to the characters in the in 'file' (i.e. they are not IUPAC supported characters) for the first 3'_barcodes.fasta after the attempt to link it to the 5' barcodes.fasta file. 

It may be useful to implement a fix for this.

**Comment by marcelm** [comment]
You can currently not combine the `file:` syntax with the linked adapter syntax like this. You can only use `file:` once in the beginning of the adapter specification and the rest must be a file name. In your case, cutadapt tries to load adapters from a file named `5'_barcodes.fasta...file:3'_barcodes.fasta`. (If your actual file name includes the `'` character, remember to quote it.)

What you can do is to use `-g file:adapters.fasta` and then put all the linked adapters into the FASTA file like this:
```
>adapter1
AAAA...GGGG
>adapter2
CCCC...TTTT
```

**Comment by jack1120** [comment]
Kicking myself for not thinking of that. Thanks!
