### ISSUE TITLE
Tests failing with missing positional argument: cores

### ISSUE THREAD

**Issue by a1an77** [marcelm/cutadapt#284]
The following tests (output excerpt) are failing in the current master

TypeError: test_paired_end_legacy() missing 1 required positional argument: 'cores'
TypeError: test_first_too_short() missing 1 required positional argument: 'cores'
TypeError: test_second_too_short() missing 1 required positional argument: 'cores'
TypeError: test_unmatched_read_names() missing 1 required positional argument: 'cores'
TypeError: test_p_without_o() missing 1 required positional argument: 'cores'
TypeError: test_paired_but_only_one_input_file() missing 1 required positional argument: 'cores'
TypeError: test_legacy_minlength() missing 1 required positional argument: 'cores'
TypeError: test_paired_end() missing 1 required positional argument: 'cores'
TypeError: test_paired_end_qualtrim() missing 1 required positional argument: 'cores'
TypeError: test_paired_end_qualtrim_swapped() missing 1 required positional argument: 'cores'
TypeError: test_paired_end_cut() missing 1 required positional argument: 'cores'
TypeError: test_paired_end_upper_a_only() missing 1 required positional argument: 'cores'
TypeError: test_discard_untrimmed() missing 1 required positional argument: 'cores'
TypeError: test_discard_trimmed() missing 1 required positional argument: 'cores'
TypeError: test_interleaved_in_and_out() missing 1 required positional argument: 'cores'
TypeError: test_interleaved_in() missing 1 required positional argument: 'cores'
TypeError: test_interleaved_out() missing 1 required positional argument: 'cores'
TypeError: test_pair_filter() missing 1 required positional argument: 'cores'
TypeError: test_nextseq_paired() missing 1 required positional argument: 'cores'

**Comment by marcelm** [comment]
[Travis succeeds](https://travis-ci.org/marcelm/cutadapt), so I need a little bit more context.

**Comment by a1an77** [comment]
I just installed for developers and run the tests with nosetests after activating the virtualenv

**Comment by marcelm** [comment]
The problem was that `pytest` needs to be used instead of `nosetests`. I’ve now documented this.
