### ISSUE TITLE
Confused statstics output in cutadapter version 1.14 and 1.15 

### ISSUE THREAD

**Issue by smw1414** [marcelm/cutadapt#285]
Hi,

I performed quality and adapter trimming with sample ERR1294577 using cutadapter version 1.14 and 1.15. But, the bases statistics looks conflict.  

The sum of Quality-trimmed bp of read 1 and 2 in version 1.14 equates to either Quality-trimmed bp of read 1 or 2 in version 1.15. I think that the base statistics of cutadapter version 1.14 makes more sense to me. Thank you.   

Best, 

> This is cutadapt 1.15 with Python 2.7.12
Command line parameters: -m 32 -q 20 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT -o /data/cutadapt_output/trimmed_1.fq.gz -p /data/cutadapt_output/trimmed_2.fq.gz ERR1294577_1.fastq.gz ERR1294577_2.fastq.gz
Running on 1 core
Trimming 2 adapters with at most 10.0% errors in paired-end mode ...
Finished in 1173.29 s (35 us/read; 1.71 M reads/minute).
=== Summary ===
Total read pairs processed:         33,527,575
  Read 1 with adapter:               1,453,082 (4.3%)
  Read 2 with adapter:                 164,019 (0.5%)
Pairs that were too short:           1,898,310 (5.7%)
Pairs written (passing filters):    31,629,265 (94.3%)
Total basepairs processed: 6,772,570,150 bp
  Read 1: 3,386,285,075 bp
  Read 2: 3,386,285,075 bp
Quality-trimmed:             599,867,334 bp (8.9%)
  Read 1:   299,933,667 bp
  Read 2:   299,933,667 bp
Total written (filtered):  6,294,504,877 bp (92.9%)
  Read 1: 3,153,212,688 bp
  Read 2: 3,141,292,189 bp 

>This is cutadapt 1.14 with Python 3.5.2
Command line parameters: -m 32 -q 20 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT -o trimmed1.fastq.gz -p trimmed2.fastq.gz ERR1294577_1.fastq.gz ERR1294577_2.fastq.gz
Trimming 2 adapters with at most 10.0% errors in paired-end mode ...
Finished in 3975.66 s (119 us/read; 0.51 M reads/minute).
=== Summary ===
Total read pairs processed:         33,527,575
  Read 1 with adapter:               1,453,082 (4.3%)
  Read 2 with adapter:                 164,019 (0.5%)
Pairs that were too short:           1,898,310 (5.7%)
Pairs written (passing filters):    31,629,265 (94.3%)
Total basepairs processed: 6,772,570,150 bp
  Read 1: 3,386,285,075 bp
  Read 2: 3,386,285,075 bp
Quality-trimmed:             299,933,667 bp (4.4%)
  Read 1:    88,069,741 bp
  Read 2:   211,863,926 bp
Total written (filtered):  6,294,504,877 bp (92.9%)
  Read 1: 3,153,212,688 bp
  Read 2: 3,141,292,189 bp

**Comment by marcelm** [comment]
Thanks for the report. This issue has been fixed already in the development version, see issue #280. I will try to release a fixed version soon.
