### ISSUE TITLE
error in adapter sequence

### ISSUE THREAD

**Issue by qgao2** [marcelm/cutadapt#288]
Hello
I am running the cutadapt with single-end fastq and do the demultiplexing without any trimming. the script is as below:
cutadapt -a barcode_box5_cutadapt.fasta --no-trim --untrimmed-o untrimmed_lane2.fastq.gz -o trimmed-{name}.fastq.gz Sample_lane2.fastq

But I got the error message like this:
cutadapt: error: Character 'O' in adapter sequence 'BARCODE_BOX5_CTTADAPT.FASTA' is not a valid IUPAC code. Use only characters XACGTURYSWKMBDHVN.

I double check/search my adapter file, there is no character 'O'. here are the first several lines in the adapter fasta file:
>Lane2Sample1
ACGAGTGCGT
>Lane2Sample2
ACGCTCGACA
>Lane2Sample3
AGACGCACTC
>Lane2Sample4
AGCACTGTAG
>Lane2Sample5
ATCAGACACG

Can't figure out why getting this error....

**Comment by marcelm** [comment]
The `-a` option requires the actual adapter sequence by default. That is, you would write it as `-a ACGAGTGCGT`, for example. If you want to provide a file name, then you need to write `-a file:barcode_box5_cutadapt.fasta`. Does that help?

**Comment by qgao2** [comment]
Nice, it works. Thank you!
Another question, is there a way to let cutadapt run faster? 
I have 100Gb fastq file, and it took more than one day to finish the demultiplexing, but I have around 30 more fastq files in a similar size and need to be demultiplexed.

**Comment by marcelm** [comment]
I’m planning to improve this use case, but there is currently no built-in way in cutadapt to do this faster, sorry. Cutadapt does have multi-core support, but that is implemented for the case when doing demultiplexing. The only suggestion I have at the moment is to split up your input file beforehand, run cutadapt on the chunks and then merge the results afterwards. But I don’t have a script for that.

How many adapter sequences do you have in that file?

**Comment by qgao2** [comment]
Thank you, Marcel. 
I have 96 adapter sequences in that file. For now, I will try to split my run between two workstations. 
Appreciate your help!

**Comment by molecules** [comment]
@qgao2 Is `pigz` (http://www.zlib.net/pigz/) available to your cutadapt installation? I got about an 8x speed-up with `pigz` in my `$PATH`.

**Comment by qgao2** [comment]
Thank you, @molecules. I will try with pigz.

**Comment by marcelm** [comment]
The next version of Cutadapt (going to be released soon) will support much faster demultiplexing if you

* anchor all your barcode sequences (prefix them with `^` in your FASTA file, as in `^ACGTACGT`)
* use `--no-indels`
* use a maximum error rate that corresponds to allowing at most two errors. Since your barcodes have a length of 10, using the default error rate of 10% (`-e 0.1`) will work fine as that allows one error.

And yes, you should make sure that you have `pigz` installed.
