### ISSUE TITLE
Cutadapt 1.16 error when istalling with conda/pip

### ISSUE THREAD

**Issue by Mestizia** [marcelm/cutadapt#293]
Hi,

I installed cutadapt version 1.16 [tried from conda, pip and installing the dependencies one by one].
However, it gives an error message even when providing no arguments [no difference with arguments obviously]:

python2.7 .local/bin/cutadapt
Traceback (most recent call last):
  File ".local/bin/cutadapt", line 7, in <module>
    from cutadapt.__main__ import main
  File "/home/traca001/.local/lib/python2.7/site-packages/cutadapt/__main__.py", line 71, in <module>
    from xopen import xopen
  File "/home/traca001/.local/lib/python2.7/site-packages/xopen.py", line 161, in <module>
    class ClosingBZ2File(bz2.BZ2File, Closing):
AttributeError: 'module' object has no attribute 'BZ2File'

Installing version 1.15 worked just fine.

Cheers

**Comment by marcelm** [comment]
This looks like some weird installation problem, possibly a conflict with an older installation.

Can you try using the conda version instead? You say it also didn’t work, but try to run `export PYTHONNOUSERSITE=x` before you start cutadapt and see whether that makes the error disappear.

**Comment by Mestizia** [comment]
Hi sorry for the delay.
Can't replicate it anymore though! 
Thanks for the responsiveness 👍
