### ISSUE TITLE
ResourceWarning

### ISSUE THREAD

**Issue by adityabandla** [marcelm/cutadapt#295]
I get this while using Cutadapt v1.16

cutadapt/pipeline.py:363: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='r' encoding='UTF-8'>
sys.stdin = os.fdopen(stdin_fd)

The run finishes smoothly though. Known bug?

**Comment by marcelm** [comment]
Hm, no, I haven’t seen that before. Seems harmless, but perhaps it’s hiding a real bug. Do you always get this? Which command-line do you use exactly?

**Comment by adityabandla** [comment]
Command line parameters: -a AGATCGGAAGAGC -A AGATCGGAAGAGC --error-rate 0.1 --max-n 0 --no-indels --times 1 --minimum-length 100 --overlap 3 -j 48 -o R1.fastq -p R2.fastq

**Comment by marcelm** [comment]
Hm, I still cannot reproduce this. Which Python version are you using? How do you provide the input files? You omitted that from your command line. I don’t need the actual file names, just the file extension. Compression or not is possibly important.

**Comment by marcelm** [comment]
The ResourceWarning seems to be disabled by default and shouldn’t even be printed. Do you by any chance have the `PYTHONWARNINGS` environment variable set to `default` or `all`?

Also, on which platform are you? Linux or macOS?

**Comment by adityabandla** [comment]
Ah my bad, this was the command I had used 

module load python/3.5.1
./.local/bin/cutadapt -a AGATCGGAAGAGC -A AGATCGGAAGAGC --error-rate 0.1 --max-n 0 --no-indels --times 1 --minimum-length 100 --overlap 3 -j 48 \
-o ./adapters_trimmed/$(basename $i .fastq).fastq \
-p ./adapters_trimmed/$(basename $j .fastq).fastq $i $j

I am running this on a linux cluster. The PYTHONWARNINGS variables doesn't seem to be set at all.

**Comment by marcelm** [comment]
Thanks a lot - although I’m still unable to reproduce it. Possibly there’s a difference between Python 3.5.1rc1 which you are using and Python 3.5.5 I have tested it with, or the way Python is installed on your cluster is a bit different.

Anyway, the warning is correct in the sense that there’s an unclosed file that should be closed. I’ve tried to fix this now by closing the file explicitly.

if you feel like it, you could apply the change that I made in commit aaef7dd to `~/.local/lib/python3.5/site-packages/cutadapt/pipeline.py` on your system and let me know whether that makes the warning disappear. (That is, add `sys.stdin.close()` in line 363. Make sure to indent with two tab characters.) This is totally optional and you can also just wait for the next release.

Thanks for reporting!

**Comment by adityabandla** [comment]
Thanks Marcel! Made that change and the warning disappeared

**Comment by marcelm** [comment]
Great, thanks!
