### ISSUE TITLE
--no-trim seems not working

### ISSUE THREAD

**Issue by foehnwind** [marcelm/cutadapt#296]
Dear author, thanks for developing this wonderful software! 

One issue appears regarding `--no-trim`. When it is set, the program will consume hundreds-gigabyte memory and crash eventually. 

* Python version 2.7.13
* cutadapt version 1.15
* installed via pip (version 9.0.1)
* usage `cutadapt -g $kmer -f fastq -o $outFq --no-trim --info-file=$outInfo $inFq  >$outStats`.

**Comment by marcelm** [comment]
Hi, and thanks for reporting. I don’t see this behavior when I test `--no-trim` on one of my datasets. Can you try to make the command-line a bit simpler by leaving out the `--info-file=` option and see whether the problem still occurs? A few more questions:
* When you used the `--info-file` option, did the created file contain anything?
* Does the `$outFq` file contain anything?
* What type of reads are you trimming? (Illumina?)
* How did you find out that the process consumes so much memory?
* Which platform are you on (Linux, macOS?)

**Comment by foehnwind** [comment]
Hi, thanks for your prompt response. Actually, when `--info-file=` option is removed, the problem is gone. 

To your questions, when `--no-trim` and `--info-file=` are both set, the program increases memory usage slowly, until runs out of memory after several hours. And 
* `--info-file` output contains nothing;
* $outFq contains nothing;
* Illumina single-end
* by htop
* on Linux

**Comment by marcelm** [comment]
Interesting! I can see how memory grows as well when I combine `--no-trim` and `--info-file`. I’ll see what I can do.

**Comment by marcelm** [comment]
I’ve found where the problem is (an infinite loop when the info file is written), but will need some spare time to fix it.

**Comment by foehnwind** [comment]
Great!

**Comment by marcelm** [comment]
It’s taken a while, but the issue should now be fixed. Thanks again for reporting!

**Comment by marcelm** [comment]
To get the version with the fix, you can [follow the instructions for installing a development version](https://cutadapt.readthedocs.io/en/latest/installation.html#installing-the-development-version).

**Comment by foehnwind** [comment]
Nice, thanks.
