### ISSUE TITLE
How to deal with pairs reads with only an adaptor within the first read?

### ISSUE THREAD

**Issue by werhoog** [marcelm/cutadapt#298]
Hi, this software works perfectly. But  what should I do  to trim only one read (read1 ) in a pair reads?That to say ,I just do trimming in the first read, and do nothing to the second reads?

Thank you!  
- Cutadapt and Python version
cutadapt version 1.15

**Comment by werhoog** [comment]
And I just do not want to do it separatly for I want to keep pairs  consistenctly. 
Will -a "*********" -A ""  -o out1.fastq  -p out2.fastq  reads1.fstq   reads2.fastq  work?
Thank you!

**Comment by marcelm** [comment]
Just leave out the `-A` option entirely if you don’t want to trim read 2. So use only `-a XXXXXX`. The pairs will be synchronized as you want it.

**Comment by werhoog** [comment]
Hi,it really work,but this time I just want to trim read2.However,the stdout  shows some reads 2 did have barcodes when I just keep -A without -a , the -o and -p files is null.
And I use "-a N -A barcode"  and it worked!!
So,am I right and why leaving out -a  didn't work?
I just worry only keep  -a when I just want trim read1 which may be some mistakes
Thank you!

**Comment by marcelm** [comment]
I’m not sure I understand. Can you describe again which command you used, which output you get and which output you would have expected?

**Comment by werhoog** [comment]
1. I want to trim reads2(pairEnd sequence) only for barcodes only anchor in reads2(reads1 not)

2. I use  command   /// -A "******" -o out1.fastq -p out2.fastq reads1.fstq reads2.fastq  ///   without  ///-a ****/// for there are not any barcodes in reads1 

reault: I get null in out1.fastq and out2.fastq , however the stdout files (files descibe the summary the results of trimming )shows  that barcodes did in reads2 for ///"around  87%  " barcodes in reads trimmed.

3.And I trial //// -a N  -A "******" -o out1.fastq -p out2.fastq reads1.fstq reads2.fastq ///  .
It worked,because there are cleaned reads in  out1.fastq and out2.fastq files

Why ?
Thank you!

**Comment by marcelm** [comment]
When you say “I get null in out1.fastq and out2.fastq”, does that mean that these files empty (zero bytes)?

Can you please copy the full report (the stdout output) here? Your adapter sequences will be in there. If they are secret, remember to remove them before you do so.

**Comment by marcelm** [comment]
No reply in a while, so closing for now. Feel free to re-open.
