### ISSUE TITLE
Potentially incorrect trim counts for 2nd read when trimming multiple adapters

### ISSUE THREAD

**Issue by jeremycfd** [marcelm/cutadapt#306]
Hi there. I'm trimming primers off of the 5' ends of forward and reverse reads. Because the reads are quite long, there are sometimes reverse-complement primers that I'm trimming out as well. I've found that when I remove all four (2 forward, 2 reverse) simultaneously, using -n 2 in order to do so, the primers are removed as I would expect from the output, but I think the summary information reporting how many of each primer was removed is under-representing certain removal events.

Cutadapt v1.16
Python v2.7.12

`cutadapt -n 2 -g 16Sforward=AGAGTTTGATCCTGGCTCAG -G 16Sreverse=ATTACCGCGGCTGCTGG -a RC16Sreverse=CCAGCAGCCGCGGTAAT -G RC16Sforward=CTGAGCCAGGATCAAACTCT Sample_R1_001.fastq.gz Sample_R2_001.fastq.gz -o cutadapt_R1.fastq.gz -p cutadapt_R2.fastq.gz > Summary_Cutadapt.tsv`

> === First read: Adapter RC16Sreverse ===
> Sequence: CCAGCAGCCGCGGTAAT; Type: regular 3'; Length: 17; Trimmed: 646015 times.
> === First read: Adapter 16Sforward ===
> Sequence: AGAGTTTGATCCTGGCTCAG; Type: regular 5'; Length: 20; Trimmed: 1837943 times.
> === Second read: Adapter 16Sreverse ===
> Sequence: ATTACCGCGGCTGCTGG; Type: regular 5'; Length: 17; **Trimmed: 1174076 times.**
> === Second read: Adapter RC16Sforward ===
> Sequence: CTGAGCCAGGATCAAACTCT; Type: regular 5'; Length: 20; Trimmed: 669287 times.

`cutadapt -g 16Sforward=AGAGTTTGATCCTGGCTCAG -G 16Sreverse=ATTACCGCGGCTGCTGG Sample_R1_001.fastq.gz Sample_R2_001.fastq.gz –o test1.fastq.gz –p test2.fastq.gz > testsummary.tsv`

> === First read: Adapter 16Sforward ===
> Sequence: AGAGTTTGATCCTGGCTCAG; Type: regular 5'; Length: 20; Trimmed: 1823582 times.
> === Second read: Adapter 16Sreverse ===
> Sequence: ATTACCGCGGCTGCTGG; Type: regular 5'; Length: 17; **Trimmed: 1787148 times.**

Increasing -n to 4 did not change the reporting for count for 16Sreverse in the first scenario. And as I mentioned above, the primers are clearly being removed.

Thanks!

**Comment by jeremycfd** [comment]
So after thinking about this some more, I realized I wasn't taking account of 16Sreverse that no longer needed to be removed because RC16Sforward was removed, thereby getting rid of 16Sreverse in the process. Doh!

**Comment by marcelm** [comment]
I’m glad you solved it yourself :-)
