### ISSUE TITLE
Cutadapt outputing reads with extra lines

### ISSUE THREAD

**Issue by carlyraea** [marcelm/cutadapt#313]
cutadapt version 1.16, installed with conda
iPyrad version 0.7.19, installed with conda
Python version 2.7.14

1. I ran cutadapt on CAS_11_S1_R1_001.fastq
2. Then I fed CAS_11_S1_R1_001_noadapters.fastq into iPyrad
3. iPyrad gives errors in step 2, and crashes in step 3 due to multiple errors like this:

cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but found 'EEE/EEEA'

Sometimes the strings it cites instead of @ are not present anywhere in the document if I search the text, none of the found strings are in line 1, and most importantly, sometimes there is an extra line of text. Here's a malformed read and a regular read:

@nb501447:153:HHVTJBGX3:4:23612:13750:9971 1:N:0:1
CAATTCATCAACGATTTTGATAATTCCAAAATGGAGTCATTTAGGTCGAAGAAAAAGATTTATGCCTCCTTTCCTCAAAAGTT
+
EEEEEEEEEEEA<EEEEAEEEEEEAEEEEEEEAEEEEAAEAE/EEEEEEEEAEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEE
**A//<6/AEEEEEEEE<EEEEEEEEEEEEEEEEEEE/**
@nb501447:153:HHVTJBGX3:2:23310:16113:12441 1:N:0:1
CCAGATCGGAAGATCCGTATTCCCGTTTTTTGTTTAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
E/AAEEEEEE/EEAE/////</<//6/AE/EA/6///EEEEEEEEEEE//AA/6AEEEEEEEEEEEEEEEEEEEEEEEEEEEE

Cutadapt code:
/projects/caan8813/software/miniconda2/bin/cutadapt -a AGATCGGAAGATCTCGTATGCCGTCTTCTGCTTG  -g  CTCTTTCCCTACACGACGCTCTTCCGATCT -m 35 -o cladonia_noadapt_redo2.fastq /projects/caan8813/data/CAS_11_S1_R1_001.fastq   

iPyrad code:
ipyrad -p /projects/caan8813/data/params_cladonia_macilenta2.txt -s 1234567

Thanks for any help!

**Comment by marcelm** [comment]
Can you please run this to check whether the file that cutadapt produces is corrupt: `cutadapt CAS_11_S1_R1_001_noadapters.fastq > /dev/null`. It will just attempt to parse the file and not do anything else. What is the output?

**Comment by carlyraea** [comment]
Hello, it says:

[caan8813@shas0137 caan8813]$ cutadapt cladonia_noadapt_redo2.fastq >
/dev/null

This is cutadapt 1.16 with Python 2.7.14

Command line parameters: cladonia_noadapt_redo2.fastq

Running on 1 core

Trimming 0 adapters with at most 10.0% errors in single-end mode ...

Finished in 668.34 s (3 us/read; 20.30 M reads/minute).


=== Summary ===


Total reads processed:             226,084,504

Reads with adapters:                         0 (0.0%)

Reads written (passing filters):   226,084,504 (100.0%)


Total basepairs processed: 19,859,435,280 bp

Total written (filtered):  19,859,435,280 bp (100.0%)


*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by marcelm** [comment]
Thanks. It appears that the file that you put into iPyrad is actually fine, so I’ll have to assume that the corruption occurs within iPyrad. I don’t know how iPyrad works internally, but if it crashes in step 2, I guess there’s something going on in step 1 that causes this.

Since this doesn’t actually appear to be a bug in cutadapt, I’m going to close this issue and have to ask you to report this to the iPyrad folks instead!

Please report back if you do find a way to create a corrupt output file directly with cutadapt.
