### ISSUE TITLE
cutadapt installation issue

### ISSUE THREAD

**Issue by DenisGoryunov** [marcelm/cutadapt#314]
Hi,
I faced with an error when i tried install cutadapt on our cluster by command:
pip install --user --upgrade cutadapt

"You are using pip version 7.1.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting cutadapt
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/68/73/2ae48245bbf6d84a24bdf29540ed01669f09c5d21c26258f2ce07e13c767/cutadapt-1.16.tar.gz (320kB)
    100% |████████████████████████████████| 323kB 404kB/s 
    Complete output from command python setup.py egg_info:
    At least Python 2.7 is required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6JFnwD/cutadapt"

But if i type in the terminal:
python --version
I got:
Python 2.7.3

What is wrong with my installation?

Regards,
Denis
-->

**Comment by marcelm** [comment]
For some reason, the `pip` command is run under Python 2.6 even though Python 2.7 is installed.

Perhaps you can run `pip2.7` instead (if that exists), or you can try running pip with `python -m pip`, that is:
```
python -m pip install --user --upgrade cutadapt
```
I can recommend learning how to use [Conda](https://conda.io/) together with [bioconda](https://bioconda.github.io/), see also the [section in the docs](https://cutadapt.readthedocs.io/en/latest/installation.html#installation-with-conda). It really makes life easier if you plan to use more bioinformatics tools in the future, and is probably your easiest option if the tips I gave you just now didn’t help.

**Comment by DenisGoryunov** [comment]
Thanks. I tried to install conda in my home directory on a cluster locally, but stuck with pycosat. It seems i need root privileges for it installation.

**Comment by marcelm** [comment]
You don’t need root permissions for Conda - that is one of the reasons for using it.

Let me know if you think I could be of more help.
