### ISSUE TITLE
ImportError: No module named cutadapt.__main__

### ISSUE THREAD

**Issue by stayingsong** [marcelm/cutadapt#324]
I installed cutadapt version 1.16 via pip and was trying to run it using Trim Galore! version 0.4.4 as a wrapper script.

However, I am encountering this error while running cutadapt:

Traceback (most recent call last):
  File "/netapp/sali/msong/.local/bin//cutadapt", line 7, in <module>
    from cutadapt.__main__ import main
ImportError: No module named cutadapt.__main__

Any ideas on why this issue is coming up and preventing cutadapt from running?

**Comment by stayingsong** [comment]
Nevermind, realized it was an obvious oversight, forgot to specify where my custom Python libraries were located.

**Comment by iichelhadi** [comment]
> Nevermind, realized it was an obvious oversight, forgot to specify where my custom Python libraries were located.

dear stayingsong,
Could you please explain how you solved the issue? I am running against the same problem
regards

**Comment by marcelm** [comment]
I can try to help if you post your full error message. Also please describe which command you used to install Cutadapt.

**Comment by iichelhadi** [comment]
it is ok out IT department managed to solve the issue. It seemed to be related to having multiple python versions installed on the HPC. Thank you

**Comment by marcelm** [comment]
Great, I’m glad you got it solved!

**Comment by Whale-fall** [comment]
Hello guys, i meet the problem again，can you help me figure it out?I am running cutadapt in HPC.When i run it in login node,everything is ok.but the problem appears when i running it in compute nodes.
![image](https://user-images.githubusercontent.com/22662209/120059808-61916000-c086-11eb-8128-1628a6f42e01.png)
![image](https://user-images.githubusercontent.com/22662209/120059834-92719500-c086-11eb-813b-a3c7dd73c8f5.png)
