### ISSUE TITLE
Remove adapter with internal barcode varying in length

### ISSUE THREAD

**Issue by AliceLedent** [marcelm/cutadapt#325]
Hi,

cutadapt version 1.12
installation through pip
command line : cutadapt -a ACACTCTTTCCCTACACGACGCTCTTCCGATCT...CWGAGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG -A CTCGGCATTCCTGCTGAACCGCTCTTCCGATCT..."CWGN{4,8}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" --nextseq-trim=20 -e 0.1 -o cutadapt_L001.R1.fastq.gz -p cutadapt_L001.R2.fastq.gz Undetermined_S0_L001_R1_001.fastq.gz Undetermined_S0_L001_R2_001.fastq.gz

As you can see, i want to use cutadapt to remove 5' and 3' adaptor on GBS paired-end data. The problem is that the 3' adapter of my paired read contains a barcode (complement of the barcode in the forward read) that vary in length (from 4 to 8 bp) and that i want to remove as well. But cutadapt doesn't support the notation {4,8}. Is there a way for me to be able to remove that barcode with another notation or should i start the sequence of this 3' adapter of my paired read after the CWG and barcode and then find another way to remove the barcode from my sequence afterward (i.e. may be by giving a black list sequence for the population genetics analyses?)

Thanks in advance,
Alice

**Comment by marcelm** [comment]
You’re right that the `{4,8}` notation isn’t supported. As a work-around, you can specify the five possibilities explicitly (line breaks added to make it easier to read):
```
-A "CTCGGCATTCCTGCTGAACCGCTCTTCCGATCT..."CWGN{4}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
-A "CTCGGCATTCCTGCTGAACCGCTCTTCCGATCT..."CWGN{5}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
-A "CTCGGCATTCCTGCTGAACCGCTCTTCCGATCT..."CWGN{6}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
-A "CTCGGCATTCCTGCTGAACCGCTCTTCCGATCT..."CWGN{7}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
-A "CTCGGCATTCCTGCTGAACCGCTCTTCCGATCT..."CWGN{8}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
```
This is cumbersome and somewhat inefficient, but should get the job done.

I’d like to add direct support for the notation, but I’m not sure when I’ll have time for that.

**Comment by AliceLedent** [comment]
Perfect,
Thank you very much!

**Comment by marcelm** [comment]
Regarding the first question: The removed adapter can be different for each read. That should be exactly what you want if each read contains only one adapter. Is this what you meant?

Regarding the second question: In that case, use `--times=2` (or the equivalent short form `-n 2`). Then Cutadapt removes up to two adapters from each read. More precisely: For each read, Cutadapt searches for both adapters and removes the best matching one. If an adapter was found, it will do the same (search for both adapters, remove the best matching one) once more.

There’s one difference to using linked adapters, however: It is possible that Cutadapt trims the same adapter twice from a read. If you don’t want that, you need to run the program twice, once to remove the 5' adapter and once to remove the 3' one.

It would be nice if there was a way to specify which of the linked adapters must be present, but I don’t know how the command-line syntax for that should look like.

**Comment by AliceLedent** [comment]
Hi!

Ok yes it totally make sense now!

When using n=2 does the program remove always two adapters or if it finds only one matching adapter it could stops.
If it stops when there is no more matching adapter, i suppose i could use n=4 and thus allow for three copy of one adapter without missing the second one if present?
When using the "-a XXXX -A YYYY -g WWWW -G ZZZZZ -n 2" notation, will the program search 2 times for the 4 adapters in each reads or 2 times for -a and -g in the forward read and 2 times for -A and -G for the reverse read?

Thanks a lot, this is really useful!

**Comment by marcelm** [comment]
> When using n=2 does the program remove always two adapters or if it finds only one matching adapter it could stops.

The program stops when it does not find an adapter.

> If it stops when there is no more matching adapter, i suppose i could use n=4 and thus allow for three copy of one adapter without missing the second one if present?

Yes, exactly.

> When using the "-a XXXX -A YYYY -g WWWW -G ZZZZZ -n 2" notation, will the program search 2 times for the 4 adapters in each reads or 2 times for -a and -g in the forward read and 2 times for -A and -G for the reverse read?

The latter. The `-a` and `-g` adapters are only ever searched for in the forward read. The `-A` and `-G` adapters are only ever searched for in the reverse read. The `-n` option applies to forward and reverse read separately. The program searches twice for the `-a` and `-g` adapters in the forward read; and it searches twice for the `-A` and `-G` adapters in the reverse read.

**Comment by AliceLedent** [comment]
Perfect!

All is clear now!
Thanks a lot for those super quick answers!

**Comment by marcelm** [comment]
You’re welcome!
