### ISSUE TITLE
filtering paired reads of uneven length

### ISSUE THREAD

**Issue by juugii** [marcelm/cutadapt#326]
Hello,
I have some paired fastq files from single cell experiments (10x). After demultiplexing, I get reads of uneven length. R1 contain the barcodes and are 26 long while R2 contain the cDNA sequence and are 98 long. I want to trim and quality filter the reads whilst keeping their original length (or simply discard the reads). The approach I use is:

cutadapt 1.16 with Python 3.6.5 from pip.
cutadapt -j 16 -q 30 --max-n 0 --minimum-length 26 --pair-filter=any -o trimmedSample_R1.fastq.gz -p trimmedSample_R2.fastq.gz rawSample_R1.fastq.gz rawSample_R2.fastq.gz

The problem is I can't set up a different minimum length for R1 and R2, as there is no option for that. So with this approach I get R2 26-98 long which is not what I would like to obtain. I could process R1 and R2 separately but it is mandatory to keep R1 and R2 synchronized.
Is it possible to do that with cutadapt?
Many thanks for the information.

**Comment by marcelm** [comment]
Hi, thanks for the report. It’s currently not possible to specify separate lengths for R1 and R2. Perhaps my assumptions for why I designed it this way are no longer valid - your experiment seems a good counterexample.

As a workaround, you can run cutadapt a second time on the output files and specify `--minimum-length=98`. Something like this:
```
cutadapt --minimum-length=98 -o out.R1.fastq.gz -p out.R2.fastq.gz trimmedSample_R1.fastq.gz trimmedSample_R2.fastq.gz
```
Note that `--pair-filter=any` is the default and that you can therefore omit it.

**Comment by juugii** [comment]
Hi Marcel, thank you very much for your feedback.
In the workaround you are mentioning, won't all the 26-bp long R1 reads
be discarded in the second pass with such a length filter?

Le 16/08/2018 à 15:34, Marcel Martin a écrit :
> Hi, thanks for the report. It’s currently not possible to specify separate lengths for R1 and R2. Perhaps my assumptions for why I designed it this way are no longer valid - your experiment seems a good counterexample.
> 
> As a workaround, you can run cutadapt a second time on the output files and specify `--minimum-length=98`. Something like this:
> ```
> cutadapt --minimum-length=98 -o out.R1.fastq.gz -p out.R2.fastq.gz trimmedSample_R1.fastq.gz trimmedSample_R2.fastq.gz
> ```
> Note that `--pair-filter=any` is the default and that you can therefore omit it.
>

**Comment by marcelm** [comment]
Sorry, yes you are right. On the second pass, you need to swap the R1 and R2 files. Cutadapt will work in "legacy mode" in which it only checks the length of R1 (which in fact will be your R2). Please verify that this is indeed the case (cutadapt should print something like "trimming 0 adapters in paired-end legacy mode").

I should really implement `--pair-filter=first` and `--pair-filter=second` to make this easier (although this won’t solve the original issue you reported).

**Comment by juugii** [comment]
Hi Marcel, I tried the workaround using the legacy mode and it solved my problem. So I can close the issue. However the trick doubles the processing time (up to about one hour with 32 cores on my files), so any future implementation of options for paired-reads of uneven length would be useful.
Many thanks for your prompt and great help!
Best wishes.

**Comment by marcelm** [comment]
Great, thanks for getting back. I’ve opened #327 for your suggestion. Please follow that if you want to know when it’s done.

Do you compress the intermediate files? Then at least some of that processing time is spent on compressing/decompressing the data. You may be able to avoid some of the overhead by [piping the uncompressed reads between the two processes](https://cutadapt.readthedocs.io/en/stable/recipes.html#piping-paired-end-data). Not sure how much that saves, though.

**Comment by juugii** [comment]
Thanks a lot. I'll try piping uncompressed reads between the passes.
