### ISSUE TITLE
Trimming linked adapters

### ISSUE THREAD

**Issue by adityabandla** [marcelm/cutadapt#335]
Using v1.18, python v3.5.1

I am trying to trim primers from a paired-end dataset. I normally use the linked option with -a FWD...RCREV -A REV...RCFWD, however this didn't work. I think this was due to improper adapter trimming by the sequencing facility, with parts of the adapter still remaining on the reads.

To work around this, I used -g FWD...RCREV -G REV...RCFWD, however, most reads get thrown away with the --discard-untrimmed option

Interestingly, when I used only -g FWD -G REV, >90% reads are trimmed properly and retained. Not exactly sure why it doesn't work when the linked part is added

**Comment by adityabandla** [comment]
I went through the docs and I understand now why -g FWD...RCREV -G REV...RCFWD this doesn't work as expected. When using -g and -G for linked adapters, can it be made to function like -a and -A i.e. the 3' adapter being optional

**Comment by marcelm** [comment]
If I understand correctly, you would like to have a linked adapter type where 1) the 5' adapter is not anchored, but required and 2) the 3' adapter is optional. I would like to make sure that this would really help in your situation. Could you please explain how your reads look and what type of data this is. Do you want to remove the sequencing adapters only or PCR primers?

I agree that it would make sense to somehow be able to specify which of the two reads are required, but I cannot change how the `-g` and `-G` options behave as that behavior was requested explicitly by other users for certain types of data (see issue #256).

I’m considering changing the behavior for `-a ADAPTER1...ADAPTER2` to not automatically anchor the 5' adapter, but this would be backwards incompatible.

**Comment by marcelm** [comment]
If you need a solution now, you can run Cutadapt twice: Run it once with the 5' adapter and the `--discard-untrimmed` option. Then run it again to remove the 3' adapter, but omit the `--discard-untrimmed` option (which makes the 3' adapter optional).

**Comment by adityabandla** [comment]
> If I understand correctly, you would like to have a linked adapter type where 1) the 5' adapter is not anchored, but required and 2) the 3' adapter is optional. I would like to make sure that this would really help in your situation. Could you please explain how your reads look and what type of data this is. Do you want to remove the sequencing adapters only or PCR primers?
> 
> I agree that it would make sense to somehow be able to specify which of the two reads are required, but I cannot change how the `-g` and `-G` options behave as that behavior was requested explicitly by other users for certain types of data (see issue #256).
> 
> I’m considering changing the behavior for `-a ADAPTER1...ADAPTER2` to not automatically anchor the 5' adapter, but this would be backwards incompatible.

Hi Marcel

That's right. This is for trimming primers from 16S amplicon reads (Illumina MiSeq). I skip adapter trimming for two reasons. Some datasets have adapters already stripped by the sequencing company and secondly, trimming primers anyways gets rid of the trailing adapters.

In this particular dataset, the seq company had already trimmed the adapters. However, I dont think it was done in a proper way. When inspecting the reads, there were still traces of adapters on most reads, so using the linked adapter command (-a -A) for primer trimming didn't really work well.

As you suggest, perhaps making the linked adapters (-a -A) without the requirement for anchoring might solve this

Regards,
Aditya

**Comment by adityabandla** [comment]
Will this be implemented anytime soon?

**Comment by marcelm** [comment]
Thanks for being still interested! I don’t have that much spare time at the moment, but I’ll see what I can do.

**Comment by marcelm** [comment]
Hi, I have implemented a solution for this. For linked adapters, it is now possible to choose which of its adapters should be required or optional, overriding the default.

So what you will be able to do in the next release of Cutadapt is to write `-g "FWD...RCREV;optional"`, which should do what you want.

**Comment by marcelm** [comment]
And to clarify a bit: The `optional` refers to the sequence immediately preceding it, so something like this is also valid: `-g "FWD;optional...RCREV"`. The quotation marks are necessary because the semicolon would be interpreted by the shell otherwise.

**Comment by luchaoqi** [comment]
Hello, I am new to Cutadapt and sorry if this question is very basic:
I would like to know in paired-end sequencing I have R1 e.g. `ATGC...` and correponding R2 e.g. `...GCAT`. So, to remove adapter `ATGC`, am I supposed to run `cutadapt -g ^ATGC -G GCAT$ -o output.R1 -p output.R2 input.R1 input.R2` in this case?
I searched for the documentation [here](https://cutadapt.readthedocs.io/en/stable/guide.html#regular-3-adapters) and the example there is still a bit confusing for me.

**Comment by marcelm** [comment]
Hi, since this is a new question, can you please open a new issue?

**Comment by luchaoqi** [comment]
> Hi, since this is a new question, can you please open a new issue?

Sure, opened here: https://github.com/marcelm/cutadapt/issues/597
