### ISSUE TITLE
paired linked adapter cutting too many parameters error

### ISSUE THREAD

**Issue by djbradshaw2** [marcelm/cutadapt#340]
Dear Whom It May Concern, 

Cutadapt version 1.17, installed using  conda, Python 3.5.5

I am getting the following error running this script with a manifest file run through snakemake. I am unsure how to fix it?

Thank you for your time and help, 

Sincerely,

David Bradshaw

cutadapt: error: Too many parameters.
Error in job trim_reads while creating output files /home/microbiology/Raw_Data/LWSD17_IMTA/LWSD17/5185-FP1D17S-515yF-806bR_R1_val_1.fq.gz, /home/microbiology/Raw_Data/LWSD17_IMTA/LWSD17/5185-FP1D17S-515yF-806bR_R2_val_2.fq.gz.
RuleException:
CalledProcessError in line 50 of /home/microbiology/NICK/cutadapt_snakemake:
Command 'cutadapt -a GTGYCAGCMGCCGCGGTAA...ATTAGAWACCCBNGTAGTCC -A GGACTACNVGGGTWTCTAAT...TTACCGCGGCKGCTGRCAC -q 20 -m 50 -o `dirname /home/microbiology/Raw_Data/LWSD17_IMTA/LWSD17/5185-FP1D17S-515yF-806bR_R1.fastq`-p 'dirname /home/microbiology/Raw_Data/LWSD17_IMTA/LWSD17/5185-FP1D17S-515yF-806bR_R2.fastq' /home/microbiology/Raw_Data/LWSD17_IMTA/LWSD17/5185-FP1D17S-515yF-806bR_R1.fastq /home/microbiology/Raw_Data/LWSD17_IMTA/LWSD17/5185-FP1D17S-515yF-806bR_R2.fastq' returned non-zero exit status 2
  File "/home/microbiology/NICK/cutadapt_snakemake", line 50, in __rule_trim_reads
  File "/home/microbiology/miniconda3/envs/qiime2-2018.8/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message

Below is the actual command in snakemake

"cutadapt -a GTGYCAGCMGCCGCGGTAA...ATTAGAWACCCBNGTAGTCC -A GGACTACNVGGGTWTCTAAT...TTACCGCGGCKGCTGRCAC -q 20 -m 50 -o `dirname {input[0]}`-p 'dirname{input[1]}' {input[0]} {input[1]}"

**Comment by marcelm** [comment]
Hi David,

this isn’t really a problem in Cutadapt itself, so strictly speaking you should report this somewhere else.

I’m assuming you wrote the Snakefile yourself. If you didn’t, you should definitely report this problem to the author of the Snakefile. The problem in the Cutadapt command appears to be in the output file names. Your Snakefile specifies this for the output files:
```
-o `dirname {input[0]}`-p 'dirname{input[1]}'
```
There are a couple of problems:
- There’s a space missing before the `-p`
- The first `dirname` command is within backticks, but the second is within normal quotes
- A space is missing after the second `dirname`
- `dirname` (if used correctly) would strip the last component of a path and leave only the directory name (hence the name). So "dirname a/b/file.fastq" gives you "a/b". But the command as given then doesn’t include an output file name (Cutadapt needs a full file name, not only the name of an output directory).

Anyway, you should not manipulate the path names with `dirname` in a Snakefile. Just specify a correct `output:` file in the rule and use that. Overall, it would look something like this:
```
rule:
  input: fastq1=..., fastq2=...
  output: fastq1=..., fastq2=...
  run:
    "cutadapt -a GTGYCAGCMGCCGCGGTAA...ATTAGAWACCCBNGTAGTCC -A GGACTACNVGGGTWTCTAAT...TTACCGCGGCKGCTGRCAC -q 20 -m 50 -o {output.fastq1} -p {output.fastq2} {input.fastq1} {input.fastq2}
```

**Comment by djbradshaw2** [comment]
Dear marcelm,

Thank you for the edits (I should have caught those) and information. My PI and I wrote the Snakefile, we are running about 483 paired samples through the cutadapt program, so we were using a manifest file with a list of locations to input them all in with a one click run using snakemake. Seems like that may not be possible if cutadapt needs a full file name thank you very much for your help in any case. 

Sincerely, 

David Bradshaw
