### ISSUE TITLE
Cutadapt error with -m paramter

### ISSUE THREAD

**Issue by weiiioyo** [marcelm/cutadapt#348]
Hi,
   I've met some problem when I used cutadapt 1.18. My commad line was as followed:
```
cutadapt/1.18/bin/cutadapt -g AAGCAGTGGTATCAACGCAGAGTACATGGG -O 3 -e 0.1 --minimum-length=20 --pair-filter=both -o trim_C_1.1.fq.gz -p trim_C_1.2.fq.gz C_1_1.clean.fq.gz C_1_2.clean.fq.gz
```
But when I checked my result, I found some reads which length were 0 in my final results.
Command line:
```
gunzip -c trim_C_1.1.fq.gz | grep -A 4 '@ST-E00318:691:HTKHFCCXY:3:1110:15747:41286'
```
Result:
```
@ST-E00318:691:HTKHFCCXY:3:1110:15747:41286 1:N:0:ATCACGAT

+

@ST-E00318:691:HTKHFCCXY:3:1110:23216:41286 1:N:0:ATCACGAT

```
Could you help me solve this problem?
Thank you.

**Comment by weiiioyo** [comment]
My raw data result:
Command:
```
gunzip -c C_1_1.clean.fq.gz | grep -A 4 '@ST-E00318:691:HTKHFCCXY:3:1110:15747:41286'
```
Result:
```
@ST-E00318:691:HTKHFCCXY:3:1110:15747:41286 1:N:0:ATCACGAT
AAGCAGTGGTATCAACGCAGAGTACATGGAAAGCAGTGGTATCAACGCAGAGTACATGGAAAGCAGTGGTATCAACGCAGAGTACATGGAAAGCAGTGGTATCAACGCAGAGTACATGGAAAGCAGTGGTATCAACGCAGAGTACATGGG
+
AAFFFJFFJFJJJJJJJJFJJJJFJJJAJJJJJJF<JJJJFJ-FJFJJFJ<FFJJJJFJJJFJFJJJFJJJJJJJFJJJJAFFJJJFJFJFJJJ7JFFFJAFJJFJJJJJJJ7JJJFFJ7J<FJAJ7JFJJJFF<JJJ7AF7JFF7FFA-

```

**Comment by marcelm** [comment]
Hi, did you solve you problem? You should be able to fix it by omitting the `--pair-filter=both` option. If you leave it in, a read pair is only filtered if *both* reads (R1 and R2) have a length of at least 20 bp, and even if R1 has length 0, as in your example, it won’t be discarded as long as R2 has a length of at least 20 bp.
