### ISSUE TITLE
cutadapt "improperly paired" error

### ISSUE THREAD

**Issue by StevenMamet** [marcelm/cutadapt#350]
Hello, 

I’ve been attempting to trim primers and adapters from my fastq files without success. Of the 1144 fastq R1-R2 files, cutadapt only works for 60. The rest I get a mixture of these errors:

cutadapt: error: Reads are improperly paired. There are more reads in file 2 than in file 1.
cutadapt: error: Compressed file ended before the end-of-stream marker was reached

Though most are the "improperly paired" error. I've read through this post (https://github.com/marcelm/cutadapt/issues/197) and this one (https://github.com/marcelm/cutadapt/issues/199), though I don't have the same issue with the sample IDs. Plus, each R1-R2 pair has the same number of reads, so I'm not sure where this error is coming from. I've attached four files here. The first two are files that were trimmed successfully using the command pasted below. The next two are files that cutadapt thinks are improperly paired.

[10-897_S140_L001_R1_001.fastq.gz](https://github.com/marcelm/cutadapt/files/2750931/10-897_S140_L001_R1_001.fastq.gz)
[10-897_S140_L001_R2_001.fastq.gz](https://github.com/marcelm/cutadapt/files/2750932/10-897_S140_L001_R2_001.fastq.gz)

[1-901_S199_L001_R1_001.fastq.gz](https://github.com/marcelm/cutadapt/files/2750928/1-901_S199_L001_R1_001.fastq.gz)
[1-901_S199_L001_R2_001.fastq.gz](https://github.com/marcelm/cutadapt/files/2750929/1-901_S199_L001_R2_001.fastq.gz)

I can't see any obvious differences between the file pairs (e.g. info up to the trailing whitespace is the same, a search of "+" in the fastq file yields identical counts in each pair), so can't seem to figure out why I'm getting this error. 

Any advice? Thanks so much.

Steve

**- Cutadapt and Python version**
cutadapt 1.18
Python 3.5.5

**- How you installed the tool (conda or pip, for example)**
pip install --user --upgrade cutadapt

**- Which command-line parameters you used**
parallel --link --jobs 50   'cutadapt \
    --pair-filter any \
    --no-indels \
    --discard-untrimmed \
    -a TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG \
    -A GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG \
    -g CGAAATYGGTAGACGCTACG \
    -G CCDTYGAGTCTCTGCACCTATC \
    -o primer_trimmed_fastqs/{1/} \
    -p primer_trimmed_fastqs/{2/} \
    {1} {2} \
    > primer_trimmed_fastqs/{1/}_cutadapt_log.txt'   ::: raw_reads/*_R1*.fastq.gz ::: raw_reads/*_R2*.fastq.gz

**Comment by StevenMamet** [comment]
Here's an update: it turns out I had actually been using cutadapt 1.14. WIth that version only 30 pairs of the ~1100 fastq files I had would pass cutadapt. I checked several of the files that failed (including the two I mentioned earlier) and found they were incorrectly labeled as "improperly paired". After updating to 1.18, I found now 151 pairs passed cutadapt. Inspecting the pairs that didn't pass this round showed those files did indeed have differing amounts of reads. So in a nutshell—I messed up by using an old version of cutadapt, but in the end found out some of the pairing errors were true, so perhaps there was some file corruption when those sequences came of the sequencer.

**Comment by marcelm** [comment]
Ok, great. While you found this out, I tried to reproduce it using the files you provided (using Cutadapt 1.18) and wasn’t able to.

For the record, here’s a command that uses Cutadapt to check whether paired-end FASTQ files are properly paired:
```
cutadapt -o /dev/null -p /dev/null R1.fastq.gz R2.fastq.gz
```
Thanks for the `parallel` example with `--link` – I wasn’t aware that this option existed, very useful!

**Comment by StevenMamet** [comment]
Thanks for the check command. That will come in handy!

And I borrowed the parallel --link command from the microbiome helper git:

https://github.com/LangilleLab/microbiome_helper/wiki/Amplicon-SOP-v2-(qiime2-2018.8)

Very useful indeed!

**Comment by JenPryor** [comment]
Hi there, I've had the same issue and have now identified reads which are "improperly paired" and I am wondering what to do now? Did you delete those reads? Or edit the fastq files so that they have the same number of reads? or is there some other action I should take? Thank you for any help, I am very new to this!

**Comment by marcelm** [comment]
There are some scripts out there that re-synchronize paired-end reads that are no longer properly paired.

That said, it would be preferable to process the data in such a way that improperly paired reads don’t occur in the first place. Cutadapt should never produce files that are improperly paired (if it did, please open a separate issue), so I am assuming the problem comes from some other tool that you ran. Perhaps that tool has a bug or need some command-line option to work correctly.

**Comment by JenPryor** [comment]
Thank you so much for your reply! I am working with data that I downloaded from the NCBI Sequence Read Archive so unfortunately, I don't have any control over what was done to the reads beforehand but all that I have done is download and import the files into Qiime2 to use cutadapt. I have around 120 SRRs and only one of them seems to be causing a problem. I can see in the corresponding fastq file that there is definitely a different number of reads between its file 1 and file 2 so I think I will just delete that one, however I'm unsure if deleting it from the .qza file will cause any issues. Thanks for your help!
