### ISSUE TITLE
Trimming batch of sequences based on specific region

### ISSUE THREAD

**Issue by Thijmen18** [marcelm/cutadapt#351]
Hi,

I am trying to find a solution using cutadapt for the following: I have a list of specific regions I need to trim from a batch of sequences. Is there a way to do this in cutadapt?

The list of specific 'to trim' regions, like so (but then for multiple sequences):
Sequence name, length, span(s),
sequence1	433	1..56
sequence2	972	1..67

Would it be possible to trim sequences in batch with cutadapt, with specific regions specified?

Thanks in advance!

**Comment by marcelm** [comment]
I’m not sure what you mean by *sequences*. Do you have multiple FASTA or FASTQ files and want to trim each differently?

**Comment by marcelm** [comment]
I’m closing this issue for now, but please feel free to comment if it is still relevant.
