### ISSUE TITLE
Many unknown seqs after demultiplexing mixed forward and reverse reads in R1 and R2

### ISSUE THREAD

**Issue by nitschkematthew** [marcelm/cutadapt#356]
_NOTE: I have modified the title to disambiguate what I previously incorrectly described as 'interleaved' - which is a different file format to what I described below._

First off - I am really enjoying cutadapt! Quickly becoming a core tool in my pipes so thanks for the continued development.

I often use cutadapt (currently using v 1.18) to demultiplex paired-end R1 and R2 files into individual R1 and R2 files for each sample, followed by a bash script to loop cutadapt across all R1 and R2 files to remove primers, followed by dada2 and etc downstream.

However, in this instance I noticed that unknown.R1.fastq.gz and unknown.R1.fastq.gz files after demultiplexing were near half the size as the input.R1.fastq.gz and input.R2.fastq.gz files. I think I have encountered an interesting case which is described clearly here in the Qiime2 forums [https://forum.qiime2.org/t/import-multiplexed-r1-fastq-and-r2-fastq-with-mixed-forward-and-reverse-reads-truncate-reverse-primer/2052]. However, it doesnt appear to me that there was an adequate demultiplexing solution achieved before moving downstream into denoising with dada2.

In the info from the sequencer:
```
Example of R1 and R2 format (standard mixed pair format)

R1
Sequence1  barcode-forwardprimer-sequence
Sequence2  reverseprimer-sequence
Sequence3  barcode-forwardprimer-sequence
...etc

R2
Sequence1  reverseprimer-sequence
Sequence2  barcode-forwardprimer-sequence
Sequence3  reverseprimer-sequence
...etc
```
The barcode is only found on the forward primer but these are then interleaved(mixed?) into R1 and R2. When I run...
```
cutadapt -g file:barcodes.fasta -o trimmed-{name}.R1.fastq.gz -p trimmed-{name}.R2.fastq.gz input.R1.fastq.gz input.R2.fastq.gz
```
...if I understand cutadapt correctly, I am only successfully demultiplexing the samples where the barcodes are found in R1, and the rest that are barcoded in R2 are sent to the unknown files.

Do you have any suggestions regarding how to circumvent this problem and successfully demultiplex from both R1 and R2? In the cutadapt docs it states that "If adapters to be found in read 2 are given (-A/-G), they are detected and removed as normal, but these matches do not influence where the read pair is written". I guess this does not apply in this case because the adapters in read 2 NEED to influence where the pair is written. 

Many thanks!

**Comment by nitschkematthew** [comment]
Just as an afterthought, what if I was to take the unknown.1.fastq.gz and unknown.2.fastq.gz spit out after running the first round of cutadapt as above, swap them and simply rename them as

```
unknown.R2.fastq.gz = unknown.R1.fastq.gz
unknown.R1.fastq.gz = unknown.R2.fastq.gz
```
then use them as inputs in a second round of the same code
```
cutadapt -g file:barcodes.fasta -o trimmed-{name}.R1.fastq.gz -p trimmed-{name}.R2.fastq.gz unknown.R1.fastq.gz unknown.R2.fastq.gz
```
This might work because the barcodes need to be in the forward file for demultiplexing with cutadapt. The only thing I would need to be aware of downstream is that after the second round of cutadapt (demultiplexing and primer-removing), the new "forward-reads" will be of "reverse-read' quality, and so will need to be run separately through dada2 to generate error models specific to the second round of demultiplexing. Concatenating of the first and second rounds can be done AFTER each have been denoised and then merged individually.

Am I going on a massive tangent here or does this seem reasonable?

**Comment by marcelm** [comment]
Interesting, thanks for sharing. It seems whichever seemingly reasonable assumptions I make when implementing a feature, there’s always some protocol out there that proves me wrong ...

In your example of the "mixed pair format", you alternated between the two possible versions (5'-3' and the 3'-5'), but just to be absolutely certain: Is it correct that in reality this is just random? I am asking because the word *interleaved* is also used to describe the single-file paired-end FASTQ format where all the odd-numbered records are the R1 reads and the even-numbered reads are the corresponding R2 reads. But that is not the case here, right?

If I understand the problem correctly, then yes, you should be able to proceed as you suggested by running cutadapt a second time on the unknown.* files. My suggestion however would be to not rename the files. You can just reverse the roles of the R1/R2 files when you run cutadapt:
```
cutadapt -g file:barcodes.fasta -o trimmed-{name}.R2.fastq.gz -p trimmed-{name}.R1.fastq.gz unknown.R2.fastq.gz unknown.R1.fastq.gz
```
(Perhaps add a clarifying comment to ensure that whoever sees this a couple of months later doesn’t try to "fix" it.)

If this works, I’d like to at least add this to the documentation, but perhaps some feature could be added to cutadapt to make processing this type of data easier. There is a quite an old open issue #220 about trimming each read and also its reverse complement. Perhaps that would be a solution.

Also, perhaps the `--pair-adapters` which issue #347 asks for might help.

**Comment by nitschkematthew** [comment]
@marcelm thanks for the fast reply. You are correct. I misused the term 'interleaved' which I realize now describes a different standard format. I have modified the title of the issue to more accurately describe my situation

I have tested what we discussed above with piping the unknown.R2.fastq.gz unknown.R1.fastq.gz (in that order) into a second round of cutadapt. It worked beautifully. The remaining reads that were not successfully demultiplexed/trimmed after the second round of cutadapt are the true 'unknowns'! Excellent!

Feel free to tag me if you want someone to take a look at any new documentation you add related to this example.

**Comment by marcelm** [comment]
Hi, here is a suggestion for a text that I would like to add to the documentation. Comments?
```
Demultiplexing paired-end reads in mixed orientation

For some protocols, the barcode will be located either on R1 or on R2
depending on the orientation in which the DNA fragment was sequenced.

For example, the read layout could be either this ::

    R1: barcode-forwardprimer-sequence  R2: reverseprimer-sequence

or this ::

    R1: reverseprimer-sequence  R2: barcode-forwardprimer-sequence

To demultiplex such data with Cutadapt, choose one of the orientations first and
demultiplex the reads as if only that existed in the data, using a command like this ::

    cutadapt -g file:barcodes.fasta \
        -o round1-{name}.R1.fastq.gz \
        -p round1-{name}.R2.fastq.gz \
        R1.fastq.gz R2.fastq.gz

Then all the read pairs in which no barcode could be found will end up in
``round1-unknown.R1.fastq.gz`` and ``round1-unknown.R2.fastq.gz``. This will
also include the pairs in which the barcode was not actually in R1, but in R2. To
demultiplex these reads as well, run Cutadapt a second time with those “unknown”
files as input, but also reverse the roles of R1 and R2 ::

    cutadapt -g file:barcodes.fasta \
        -o round2-{name}.R2.fastq.gz \
        -p round2-{name}.R1.fastq.gz \
        round1-unknown.R2.fastq.gz round1-unknown.R1.fastq.gz
```

**Comment by nitschkematthew** [comment]
Sorry for the late reply @marcelm 
That reads very straight forward to me and I imagine will be useful to quite a few people in the future.

**Comment by marcelm** [comment]
Thanks! I added the section to the documentation.
