### ISSUE TITLE
Advice for TruSeq Short Insert Sizes Lacking in User Guide

### ISSUE THREAD

**Issue by DarioS** [marcelm/cutadapt#362]
The section of the user guide for Illumina TruSeq recommends `-a` and `-A` but this ignores reads which have extremely short inserts, such that the entire adapter sequence is contained within them, followed by some other sequence. A command which works in this case (adapter not anchored at read end) should be added to the documentation. Perhaps apart from the mention of BWA-MEM soft-clipping in the documentation, it could also mention STAR which does the same for RNA-seq.

**Comment by marcelm** [comment]
I don’t quite understand – the `-a` and `-A` adapter types will find an adapter even if it is followed by other sequence (as [documented](https://cutadapt.readthedocs.io/en/stable/guide.html#regular-3-adapters)). I can add the note about soft-clipping with STAR.

**Comment by marcelm** [comment]
I’ve rewritten the section about 5' clipping a bit. It now also mentions STAR and makes it clear that this is only an example of a read mapper that does it.

Regarding the `-a`/`-A`, please re-open if you think this is still an issue.

Updating docs should be visible at https://cutadapt.readthedocs.io/en/latest/guide.html#illumina-truseq soon.
