### ISSUE TITLE
Trim if TruSeq Read 2 Adapter is Truncated

### ISSUE THREAD

**Issue by DarioS** [marcelm/cutadapt#363]
Quite a few reads from a short insert size data set I have contain TruSeq adapter in the second read after trimming.

![image](https://user-images.githubusercontent.com/631218/53770718-4cbfd380-3f34-11e9-9f13-7ab03b4fe512.png)

The read 1 adapter is trimmed by cutadapt because the complete adapter sequence is found in the reads.

![image](https://user-images.githubusercontent.com/631218/53770740-5fd2a380-3f34-11e9-91e7-a71201f3895d.png)

According to the Illumina's specification and to cutadapt's user guide, the TruSeq read 2 adapter is longer than the read 1 adapter. I notice that many reads in my dataset have a truncated read 2 adapter (many have the full-length version, too) which is coincidentally the same length as the read 1 adapter.

![image](https://user-images.githubusercontent.com/631218/53770792-809af900-3f34-11e9-9767-dfa8a8e7b373.png)

The read 2 adapter is not trimmed because it is truncated. Is it recommended to simply change the value of `-A` to be the same length as the string `-a` to erase adapters thoroughly? The sequence following the truncated adapter appears to be CTCACCAAGTGTAGAT in a couple of reads I have looked at manually. It's not random but probably another part of the TruSeq sequencing kit.

![image](https://user-images.githubusercontent.com/631218/53770932-fef79b00-3f34-11e9-95fe-cdeb5fff3baa.png)

**Comment by marcelm** [comment]
Thanks for this! The TruSeq section in the docs was simply outdated. The nice Illumina document with all the adapter sequences simply didn’t exist when I wrote it.

The recommendation refers to an older version of the protocol. While I cannot reconstruct right now when and how exactly it changed, it is probably much safer just to defer the reader to the Illumina document. The given adapter sequences will also work for the older protocol versions, so it should be safe.
