### ISSUE TITLE
cutadapt error "AssertionError" when use both "-g/G" and "-q"

### ISSUE THREAD

**Issue by CatKucha** [marcelm/cutadapt#370]
- Cutadapt and Python version
cutadapt 2.0 with Python 3.7.2
- How you installed the tool (conda or pip, for example)
I use codna _conda install -c bioconda cutadapt_
- Which command-line parameters you used
_cutadapt  -g GTGCCAGCMGCCGCGGTAA -G CCGTCAATTCMTTTRAGTTT  -q 15,10 -o test_R1_adpt.fastq -p test_R2_adpt.fastq Z6.raw_1.fastq.gz  Z6.raw_2.fastq.gz_

I got this error message:

> This is cutadapt 2.0 with Python 3.7.2
> Command line parameters: -g GTGCCAGCMGCCGCGGTAA -G CCGTCAATTCMTTTRAGTTT -q 15,10 -o test_R1_adpt.fastq -p test_R2_adpt.fastq Z6.raw_1.fastq.gz  Z6.raw_2.fastq.gz
> Processing reads on 1 core in paired-end mode ...
> Traceback (most recent call last):
>   File "/home/Cat/anaconda3/bin/cutadapt", line 12, in <module>
>     sys.exit(main())
>   File "/home/Cat/anaconda3/lib/python3.7/site-packages/cutadapt/__main__.py", line 787, in main
>     stats = runner.run()
>   File "/home/Cat/anaconda3/lib/python3.7/site-packages/cutadapt/pipeline.py", line 723, in run
>     (n, total1_bp, total2_bp) = self._pipeline.process_reads(progress=self._progress)
>   File "/home/Cat/anaconda3/lib/python3.7/site-packages/cutadapt/pipeline.py", line 320, in process_reads
>     read1, read2 = modifier(read1, read2, matches1, matches2)
>   File "/home/Cat/anaconda3/lib/python3.7/site-packages/cutadapt/modifiers.py", line 33, in __call__
>     return self._modifier1(read1, matches1), self._modifier2(read2, matches2)
>   File "/home/Cat/anaconda3/lib/python3.7/site-packages/cutadapt/modifiers.py", line 178, in __call__
>     match = self._best_match(trimmed_read)
>   File "/home/Cat/anaconda3/lib/python3.7/site-packages/cutadapt/modifiers.py", line 106, in _best_match
>     match = adapter.match_to(read)
>   File "/home/Cat/anaconda3/lib/python3.7/site-packages/cutadapt/adapters.py", line 841, in match_to
>     alignment = self.aligner.locate(read_seq)
>   File "src/cutadapt/_align.pyx", line 515, in cutadapt._align.Aligner.locate
> AssertionError

However when I remove "-q 15,10" parameter cutadapt works fine. And when I use only "-a/A" with "-q 15,10" it also works. So how to solve this error?
Bestwishes!
Cat

**Comment by marcelm** [comment]
Hi, the error you see was already reported yesterday in issue #369. I’ve fixed it in the source code already, but the most recent release still contains the bug. I’ll make a new release soon.

**Comment by CatKucha** [comment]
Thank you! I'll try the source code ^__^
And sorry I didn't look at that issue. Thanks again!

**Comment by marcelm** [comment]
In case you need it: The installation instructions for the development version were incorrect. I have just updated them, see https://cutadapt.readthedocs.io/en/latest/installation.html#installing-the-development-version .

**Comment by jmmack** [comment]
I believe I am having the same issue as OP, but when I try to install from source I get this error:
`ERROR: Cython is not installed. Install at least Cython version 0.28 to continue.`

But it's already installed?

`cython -V`
Cython version 0.29.6

**Comment by marcelm** [comment]
Did you follow the instructions that I linked to above? If not, how exactly did you try to install the development version?

**Comment by jmmack** [comment]
Yes, it was the instructions from: https://cutadapt.readthedocs.io/en/latest/installation.html#installing-the-development-version

Install:
```
sudo apt-get install python3-venv
sudo apt-get install build-essential
sudo python3 -m venv /home/shared/software/cutadapt-venv

/home/shared/software/cutadapt-venv/bin/pip install git+https://github.com/marcelm/cutadapt.git#egg=cutadapt
```
Just for reference:
```
which cython
/usr/local/bin/cython

cython -V
Cython version 0.29.6
```
Full message:
```
Collecting cutadapt from git+https://github.com/marcelm/cutadapt.git#egg=cutadapt
  Cloning https://github.com/marcelm/cutadapt.git to /tmp/pip-build-unco3v63/cutadapt
Requirement already satisfied: dnaio>=0.3 in /home/shared/software/cutadapt-venv/lib/python3.6/site-packages (from cutadapt)
Requirement already satisfied: xopen>=0.5.0 in /home/shared/software/cutadapt-venv/lib/python3.6/site-packages (from cutadapt)
Installing collected packages: cutadapt
  Running setup.py install for cutadapt ... error
    Complete output from command /home/shared/software/cutadapt-venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-unco3v63/cutadapt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tooh9lmd-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/shared/software/cutadapt-venv/include/site/python3.6/cutadapt:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cutadapt
    copying src/cutadapt/__main__.py -> build/lib.linux-x86_64-3.6/cutadapt
    copying src/cutadapt/modifiers.py -> build/lib.linux-x86_64-3.6/cutadapt
    copying src/cutadapt/utils.py -> build/lib.linux-x86_64-3.6/cutadapt
    copying src/cutadapt/align.py -> build/lib.linux-x86_64-3.6/cutadapt
    copying src/cutadapt/adapters.py -> build/lib.linux-x86_64-3.6/cutadapt
    copying src/cutadapt/pipeline.py -> build/lib.linux-x86_64-3.6/cutadapt
    copying src/cutadapt/filters.py -> build/lib.linux-x86_64-3.6/cutadapt
    copying src/cutadapt/report.py -> build/lib.linux-x86_64-3.6/cutadapt
    copying src/cutadapt/__init__.py -> build/lib.linux-x86_64-3.6/cutadapt
    running build_ext
    ERROR: Cython is not installed. Install at least Cython version 0.28 to continue.
    
    ----------------------------------------
Command "/home/shared/software/cutadapt-venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-unco3v63/cutadapt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tooh9lmd-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/shared/software/cutadapt-venv/include/site/python3.6/cutadapt" failed with error code 1 in /tmp/pip-build-unco3v63/cutadapt/
```

**Comment by marcelm** [comment]
Ok, thanks. This is probably not the issue, but please don’t use `sudo` for the `python3 -m venv /home/shared/software/cutadapt-venv` part if you can avoid it. (`apt-get` requires `sudo` of course.) If you do get permission problems later, remove the `/home/shared/software/cutadapt-venv` directory and start over without `sudo`.

Cython needs to be installed within the virtual environment, so the Cython that you get with `which cython` is actually not the one that will be used.

The easiest way to solve this is probably to just upgrade `pip` within the virtual environment before installing cutadapt. Recent pip versions should automatically install Cython.

So please try this:
```
/home/shared/software/cutadapt-venv/bin/pip install --upgrade pip
```
Then repeat the last step:
```
/home/shared/software/cutadapt-venv/bin/pip install git+https://github.com/marcelm/cutadapt.git#egg=cutadapt
```
If this works, I’ll update the instructions in the documentation.

**Comment by jmmack** [comment]
Those steps worked, thank you!

Here's what I did in total:

```
sudo apt-get install python3-venv
sudo apt-get install build-essential
python3 -m venv /home/shared/software/cutadapt-venv

/home/shared/software/cutadapt-venv/bin/pip install --upgrade pip

/home/shared/software/cutadapt-venv/bin/pip install git+https://github.com/marcelm/cutadapt.git#egg=cutadapt

/home/shared/software/cutadapt-venv/bin/cutadapt --version
```
2.2.dev6+gf6ea75a

**Comment by marcelm** [comment]
Thanks, I’ve fixed in the instructions!
