### ISSUE TITLE
Question regarding linked adapters in PE reads

### ISSUE THREAD

**Issue by aistBMRG** [marcelm/cutadapt#372]
Hi,

Thank you very much for keeping to develop Cutadapt -- it is a great tool in my research.

Now, small question regarding read filtering from linked adapters and PE reads. I have an amplicon set that is shorter than the read length, so I expected to see both forward and reverse primers in both reads. As suggested, I am running the following type of command:

cutadapt \
-a ^ACWCCTACGGGWGGCWGC...CAGCMGCCGCGGTAATWC \
-A ^GWATTACCGCGGCKGCTG...GCWGCCWCCCGTAGGWGT --discard-untrimmed \
-o ${x}_R1_trimmed.fastq -p ${x}_R2_trimmed.fastq \
${x}_L001_R1_001.fastq.gz ${x}_L001_R2_001.fastq.gz

Now, it is mentioned in the manual that linked adapters are only considered trimmed when both  adapters are found. This is the behavior I want but I am not sure if it applies here. Basically, I want to discard all pairs where not all 4 adapters/primers are found ... is this what will happen?

Regards,

Dieter.

**Comment by aistBMRG** [comment]
actually looking at the output it seems that only the anchored 5' adapter is considered:

Total read pairs processed:            345,393
  Read 1 with adapter:                 **328,865** (95.2%)
  Read 2 with adapter:                 **323,693** (93.7%)
Pairs written (passing filters):       _320,666_ (92.8%)

=== First read: Adapter 1 ===

Sequence: ACWCCTACGGGWGGCWGC...CAGCMGCCGCGGTAATWC; Type: linked; Length: 18+18; 5' trimmed: **328865** times; 3' trimmed: 313159 times

=== Second read: Adapter 4 ===

Sequence: GWATTACCGCGGCKGCTG...GCWGCCWCCCGTAGGWGT; Type: linked; Length: 18+18; 5' trimmed: **323693** times; 3' trimmed: 280917 times

Thanks.

Dieter.

**Comment by marcelm** [comment]
Yes, if you use `-a` or `-A` to specify a linked adapter, only the anchored adapters are required. If you use `-g` or `-G` instead, then both adapters will be required. See also https://cutadapt.readthedocs.io/en/stable/guide.html#changing-which-adapters-are-required . I’ve rewritten parts of that section recently, so perhaps it’s worth re-reading.

**Comment by marcelm** [comment]
I hope my answer was helpful, so closing for now.
