### ISSUE TITLE
How to install and use cutadapt-1.18

### ISSUE THREAD

**Issue by galagoz** [marcelm/cutadapt#374]
Hi all,

I've been trying to install and use Cutadapt-1.18 on a server with python2.7.6. Since I need to use this version, I guess I'm not able to use pip, and since I'm not familiar with conda, I basically downloaded "[cutadapt-1.18-cp27-cp27m-manylinux1_x86_64](https://pypi.org/project/cutadapt/1.18/#files)" to my laptop and moved it to the server. However, there is not a setup/make/cutadapt file in the folder. So, I'm not sure how to run cutadapt, I'd be more than happy if you could help me with this issue.

PS: I also tried to use version 1.3, there was a setup.py file in the downloaded folder, but I could not proceed with `python setup.py install`, I received the following output:

```
running install
running build
running build_py
running build_ext
skipping 'cutadapt/calign.c' Cython extension (up-to-date)
running build_scripts
running install_lib
creating /usr/local/lib/python2.7/dist-packages/cutadapt
error: could not create '/usr/local/lib/python2.7/dist-packages/cutadapt': Permission denied
```

I guess it's because I don't have sudo permissions in the server, because I was able to overcome this issue with version 1.3 on my laptop by running the same command as sudo.

Best regards,
Gökberk

**Comment by marcelm** [comment]
Do you have internet access on that server? pip will work in that case. You can try `pip install --user --upgrade cutadapt`. This what is described on https://cutadapt.readthedocs.io/en/stable/installation.html#quick-installation , but replacing `pip3` with just `pip`.

**Comment by galagoz** [comment]
Yes actually I tried using pip on server and it worked as you said, but it downloads the most recent version and I cannot use that for my SOLiD colorspace data.

**Comment by marcelm** [comment]
You *really* have SOLiD data? Wow :-) (It’s not *new* data, I hope.)

pip should actually realize that Cutadapt 1.18 is the last Python 2 version of the package and install that one (if you run pip under Python 2). It is possible that you are using an older pip version, though, or that your pip actually is a Python 3 version. Anyway, you can specify the Cutadapt version that you want to have like this:
```
pip install --user --upgrade cutadapt==1.18
```

**Comment by galagoz** [comment]
Thanks for your quick response! Nope it's not new, it's an old dataset that I want to look into :)

And it worked, thanks a lot! However, I have another question now, if it's not too much to ask. After I downloaded v1.18 using your command, I checked the [GEO page](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1932267) of the dataset I want to look into and copied the exact same command that people used before with cutadapt-1.18 (changed only the fastq file, output name and directories): `~/.local/bin/cutadapt -c -m 30 -a CTCGAGGGCGCGCCGGATCCATATACGCCTTGGCCGTACAGCAG -g CTCGAGGGCGCGCCGGATCCATATACGCCTTGGCCGTACAGCAG -a AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA fastq/E08/SRR2930102.fastq > ./SRR2930102_trimmed.fastq`

However, I received the following output:
```

This is cutadapt 1.18 with Python 3.6.8
Command line parameters: -c -m 30 -a CTCGAGGGCGCGCCGGATCCATATACGCCTTGGCCGTACAGCAG -g CTCGAGGGCGCGCCGGATCCATATACGCCTTGGCCGTACAGCAG -a AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA fastq/E08/SRR2930102.fastq
Processing reads on 1 core in single-end mode ...
cutadapt: error: In read named 'SRR2930102.1 1_3_1142_F3 length=50': length of colorspace quality sequence (51) and length of read (50) do not match (primer is: 'T')
```

I was wondering what might be the reason for this difference at quality seq. length and length of read. Also, I checked [your page about colorspace reads](https://cutadapt.readthedocs.io/en/v1.18/colorspace.html), but couldn't find anything about the option "-m", what would that be?

Also, even though when I run `python -V` on the server, it says `Python 2.7.6`, when I ran cutadapt it used version 3.6.8 for some reason. I'm not sure how to switch to python 2, is there a way to specify which python version it should use or is this even a problem?

Sorry for tons of questions, thanks in advance.

**Comment by marcelm** [comment]
Great, I’m glad you got it installed.

Regarding SOLiD data downloaded from SRA: You need to add [the `--format=sra-fastq` option](https://cutadapt.readthedocs.io/en/v1.18/colorspace.html#sequence-read-archive) to the commandline.

The `-m` option is not related to colorspace. It is shorthand for `--minimum-length`, that is, all reads shorter than the given length (30 in your case) will be discarded. You can see it described when you run `cutadapt --help`.

Finally, the Python version does not matter for Cutadapt 1.18. It supports both Python 2 and 3. If it runs, you’re fine!

**Comment by galagoz** [comment]
Thank you very much, it worked! And apparently I should have read the manual more carefully.

Best wishes!
