### ISSUE TITLE
Problem with only one sequence in a file

### ISSUE THREAD

**Issue by ogandril** [marcelm/cutadapt#376]
I am using `-g file:tags.fa` to specifiy the sequences of interest.
When there are two sequences, it works fine:
```
>Plate1
^GACT
>Plate2
^CATG
```
When I am using only the first two lines:
```
>Plate1
^GACT
```
I get the following error:

```
Command error:
  Traceback (most recent call last):
    File "/usr/bin/cutadapt", line 10, in <module>
      sys.exit(main())
    File "/usr/lib/python3.6/site-packages/cutadapt/__main__.py", line 803, in main
      stats = runner.run()
    File "/usr/lib/python3.6/site-packages/cutadapt/pipeline.py", line 727, in run
      (n, total1_bp, total2_bp) = self._pipeline.process_reads(progress=self._progress)
    File "/usr/lib/python3.6/site-packages/cutadapt/pipeline.py", line 324, in process_reads
      read1, read2 = modifier(read1, read2, matches1, matches2)
    File "/usr/lib/python3.6/site-packages/cutadapt/modifiers.py", line 32, in __call__
      return self._modifier1(read1, matches1), read2
    File "/usr/lib/python3.6/site-packages/cutadapt/modifiers.py", line 179, in __call__
      match = AdapterCutter.best_match(self.adapters, trimmed_read)
    File "/usr/lib/python3.6/site-packages/cutadapt/modifiers.py", line 107, in best_match
      match = adapter.match_to(read)
    File "/usr/lib/python3.6/site-packages/cutadapt/adapters.py", line 797, in match_to
      assert match.length >= self.min_overlap
  AssertionError
```

I tried to simply duplicate the first tag
```
>Plate1
^GACT
>Plate1
^GACT
```
And this worked fine...

Any specific reason why cutadapt is expecting at least two sequences in the file?

Best

Olivier

*Edit (this was hidden within the comment in the issue template):*

Please provide the following information:

- Cutadapt and Python version

   * cutadapt: 2.1
   * Python 2.7.10

- How you installed the tool (conda or pip, for example)

   `docker profile`

- Which command-line parameters you used

   `cutadapt --no-trim -e 0 --no-indels   -g file:tags2.fa   --pair-filter=any --minimum-length 14 --discard-untrimmed   -o {name}_R1.fastq   -p {name}_R2.fastq   10k_R1_cut.fastq 10k_R2_cut.fastq > plate_output.txt`

**Comment by marcelm** [comment]
Cutadapt does not require two sequences per se, so this is a bug.

I would like to reproduce the problem. Do you think you could make the input FASTQ files available to me?

**Comment by ogandril** [comment]
> Le 17 avr. 2019 à 13:50, Marcel Martin <notifications@github.com> a écrit :
> 
> Cutadapt does not require two sequences per se, so this is a bug.
> 
OK
> I would like to reproduce the problem. Do you think you could make the input FASTQ files available to me?
> 
Sure.

Attached.

Olivier

**Comment by marcelm** [comment]
I think if your attachment did not make it here. Can you send the files directly to marcel.martin (at) scilifelab.se, please?

**Comment by ogandril** [comment]
And the actual files for specifying the sequences to cut

**Comment by marcelm** [comment]
Thanks, that was helpful. The problem appears to be the 40th read in the file, which is empty. Cutadapt apparently cannot handle that when `--no-indels` is used together with an anchored 5' adapter. I’ll fix this.

**Comment by ogandril** [comment]
> Le 17 avr. 2019 à 14:21, Marcel Martin <notifications@github.com> a écrit :
> 
> Thanks, that was helpful. The problem appears to be the 40th read in the file, which is empty. Cutadapt apparently cannot handle that when --no-indels is used together with an anchored 5' adapter. I’ll fix this.
> 
Excellent! Thank’s for your fast answer!
Keep me posted when it’s fixed.

Best

Olivier

**Comment by marcelm** [comment]
This is now fixed in the development version. There haven’t been that many changes since the last release, so I was planning to work on one or two more issues before the next release. You can install the development version until then (or convince me to make a release anyway).

**Comment by ogandril** [comment]
> Le 17 avr. 2019 à 16:22, Marcel Martin <notifications@github.com> a écrit :
> 
> This is now fixed in the development version. There haven’t been that many changes since the last release, so I was planning to work on one or two more issues before the next release. You can install the development version until then (or convince me to make a release anyway).
> 
:-)
I’d love to have a release, but as a matter of fact since you have been so helpful, I would like to submit another potential bug. 
Less problematic but slows down the execution of my pipe.
I just submitted the new issue. (#377)

Best

Olivier

**Comment by marcelm** [comment]
Ok, Cutadapt 2.2 is now released!

**Comment by ogandril** [comment]
Thank’s a lot!

Olivier
