### ISSUE TITLE
Multi-core support dependent upon command used

### ISSUE THREAD

**Issue by ogandril** [marcelm/cutadapt#377]
I am using cutadapt twice in a nextflow pipe.

The first time I specifiy that I want it to use the four cores of my machine and ity goes well:

  cutadapt -q 30,30 -a AGATCGGAAGAG -g CTCTTCCGATCT \
  -A AGATCGGAAGAG -G CTCTTCCGATCT \
  -j 4 \
  -o ${pair_id}1_cut.fastq -p ${pair_id}2_cut.fastq \
  ${reads[0]} ${reads[1]} > ${pair_id}_adaptor_removal_report.txt

The second time if I use   -j 4 \ in the process, it produces a bug (unfortunately, with no specific understandable output)

  cutadapt --no-trim -e 0 --no-indels \
  -g file:${tags} \
  -j 4 \
  --pair-filter=any --minimum-length 14 --discard-untrimmed \
  -o {name}_R1.fastq \
  -p {name}_R2.fastq \
  ${reads[0]} ${reads[1]} > plate_output.txt

Olivier

**Comment by marcelm** [comment]
I would like to help, but I will need some kind of error message. What is the bug exactly? What is different from what you would expect?

**Comment by ogandril** [comment]
Here are the erorr lines from my pipe:

[4d/7af214] Submitted process > demultiplex_barcode_plate (10k_R)
ERROR ~ Error executing process > 'demultiplex_barcode_plate (10k_R)'

Caused by:
  Process `demultiplex_barcode_plate (10k_R)` terminated with an error exit status (1)

Command executed:

  cutadapt --no-trim -e 0 --no-indels   -g file:tags.fa   -j 4   --pair-filter=any --minimum-length 14 --discard-untrimmed   -o {name}_R1.fastq   -p {name}_R2.fastq   10k_R1_cut.fastq 10k_R2_cut.fastq > plate_output.txt

Command exit status:
  1

Command output:
  (empty)

**Comment by ogandril** [comment]
The very same command without -j 4 works just fine.

**Comment by marcelm** [comment]
What are the contents of `plate_output.txt` until the point it crashes? You can also remove the `> plate_output.txt` from your Nextflow process definition and re-run it. Then the "Command output:" section should contain something. Do you have the same problem when you run the command manually (that is, not from within Nextflow)?
(I may not reply until after the Easter weekend.)

**Comment by ogandril** [comment]
The contents of plate_output.txt until the point it crashes;

This is cutadapt 2.1 with Python 3.6.6
Command line parameters: --no-trim -e 0 --no-indels -g file:tags.fa -j 4 --pair-filter=any --minimum-length 14 --discard-untrimmed -o {name}_R1.fastq -p {name}_R2.fastq 10k_R1_cut.fastq 10k_R2_cut.fastq
Building index of 2 adapters ...
Built an index containing 2 strings.
ERROR: Running in parallel is currently not supported for the given combination of command-line parameters.
These options are not supported: --info-file, --rest-file, --wildcard-file, --untrimmed-output, --untrimmed-paired-output, --too-short-output, --too-short-paired-output, --too-long-output, --too-long-paired-output, --format
Omit --cores/-j to continue.
~

**Comment by ogandril** [comment]
I should have tried that before! That was very interesting!
But I do not see any of my options in the list?

**Comment by marcelm** [comment]
Ah, I could have seen that myself. The problem is that multi-core is currently not supported when doing demultiplexing (that is, when the output file name includes `{name}`). I will change the error message to mention that as well.

Supporting multicore demultiplexing should not be too hard, but I need to find some time to implement it.

**Comment by ogandril** [comment]
OK, thank's for your prompt answer. 

Now I would like to plead for a 2.2 release :-) 

Le 2019-04-18 17:40, Marcel Martin a écrit :

> Ah, I could have seen that myself. The problem is that multi-core is currently not supported when doing demultiplexing (that is, when the output file name includes {name}). I will change the error message to mention that as well. 
> 
> Supporting multicore demultiplexing should not be too hard, but I need to find some time to implement it. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/marcelm/cutadapt/issues/377#issuecomment-484565875
[2]
