### ISSUE TITLE
Trouble demultiplexing dual indexed reads

### ISSUE THREAD

**Issue by thermokarst** [marcelm/cutadapt#378]
Thanks for the great tool, @marcelm! I am trying to test out the recently-added dual-index demultiplexing functionality. I can get DI _trimming_ to work, but not demultiplexing --- no reads are demultiplexed. I am _hoping_ this is just user error on my end --- any assistance would be greatly appreciated!

Possibly related to #347.

- `cutadapt` 2.1
- `python` 3.6

## Minimum working example

<details>
<summary><code>forward.fastq.gz</code></summary>

```
@id1
AAAAACGTACGT
+
zzzzzzzzzzzz
@id2
CCCCACGTACGT
+
zzzzzzzzzzzz
@id3
AAAAACGTACGT
+
zzzzzzzzzzzz
@id4
CCCCACGTACGT
+
zzzzzzzzzzzz
@id5
CCCCACGTACGT
+
zzzzzzzzzzzz
@id6
GGGGACGTACGT
+
zzzzzzzzzzzz
```
</details>

<details>
<summary><code>reverse.fastq.gz</code></summary>

```

@id1
GGGGTGCATGCA
+
zzzzzzzzzzzz
@id2
TTTTTGCATGCA
+
zzzzzzzzzzzz
@id3
GGGGTGCATGCA
+
zzzzzzzzzzzz
@id4
TTTTTGCATGCA
+
zzzzzzzzzzzz
@id5
TTTTTGCATGCA
+
zzzzzzzzzzzz
@id6
TTTTTGCATGCA
+
zzzzzzzzzzzz
```
</details>

command run:
```bash
cutadapt \
  -g sample1=AAAA \
  -G sample1=GGGG \
  -g sample2=CCCC \
  -G sample2=TTTT \
  --pair-adapters \
  --error-rate 0 \
  -o output/{name}.1.fastq.gz \
  -p output/{name}.2.fastq.gz \
  --untrimmed-output output/untrimmed.1.fastq.gz \
  --untrimmed-paired-output output/untrimmed.2.fastq.gz \
  forward.fastq.gz \
  reverse.fastq.gz
```

This results in two "untrimmed" files:

<details>
<summary><code>output/untrimmed.1.fastq.gz</code></summary>

```
@id1
ACGTACGT
+
zzzzzzzz
@id2
ACGTACGT
+
zzzzzzzz
@id3
ACGTACGT
+
zzzzzzzz
@id4
ACGTACGT
+
zzzzzzzz
@id5
ACGTACGT
+
zzzzzzzz
@id6
GGGGACGTACGT
+
zzzzzzzzzzzz
```
</details>

<details>
<summary><code>output/untrimmed.2.fastq.gz</code></summary>

```

@id1
TGCATGCA
+
zzzzzzzz
@id2
TGCATGCA
+
zzzzzzzz
@id3
TGCATGCA
+
zzzzzzzz
@id4
TGCATGCA
+
zzzzzzzz
@id5
TGCATGCA
+
zzzzzzzz
@id6
TTTTTGCATGCA
+
zzzzzzzzzzzz
```
</details>

There are two surprising things here:
- There are no demultiplexed files, even though the barcodes were clearly found and removed
- The trimmed reads are showing up in the untrimmed output. My guess is that it is just because they weren't demultiplexed, but I have no idea.

Did I misunderstand this part of the documentation:

![image](https://user-images.githubusercontent.com/274668/56697855-cd818d00-66a4-11e9-916f-3c7f629c6fa0.png)

If I run this command sans `--pair-adapters` the reads appear to demultiplex as expected.

Thanks for reading this far, please let me know if you need additional details from me.

**Comment by marcelm** [comment]
I confirm what you’re seeing. I believe my tests weren’t sufficient. I’ll investigate.

**Comment by marcelm** [comment]
Ok, this was a bit embarrasing because the `--pair-adapters` option was explicitly designed for demultiplexing (as the documentation states), but I only tested whether trimming (without demultiplexing) worked properly.

Thanks by the way for the really nice test! That has made it very easy to reproduce. I have taken the liberty of integrating it as a unit test into Cutadapt.

I have fixed the problem now.

**Comment by marcelm** [comment]
Cutadapt 2.3 with the fix is now on PyPI. Bioconda package coming soon.

**Comment by thermokarst** [comment]
Awesome, thanks @marcelm! Tested 2.3 out and everything works as expected. Thanks for the quick turnaround!

**Comment by marcelm** [comment]
Great to hear, glad I could help!
