### ISSUE TITLE
Feature request: Add `--output-format` flag

### ISSUE THREAD

**Issue by nylander** [marcelm/cutadapt#380]
Hi,
I was trying to get cutadapt to print fasta format to stdout, but since the output is auto-detected from the file suffix of the output file, I could not find a way. 

A possible solution is to add a new option, `--output-format`, or similar, to override the automatic (filename-based) setting?  Could potentially be very useful:
```
cutadapt  [other options]  --output-format=fasta  input.fastq  |  \
    [some downstream analyses on fasta format]
```
Cheers
Johan

**Comment by marcelm** [comment]
I’ve now added an option named `--fasta`. I started with `--output-format` at first, but then realized that this would introduce too many sources of errors, in particular I would have to check whether `--output-format=fastq` is used although the input is FASTA. When I implement more output formats, I can still add `--output-format`.

**Comment by marcelm** [comment]
The option only influences the format of the data that gets written to standard output, everything else (for which file names need to be provided anyway) is still detected based on the file name.
