### ISSUE TITLE
No report when --report=minimal

### ISSUE THREAD

**Issue by adefelicibus** [marcelm/cutadapt#381]
Hi, I'm using Cutadapt version 2.3 that I installed with conda with the command-line parameteters:
```sh
cutadapt --trim-n -m 100 -g CCTACGGGRSGCAGCAG -G GGACTACHVGGGTWTCTAAT --report=minimal -o results/tmp/cutadapt/trimmed/180503651071-1-1-1_S29_L001_R1.fastq.gz -p results/tmp/cutadapt/trimmed/180503651071-1-1-1_S29_L001_R2.fastq.gz --untrimmed-output results/tmp/cutadapt/untrimmed/180503651071-1-1-1_S29_L001_R1.fastq.gz --untrimmed-paired-output results/tmp/cutadapt/untrimmed/180503651071-1-1-1_S29_L001_R2.fastq.gz results/tmp/fastq/180503651071-1-1-1_S29_L001_R1.fastq.gz results/tmp/fastq/180503651071-1-1-1_S29_L001_R2.fastq.gz
```
I received the output like this:
```sh
[ 8<---------] 00:00:03        30,000 reads  @    145.7 µs/read;   0.41 M reads/minute
```
and no minimal report.

But, if I use the option  **--report=full**, I get the full report.

Using Cutadapt version 1.18 I get the desired minimal report:
```sh
status  in_reads        in_bp   too_short       too_long        too_many_n      out_reads       w/adapters      qualtrim_bp     out_bp  w/adapters2     qualtrim2_bp    out2_bp
OK      140663  71738130        0       0       0       131208  135612  0       37789941        135005  0       24283833
```

According to the Cutadapt documentation, nothing has changed about the report.

Best.

**Comment by marcelm** [comment]
Hi and thanks for the report. I’m traveling at the moment and will look into this after I return.

**Comment by marcelm** [comment]
Thanks for your patience. I’ve been able to reproduce the problem and was able to fix it. The next Cutadapt release will again have a working `--report=minimal` option.

**Comment by adefelicibus** [comment]
Thanks @marcelm!
