### ISSUE TITLE
Naive question

### ISSUE THREAD

**Issue by AnaSofia94** [marcelm/cutadapt#383]
I'm using cutadpat 1.18 and python 3.7.2 .
Currently, I'm using cutadapt this way:

cutadapt -b PrimerFW1-b PrimerRV1 -O 10 --trimmed-only 

But now I want to add, another primer like this:

cutadapt -b PrimerFW1-b PrimerRV1 -b PrimerFW2 -b PrimerRV2 -O 10 --trimmed-only 

Should I use the parameter -b or another one?

**Comment by marcelm** [comment]
Which option to use depends on which type of adapter you have. I recommend against the `-b` option as you may get false positive matches. I explain what the different adapter types do in [the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types).

Note that Cutadapt will by default trim only one of the given adapters from each read. So in the first example that you give, Cutadapt will trim *either* PrimerFW1 *or* PrimerRV1. If you want to remove both, you may want to use linked adapters (explained in the documentation as well). In the second example, you may want to use *two* linked adapters.
