### ISSUE TITLE
Why diffrent for adapter file?

### ISSUE THREAD

**Issue by hmyh1202** [marcelm/cutadapt#385]
The cutadapt 1.8.3 (Python-3.3.2)  produced adapter and sequence file was only contain reads info that contain adapter.
Now the  latest version cutadapt output all reads, and the reads that do not contain adapters also write out. Why ?!

**Comment by hmyh1202** [comment]
cutadapt -a ANNGCAGCAGCAGCGACAG -O 5 --info-file=read1.adapter.txt

**Comment by marcelm** [comment]
Hi, I don’t see this myself. The info file contains lines for each read, even those that do not contain an adapter (a -1 in the second column). This was already the case in 1.8.3 (I’ve just tested this to make sure).

However, the info file format has changed slightly: It now contains additional columns for the qualities (see the documentation). Perhaps this is giving you trouble?

**Comment by hmyh1202** [comment]
Usually, the lines that do not contain an adpter would not be used in the dowstream analysis, and only reads that contain adapter(s)  would be trimed or filtered.
I would write out all reads and waste some storage space, and I ofen fiter the 2st column (-1) data.

**Comment by marcelm** [comment]
The info file is designed to keep all information that may be required by downstream analysis. In your analysis, you keep the reads that contain adapters, but in other analyses, one would keep those without adapters, so the information needs to be there. It’s expected that you need to do some extra processing for your particular application.

Backwards compatibility is important to me, so I cannot change the info file format, except for adding further columns. It would of course be possible to add options for customizing the format. Let me know if you have any suggestions in that direction.

**Comment by hmyh1202** [comment]
Yes I have do extra processing for my particular application.  Can you add a parameter to meet the requirements? May be not necessary.
Thank you.
