### ISSUE TITLE
output fastq format problem 

### ISSUE THREAD

**Issue by apoosakkannu** [marcelm/cutadapt#386]
Hi, I used cutadapt interleaved option and the output is having problem when using it in racon polishing. The error is saying that is not fastq format. Could you give me  any idea what could be the reason. I used the following command, cutadapt --interleaved -q 20 -o trim.fastq r1.fastq r2.fastq

**Comment by marcelm** [comment]
Could you please clarify: Which program is giving you the error message?

**Comment by apoosakkannu** [comment]
the program is Racon: https://github.com/isovic/racon. I got the following error message. 

[racon::Polisher::initialize] loaded target sequences 4.302 s
terminate called after throwing an instance of 'std::invalid_argument'
 what():  [bioparser::FastqParser] error: invalid file format!

**Comment by marcelm** [comment]
You can use Cutadapt to check the `trim.fastq` file:
```
cutadapt --interleaved -o /dev/null trim.fastq
```
If this does not give an error message, the file should be fine, and you will need to take this to the Racon developers. (In that case, let me know whether they think Cutadapt has produced invalid output.)

**Comment by apoosakkannu** [comment]
Hi, thanks. It was the problem of having the small length sequences, so i used -m parameter to filter the small ones and it worked.

**Comment by marcelm** [comment]
Ok, great, then let’s close this. (Perhaps you want to file an issue for racon, I’d argue that empty/very short reads are totally fine.)
