### ISSUE TITLE
Problem installing cutadapt windows 

### ISSUE THREAD

**Issue by AnaSofia94** [marcelm/cutadapt#389]
Hello,
I'm having problems installing cutadapt in windows 2012, my python version is 3.5.0 and my cutadapt version to install is 1.18.
I installed cutadapt with pip: pip3 install --user --upgrade cutadapt
But I continue to have the same error in the installation: Failed building wheel for cutadapt
Thank you for the help.

**Comment by marcelm** [comment]
There may be a chance I can help if you post the full error message, but I don’t support running Cutadapt on Windows as I don’t use Windows myself.

**Comment by AnaSofia94** [comment]
The error message says: "Could not build wheels for cutadapt which use PEP 517 and cannot be installed directly". Thank you for the help.

**Comment by marcelm** [comment]
I need also everything between `pip3 install --user --upgrade cutadapt` and that error message.

**Comment by AnaSofia94** [comment]
Here is the full error: 
![cutadapt_error](https://user-images.githubusercontent.com/31896975/61799160-854c4500-ae22-11e9-8ab6-fb4d17b92db0.png)

**Comment by AnaSofia94** [comment]
Here is the full error: 
![cutadapt_error](https://user-images.githubusercontent.com/31896975/61799383-f1c74400-ae22-11e9-929d-6136863fb64d.png)

**Comment by marcelm** [comment]
Sorry, but I don’t have an idea of what the problem might be. I found another page where the problem could be solved by updating to Python 3.5.3, maybe that is something to try. Otherwise, I cannot help further, sorry.

**Comment by marcelm** [comment]
Closing now. Please let me know if you found a way to solve this and I will add it to the documentation.
