### ISSUE TITLE
Add adapter header in file to read header in output

### ISSUE THREAD

**Issue by eboyden** [marcelm/cutadapt#390]
It would be terrific if there were an option, when using FASTA files for adapter sequences, to add the FASTA header data to the output FASTQ header; this would allow tracking which adapter sequences were used to trim a particular output read.

**Comment by eboyden** [comment]
Ugh I just discovered that this is already possible with -x or -y, sorry for the spam.

**Comment by marcelm** [comment]
If you have an idea of how to make this better discoverable, let me know. (I’m on vacation, will reply to your other issue later.)
