### ISSUE TITLE
Multicore support for additional options (as per #270)?

### ISSUE THREAD

**Issue by eboyden** [marcelm/cutadapt#391]
Wondering if multicore support for the options below is still being actively worked on (particularly --untrimmed-output and --untrimmed-paired-output), as mentioned in #270 

ERROR: Running in parallel is currently not supported for the given combination of command-line parameters.
These options are not supported: --info-file, --rest-file, --wildcard-file, --untrimmed-output, --untrimmed-paired-output, --too-short-output, --too-short-paired-output, --too-long-output, --too-long-paired-output, --format
Also, demultiplexing is not supported.

**Comment by marcelm** [comment]
I can try to work on this as one of the next features. I was initially hoping to get a general solution in place so all the options would work, but will probably not have time for that. However, just adding support for `--untrimmed-output`/`--untrimmed-paired-output` should not be hard.

**Comment by marcelm** [comment]
These options are now supported (in the development version):

* `--untrimmed-output`, `--untrimmed-paired-output`
* `--too-long-output`, `--too-long-paired-output`
* `--too-short-output`, `--too-short-paired-output`
