### ISSUE TITLE
TypeError _call_() takes 3 positional arguments but 5 were given

### ISSUE THREAD

**Issue by SusanaFreitas** [marcelm/cutadapt#393]
Dear all
I am trying to run cutadapt with the command below but I keep getting the same error:
TypeErrror: __call__() takes 3 positional arguments but 5 were given.
The cutadapt and python versions are:
cutadapt version 2.4
python 3.7.2

I am using cutadapt on the university server and it was installed by the IT team (we upload it via module system).
I found this issue here:
https://github.com/marcelm/cutadapt/issues/203
so I tried to remove all possible options, but I always get the same error.
Do you think you could help??

Thanks!!!

_cutadapt -b GATCGGAAGAGCACACGTCTGAACTCCAGTCAC -b ATCTCGTATGCCGTCTTCTGCTTG -B AATGATACGGCGACCACCGAGATCTACAC -B ACACTCTTTCCCTACACGACGCTCTTCCGATCT -e 0.2 -n 3 --discard-trimmed --info-file read1.txt -q 20 -m 40 -o read1-trimmed1.fastq.gz -p read2-trimmed2.fastq.gz AH3TLYBBXX_lane4-s324-index--CACCTTAC-CTTCGCCT-84-505_S324_L004_R1_001.fastq.gz AH3TLYBBXX_lane4-s324-index--CACCTTAC-CTTCGCCT-84-505_S324_L004_R2_001.fastq.gz_

**Comment by marcelm** [comment]
Can you please post the full error message? (Not only the last line with the TypeError?)

**Comment by SusanaFreitas** [comment]
Here it is:

This is cutadapt 2.4 with Python 3.7.2
Command line parameters: -b GATCGGAAGAGCACACGTCTGAACTCCAGTCAC -b ATCTCGTATGCCGTCTTCTGCTTG -B AATGATACGGCGACCACCGAGATCTACAC -B ACACTCTTTCCCTACACGACGCTCTTCCGATCT -e 0.2 -n 3 --discard-trimmed --info-file read1.txt -q 20 -m 40 -o read1-trimmed1.fastq.gz -p read2-trimmed2.fastq.gz AH3TLYBBXX_lane4-s324-index--CACCTTAC-CTTCGCCT-84-505_S324_L004_R1_001.fastq.gz AH3TLYBBXX_lane4-s324-index--CACCTTAC-CTTCGCCT-84-505_S324_L004_R2_001.fastq.gz
Processing reads on 1 core in paired-end mode ...
Traceback (most recent call last):
  File "/mnt/software/.local/easybuild/software/lang/Python/3.7.2/bin/cutadapt", line 10, in <module>
    sys.exit(main())
  File "/mnt/software/.local/easybuild/software/lang/Python/3.7.2/lib/python3.7/site-packages/cutadapt/__main__.py", line 848, in main
    stats = runner.run()
  File "/mnt/software/.local/easybuild/software/lang/Python/3.7.2/lib/python3.7/site-packages/cutadapt/pipeline.py", line 737, in run
    (n, total1_bp, total2_bp) = self._pipeline.process_reads(progress=self._progress)
  File "/mnt/software/.local/easybuild/software/lang/Python/3.7.2/lib/python3.7/site-packages/cutadapt/pipeline.py", line 331, in process_reads
    if filter_(read1, read2, matches1, matches2):
TypeError: __call__() takes 3 positional arguments but 5 were given

**Comment by marcelm** [comment]
Thanks, I’ll look into this. It appears that using `--info-file` is the problem here.

**Comment by marcelm** [comment]
I’ve fixed the crash. The problem was that the `--info-file` option did not work when processing paired-end data. Note that in the fixed version, the info file will still only contain data about R1, and everything that happens to R2 will simply be ignored. That is, there is at the moment no `--paired-info-file` option or similar. If you are interested in that, please file a new issue!

And for completeness: The same crash would also have occurred for the options `--wildcard-file` and `--rest-file`. This has also been fixed.

If you want to test this, please [install the development version](https://cutadapt.readthedocs.io/en/stable/installation.html#installing-the-development-version) of Cutadapt.

**Comment by SusanaFreitas** [comment]
Thanks!!
I tried without the --info-file option and it worked. 

Best
Susana
