### ISSUE TITLE
how to trim NexteraPE-PE.fa and Overrepresented sequences in PE sequence

### ISSUE THREAD

**Issue by qiaowei-vvjoe** [marcelm/cutadapt#397]
Hi 
Thank you so much for the wonderful tools.
It is my first time to use cutadapt 2.4 with Python 3.6.5 and I install it by pip3.
Now I have some PE raw data and after fastqc I found they are Nextera transposase sequence and also have lots of overrepresented sequence.I searched the NexteraPE-PE.fa through trimmomatic:

$ cat NexteraPE-PE.fa
>PrefixNX/1
AGATGTGTATAAGAGACAG
>PrefixNX/2
AGATGTGTATAAGAGACAG
>Trans1
TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
>Trans1_rc
CTGTCTCTTATACACATCTGACGCTGCCGACGA
>Trans2
GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
>Trans2_rc
CTGTCTCTTATACACATCTCCGAGCCCACGAGAC

but I am not sure about how to trim the adapter and overrepresented sequence. Should it be trimmed R1&R2 together or one by one, and I am also not sure about the Anchored 3’ adapter of -a,-A,should they must be all trimmed?and my code is 
`~/configure/python3/bin/cutadapt \
-a CTGTCTCTTATACACATCTGACGCTGCCGACGA  \
-A CTGTCTCTTATACACATCTCCGAGCCCACGAGAC  \
-e 0.1 -O 5 -m 50  --pair-filter=both \
-o read_R1.fq -p read_R2.fq test1.fastq test2.fastq >& log.txt`

I am not sure if it can deal with my data.
Thanks so much in advance.

**Comment by marcelm** [comment]
Hi, it’s hard to say for me which command you need to run exactly. If you’re unsure, you could just try to trim *all* adapter sequences you know about and see which ones of those Cutadapt finds. Provide the sequences both with `-a` and `-A` (so give each sequence twice).

I don’t think you need to trim the overrepresented sequences. These could be actual sequences, which you wouldn’t want to trim, or if it’s adapters, then the adapter trimming will take care of it.

**Comment by qiaowei-vvjoe** [comment]
Hi Martin @marcelm 
I find a website like the same question:https://bioinformatics.stackovernet.com/cn/q/2743
and I am not sure why he use these sequences to cut -A CTGTCTCTTATACACA -a CTGTCTCTTATACACA -G GATGTGTATAAGAGACAG 
-g GATGTGTATAAGAGACAG...I always thought it should be cut by the whole adapter...maybe I thought I am not too much sure about how cutadapt work..Besides I just trimmed adapter not overrepresented sequences according to your advice.

**Comment by marcelm** [comment]
It is ok to search only for a 5' part of the adapter. Cutadapt will remove the adapter itself and the sequence that follows it anyway, so the result is the same as when searching for the whole sequence. Was that what you meant?
