### ISSUE TITLE
Problem running cutadapt - windows 10

### ISSUE THREAD

**Issue by Caro0026** [marcelm/cutadapt#405]
Hi @marcelm ,

I've just installed cutadapt using miniconda and the pip command line. It seemed to work. 

`(base) C:\Users\Administrator>pip install --upgrade cutadapt
Requirement already up-to-date: cutadapt in c:\programdata\miniconda3\lib\site-packages (2.5)
Requirement already satisfied, skipping upgrade: dnaio~=0.3.0 in c:\programdata\miniconda3\lib\site-packages (from cutadapt) (0.3)
Requirement already satisfied, skipping upgrade: xopen~=0.8.1 in c:\programdata\miniconda3\lib\site-packages (from cutadapt) (0.8.2)`

Now I am trying to run it I have the following error message:

```
(base) C:\Users\Administrator>cutadapt --version
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\cutadapt.exe\__main__.py", line 5, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\cutadapt\__main__.py", line 71, in <module>
    from cutadapt.report import full_report, minimal_report
  File "c:\programdata\miniconda3\lib\site-packages\cutadapt\report.py", line 10, in <module>
    from .filters import (NoFilter, PairedNoFilter, TooShortReadFilter, TooLongReadFilter,
  File "c:\programdata\miniconda3\lib\site-packages\cutadapt\filters.py", line 21, in <module>
    from .utils import raise_open_files_limit
  File "c:\programdata\miniconda3\lib\site-packages\cutadapt\utils.py", line 4, in <module>
    import resource
ModuleNotFoundError: No module named `'resource'
```
I first tryed to install the 'resource' module and tryed again. Same error message.
I've google it and but without success. Seems like a Windows compatibility problem. 

Has anyone been subjected to a similar issue? I am not familiar with Python, I might be missing something obvious. I have been through different websites but have'n seen similar problems concerning cutadapt. Hope someone can help with this. Thanks in advance for that.

- Cutadapt V 2.5 and Python V 3.7.3 - Installed via pip - Windows 10 / 64-bit

cheers,

Caroline

**Comment by marcelm** [comment]
Hi, issue #404 (filed just a couple minutes earlier than yours) mentions the exact same error message. I’ll reply over there and close this issue.

**Comment by Caro0026** [comment]
Ok, thanks for that.

Caroline

Le mer. 25 sept. 2019 à 16:01, Marcel Martin <notifications@github.com> a
écrit :
