### ISSUE TITLE
Error on empty input files

### ISSUE THREAD

**Issue by f-heeger** [marcelm/cutadapt#407]
I am running cutadapt (version 2.3 installed from bioconda) automatically on big number of fasta files. Some of these files are empty, because this is one step in a series of filtering steps. For this files I get the following error:
> dnaio.exceptions.UnknownFileFormat: Input file format unknown

For me it would be better if it would instead just produce an empty output file.

I understand that providing an empty input file and expecting an empty output file might be a bit of an edge case and it would possibly remove a sanity check for other use cases, but it would make using cutadapt in an automated pipeline much easier (at least for me). Maybe this behaviour could be optional or cause a warning?

I don't think it is relevant, but my command line is:
>  cutadapt -g AACACTCGCAYAYATGYTAGA...GGCACCAGACTTGCCCTCCAA --discard-untrimmed --cores 6 --error-rate 0.300000 -o out.fasta in.fasta > logfile.txt

**Comment by marcelm** [comment]
Oh, this is supposed to work and even covered by the automated integration tests. It appears that the problem occurs only when multiple cores are used. I’ll need to fix this.

**Comment by f-heeger** [comment]
Ok, that gives me at least a work around (using one core) for now. Thanks for the quick answer and the awesome tool.
