### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by outpaddling** [marcelm/cutadapt#409]
Cutadapt 2.5 appears to work fine with xopen 0.8.2 and dnaio 0.4.

Should setup.py be relaxed to allow newer versions, or are the known issues with xopen > 0.8.1 and dnaio > 0.3?

Suggested patch:

```
-    install_requires=['dnaio~=0.3.0', 'xopen~=0.8.1'],
+    install_requires=['dnaio>=0.3.0', 'xopen>=0.8.1'],

```

**Comment by marcelm** [comment]
The `xopen~=0.8.1` specifier already includes xopen version 0.8.2 (the tilde means it’s a [compatible release specifier](https://packaging.python.org/guides/distributing-packages-using-setuptools/#semantic-versioning-preferred)).

For dnaio, it is correct that the `dnaio~=0.3.0` incorrectly excludes dnaio 0.4. I’ve fixed this in the development version of Cutadapt. The actual mistake was to increase the dnaio version from 0.3 to 0.4 while I should have gone to 0.3.1 instead.

I hope to release Cutadapt 2.6 this week, which should take care of this. Thanks for pointing this out!

**Comment by outpaddling** [comment]
Awesome, thanks!
