### ISSUE TITLE
Dependencies list is not accurate

### ISSUE THREAD

**Issue by jrdemasi** [marcelm/cutadapt#413]
I am installing cutadapt from source, and it works fine until it's time to run it.  Every time I keep getting a different missing module -- first xopen, then others.  Could you make the dependencies list accurately list all dependencies?  From readthedocs: 

Dependencies

Cutadapt installation requires this software to be installed:

Python 3.4 or newer
Possibly a C compiler. For Linux, Cutadapt packages are provided as so-called “wheels” (.whl files) which come pre-compiled.

**Comment by marcelm** [comment]
How did you install exactly? How do you attempt to run it? The installation instructions say to use `pip3 install ...`, which will automatically download and install the required Python packages. You should never need to do this explicitly. To install from unpacked sources, you need to run some variant of `pip3 install .` within the unpacked distribution.

The instructions are meant for users and "Dependencies" therefore should be interpreted to mean "whatever needs to have been installed through some other means before `pip install` can be run". The authoritative list of dependencies is in `setup.py`.
