### ISSUE TITLE
Using naming with linked adapters

### ISSUE THREAD

**Issue by vaofford** [marcelm/cutadapt#414]
cutadapt version 2.5 installed with pip (python 3.6.8)

Hullo, 

I'm try to use naming with linked adapters, but can't seem to get the syntax quite right.

For example:

`cutadapt -e 0.5 --pair-adapters -g MyAdapterR1=^TGACCACAAAGTGTCCTGCACTCTGATGATTTT...TTCTCCTTTAATCCTGGC -o R1.trim.fq.gz -G MyAdapterR2=^GCCAGGATTAAAGGAGAA...TGCAGGACACTTTGTGGTCA -p R2.trim.fq.gz R1.fq.gz R2.fq.gz`

Gives me:

=== First read: **Adapter 1** ===
Sequence: TGACCACAAAGTGTCCTGCACTCTGATGATTTT...TTCTCCTTTAATCCTGGC; Type: linked; Length: 33+18; 5' trimmed: 501447 times; 3' trimmed: 501447 times

But, I'm trying to get:

=== First read: **MyAdapterR1** ===
Sequence: TGACCACAAAGTGTCCTGCACTCTGATGATTTT...TTCTCCTTTAATCCTGGC; Type: linked; Length: 33+18; 5' trimmed: 501447 times; 3' trimmed: 501447 times

Does that make sense? Is this possible?

Many thanks in advance!

Victoria

**Comment by marcelm** [comment]
Hi and thanks for reporting! It appears you found a bug. i’ll fix this now.

**Comment by marcelm** [comment]
It’s now fixed, but you’ll either have to install the development version of Cutadapt or wait until the next release to get the repaired version. Thanks again for finding this.
