### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tseemann** [marcelm/cutadapt#415]
43 commits since 2.5
https://github.com/marcelm/cutadapt/compare/v2.5...master

(i am a homebrew and conda packager)

**Comment by marcelm** [comment]
Yes, I know, it’s time ... My initial aim was to finish `--revcomp` (#220) for the new release, but that might as well wait.

**Comment by marcelm** [comment]
I’ve tagged version 2.6 just now. The release should be on PyPI soon. Before the Bioconda package can be updated, conda-forge/xopen-feedstock#4 needs to be merged, but I don’t know what the problem with that one is.

**Comment by tseemann** [comment]
Thanks @marcelm  - i didn't mean to pressure you, just I know I often forget to make releases on my own projects and end up supporting bugs I have already fixed.   Conda and Brew work off releases only (or tags) so `master` is never an option.  Appreciate it, and i'll try and get help with the `open-feedstock` issue.

**Comment by marcelm** [comment]
No worries, I didn’t feel pressured. I just need to remember that making a release is very easy so there’s no reason to hold back.

**Comment by tseemann** [comment]
Yeah, took me a while to get into that mindset too!
I actually just tag versions in between, so that package managers still have .tar.gz to use, but I don't need to go to github. Just `git tag v2.3.1 && git push --tags`.

**Comment by marcelm** [comment]
The above line is all I need to do to make a release that gets pushed to PyPI :-)
