### ISSUE TITLE
pigz Multiple Cores Option Used

### ISSUE THREAD

**Issue by DarioS** [marcelm/cutadapt#416]
Even though I am doing cutadapt on a single thread, I notice in the output of top that 4 threads have been specified to pigz (although it's using less than one for each process).

> Processing reads on 1 core in paired-end mode ...

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
13261 dario     35  15  318140   3920   1520 S  47.2  0.0   0:47.19 pigz -p 4                                                                                                                           
13256 dario     35  15  318140   3896   1496 S  46.8  0.0   0:46.00 pigz -p 4                                                                                                                           
```

Should pigz be set to use the same number of total threads as the cutadapt process?

**Comment by marcelm** [comment]
Hi, this has been reported before in #290. I’m currently working on this, and I hope to fix at least the single-core case for the next release.
