### ISSUE TITLE
minimum length post trimming (improvement)

### ISSUE THREAD

**Issue by svsuresh** [marcelm/cutadapt#418]
Please refer to https://www.biostars.org/p/405509/.  Trimming by cutadapt some times results in empty reads i.e reads with header (and the third line) only. This causes the issue for some tools. Proposed solutions are:

1. make -m (minimum length) mandatory so that no zero length reads remain post trimming
2. Cutadapt by default implements -m >0 during trimming.

Though user can set -m as 1 while trimming (which is optional as of current release), some users may not know such a file can be produced post trimming (i.e fastq file with zero length reads).

**Comment by marcelm** [comment]
This has been reported before in #392. Please see my comment on that issue for my reasons for keeping it the way it is at the moment. (Short answer: I think the other tools should be fixed.)

However, I realize this is a problem that comes up regularly. I think what I can do is to print a warning when reads were trimmed to a length of zero, something like:
```
WARNING: 42 reads were empty (length 0) after trimming.
Some tools may have problems processing the created file.
Use option -m 1 to remove zero-length reads.
```

**Comment by svsuresh** [comment]
Yes, thank you and sorry for the delayed reply.

**Comment by marcelm** [comment]
Ok, I have filed #428 for this.
