### ISSUE TITLE
cutadapt: error: Placement restrictions (with X, ^, $)

### ISSUE THREAD

**Issue by Carly-31** [marcelm/cutadapt#422]
cutadapt version 2.6  Python version 3.7+

Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: Placement restrictions (with X, ^, $) not supported for 'anywhere' (-b) adapters
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: Placement restrictions (with X, ^, $) not supported for 'anywhere' (-b) adapters
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: Placement restrictions (with X, ^, $) not supported for 'anywhere' (-b) adapters
rm: cannot remove 'stp0_Processed.fa': No such file or directory
rm: cannot remove 'stp1_Processed.fa': No such file or directory
   --- Stop oligo trimming for M1F-1_raw completed

**Comment by marcelm** [comment]
Hi, can you be more specific? What are you trying to do?

**Comment by Carly-31** [comment]
Hello sorry I am trying to use sRNAnalyzer which uses the cutadapt to remove adapters
when I run the code I get an error.

**Comment by marcelm** [comment]
Cutadapt allows to restrict where an adapter is allowed to occur in a read. To do so, you add a `^` to the beginning of the specified adapter sequence, a `$` to the end of it, or an `X` to either end (the Cutadapt documentation has more details). These are the “placement restrictions” mentioned in the error message.

Cutadapt supports 5' adapters, 3' adapters and a third "anywhere" adapter type. The placement restrictions can only be used with the 5' adapters and 3' adapters, not with the "anywhere" type.

If you have control over the adapter sequences, check whether they contain `X`, `$` or `^`. If you have control over the adapter type, use the 5' or 3' adapter type as appropriate. If you do not have control over either, you will need to contact the authors of sRNAnalyzer as they seem to call Cutadapt in an incorrect way in their pipeline.

**Comment by Carly-31** [comment]
Thank you so much

**Comment by marcelm** [comment]
Great, I’ll close this issue then for now, but if there is anything else, just comment below and I’ll re-open if necessary.
