### ISSUE TITLE
-M --maximum-length info in documentation 

### ISSUE THREAD

**Issue by AstrobioMike** [marcelm/cutadapt#424]
Hi there, thanks for the great tool :) 

The docs read for `-M`:

--maximum-length LENGTH or -M LENGTH
Discard processed reads that are longer than LENGTH. **Reads that are too long even before adapter removal are also discarded.**

I _think_ maybe this was just an accidental copy/alteration of the `-m` min-length (where that seems intuitive), but that doesn't seem to be the case for the max setting as reads too long before but under `-M` after trimming are retained (as i think would be desired). At least as late as version 2.3, toy example below. 

Thanks again!

First sequence is 16 bps before trimming, 11 after ; Second sequence is 15 before trimming, 10 after:
![image](https://user-images.githubusercontent.com/13923308/69000152-26528600-0880-11ea-8a5c-fe87be6acc3c.png)

 
No max set, both through just fine of course:
![image](https://user-images.githubusercontent.com/13923308/69000154-2e122a80-0880-11ea-91fb-8436a1e71f8c.png)

Max = 10 set, even though they are both too long before trimming, one is 10 after trimming, and that one makes it through:
![image](https://user-images.githubusercontent.com/13923308/69000156-34a0a200-0880-11ea-804a-f5f0cee01845.png)

**Comment by marcelm** [comment]
Ah, yes, the behavior is as intended, but the documentation doesn’t make much sense. I wanted to emphasize that the filter is applied even to those reads in which no adapter was found.

**Comment by marcelm** [comment]
I’ve rewritten the section a bit by removing the misleading sentence and adding: "Filters are applied to all processed reads, no matter whether they have been modified by adapter- or quality trimming." above the bulleted list. Feel free to double-check if you have time: https://cutadapt.readthedocs.io/en/latest/guide.html#filtering-reads

**Comment by marcelm** [comment]
And thanks for the report!

**Comment by AstrobioMike** [comment]
Looks good to me! Well except for a tiny typo of "are" instead of "or", if you care about that :)

![image](https://user-images.githubusercontent.com/13923308/69000720-ee9c0c00-0888-11ea-9cca-ccf04470bd82.png)

And thanks again!

**Comment by marcelm** [comment]
That’s now also fixed, thanks!
