### ISSUE TITLE
Consider changing the default gzip compression level

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#425]
This has been mentioned in #412: Reducing the default compression level would improve overall speed since compression is often the bottleneck.

The current default compression level is 6. I may be convinced to change this to 5, which would reduce the CPU time spent on compression by roughly 50% while increasing output size by only a couple of percent.

**Comment by rhpvorderman** [comment]
Cutadapt only produces intermediary files. These files are mapped and the resulting BAM file may be stored. The original fastq files may be stored as well. But Cutadapt's files are only stored during the run of the pipeline in my experience.

So my opinion is towards the more speed vs the more compression part.

I did a few benchmarks some time ago that can be interesting. One-threaded pigz was used because it is more efficient than gzip and also more efficient than multi-threaded pigz.

```
for i in {1..9}; do echo $i; time pigz -p 1 -$i -c very_big.fastq > very_big.fastq.$i.gz ; du -h very_big.fastq.$i.gz ; done
1

real  1m30.303s
user  1m27.889s
sys 0m1.704s
2.3G  very_big.fastq.1.gz
2

real  1m38.963s
user  1m36.366s
sys 0m1.884s
2.2G  very_big.fastq.2.gz
3

real  2m22.744s
user  2m20.532s
sys 0m1.872s
2.1G  very_big.fastq.3.gz
4

real  2m8.273s
user  2m5.176s
sys 0m1.900s
2.1G  very_big.fastq.4.gz
5

real  3m42.058s
user  3m39.126s
sys 0m2.164s
2.0G  very_big.fastq.5.gz
6

real  8m10.556s
user  8m6.955s
sys 0m2.532s
2.0G  very_big.fastq.6.gz
7

real  13m46.618s
user  13m43.446s
sys 0m2.912s
1.9G  very_big.fastq.7.gz
8

real  24m20.805s
user  24m17.013s
sys 0m3.456s
1.9G  very_big.fastq.8.gz
9

real  31m7.365s
user  31m3.577s
sys 0m3.544s
1.9G  very_big.fastq.9.gz
```

Given the small differences in file sizes I think the optimum is somewhere at level 1 or 2. But level 5 is indeed already a huge improvement over level 6 in terms of compute time.

**Comment by marcelm** [comment]
Interesting that you also measure level 3 as being slower than level 4. I noticed that anomaly also in my tests.

**Comment by rhpvorderman** [comment]
Compression levels 1,2 and 3 use a different algorithm I believe. So that's why there might be a difference between 3 and 4. Different tradeoffs. (Unfortunately I cannot find the source for this different algorithm stuff).

**Comment by marcelm** [comment]
Maybe the solution is to switch to a different implementation of the compression algorithm.

I found [zlib-ng](https://github.com/zlib-ng/zlib-ng) and it appears to be about twice as fast as regular gzip.

And a little bit later I found [libdeflate](https://github.com/ebiggers/libdeflate), which in my tests is even three times as fast as regular gzip.

**Comment by rhpvorderman** [comment]
I did some benchmarking. big2.fastq.gz is a WGS readlength=150 fastq file. It is 1,6G uncompressed and 657M here compressed with `gzip -1`.  These are the performances for the different levels

### Default
```
$ hyperfine -w 2 -r 5 "cutadapt --cores 4 -a AGATCGGAAGAG -m 20 -o ramdisk/cut.fq.gz big2.fastq.gz" && du -h ramdisk/cut.fq.gz 
Benchmark #1: cutadapt --cores 4 -a AGATCGGAAGAG -m 20 -o ramdisk/cut.fq.gz big2.fastq.gz
  Time (mean ± σ):     53.309 s ±  0.282 s    [User: 263.654 s, System: 3.526 s]
  Range (min … max):   52.991 s … 53.747 s    5 runs
581M	ramdisk/cut.fq.gz
```

### Compression level 5
```
$ hyperfine -w 2 -r 5 "cutadapt --cores 4 -a AGATCGGAAGAG -m 20 --compression-level 5 -o ramdisk/cut.fq.gz big2.fastq.gz" && du -h ramdisk/cut.fq.gz 
Benchmark #1: cutadapt --cores 4 -a AGATCGGAAGAG -m 20 --compression-level 5 -o ramdisk/cut.fq.gz big2.fastq.gz
  Time (mean ± σ):     24.230 s ±  0.055 s    [User: 152.256 s, System: 3.588 s]
  Range (min … max):   24.162 s … 24.300 s    5 runs
598M	ramdisk/cut.fq.gz
```

### Compression level 1
```
$ hyperfine -w 2 -r 5 "cutadapt --cores 4 -a AGATCGGAAGAG -m 20 --compression-level 1 -o ramdisk/cut.fq.gz big2.fastq.gz" && du -h ramdisk/cut.fq.gz 
Benchmark #1: cutadapt --cores 4 -a AGATCGGAAGAG -m 20 --compression-level 1 -o ramdisk/cut.fq.gz big2.fastq.gz
  Time (mean ± σ):     12.664 s ±  0.057 s    [User: 89.837 s, System: 3.633 s]
  Range (min … max):   12.579 s … 12.732 s    5 runs
657M	ramdisk/cut.fq.gz
```
Now the total times are somewhat misleading. The core utilization is not the same across benchmarks.

- level 6 (default): 396% pigz (compression) 12% pigz (decompression) 12% for each of the 4 cutadapt threads.
- level 5: 396% pigz (compression), 36% pigz decompression, 36% for each of the 4 cutadapt threads.
- level 1: 264% pigz (compression), 72% pigz decompression, 84% for each of the 4 cutadapt threads.

Also take in account the user time. That is the actual compute time needed. In our setup we would run cutadapt with `--cores 4` on a system that is restricted to 4 cores (by SLURM). So the actual runtimes would be

- level 6 (default): 264 / 4 = 66 seconds
- level 5: 152 / 4 = 38 seconds
- level 1: 90 / 4 = 23 seconds

In my personal opinion the enormous speedups of level 1 are worth the extra filesize. But the `-z` flag is available for me and so is `--compression-level` flag as well. So I don't mind a different default. 

One extra reason to go for a lower compression level is that everything under 3 is supported by igzip. I just run the benchmark with the igzip enabled xopen PR and the isa-l package from conda-forge. (This still uses pigz for decompression).

```
$ hyperfine -w 2 -r 5 "cutadapt --cores 4 -a AGATCGGAAGAG -m 20 --compression-level 1 -o ramdisk/cut.fq.gz big2.fastq.gz" && du -h ramdisk/cut.fq.gz 
Benchmark #1: cutadapt --cores 4 -a AGATCGGAAGAG -m 20 --compression-level 1 -o ramdisk/cut.fq.gz big2.fastq.gz
  Time (mean ± σ):     11.865 s ±  0.146 s    [User: 59.307 s, System: 3.280 s]
  Range (min … max):   11.660 s … 12.038 s    5 runs
 
619M	ramdisk/cut.fq.gz
```
Note that the fastq file is much smaller than default compression level 1 from pigz. Also note that the user time is only 60 seconds! Meaning this will finish in just 15 seconds on a 4 core system. 33% faster than with pigz.

When the newest xopen is released on conda-forge with the igzip changes and a dependency on the isa-l package from conda forge I think level 1 is a great default. Filesize is 6,5% bigger for a massive 77% reduction in compute time.

**Comment by kim-fehl** [comment]
By the way, there is a typo in the documentation (capital Z instead of lowercase z). And in such cases, cutadapt says that it does not understand input file names, so that was hard to reveal the real reason while using this wrong parameter name.

> The default compression level for gzip output is 6. Use option `-Z `to change this to level 1. The files need more space, but it is faster and therefore a good choice for short-lived intermediate files.

https://cutadapt.readthedocs.io/en/stable/guide.html#standard-input-and-output

**Comment by marcelm** [comment]
@kim-fehl The documentation is correct: The name of the option is `-Z` with an uppercase `-Z`. Can you open a new bug report with the exact command line that you were using and the error message that you got?

**Comment by kim-fehl** [comment]
> The name of the option is `-Z` with an uppercase `-Z`. 

You are right. I just used `-Z 1` while the correct options are either `--compression-level 1` or `-Z`.  Sorry for bothering!
