### ISSUE TITLE
multicore support for --info-file option

### ISSUE THREAD

**Issue by SDmetagenomics** [marcelm/cutadapt#427]
is there still muticore support planned for the --info-file option, as I saw some further options were given support in issue #391 . Currently using cutadapt to trim adapters from paired end reads, and want to parse the different types of adapters present in large paried end fastq files, which takes a long time with one core using the --info-file option. Also, totally fine it just provides info about forward read (R1) only, but would be great if It could use more cores for speedup.

- Cutadapt v2.5 on Python 3.6.5

**Comment by marcelm** [comment]
This is planned, but until now, no one has asked for it so I haven’t prioritized it. Since you do ask now, I can look into this for one of the next versions.

**Comment by SDmetagenomics** [comment]
That would be awesome if it could be implemented. I love this program, its very powerful and your documentation is excellent! 

-Spencer 

-----
Spencer Diamond, PhD
Twitter: @Dr__Diamond <https://twitter.com/Dr__Diamond>
Postdoctoral Scholar, Banfield Laboratory
Department of Earth and Planetary Science
University of California Berkeley

This message is intended for only the addressee(s) and may contain privileged or confidential information. Any distribution, unauthorized use, or copying is prohibited. If you have received this message in error, please notify the sender and delete the email.

**Comment by marcelm** [comment]
This is now implemented. I think I’ll make a new release now, so Cutadapt 2.7 should support this. If you have time, can you please test creating an info file with and without multicore and check whether the two output files are identical? I have some automated tests, but I don’t know whether they cover all the corner cases.

**Comment by SDmetagenomics** [comment]
Amazing Thank you so much…it is working perfectly!

-----
Spencer Diamond, PhD
Twitter: @Dr__Diamond <https://twitter.com/Dr__Diamond>
Postdoctoral Scholar, Banfield Laboratory
Department of Earth and Planetary Science
University of California Berkeley

This message is intended for only the addressee(s) and may contain privileged or confidential information. Any distribution, unauthorized use, or copying is prohibited. If you have received this message in error, please notify the sender and delete the email.

**Comment by marcelm** [comment]
Great, thanks for the feedback! :-)
