### ISSUE TITLE
How to install cutadapt using source code

### ISSUE THREAD

**Issue by NextGenBioinformatics** [marcelm/cutadapt#429]
Hello,

I am wondering if there is a way to install cutadapt using the compressed source code file from here:
https://github.com/marcelm/cutadapt/releases

I know there is a way using pip but I don't want to generate an executable file in the folder: $HOME/.local/bin

Many thanks,

**Comment by Citteny** [comment]
Hi, hope its ok i'm commenting,
to install cutadapt from the source code follow the instructions in the documatation:
https://cutadapt.readthedocs.io/en/stable/develop.html#development-installation

**Comment by marcelm** [comment]
@Citteny is correct. Also, for a source code release, please use the appropriate `.tar.gz` file that is available on https://pypi.org/project/cutadapt/#files . The files on the GitHub "releases" page are automatically generated and untested.
