### ISSUE TITLE
Issues intalling cutadapat in server windows

### ISSUE THREAD

**Issue by AnaSofia94** [marcelm/cutadapt#434]
Good morning, 
I'm trying to install cutadapat in a server on windows, with this command:

pip3 install --user --upgrade --cutadapt

which gives me this error: could not find a version that satisfies the requirement cutadapat. No matching distribution found for cutadapat. 

So, then I try to install this way: 
pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org --user --upgrade cutadapat 

But then I get this error:

![image](https://user-images.githubusercontent.com/31896975/72334477-430b0e80-36b5-11ea-8ee5-60a58ec57e8e.png)

I'm using cutadapat-1.18 and python version 3.5.
Thanks

**Comment by marcelm** [comment]
Hi, did you just misspell "cutadapt"? You wrote "cutadapat", but the last "a" shouldn’t be there.

**Comment by AnaSofia94** [comment]
Hi, sorry I misspelled here, but wrote it right in command line.

**Comment by marcelm** [comment]
Ok, it is a good idea to use copy & paste to avoid this time of problem.

You reported #389 previously. What has changed since then?

Note that, as I said in that issue, I cannot help a lot with running Cutadapt on Windows since I do not use Windows myself. I will try to help a little bit, though.

**Comment by AnaSofia94** [comment]
Nothing changed, cause I didn't used this server to run cutadapat. But now I need to use it.

**Comment by marcelm** [comment]
I got access to a Windows 10 virtual machine and tried it. I got Cutadapt working doing this:

- Download Python 3.8.1 (for Windows) from https://python.org/ and install it. During installation, I made sure that the "Add Python 3.8 to PATH" box was selected (don’t know if that is necessary).
- Download and install "Build Tools for Visual Studio 2019" from https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019 . During installation, when the dialog about which components to install pops up, ensure that "C++ Build tools" is ticked.
- Open the command line (`cmd.exe`)
- Run `python -m pip install cutadapt`
- That’s already it:
```
C:\Users\MM>cutadapt --version
2.8

C:\Users\MM>
```

**Comment by AnaSofia94** [comment]
I did has you said and I have this error:Building wheel for cutadapt (PEP 517): finished with status 'error'
Do you have any other issues related to this problem?

**Comment by marcelm** [comment]
That error message is not helpful without context. Please post the full error message, if you can preferably by copy & paste, not a screenshot. You can search for issues in this repository using the search bar on the top of this page.

**Comment by AnaSofia94** [comment]
this is the entire error message:
python :   ERROR: Command errored out with exit status 1:
At line:1 char:1
+ python -m pip install cutadapt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  ERROR: Comman... exit status 1::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   command: 'C:\Program Files\Python 3.5\python.exe' 'C:\Program Files\Python 3.5\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 
'C:\Users\ANA~1.MOR\AppData\Local\Temp\tmpivbh6zvr'
       cwd: C:\Users\ANA~1.MOR\AppData\Local\Temp\pip-install-jwrumi3q\cutadapt
  Complete output (21 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\adapters.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\align.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\filters.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\log.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\modifiers.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\parser.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\pipeline.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\report.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\utils.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\_version.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\__init__.py -> build\lib.win-amd64-3.5\cutadapt
  copying src\cutadapt\__main__.py -> build\lib.win-amd64-3.5\cutadapt
  running build_ext
  building 'cutadapt._align' extension
  error: [WinError 2] The system cannot find the file specified
  ----------------------------------------
  ERROR: Failed building wheel for cutadapt

**Comment by marcelm** [comment]
I don’t know what that error message means, sorry.

Please try this command, it will try to use Python 3.8 instead of 3.5:
```
py -3.8 -m pip install cutadapt
```

**Comment by AnaSofia94** [comment]
I have python versio 3.5, could that be the problem?

**Comment by marcelm** [comment]
Hm, when you said "I did as you said", I thought you now had Python 3.8. I now tried Python 3.5 and got also an error (but not the same), so if you can, try it with Python 3.8. It should also work with Python 3.5, but I don’t know at the moment what the problem is with that version.

**Comment by AnaSofia94** [comment]
Hi marcelm, I managed to install cutadapt in windows server, by changing the python version from 3.5 to 3.8. 
Thanks for the support.

**Comment by marcelm** [comment]
Oh, great! Thanks for letting me know.
