### ISSUE TITLE
`conda install -c bioconda cutadapt` does not work

### ISSUE THREAD

**Issue by ckywong** [marcelm/cutadapt#435]
I installed Miniconda3-latest-Linux-x86_64.sh (dated Oct 25 14:35) on CentOS 7, which gave me python 3.7.4 and conda 4.7.12.  When I did
> conda install -c bioconda cutadapt

it wanted to install cutadapt 1.18.  If I did
> conda install -c bioconda cutadapt=2.8'

it showed unresolvable dependencies:
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: | 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                                    
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> 
> 
> Package libgcc-ng conflicts for:
> cutadapt=2.8 -> libgcc-ng[version='>=7.3.0']
> python=3.7 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
> Package libstdcxx-ng conflicts for:
> python=3.7 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
> Package zlib conflicts for:
> python=3.7 -> zlib[version='>=1.2.11,<1.3.0a0']
> Package sqlite conflicts for:
> python=3.7 -> sqlite[version='>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0|>=3.30.1,<4.0a0']
> Package openssl conflicts for:
> python=3.7 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
> Package xopen conflicts for:
> cutadapt=2.8 -> xopen[version='>=0.8.4']
> Package dnaio conflicts for:
> cutadapt=2.8 -> dnaio[version='>=0.4.1']
> Package pip conflicts for:
> python=3.7 -> pip
> Package xz conflicts for:
> python=3.7 -> xz[version='>=5.2.4,<6.0a0']
> Package tk conflicts for:
> python=3.7 -> tk[version='>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
> Package pigz conflicts for:
> cutadapt=2.8 -> pigz
> Package libffi conflicts for:
> python=3.7 -> libffi[version='>=3.2.1,<4.0a0']
> Package ld_impl_linux-64 conflicts for:
> python=3.7 -> ld_impl_linux-64
> Package ncurses conflicts for:
> python=3.7 -> ncurses[version='>=6.1,<7.0a0']
> Package readline conflicts for:
> python=3.7 -> readline[version='>=7.0,<8.0a0']

`python -m pip install cutadapt` works fine though.  Could someone please take a look at it or tell me what I missed?  Thanks a lot!

**Comment by marcelm** [comment]
Hi, it appears that there’s a conflict between the cutadapt package and the packages that you already have installed (I cannot say which one is the problem). I recommend that you create a fresh new environment like this:
```
conda create -n cutadapt cutadapt=2.8
```
This will create an environment named `cutadapt`. You’ll have to activate that environment with `conda activate cutadapt` and can the run `cutadapt`.

Generally, it’s a good idea to not install too much software into the Conda base environment, but to use Conda’s ability of having different environments. For each project or purpose, create a new environment with just the tools that you need. This way, when an environment gets messed up, just delete it (`conda env remove -n the-environment-name`) and create a new one.

I will update the Cutadapt installation instructions with the above advice.
