### ISSUE TITLE
Flexible read name modifications

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#437]
A new command-line option would be useful that allows to provide a template for changing the read name.

The idea is to have a more general version of the `-x` and `-y` options, which can currently only add prefixes or suffixes to read names and only work well for single-end reads.

I’m using the following terms: The FASTQ header line consists of a *read id* and is optionally followed by a *separator* (whitespace) and a *read comment*. The two constituent reads of a paired-end read are *R1* and *R2*.

In paired-end FASTQ files, the read ids of R1 and R2 need to be identical. Cutadapt enforces this when reading paired-end FASTQ files, except that it allows a single trailing "1" or "2" as only difference between the read ids. This allows for read ids ending in `/1` and `/2` (some old formats are like this) or `.1` and `.2` (`fastq-dump` produces this).

# Some requirements

* If read names are modified by Cutadapt, the read ids should still match. (That is, Cutadapt itself would not complain when reading its own output.)
* It should be possible to move information from R1 to R2. That is, when removing a UMI from R1, it should be possible to have it in both headers.

# Suggested template variables

## Single-end

* `{id}` -- The part of the header before the whitespace separator
* `{comment}` -- The part of the header after the whitespace separator
* `{length}` -- Read length
* `{removed_prefix}` or `{cut}` -- The bases removed with `--cut`
* `{name}` -- This is already supported by the `-x`/`-y` options and is the name of the last matching adapter, or the string `no_adapter` if there was no match. Even though it should probably have been called `{adapter_name}`, this should continue to work for compatibility.

The following variables would have lower priority in my opinion and would not be implemented at first.

* `{sep}`-- The separator between id and comment (using a space should be fine, tabs are rare anyway)
* `{header}` -- The full original header (`{id} {comment}` should work just as well most of the time)
* `{match}` -- Complete information about the match. This would be all the information present in the `Match` object that is available internally anyway. The information includes: Start and end position within the adapter, start and end position within the sequence, number of matches, number of errors, name of the matched adapter.
* `{matched_sequence}` -- If there was an adapter match, this would be the matched part of the sequence. Alternatively, this could be spelled as `{match.sequence}`
* `{matched_adapter}` -- Matched part of the adapter. Could be spelled as `{match.adapter_sequence}`.

## Paired-end

For paired-end reads, it may be useful to allow specifying two different templates, one for R1 and one for R2, but that may not be necessary initially. The following assumes we have one option only.

The same templates as for single-end reads would be allowed, and they would be interpreted relative to the read whose name is being set. That is, if `{length}` is used, this would be replaced with the length of R1 in the header of R1 and with the length of R2 in the header of R2.

Additionally, we want to allow transferring information from R1 or R2 into both headers. For this, there would be read-specific versions of the template variables, such as `{length_r1}` and `{length_r2}`, which would always contain the length of R1 and R2, respectively.

So there would be `{cut_r1}`, `{cut_r2}`, `{comment_r1}`, `{comment_r2}`, `{match_r1}`, `{match_r2}`, etc. Also:

* `{rn}` -- The read number (1 for R1 and 2 for R2).

*Edited on 2020-04-22 to take comments into account.*

**Comment by and3k** [comment]
Hi!

it would also be convenient to have support for `{sequence}`. Using the example from the tutorial:

```
cutadapt -a adapter1=ACGT -y ' we found {sequence}' input.fastq
```

would result in `read1 we found ACGT`.

Where `{sequence}` is the actually matched sequenced (including any mismatches). It may be even useful to have two options, one where the actual sequence is put there (with the mismatches, i.e., `{sequence}`), and one where the sequence of the adapter is put there (e.g., `{adapter}`).

It could be even further extended by options for putting the whole trimmed sequences there, trimming positions, etc? Maybe also a shortcut option which gives the complete report with all trimming details as a suffix (in a standardize format), so it’s 100% clear how every single read was trimmed.

Thanks!

Best,
Bela

**Comment by eboyden** [comment]
I also suggest adding the ability to identically modify the read name for both reads in a pair (e.g. with the adapter name) even when you trim/modify/annotate only one of the reads in the pair, to keep the read names consistent and avoid breaking downstream tools.  Right now it seems like the most obvious way to do this would be to use --pair-adapters and use a set of read 2 adapters with the same names as the read 1 adapters, but use wildcard-only read 2 adapter sequences...except N-only adapters don't seem to be supported.

**Comment by marcelm** [comment]
@andk Good suggestions! I think something like `{matched_sequence}` is doable. I’ll probably need to defer the other suggestions to a later iteration, though. (Need to get *something* implemented first.)

@eboyden
> I also suggest adding the ability to identically modify the read name for both reads in a pair (e.g. with the adapter name)

This would be a requirement, yes. Cutadapt already now is quite strict when parsing paired-end FASTQ files in that the read ids need to be identical in R1 and R2, and it tries to maintain that invariant when modifying read names. (If it doesn’t, I’d consider it a bug.)

So a new option, if implemented, would need to ensure that the read ids are identical even after the modification. Note that this probably only applies to the *ids* (that is, the part before the first whitespace). The "comment" part after the first whitespace can be different between R1 and R2.

**Comment by andk** [comment]
Hello, previous comment has a typo in the mention of @and3k.
- s/andk/and3k/
Greetings,

**Comment by marcelm** [comment]
Sorry! Thanks for the correction.

**Comment by eboyden** [comment]
The suggestion to modify the comment instead of the read id was a good one, but existing comments that aren't easily stripped (e.g. from bcl2fastq [rn:N:0:barcodes]) complicate this strategy, at least until the changes proposed here are implemented.  One additional variable worth adding might be {rn} or somesuch to indicate the read number.  It would be nice to have the ability to remove a bcl2fastq comment from paired read data but move the read number to the end of the read id e.g. /1 or /2.  Alternatively allowing independent modification of read name 1 and read name 2 (e.g. with -X/-Y) would facilitate this (though obviously this could be risky).

BTW thanks for developing (and maintaining) this software, it is incredibly useful for amplicon-based NGS trimming with several key features that are difficult to find elsewhere.

**Comment by marcelm** [comment]
Thanks all, I’ve update the issue description to reflect the suggestions from your comments.

**Comment by gudeqing** [comment]
Hi, may you keep it simple and just make the primer name or primer itself be the suffix of read ID. And I think other postions such as 'prefix' would not be supported by most downstream tools.
Best regards!

**Comment by qifei9** [comment]
> Cutadapt already now is quite strict when parsing paired-end FASTQ files in that the read ids need to be identical in R1 and R2, and it tries to maintain that invariant when modifying read names. (If it doesn’t, I’d consider it a bug.)

Now I meet a case, where I am processing paired-end reads and have multiple linked adapters for both R1 and R2 (the adapters of R1 and R2 are not paired). Then I want to modify the read ids of both R1 and R2 by which adapter of R1 is trimmed, and, of course, keep the read ids identical between R1 and R2. For R2, I don't care which adapter is trimmed, as long as its required 5'-end adapter is trimmed. 

I put adapters in ada_R1.fa and ada_R2.fa and try to achieve the above goal (using version 2.10). Then I found the ids of R1 and R2 are not kept identical. With `-x '{name}_'`, the ids of R1 and R2 are modified, respectively, by the names of trimmed adapters on R1 and R2, which could be different. `{name1}` is not recognized, it adds literally "{name1}".

**Comment by marcelm** [comment]
Hi again. I have just added an initial implementation of a `--rename` option. It looks slightly different than what I initially suggested, so have a read through https://cutadapt.readthedocs.io/en/latest/guide.html#rename-renames-reads to see how it works.

I am not closing this issue, yet, because I’d like to add `{matched_sequence}` and possibly `{rn}` as well before doing so. For the other suggested options, new issues should be opened.

@eboyden Do you think that the `{rn}` template is still necessary with the new `--rename` option? As implemented now, you could remove the comments from both R1 and R2 with `--rename '{id}'`.

@qifei9 Yes, `-x` does not keep read IDs identical, but the new `--rename` option enforces it. Note that combinatorial demultiplexing is a different thing. It also happens to use curly braces `{` and `}`, but the `{name1}` and `{name2}` are the names of found adapters, not read names, and these placeholders need to be used within the output file names, not in the renaming template.

**Comment by eboyden** [comment]
@marcelm This is a great new feature, and it solves my main concern; however a `{rn}` option would still be appreciated. Right now there's still no means within Cutadapt to annotate reads as 1 or 2 unless they're already annotated; and if they're annotated in the comment (as bcl2fastq2 does), then there's no easy way to extract the read number but discard the rest of the comment (while the read number could be placed in the adapter names--assuming the lists are distinct--this strategy fails when an adapter is not found).

**Comment by marcelm** [comment]
Closing this issue now as the remaining features have been added:
- The `{rn}` placeholder was added already in Cutadapt 3.2
- I have added a `{match_sequence}` placeholder just now.

Please open a new issue for any remaining feature requests!
