### ISSUE TITLE
adapter trimming of pairend data  

### ISSUE THREAD

**Issue by U201412486** [marcelm/cutadapt#439]
Hi,
  How can I understand the parameter of -A when I want to filter the adapers of pairend data ?  For example,I have data named R1.fastq.gz,R2.fastq.gz produced by nextera xt library.Here are my codes.
  `cutadapt -a AGAT -A ATCT -o 1 -p 2  R1.fastq.gz R2.fastq.gz` 
  ATCT is the reverse complemental sequence of AGAT.
  And,it can filter the adapter of  R1.fastq.gz and can not filter the adapter of R2.fastq.gz .How can I set the value of A?
  Thanks,
  sun,

**Comment by marcelm** [comment]
Hi, I’m not sure I understand what exactly you’re asking. If you’re asking for the adapter sequences for Nextera, you can find these online in various places.

The `-A` sequence is usually *not* just the reverse complement of the one you use for `-a`.

**Comment by U201412486** [comment]
According to https://support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html,the -a sequence is CTGTCTCTTATACACATCT.So,what is the -A sequence for nextera pairend data?
Thanks,

**Comment by marcelm** [comment]
So in the footnote, it says:
> For TruSeq Small RNA and Ribo Profile, only one sequence is provided as single-read runs are recommended. For Nextera/TruSight, the same sequence is used for both reads.

I would try to use the sequence and also the reverse-complemented sequence and see whether that works.

**Comment by U201412486** [comment]
Hi, I have tried.It works when -a sequence and -A sequence are same for Nextera pairend data.

**Comment by marcelm** [comment]
Great! İ’m closing this issue then. Feel free to comment if you have more questions.
