### ISSUE TITLE
Support for modifying read names (suffix/prefix) with sequence

### ISSUE THREAD

**Issue by and3k** [marcelm/cutadapt#440]
Hi!

cutadapt is really great! Thanks!

Related to #437, it would also be convenient to have support for `{sequence}` in `--suffix` in addition to `{name}`.

Using the example from the tutorial:

```
cutadapt -a adapter1=ACGT -y ' we found {sequence}' input.fastq
```

would result in `read1 we found ACGT`.

Where `{sequence}` is the actually matched sequenced (including any mismatches). It may be even useful to have two options, one where the actual sequence is put there (with the mismatches), and one where the sequence of the adapter is put there.

It could be even further extended by options for putting the whole trimmed sequences there, trimming positions, etc? Maybe also a shortcut option which gives the complete report with all trimming details as a suffix (in a standardize format), so it’s 100% clear how every single read was trimmed.

Thanks!

Best,
Bela

**Comment by marcelm** [comment]
Hi, this is so close to what is suggested in #437, could you just add it as a comment there (and close this)?

**Comment by and3k** [comment]
Can do! Thanks!
