### ISSUE TITLE
Expected number of errors filtering of trimmed sequence

### ISSUE THREAD

**Issue by and3k** [marcelm/cutadapt#441]
Hi!

Maybe this is outside the scope of cutadapt, but since quality trimming is also supported: It would be awesome to have support for expected errors filtering, which can be a better alternative to quality trimming.

See also:
* https://academic.oup.com/bioinformatics/article/31/21/3476/194979
* DADA2’s `maxEE` paramter in `filterAndTrim` https://benjjneb.github.io/dada2/tutorial.html 

Thanks!
Bela

**Comment by marcelm** [comment]
Thanks for the suggestion! I have actually implemented something like this a while ago, but not within Cutadapt. If I find the code, it’s perhaps not too hard to add it to Cutadapt as an option.

**Comment by marcelm** [comment]
I’m almost embarrassed to say this, but this is now implemented. I’ve added an option `--max-ee` (or write it as `--max-expected-errors`) that can be used to filter out reads that exceed a given number of expected errors.

**Comment by and3k** [comment]
This is most excellent! Thank you very much!
