### ISSUE TITLE
--action=revcomp

### ISSUE THREAD

**Issue by jromagn** [marcelm/cutadapt#442]
I would like to be able to reverse complement reads in which an adapter was/was not found, to normalize orientations. Is there a way to do this, and if not, could it be added?

current version 2.8

edit to clarify:
I am working with paired end files, so the current --rc implementation does not help. Implementing --rc for paired ends would also solve this issue, I am assuming this was not done for a reason.

**Comment by marcelm** [comment]
The only reason I haven’t implemented `--rc` for paired-end reads was that I wasn’t sure whether there’s any interest in that and how exactly it should work. Can you share a bit more how your read layout is (what adapter type and how many) and how you think that `--rc` should work exactly?

My current thinking is that `--rc` for paired-end reads should not actually reverse-complement anything, but only swap R1 and R2. Would that be the correct behavior in your case?

Note: I’m taking some time off, it may take a while until I reply.

**Comment by jromagn** [comment]
I am not sure the behavior I am trying to achieve is intended by illumina, I will try to describe what I am seeing in the files:

A `R1 5'NNNN...ADAPTER1...NNNN3' R2 5'NNNN...2retpada...NNNN3'` x10000
B `R1 5'NNNN...1retpada...NNNN3' R2 5'NNNN...ADAPTER2...NNNN3'` x1000
C `R1 5'NNNN...2retpada...NNNN3' R2 5'NNNN...ADAPTER1...NNNN3'` x10000
D `R1 5'NNNN...ADAPTER2...NNNN3' R2 5'NNNN...1retpada...NNNN3'` x1000

These four cases in roughly these numbers. I think cases A and C are intended, I was able to combine them by 
`cutadapt -g ADAPTER1 -G 2retpada -o out1 -p out2 R1 R2`
`cutadapt -g ADAPTER1 -G 2retpada -o out3 -p out4 R2 R1`
`copy /b /y out1+out3`
`copy /b /y out2+out4`

This seems like a common enough task that it should be an option (swap a read between R1 and R2 if it is a better match swapped, also keep order, no duplicates), but I was actually thinking about getting the reverse complement of cases B and D.

After some more thinking about this, I am leaning towards that those cases are erroneous behavior in the illumina chemistry, and should be discarded, but over 10% being like that originally made me think they should be included in the secondary analysis.

**Comment by jromagn** [comment]
I looked more carefully at the data and it is probably not valuable to combine these cases; B and D occurred when there was a large deletion of about 200-300 bases, bringing the two adapters closer than they were expected. I think the original request for this issue is resolved, you may still want to consider the --swap functionality described above.
