### ISSUE TITLE
greedy search for multiple adapter occurrences on 5' end

### ISSUE THREAD

**Issue by luyoutao** [marcelm/cutadapt#445]
Dear developer,

Thanks for developing cutadapt. I have a question regarding how to deal with multiple adapters on  5' end (-g). 

According to the manual, when cutadapt sees two copies of 5' adapter,
`cccccADAPTERgggggADAPTERttttt`
it cuts the first (leftmost) only, 
`gggggADAPTERttttt`

I wonder if there is a switch to disable this behavior and let cutadapt cut till the end of the last occurrence. 

Thanks,

**Comment by marcelm** [comment]
Hi, there is already an issue about this at #254. Could you add the above information to that issue? I’m going to close this issue now to avoid a duplicate.

I’m currently not working, so any replies may take a while.
