### ISSUE TITLE
[question] --trim-n only at the 3' end of the read

### ISSUE THREAD

**Issue by martynakgajos** [marcelm/cutadapt#447]
Is it possible to trim only N at one end of the read?

**Comment by marcelm** [comment]
Not at the moment, but the `N` bases at the 3' end should also have a very low quality, so you should be able to use regular quality trimming with `-q`, perhaps with a quite low threshold such as `-q 5`. Would that work in your case?

**Comment by marcelm** [comment]
I hope you have a solution! Closing now.
