### ISSUE TITLE
AttributeError when handling  .bzip2 files.

### ISSUE THREAD

**Issue by DriesSchaumont** [marcelm/cutadapt#448]
Hi,
I think there might be something wrong with processing .bzip2 files.

Cutadapt 2.8 with Python 3.6.9
Installed using pip 20.0.2

When running using the following parameters:
Command line parameters: -u 9 -u -5 -j 32 -U 5 -o 1.fastq.bz2 -p 2.fastq.bz2 trimmed_1.fastq.bz2 trimmed_2.fastq.bz2

I got the following error message (I redacted some paths)

```
Processing reads on 32 cores in paired-end mode ...
ERROR: Traceback (most recent call last):
  File ".venv/lib/python3.6/site-packages/cutadapt/pipeline.py", line 518, in run
    outfiles = self._make_output_files()
  File ".venv/lib/python3.6/site-packages/cutadapt/pipeline.py", line 559, in _make_output_files
    output.name = orig_outfile.name
AttributeError: 'BZ2File' object has no attribute 'name'

Traceback (most recent call last):
  File ".venv/bin/cutadapt", line 8, in <module>
    sys.exit(main())
  File ".venv/lib/python3.6/site-packages/cutadapt/__main__.py", line 878, in main
    stats = runner.run()
  File ".venv/lib/python3.6/site-packages/cutadapt/pipeline.py", line 740, in run
    raise e
AttributeError: 'BZ2File' object has no attribute 'name'
```

I presume this is not related to the specific file I was parsing, so I have not tested with other .bzip2 files. Please let me know if you require me to do so. 

Kind Regards,
Dries

**Comment by marcelm** [comment]
Thanks for reporting! I was able to reproduce this. Give me a bit of time to fix it.

**Comment by marcelm** [comment]
This is fixed now. The bug occurred when trying to write to `.xz` or `.bz2` files while running on multiple cores.

**Comment by mickymous1** [comment]
AttributeError: 'BZ2File' object has no attribute 'extractall' Happening while extracting Bz2 file

**Comment by marcelm** [comment]
@mickymous1 Can you please file a new issue and also include the full terminal output?
