### ISSUE TITLE
Piping untrimmed paired-end reads to another instance of cutdapt

### ISSUE THREAD

**Issue by brendanf** [marcelm/cutadapt#450]
Cutadapt 2.8 with Python 3.6.7
installed via conda

I'm trying to pipe together different instances of cutadapt to trim adapters and demultiplex paired-end reads which may be in either orientation.  I'm aware of the --revcomp option, but I don't want to use it because I'd prefer to keep the two orientations in separate files, because I will treat them somewhat differently later in the pipeline.

Here's what I've tried:

```bash
mkfifo untrim_pipe_R1.fastq untrim_pipe_R2.fastq
cutadapt \
    --pair-adapters\
    -a file:fwd_tags.fasta\
    -A file:rev_tags.fasta\
    -o forward_R1.fastq.gz\
    -p forward_R2.fastq.gz\
    --untrimmed-output untrim_pipe_R1.fastq \
    --untrimmed-paired-output untrim_pipe_R2.fastq \
    input_R1.fastq.gz \
    input_R2.fastq.gz &
cutadapt \
    --pair-adapters\
    -a file:fwd_tags.fasta\
    -A file:rev_tags.fasta\
    -o reverse_R2.fastq.gz\
    -p reverse_R1.fastq.gz\
    untrim_pipe_R2.fastq \
    untrim_pipe_R1.fastq &
wait
```

However, no reads are processed.  The output files `reverse_R1.fastq.gz` and `reverse_R2.fastq.gz` are created (with no contents), but not `forward_R1.fastq.gz` and `forward_R2.fastq.gz`.

I assume the problem is that the second instance of cutadapt is waiting for input on `untrim_pipe_R2.fastq` while the first instance is trying to write to `untrim_pipe_R1.fastq`, so both are blocking.

Using an interleaved file, with a script between the two instances to switch the order of the reads, might be a solution, but it appears that this isn't supported for the untrimmed reads:

```bash
cutadapt \
           --pair-adapters\
           --interleaved\
           -a file:fwd_tags.fasta\
           -A file:rev_tags.fasta\
           -m 1\
           -o forward.fastq.gz\
           --untrimmed-output untrim.fastq\
           input_R1.fastq
           input_R2.fastq
```

```
cutadapt: error: When trimming paired-end reads, you must use either none or both of the --untrimmed-output/--untrimmed-paired-output options.
```

**Comment by marcelm** [comment]
The first command looks perfectly fine to me and I would have expected it to work. You may be right that this could be a deadlock.

That the second command doesn’t work is a bug, which I’ll need to fix.

I’ll investigate; thanks for reporting!

**Comment by marcelm** [comment]
Ok, one deadlock occurs because R1 and R2 are swapped: The first process opens the R1 file for writing and waits until the connection is made from the other side. Then the second process opens the R2 file for reading and waits until the other side opens it for writing ...

However, even when I swap them back, it doesn’t work. I need to look at this closer. I’m not sure this is so easy to support. I didn’t know this, but already `open()`ing a FIFO blocks until *both* sides have been opened.

Probably it’s easier to fix interleaving so it works with `--untrimmed-output`.

**Comment by marcelm** [comment]
I looked into avoiding the deadlock, but for now, I don’t know how. So for the moment, I’ll just pretend it’s “user error” ...

Instead, I’ve now fixed the `--interleaved` option to make it work with `--untrimmed-output` (and `--too-short-output` and `--too-long-output`, which also didn’t work). I hope this is good enough for your use case. You can test it by [installing the development version](https://cutadapt.readthedocs.io/en/latest/installation.html#installing-the-development-version).
