### ISSUE TITLE
Alignment problem after adapter trimming

### ISSUE THREAD

**Issue by asumann** [marcelm/cutadapt#451]
I run Cutadapt2.5 on HPC.

I downloaded  sRNA fastq raw data online. The adapters are not given in the article or in data description. So, I use adapter.fa file which includes Illumina adapters:

>
>Reverse_adapter
AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG
>TruSeq_Universal_Adapter
AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT
>pcr_dimer
AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCTAGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG
>PCR_Primers
AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCTCAAGCAGAAGACGGCATACGAGCTCTTCCGATCT
>TruSeq_Adapter_Index_1_6
GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG
>TruSeq_Adapter_Index_2
GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG
.....

However, when I do bowtie alignment to reference genome, I got this error:
>Saw ASCII character 10 but expected 33-based Phred qual.

I don't get this error if I run bowtie **without** adapter trimming, but alignment rate is too low(%1) as expected. Hence, I believe there is something else is happening when I run cutadapt with universal adapters file.

Is there any option I should use while using adapter.fa? Or any other idea to solve this issue?

Thanks in advance!

**Comment by marcelm** [comment]
ASCII character 10 is just the newline (`\n`) character, which normally occurs at the end of each line, so it’s a bit weird Bowtie complains. Do you have a small example FASTQ file perhaps? I could also try to redroduce this without, but it’ll take longer. Which Bowtie version gives you that error?

**Comment by asumann** [comment]
I attached 1000 line from tail. (I uploaded it with a text extension, since fastq extension is not supported.) I also found that there are some quality lines with a length of 0(so comes the newline error, maybe?). Could it be a possible problem that my fastq is corrupted somehow after trimming? 

I use bowtie-v1.2.3 since it is known to perform better with small read size.

[tail1000.txt](https://github.com/marcelm/cutadapt/files/4397231/tail1000.txt)

**Comment by marcelm** [comment]
Yes, you were right, the empty reads appear to be the problem. In my opinion, this is a probem in Bowtie (1.2.3) because there are legitimate reasons for having zero-length reads. In Bowtie2, this has been fixed and I get this error message:
```
Warning: skipping read 'SRR3286340.8537955 8537955 length=50' because it was < 2 characters long
```

To solve this, please add the option `-m 1` to your cutadapt command line. This will discard all reads that are shorter than 1 bp. Or use a higher value for filtering – extremely short reads aren’t useful anyway.

**Comment by asumann** [comment]
Many thanks!!

**Comment by marcelm** [comment]
Glad I could help. I’ll close this now, but feel free to comment or open a new issue if you have further questions.
