### ISSUE TITLE
input file .fq

### ISSUE THREAD

**Issue by francesca-guana** [marcelm/cutadapt#454]
Hello!

I'm using Cutadapt 2.9 installed on Python 2.7.17
I need to know if in this version I can use a .fq file instead .fastq as input file.
Because it gives me this error:  

cutadapt: error: unrecognized arguments: s1130_1.fq.gz s1130_2.fq.gz

The command line is:

cutadapt –q 28 –m 25 –j 0 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o s1130_1_trimmed.fq.gz -p s1130_2_trimmed.fq.gz s1130_1.fq.gz s1130_2.fq.gz

**Comment by marcelm** [comment]
The command that you pasted uses “en dashes” (unicode U+2013) in the the “–q 28 –m 25 –j 0” options instead of the required hyphens (unicode U+002D).

The difference is subtle:

* Recognized: -q
* Not recognized: –q

Just replace the longer dashes with normal ones, and it should work!

**Comment by francesca-guana** [comment]
Thank you. I didn't see the difference when I typed the command.
Now it works

**Comment by marcelm** [comment]
I’ve changed Cutadapt such that it prints a warning when this happens:
```
$ cutadapt –q 28 –m 25 –j 0 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o s1130_1_trimmed.fq.gz -p s1130_2_trimmed.fq.gz s1130_1.fq.gz s1130_2.fq.gz
This is cutadapt 2.10.dev28+gbf87394 with Python 3.6.9
Command line parameters: –q 28 –m 25 –j 0 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o s1130_1_trimmed.fq.gz -p s1130_2_trimmed.fq.gz s1130_1.fq.gz s1130_2.fq.gz
WARNING: The first character in argument '–q' is '–' (an en-dash, Unicode U+2013) and will therefore be interpreted as a file name. If you wanted to provide an option, use a regular hyphen '-'.
WARNING: The first character in argument '–m' is '–' (an en-dash, Unicode U+2013) and will therefore be interpreted as a file name. If you wanted to provide an option, use a regular hyphen '-'.
WARNING: The first character in argument '–j' is '–' (an en-dash, Unicode U+2013) and will therefore be interpreted as a file name. If you wanted to provide an option, use a regular hyphen '-'.
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: unrecognized arguments: s1130_1.fq.gz s1130_2.fq.gz
```
