### ISSUE TITLE
cutadapt: error: unrecognized arguments

### ISSUE THREAD

**Issue by qicaibiology** [marcelm/cutadapt#455]
Dear Developer:
I am learning using cutadapt to analyze CLIP-Seq data. I got stuck at the very first step:
Information for my system:
Anaconda3
python version: 3.7.6
Cutadapt version:2.9
intall:
conda create -n cutadaptenv cutadapt
conda activate cutadaptenv

code I used:
`cutadapt -f fastq --match-read-wildcards --times 1 -e 0.1 -O 1 --quality-cutoff 6 -m 18 -a NNNNNAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -g CTTCCGATCTACAAGTT -g CTTCCGATCTTGGTCCT -A AACTTGTAGATCGGA -A AGGACCAAGATCGGA -A ACTTGTAGATCGGAA -A GGACCAAGATCGGAA -A CTTGTAGATCGGAAG-A GACCAAGATCGGAAG -A TTGTAGATCGGAAGA -A ACCAAGATCGGAAGA -A TGTAGATCGGAAGAG -A CCAAGATCGGAAGAG -A GTAGATCGGAAGAGC -A CAAGATCGGAAGAGC -A TAGATCGGAAGAGCG -A AAGATCGGAAGAGCG -A AGATCGGAAGAGCGT -A GATCGGAAGAGCGTC -A ATCGGAAGAGCGTCG -A TCGGAAGAGCGTCGT -A CGGAAGAGCGTCGTG -A GGAAGAGCGTCGTGT -o SRR5112140_1.trimmed1.fastq -p SRR5112140_2.trimmed1.fastq K_proteinrep1/SRR5112140_1.fastq K_proteinrep1/SRR5112140_2.fastq `

problems I cannot figure out:

> Run "cutadapt --help" to see command-line options.
> See https://cutadapt.readthedocs.io/ for full documentation.
> 
> cutadapt: error: unrecognized arguments: K_proteinrep1/SRR5112140_1.fastq K_proteinrep1/SRR5112140_2.fastq

Thank you very much for your advice!

Cai

**Comment by marcelm** [comment]
Hi, can you have a look at issue #454, where the same problem was reported a couple of days ago? In short: You possibly have some weird character in your command line.

To check whether that is the problem, simplify the command by removing options one by one (start with removing `-f fastq`, then `--match-read-wildcards`, then `--times 1` etc.), and see whether the error disappears. When it starts working, you know which option was the problem.

Also, you may want to update to Cutadapt 2.10, which I released on Wednesday. If you have the same problem as reported in #454, you will see a warning.

**Comment by qicaibiology** [comment]
I just check my script again and found that it had a typo. It is running now. But I will update it and follow your advice.
Appreciate a lot for your prompt reply!
