### ISSUE TITLE
Non-internal adapters search using fasta file

### ISSUE THREAD

**Issue by MaestSi** [marcelm/cutadapt#458]
Dear Cutadapt developer,
I would like to perform trimming of non-internal 5' adapters in paired-end reads. In the manual I found that for one single adapter it is enough to add a 'X' at the beginning of the sequence. If I want to perform this kind of search using a fasta file for adapters, is it ok to add 'X' at the beginning of each sequence, or are there better methods? The command I am using, after adding 'X' to each sequence is:
`cutadapt -g file:primers_left.fasta -G file:primers_right.fasta -o Reads_R1_trimmed.fastq -p Reads_R2_trimmed.fastq Reads_R1.fastq Reads_R2.fastq`
Thanks in advance,
Simone

**Comment by marcelm** [comment]
Yes, if you prefix all the adapters in the FASTA file with an `X`, it’ll work. I’d like to make this a bit simpler, but haven’t found a good syntax for expressing this on the command line. See #361 for a discussion.

**Comment by MaestSi** [comment]
Perfect. Maybe, as another possibility with respect to what you already proposed in the other issue, I'd suggest the following syntax with backslash to escape the special charachters (^, X):
`file\X:adapters.fa`
Thanks,
Simone

**Comment by marcelm** [comment]
Thanks for the feedback! I’ll keep it in mind when I revisit that issue.
