### ISSUE TITLE
Install cutadapt without internet connection

### ISSUE THREAD

**Issue by stevenhenry34** [marcelm/cutadapt#461]
Hi,
I am new to NGS data analysis and have no informatics background (especially with Python) so I appologize in advance for my questions.
I am trying to install Cutadapt on a Windows system without internet connection.
I have already installed latest Miniconda version, but it seems that I can't create a new virtual environment with the tutorial method without the internet.
I also tried to download a wheel for Cutadapt and run "pip install [path to the wheel]" but it says that this is not a supported wheel on this platform (whereas I have downloaded cp37 and x86_64 wheel and I have Python 3.7 under Windows x64 bits).
Is this the right way to install Cutadapt without internet (download the wheel) or is there another way? (I won't be able to try your solutions until monday).
Thanks.

**Comment by marcelm** [comment]
Hi,

Cutadapt contains some so-called extension modules that need to be compiled for the platform that the program is going to be installed on. Miniconda supports Windows, but it will still not help because the Bioconda channel of which Cutadapt is a part does not build packages for Windows. The alternative of using the pre-compiled wheels (on PyPI) will also not work, because these are only for Linux (that explains your error message).

I wrote some instructions on how to install under Windows here:
https://github.com/marcelm/cutadapt/issues/434#issuecomment-574147493
(I should add these to the documentation.)

These of course assume you have an internet connection, so you’ll have to get the Build Tools for Visual Studio 2019 on to the system some other way. Then, the `pip install` step will fail, but it may work if you copy these files over:
- https://files.pythonhosted.org/packages/4b/9d/3f98c2619206430ad11e485a2a2f6b3e37f792f11523fee372739abdc1cd/cutadapt-2.10.tar.gz
- https://files.pythonhosted.org/packages/be/46/4aebdff29822d98010b2b6b5b50f690e9a804cbd072787e2642b43e7f3f3/dnaio-0.4.2.tar.gz
- https://files.pythonhosted.org/packages/ed/b6/0006cf17f5b2f7b45ea3258602d1e0b13c6012841645b664ff4977054cd5/xopen-0.9.0-py2.py3-none-any.whl
- https://files.pythonhosted.org/packages/4b/c1/118ec08816737cc46b4dd93b22f7a138fbfb14b53f4b4718fd9983e70a50/setuptools_scm-3.5.0-py2.py3-none-any.whl
- https://files.pythonhosted.org/packages/79/36/69246177114d0b6cb7bd4f9aef177b434c0f4a767e05201b373e8c8d7092/Cython-0.29.19.tar.gz
- https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl

Put them all in one directory on the target machine and try this command:
```
python3 -m pip install -f ./ --no-index wheel-0.34.2-py2.py3-none-any.whl
python3 -m pip install -f ./ --no-index cutadapt-2.10.tar.gz
```
I don’t know what the chances are of this actually working, though since I don’t have a Windows system to test on.

**Comment by stevenhenry34** [comment]
Hi,

Sorry for the late answer.
So I installed Python 3.8.3 and I managed to install Build Tools for Visual Studio without an internet connexion. Then I put these 6 files in the working directory, but unfortunately the second line of the command failed (I copied the second try that's why "wheel 0.34.2" is already installed) :

```
C:\Users\Biomed>py -3.8 -m pip install -f ./ --no-index wheel-0.34.2-py2.py3-non
e-any.whl
Looking in links: ./
Requirement already satisfied: wheel==0.34.2 from file:///C:/Users/Biomed/wheel-
0.34.2-py2.py3-none-any.whl in c:\users\biomed\appdata\local\programs\python\pyt
hon38-32\lib\site-packages (0.34.2)

C:\Users\Biomed>py -3.8 -m pip install -f ./ --no-index cutadapt-2.10.tar.gz
Looking in links: ./
Processing c:\users\biomed\cutadapt-2.10.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Biomed\AppData\Local\Programs\Python\Python38-32\python.ex
e' 'C:\Users\Biomed\AppData\Local\Programs\Python\Python38-32\lib\site-packages\
pip' install --ignore-installed --no-user --prefix 'C:\Users\Biomed\AppData\Loca
l\Temp\pip-build-env-fpslvnpf\overlay' --no-warn-script-location --no-binary :no
ne: --only-binary :none: --no-index --find-links ./ -- setuptools wheel setuptoo
ls_scm cython
       cwd: None
  Complete output (4 lines):
  Looking in links: ./
  Collecting setuptools
    ERROR: Could not find a version that satisfies the requirement setuptools (f
rom versions: none)
  ERROR: No matching distribution found for setuptools
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Biomed\AppData\Local\Pr
ograms\Python\Python38-32\python.exe' 'C:\Users\Biomed\AppData\Local\Programs\Py
thon\Python38-32\lib\site-packages\pip' install --ignore-installed --no-user --p
refix 'C:\Users\Biomed\AppData\Local\Temp\pip-build-env-fpslvnpf\overlay' --no-w
arn-script-location --no-binary :none: --only-binary :none: --no-index --find-li
nks ./ -- setuptools wheel setuptools_scm cython Check the logs for full command
 output.
```
I also tried to run the same command for the 4 other files, the .whl files seems to work fine (including setup tools) but others .tar.gz files don't.

I installed cutadapt on another PC with internet without any problem following the way you told in issue #434. What are the chance if I just copy "Lib/site-packages" directory (where it looks like it is installed) from one PC to another?

Thanks again,

Steven

**Comment by marcelm** [comment]
Copying `Lib/site-packages` could work, but make you sure that the Python versions are the same on both machines (3.8.x).

Regarding the error message you got: It seems you also need the regular "setuptools" package (in addition to "setuptools_scm", which is a different thing). You can get it here: https://files.pythonhosted.org/packages/95/95/f657b6e17f00c3f35b5f68b10e46c3a43af353d8856bd57bfcfb1dbb3e92/setuptools-47.1.1-py3-none-any.whl . I would try that first and then your idea of copying over site-packages.

**Comment by marcelm** [comment]
Hi, I just tried to build Cutadapt for Windows (using GitHub’s virtual machines) and while I cannot test it myself, there weren’t any error messages, so perhaps it worked.

You can try to download a .exe from here:
https://github.com/marcelm/cutadapt/suites/752751340/artifacts/7747807
You should not need anything else, just download that zip file, unpack it and copy the `cutadapt.exe` file to your machine. Let me know if that works.

**Comment by stevenhenry34** [comment]
Hi,

It still doesn't work after installing setuptools

```
C:\Users\Biomed>py -3.8 -m pip install setuptools-47.1.1-py3-none-any.whl
Processing c:\users\biomed\setuptools-47.1.1-py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 41.2.0
    Uninstalling setuptools-41.2.0:
      Successfully uninstalled setuptools-41.2.0
Successfully installed setuptools-47.1.1

C:\Users\Biomed>py -3.8 -m pip install cutadapt-2.10.tar.gz
Processing c:\users\biomed\cutadapt-2.10.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Biomed\AppData\Local\Programs\Python\Python38-32\python.ex
e' 'C:\Users\Biomed\AppData\Local\Programs\Python\Python38-32\lib\site-packages\
pip' install --ignore-installed --no-user --prefix 'C:\Users\Biomed\AppData\Loca
l\Temp\pip-build-env-bl1lrt1t\overlay' --no-warn-script-location --no-binary :no
ne: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel setuptoo
ls_scm cython
       cwd: None
  Complete output (8 lines):
  Collecting setuptools
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, st
atus=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', O
SError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple
/setuptools/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, st
atus=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', O
SError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple
/setuptools/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, st
atus=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', O
SError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple
/setuptools/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, st
atus=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', O
SError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple
/setuptools/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, st
atus=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', O
SError('Tunnel connection failed: 407 Proxy Authentication Required'))': /simple
/setuptools/
    ERROR: Could not find a version that satisfies the requirement setuptools (f
rom versions: none)
  ERROR: No matching distribution found for setuptools
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Biomed\AppData\Local\Pr
ograms\Python\Python38-32\python.exe' 'C:\Users\Biomed\AppData\Local\Programs\Py
thon\Python38-32\lib\site-packages\pip' install --ignore-installed --no-user --p
refix 'C:\Users\Biomed\AppData\Local\Temp\pip-build-env-bl1lrt1t\overlay' --no-w
arn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/
simple -- setuptools wheel setuptools_scm cython Check the logs for full command
 output.
```

So let's forget this installation issue I guess... I'll try to analyze my data with either the .exe you built or the Lib/site-packages copy from the other PC but it will be a first time for me so I don't know if I could say if it is working fine.

Thank you for all!

Steven

**Comment by marcelm** [comment]
I think the problem this time was that you did not specify `-f ./ --no-index`. Perhaps you want to try that, but no worries if you don’t. Please let me know if the .exe works in case you try it (but you don’t have to).

Do you think this issue can be closed then?

**Comment by stevenhenry34** [comment]
After reinstalling BuildTools with optionnal content (the recommended installation did not includ cl.exe), your first solution (with the 6 files in the same folder) seems to work : no error, installation success!
However when I use Cutadapt in R, even if I don't get any error messages, I'm not producing any filtered reads. This is probably my bad but this is another issue...
Just saying this because the same thing happened when I tried with the cutadapt.exe file or with the Lib/site-packages copy from other PC (no error but no files produced). So finally the three methods could work, but... can't be sure :)
You can close this issue, thank you a lot!

**Comment by marcelm** [comment]
Great, thanks for the feedback!

If you need further help because you’re not getting any output, just open a new issue.
