### ISSUE TITLE
Multicores error

### ISSUE THREAD

**Issue by xiucz** [marcelm/cutadapt#462]
Hi,  
I tried to run cutadapt with 6 (or more) cores, but it threw out an error below. Should I disable the `-j` option? Or is there other ways to parallel?
`- python3 and cutadapt version2.10`

```
~QCtools/cutadapt \
-g $adapter_fwd \
-G $adapter_fwd \
-j 6 -e 0.1 -O 5 -m 50 -n 2 --pair-filter=both \
-u 29 -U 15 \
tmp1 tmp2 \
-o read1 -p read2
```

```
ValueError: FASTQ record does not fit into buffer
```
Thank you,
xiucz

**Comment by marcelm** [comment]
Hm, that particular error message should only be printed when a FASTQ record exceeds 4 million bytes, which I would not have expected to happen anytime soon. Which type of reads are you working on?

**Comment by xiucz** [comment]
I am working on UMI reads from Illumina platform, maybe Novaseq.... The goal for this command is to trim UMI and some adapter bases. And the total input bases is about 16G.
However,  if I use the default one core, it works well.

**Comment by marcelm** [comment]
At which point in the file do you get the error? The progress indicator should tell you at which read you are approximately.

There’s a hidden option for setting the buffer size. You can try to add the option `--buffer-size=40000000` (40 MB, ten times the normal size) to your command and then see whether it works with multiple cores.

**Comment by xiucz** [comment]
@marcelm 
With the hidden option `--buffer-size=40000000` and the core option `-j 6`, it works! 
Thank you and I close this issue.

**Comment by marcelm** [comment]
Thanks for the feedback; I’m glad it worked. I’ll have to investigate this a bit to see whether I can increase the default buffer size a bit.
