### ISSUE TITLE
Premature end of file encountered

### ISSUE THREAD

**Issue by XUKEREN** [marcelm/cutadapt#464]
Hi, I encountered this error when running cutadapt on two paired end fastqs. Wasn't sure where went wrong. I checked that these two fastqs are of the same length. Here is my error message:  

this is cutadapt 2.10 with Python 3.6.8
Command line parameters: -j 1 -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC a0002151975_S2_R1.fastq.paired.fq.gz
Processing reads on 1 core in single-end mode ...
cutadapt: error: Error in FASTQ file at line 201147646: Premature end of file encountered. The incomplete final record was: '@NS500323:62:H0YG6BGXX:4:22509:9837:10120 1:N:0:TTCAGCCT+CTAGTCGA\nGGTCCTCCTGGCTGCTGTCCCCACCAGGGAGCAGGGAAGGCGCTGGGGCTGCGGTGCCGGCTGCCCATCGCCTCGACGGCGCTGTGGCCGGCGCTCCTGGGCCTAGCAGCGGACGTGGGGAGCGCGGGGTCCTCCTGGCTGCTGTCCCCACCAGGGAGCAGGGAAGGCGCTGGGGCTGCGGTGCCGGCTGCCCATCGCCTCGACGGCGCTGTGGCCGGCGCTCCTGGGCCTAGCAGCGGACGTGGGGAGCGCGGGGTCCTCCTGGCTGCTGTCCCCACCAGGGAGCAGGGAAGGCGCTGGGGCTGCGGTGCCGGCTGCCCATCGCCTCGACGGCGCTGTGGCCGGCGCTCCTGGGCCTAGCAGCGGACGTGGGGAGCGCGG'

**Comment by XUKEREN** [comment]
Just realized that this fastq has missing lines. Problem solved. Thanks!!

**Comment by marcelm** [comment]
Perfect, good you found the problem yourself :-)

Let me know if you think that the error message could be improved.
