### ISSUE TITLE
Linked adapter and --discard-untrimmed

### ISSUE THREAD

**Issue by suzyH887** [marcelm/cutadapt#470]
Hi, I just wondered if you could clarify this sentence from the manual for me?

'Also, when you use the --discard-untrimmed option (or --trimmed-only) with a linked adapter, then a read is considered to be trimmed only if all required adapters were found.'

When I use linked adapters i.e. -a GTTGAATTTTAGCCYTGGC...WGAGAAATCAAAGTTTTTGGG -A CCCAAAAACTTTGATTTCTCW...GCCARGGCTAAAATTCAAC the output suggests it is keeping anything trimmed from one or the other adapter.

If I anchor it i.e. -a ^GTTGAATTTTAGCCYTGGC...WGAGAAATCAAAGTTTTTGGG -A ^CCCAAAAACTTTGATTTCTCW...GCCARGGCTAAAATTCAAC the output suggests it is only keeping reads trimmed with the anchored adapter.

I realise I don't even need linked primer for this dataset as the second primer will not be found (amplicon is too large) but I was just testing it out.

I can't see when it is only keeping both as the manual suggests. I like it how it is, so don't want it to change! But was confused by the sentence. Really sorry if I've totally misunderstood it all...

I'm using cutadapt 2.10 with Python 3.7.1

NOT ANCHORED

MAC23597:FRE lfslal$  ~/.local/bin/cutadapt  -a GTTGAATTTTAGCCYTGGC...WGAGAAATCAAAGTTTTTGGG -A CCCAAAAACTTTGATTTCTCW...GCCARGGCTAAAATTCAAC   --discard-untrimmed -e 0.2 -O 10 -o trimmed_fastq/${i}\_R1_001.fastq.gz    -p trimmed_fastq/${i}\_R2_001.fastq.gz F1_A10155-216_CPBM7_GGAGCTAC-GTAAGGAG_L001_R1_001.fastq.gz  F1_A10155-216_CPBM7_GGAGCTAC-GTAAGGAG_L001_R2_001.fastq.gz  -m 50
This is cutadapt 2.10 with Python 3.7.1
Command line parameters: -a GTTGAATTTTAGCCYTGGC...WGAGAAATCAAAGTTTTTGGG -A CCCAAAAACTTTGATTTCTCW...GCCARGGCTAAAATTCAAC --discard-untrimmed -e 0.2 -O 10 -o trimmed_fastq/trimmed_fastq_R1_001.fastq.gz -p trimmed_fastq/trimmed_fastq_R2_001.fastq.gz F1_A10155-216_CPBM7_GGAGCTAC-GTAAGGAG_L001_R1_001.fastq.gz F1_A10155-216_CPBM7_GGAGCTAC-GTAAGGAG_L001_R2_001.fastq.gz -m 50
WARNING: You specified a linked adapter as '-a ADAPTER1...ADAPTER2'. The
interpretation of what this means has changed in Cutadapt 2.0. (The 5'
adapter is now no longer anchored by default.) To get results consist
with the old behavior, you need to anchor the 5' adapter explicitly as
in '-a ^ADAPTER1...ADAPTER2'.
WARNING: You specified a linked adapter as '-a ADAPTER1...ADAPTER2'. The
interpretation of what this means has changed in Cutadapt 2.0. (The 5'
adapter is now no longer anchored by default.) To get results consist
with the old behavior, you need to anchor the 5' adapter explicitly as
in '-a ^ADAPTER1...ADAPTER2'.
Processing reads on 1 core in paired-end mode ...
[ 8=---------] 00:00:05        55,364 reads  @     96.6 µs/read;   0.62 M reads/minute
Finished in 5.35 s (97 us/read; 0.62 M reads/minute).

=== Summary ===

Total read pairs processed:             55,364
  Read 1 with adapter:                  21,487 (38.8%)
  Read 2 with adapter:                  21,414 (38.7%)
Pairs written (passing filters):        21,394 (38.6%)

Total basepairs processed:    33,218,400 bp
  Read 1:    16,609,200 bp
  Read 2:    16,609,200 bp
Total written (filtered):     11,966,857 bp (36.0%)
  Read 1:     6,004,669 bp
  Read 2:     5,962,188 bp

=== First read: Adapter 3 ===

Sequence: GTTGAATTTTAGCCYTGGC...WGAGAAATCAAAGTTTTTGGG; Type: linked; Length: 19+21; 5' trimmed: 21466 times; 3' trimmed: 222 times

No. of allowed errors:
0-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3

No. of allowed errors:
0-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3; 20-21 bp: 4

Overview of removed sequences at 5' end
length	count	expect	max.err	error counts
12	2	0.0	2	0 2
15	1	0.0	3	1
16	2	0.0	3	0 1 0 1
17	4	0.0	3	2 0 2
18	183	0.0	3	9 149 5 20
19	21255	0.0	3	20737 508 7 3
20	16	0.0	3	5 11
22	2	0.0	3	0 0 0 2
184	1	0.0	3	0 0 0 1

Overview of removed sequences at 3' end
length	count	expect	max.err	error counts
8	3	0.8	1	0 0 3
9	6	0.2	1	0 0 6
10	9	0.1	2	0 0 9
11	5	0.0	2	0 0 5
18	11	0.0	3	10 1
29	171	0.0	4	153 10 4 3 1
30	3	0.0	4	2 0 1
100	1	0.0	4	1
141	4	0.0	4	0 4
192	6	0.0	4	6
238	2	0.0	4	0 2
256	1	0.0	4	1

=== Second read: Adapter 6 ===

Sequence: CCCAAAAACTTTGATTTCTCW...GCCARGGCTAAAATTCAAC; Type: linked; Length: 21+19; 5' trimmed: 21408 times; 3' trimmed: 202 times

No. of allowed errors:
0-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3; 20-21 bp: 4

No. of allowed errors:
0-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3

Overview of removed sequences at 5' end
length	count	expect	max.err	error counts
9	1	0.2	1	0 0 1
13	1	0.0	2	0 0 1
14	1	0.0	2	1
16	1	0.0	3	0 1
17	4	0.0	3	1 0 0 2 1
18	3	0.0	3	0 0 0 3
19	19	0.0	3	2 0 10 4 3
20	88	0.0	4	14 51 15 6 2
21	21198	0.0	4	19862 1094 180 42 20
22	66	0.0	4	3 35 13 13 2
23	8	0.0	4	0 0 4 3 1
24	16	0.0	4	0 0 0 7 9
62	1	0.0	4	0 0 0 0 1
270	1	0.0	4	0 0 0 0 1

Overview of removed sequences at 3' end
length	count	expect	max.err	error counts
9	1	0.2	1	0 0 1
10	3	0.1	2	0 1 2
11	1	0.0	2	0 0 1
16	11	0.0	3	9 1 0 1
27	168	0.0	3	119 32 11 6
28	3	0.0	3	3
98	1	0.0	3	1
139	4	0.0	3	2 2
172	1	0.0	3	0 0 0 1
190	6	0.0	3	2 4
236	2	0.0	3	2
254	1	0.0	3	1

ANCHORED

MAC23597:FRE lfslal$  ~/.local/bin/cutadapt  -a ^GTTGAATTTTAGCCYTGGC...WGAGAAATCAAAGTTTTTGGG -A ^CCCAAAAACTTTGATTTCTCW...GCCARGGCTAAAATTCAAC   --discard-untrimmed -e 0.2 -O 10 -o trimmed_fastq/${i}\_R1_001.fastq.gz    -p trimmed_fastq/${i}\_R2_001.fastq.gz F1_A10155-216_CPBM7_GGAGCTAC-GTAAGGAG_L001_R1_001.fastq.gz  F1_A10155-216_CPBM7_GGAGCTAC-GTAAGGAG_L001_R2_001.fastq.gz  -m 50
This is cutadapt 2.10 with Python 3.7.1
Command line parameters: -a ^GTTGAATTTTAGCCYTGGC...WGAGAAATCAAAGTTTTTGGG -A ^CCCAAAAACTTTGATTTCTCW...GCCARGGCTAAAATTCAAC --discard-untrimmed -e 0.2 -O 10 -o trimmed_fastq/trimmed_fastq_R1_001.fastq.gz -p trimmed_fastq/trimmed_fastq_R2_001.fastq.gz F1_A10155-216_CPBM7_GGAGCTAC-GTAAGGAG_L001_R1_001.fastq.gz F1_A10155-216_CPBM7_GGAGCTAC-GTAAGGAG_L001_R2_001.fastq.gz -m 50
Processing reads on 1 core in paired-end mode ...
[ 8<---------] 00:00:03        55,364 reads  @     54.9 µs/read;   1.09 M reads/minute
Finished in 3.04 s (55 us/read; 1.09 M reads/minute).

=== Summary ===

Total read pairs processed:             55,364
  Read 1 with adapter:                  21,462 (38.8%)
  Read 2 with adapter:                  21,399 (38.7%)
Pairs written (passing filters):        21,383 (38.6%)

Total basepairs processed:    33,218,400 bp
  Read 1:    16,609,200 bp
  Read 2:    16,609,200 bp
Total written (filtered):     11,961,012 bp (36.0%)
  Read 1:     6,001,725 bp
  Read 2:     5,959,287 bp

=== First read: Adapter 3 ===

Sequence: GTTGAATTTTAGCCYTGGC...WGAGAAATCAAAGTTTTTGGG; Type: linked; Length: 19+21; 5' trimmed: 21462 times; 3' trimmed: 201 times

No. of allowed errors:
0-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3

No. of allowed errors:
0-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3; 20-21 bp: 4

Overview of removed sequences at 5' end
length	count	expect	max.err	error counts
16	2	0.0	3	0 0 0 2
17	4	0.0	3	0 0 4
18	183	0.0	3	0 156 7 20
19	21255	0.0	3	20737 508 7 3
20	16	0.0	3	0 16
22	2	0.0	3	0 0 0 2

Overview of removed sequences at 3' end
length	count	expect	max.err	error counts
8	1	0.8	1	0 0 1
9	1	0.2	1	0 0 1
18	11	0.0	3	10 1
29	171	0.0	4	153 10 4 3 1
30	3	0.0	4	2 0 1
100	1	0.0	4	1
141	4	0.0	4	0 4
192	6	0.0	4	6
238	2	0.0	4	0 2
256	1	0.0	4	1

=== Second read: Adapter 6 ===

Sequence: CCCAAAAACTTTGATTTCTCW...GCCARGGCTAAAATTCAAC; Type: linked; Length: 21+19; 5' trimmed: 21399 times; 3' trimmed: 196 times

No. of allowed errors:
0-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3; 20-21 bp: 4

No. of allowed errors:
0-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3

Overview of removed sequences at 5' end
length	count	expect	max.err	error counts
17	4	0.0	3	0 0 0 0 4
18	3	0.0	3	0 0 0 3
19	17	0.0	3	0 0 12 3 2
20	88	0.0	4	0 64 14 8 2
21	21197	0.0	4	19862 1088 184 42 21
22	66	0.0	4	0 38 13 12 3
23	8	0.0	4	0 0 4 3 1
24	16	0.0	4	0 0 0 7 9

Overview of removed sequences at 3' end
length	count	expect	max.err	error counts
16	11	0.0	3	9 1 0 1
27	168	0.0	3	119 32 11 6
28	3	0.0	3	3
98	1	0.0	3	1
139	4	0.0	3	2 2
190	6	0.0	3	2 4
236	2	0.0	3	2
254	1	0.0	3	1

**Comment by marcelm** [comment]
A linked adapter consists of a 5' and a 3' adapter. Each of these parts can be *required* or *optional*. A *required* adapter must be found, otherwise the entire read will a) remain unchanged and b) not be considered "trimmed" for the purpose of `--discard-untrimmed` and `--discard-trimmed`.

If you specify a linked adapter as `-a ADAPTER1...ADAPTER2`, then by default both adapters are *optional*. If you use anchoring, the corresponding adapter becomes *required*. So `-a ^ADAPTER1...ADAPTER2` makes the 5' adapter required, `-a ADAPTER...ADAPTER2$` makes the 3' adapter required and `-a ^ADAPTER...ADAPTER2$` makes both required.

If you specify a linked adapter with `-g ADAPTER1...ADAPTER2`, then by default both adapters are *required*.

Finally, you can override the above behavior of which adapter becomes required and which becomes optional by using the "trimming parameters" `optional` or `required`, but I think [that is explained good enough in the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#changing-which-adapters-are-required).

Of course, which of these options to use depends on how the reads look, but for amplicon trimming, you very likely need `-a ^ADAPTER1...ADAPTER2`, as you already use.

I’m not 100% sure I understood where exactly the docs were not clear enough, so let me know if that helped.

**Comment by suzyH887** [comment]
Thank you so much. I just re-read my question and realised I had totally not read the word 'required' in it.... so thought it meant all adapters needed to be found. Your explanation is very useful for clarifying it all.
Many thanks for this great package.
S

**Comment by marcelm** [comment]
Great, glad I could help!
