### ISSUE TITLE
Modifying read names by appending primer name to both read1 and read2

### ISSUE THREAD

**Issue by gudeqing** [marcelm/cutadapt#473]
Hi, I find the tool has an impressing function of modifying read names, however, I think more options may be needed to handle pair-ends. 
Note: This is cutadapt 2.10 with Python 3.7.7 Installed with Pip

## Append primer name to Read name
    cutadapt -j 10 -g file:primer.fasta -y ':{name}' --discard-untrimmed -m 20 -q 17 -u -1 -U -1 -e 0.15 --overlap 18 --info-file cut.detail.txt -o DNA.R1.clean.hasPrimer.fq -p DNA.R2.clean.hasPrimer.fq DNA.R1.clean.fq DNA.R2.clean.fq > cut.log
    command with option : -y ':{name}'
    @NB502121:62:HYC3WAFXY:1:11101:10538:9036:TCTTGCGCCTCG 1:N:0:CCATTATCGA+CGGATAACCG:**chr1:156849127-156849159:33:-:NTRK1**
    @NB502121:62:HYC3WAFXY:1:11101:10538:9036:TCTTGCGCCTCG 2:N:0:CCATTATCGA+CGGATAACCG:**no_adapter**

See above, the primer name was successfully added to the tail of read name of Read1, However, 'no_adapter' was added to the tail of read name of Read2 for there is no primer in Read2.  After the reads were aligned to reference, the result Bam file only contains first part of the read header such as '@NB502121:62:HYC3WAFXY:1:11101:10538:9036:TCTTGCGCCTCG ', that to say, primer information is not retained. Thus, I used the -x option instead and append the primer information as prefix of read name.  Unluckily, BWA complains that the read names of paired reads are not consistent with each other. 

## Hope
Thus, I hope the primer information could be added to the header of both read1 and read2, such as "@MyPrimer:NB502121:62:HYC3WAFXY:1:11101:10538:9036:TCTTGCGCCTCG 2:N:0:CCATTATCGA+CGGATAACCG". In addtion, it will be nicer if we could also choose to append primer name to the before part  ( before white space ) of read name.

Best Regards!

**Comment by marcelm** [comment]
Can you please check whether your suggestion is already covered by #437? Add a comment over there if not. I will close this issue to avoid duplicate issues.

**Comment by gudeqing** [comment]
@marcelm 
I am looking foward to your new version of this fantastic tool.
Here is my temp solution (-x option was used):

    import gzip
    import sys
    import os
    
    
    def sync_name(fq, fq2):
        """assign read id of fq to fq2"""
        if fq.endswith('.gz'):
            file = gzip.open
        else:
            file = open
        with file(fq) as fr, file(fq2) as fr2, file('__tmp.gz', 'w') as fw:
            for i, (line, line2) in enumerate(zip(fr, fr2), start=1):
                if i % 4 == 1:
                    fw.write(line.split()[0]+' '+line2.split(' ')[1])
                else:
                    fw.write(line2)
        os.rename('__tmp.gz', fq2)
    
    
    if __name__ == '__main__':
        args = sys.argv
        sync_name(args[1], args[2])

**Comment by marcelm** [comment]
I plan to make something like this possible with a syntax that may look like `--rename "{id}_{match1} {comment}"` (`id` is the read id, that is the part before the space, `match1` is the name of the adapter/primer that matched on R1, and `comment` is the part of the read name after the space). See #437 to see when that’s implemented.

**Comment by marcelm** [comment]
This has been implemented, see https://cutadapt.readthedocs.io/en/stable/guide.html#rename-renames-reads for how to use `--rename`.
