### ISSUE TITLE
Empty lines when using cutadapt for demultiplexing

### ISSUE THREAD

**Issue by cpavloud** [marcelm/cutadapt#474]
I was using cutadapt to demultiplex my reads (v1.12 with Python 3.5.3). 

Here is an example of the command I was using:
`cutadapt -g nnnncgctcttaTGGTGCATGGCCGTTCTTAGT -a GGTCTGTGATGCCCTTAGATGagcgttgtnn -G nnacaacgctCATCTAAGGGCATCACAGACC -A ACTAAGAACGGCCATGCACCAtaagagcgnnnn -o 18S_1.R1.fastq -p 18S_1.R2.fastq R1.fastq R2.fastq --untrimmed-output R1_untrimmed.fastq --untrimmed-paired-output R2_untrimmed.fastq
`
But somehow in some of the files that were created, new empty lines were added and therefore the number of lines in the produced fastq files were not multiple of 4.

Will updating to a newer version solve this issue?

**Comment by cpavloud** [comment]
I updated to cutadapt 2.10 with Python 3.7.6
and I run the command 
`
cutadapt --pair-adapters -g nnnncgctcttaTGGTGCATGGCCGTTCTTAGT -a GGTCTGTGATGCCCTTAGATGagcgttgtnn -G nnacaacgctCATCTAAGGGCATCACAGACC -A ACTAAGAACGGCCATGCACCAtaagagcgnnnn -o 18S_1.R1.fastq -p 18S_1.R2.fastq R1.fastq R2.fastq --untrimmed-output R1_untrimmed.fastq --untrimmed-paired-output R2_untrimmed.fastq
`

I think my files are ok this time.

**Comment by marcelm** [comment]
Great to hear it’s probably fixed now. Please do let me know if you see this problem in a new Cutadapt version.
