### ISSUE TITLE
Demultiplexing should always generate all possible output files

### ISSUE THREAD

**Issue by Grelot** [marcelm/cutadapt#478]
- Cutadapt 2.8 and Python 3.8
- installed with conda

run this command
```
cutadapt -m 20 --revcomp --no-indels --discard-untrimmed -g file:barcode.txt file.fastq -o {name}.fastq
```

It works fine but it seems that when an adapter is not detected on any reads, cutadapt don't produce a file. I wanted to know if it's the normal behaviour of cutadapt.

I will prefer that cutadapt generates an empty file in this case.

```
=== Adapter ../results/03_demultiplexing/01_demultiplexed/Other/teleo/SPY856 ===

Sequence: ACCGCATA...TATGCGGT; Type: linked; Length: 8+8; 5' trimmed: 0 times; 3' trimmed: 0 times
; Reverse-complemented: 0 times

```

**Comment by marcelm** [comment]
Hi, this is indeed the normal behavior at the moment. I agree that generating all output files no matter whether they contain any reads would be preferable.

**Comment by Grelot** [comment]
Thanks you for your answer. I just wanted to be sure. Yes it could be fine to have an option or something but it's not essential. In my case i have to generate myself the missing files because I use `cutadapt` into a workflow (using snakemake) and i need to know which sample have no reads (i don't want they simply disappear)
