### ISSUE TITLE
Trimming both reads when adapter is found in either pair-end

### ISSUE THREAD

**Issue by santiagorevale** [marcelm/cutadapt#479]
Hi there,

I was running the tool on pair-end and I've noticed that when the adapter is only found in one read it is only trimmed from it and not from both of them.

I'm looking for the standard Illumina Universal Adapter, which if it occurs, it does it in both reads at the same positions (because the same fragment is read from both ends at the same length). Usually, the adapter will be found and trimmed on both reads. However, when there are more mismatches than expected on one of the reads, then the read with the mismatches doesn't get trimmed. See the following example:

<pre>
Adapter looked for: AGATCGGAAGAG

@myread/1
GAAAGTCTTTCAAACAAGAANAGAAAGGAGGAATANTTGNNTACTACTGATNTATATCA<b>AGANCGGANNAG</b>CNNA
+
EEEEEEEEEEAEEEEEEEEE#EEEEEEEEEEEEEA#EE<##EEEEEEEEEE#/AEEEAEEAE#//A/##EA/##/

@myread/2
GCGTCGGTGTGATTATGTCTATGATTTCTCTTTTTGGGTTTCTCAGAGTCAACTAATAC<b>AGATCGGAAGAG</b>CGTC
+
EEEEAEAEEEEEEEAEEEAEEEEEEEEEEAEEAEEEEAEEEAAAAA&lt;AAEEAEAEEAAEEEEE&lt;AAEEE/EEAAA
</pre>

The adapter has been perfectly identified in Read 2 while in Read 1 has 3 mismatches. Thus, Read 2 will be trimmed and Read 1 will be left untouched. I believe there should be a scenario where both reads should be trimmed the same way when an adapter has been found. In this case, both reads should be trimmed from base 60 onwards:

```
@myread/1
GAAAGTCTTTCAAACAAGAANAGAAAGGAGGAATANTTGNNTACTACTGATNTATATCA
+
EEEEEEEEEEAEEEEEEEEE#EEEEEEEEEEEEEA#EE<##EEEEEEEEEE#/AEEEAE

@myread/2
GCGTCGGTGTGATTATGTCTATGATTTCTCTTTTTGGGTTTCTCAGAGTCAACTAATAC
+
EEEEAEAEEEEEEEAEEEAEEEEEEEEEEAEEAEEEEAEEEAAAAA<AAEEAEAEEAAE
```
Am I missing something and this is actually possible to achieve with _cutadapt_? I tried to run it in the following ways:

`cutadapt -a AGATCGGAAGAG -A AGATCGGAAGAG`
`cutadapt -a AGATCGGAAGAG -A AGATCGGAAGAG --pair-adapters`

but couldn't find an appropriate trimming option for what I was trying to achieve.

- Cutadapt v2.10 and Python v3.7.4

Thank you very much in advance.

**Comment by marcelm** [comment]
I’ve been wanting to implement this for a while, but I’ve worked on other features instead. This has been reported before in #332. I agree that the `--pair-adapters` option would be a natural place to look for this feature, but it does something else.

My suggested workaround is to increase the allowed error rate. You can go quite high without getting into problems due to chance matches. `-e 0.2` or even `-e 0.3` should be fine and would take care of many or perhaps most of these cases.

**Comment by santiagorevale** [comment]
Hi Marcel,

Thanks for your suggestions. I tried increasing `-e` up to `0.35` but it was actually removing unwanted stuff.

Regarding #332, I didn't properly get it until you point me to it. I'll have a look at `atropos` as well.

And thanks for your quick reply. Great tool as well!

Cheers!

**Comment by marcelm** [comment]
I’m closing this now in favor of #332.
