### ISSUE TITLE
Paired end with cutadapt

### ISSUE THREAD

**Issue by termithorbor** [marcelm/cutadapt#480]
Hi all,

is this the right code if I want to remove linked adapters e.g. 16S from both forward an reverse reads:

cutadapt -a ADAPTER1...ADAPTER2 -A ADAPTER3...ADAPTER4 -o out.1.fastq -p out.2.fastq reads.1.fastq reads.2.fastq

So is this code cutting primer 1 and 2 from forward reads (reads.1.fastq) and primer 3 and 4 from reverse reads (reads.2.fastq)?

Thank you very much in advance :)

**Comment by marcelm** [comment]
That should do it, yes. To make sure, try it out on a small FASTQ file with just a few reads to see whether it does what you want.
