### ISSUE TITLE
error message suggestion using file

### ISSUE THREAD

**Issue by Citteny** [marcelm/cutadapt#484]
Today I got this error and spent half an hour figuring it out.

`
cutadapt: error: Character '/' in adapter sequence '/ADAPTER/FILE/PATH/IN/CAPS/' is not a valid IUPAC code. Use only characters XACGTURYSWKMBDHVN.`

Eventually I saw that I forgot to write **"file:"** before that path.
Since all of the command is very long using full paths it took some time ^^"

You could add it to the error message to be something like that:
`
cutadapt: error: Character '/' in adapter sequence '/ADAPTER/FILE/PATH/IN/CAPS/' is not a valid IUPAC code. Use only characters XACGTURYSWKMBDHVN. If you are using a file, make sure to write "file:" before the path.
`

I hope you find this suggestion helpful.

Thank you so much for the amazing tool!

**Comment by marcelm** [comment]
Hi, thanks for the suggestion, this is a good idea!

I changed it to look like this (when writing `test.fa` instead of `file:test.fa`):
```
cutadapt: error: Character 'E' in adapter sequence 'TEST.FA' is not a valid IUPAC code.
Use only characters ABCDGHKMNRSTUVWXY.
A file exists named 'test.fa'. To use the sequences in that file as adapter sequences,
write 'file:' before the path, as in 'file:test.fa'.
```
