### ISSUE TITLE
pairs written is 0 when demultiplexing and discarding untrimmed

### ISSUE THREAD

**Issue by qifei9** [marcelm/cutadapt#487]
cutadapt 2.10 with Python 3.8.6

When demultiplexing paired-end reads and trimming adapter from both R1 and R2, and discarding untrimmed read pairs, the "Pairs written" in the report is always 0, although some reads do pass the filter and are outputted and demultiplexed correctly.

The command line is like:
```bash
cutadapt -g file:./adapter_5end_R1.fasta -G file:./adapter_5end_R2.fasta --discard-untrimmed -o test_d_{name}_1.fq -p test_d_{name}_2.fq tm.fq tm_p.fq >! test_d.txt
```

This also occurs when using `--pair-adapters`:

```bash
cutadapt -g file:./adapter_5end_R1.fasta -G file:./adapter_5end_R2.fasta --pair-adapters --discard-untrimmed -o test_dp_{name}_1.fq -p test_dp_{name}_2.fq tm.fq tm_p.fq >! test_dp.txt
```

However, when demultiplexing with combinatorial dual indexes, it reports the pairs written correctly

``` bash
cutadapt -g file:./adapter_5end_R1.fasta -G file:./adapter_5end_R2.fasta --discard-untrimmed -o test_dc_{name1}_{name2}_1.fq -p test_dc_{name1}_{name2}_2.fq tm.fq tm_p.fq >! test_dc.txt
```

**Comment by marcelm** [comment]
Thanks for the report. I think I have seen the same myself recently, but didn’t investigate closer. I’ll whether I can fix it.

**Comment by marcelm** [comment]
It turns out that the reported number was *always* zero when using the normal demultiplexer, whether using `--discard-untrimmed` or not. I’ve found the problem and fixed it. Thanks again!
