### ISSUE TITLE
when using --revcomp, allow to configure the addition of the " rc" string in the header

### ISSUE THREAD

**Issue by fjossandon** [marcelm/cutadapt#490]
Hello,
Using cutadapt 2.10 with Python 3.6.9, when using the `--revcomp` argument, the program appends an ` rc` string to identify the sequence on which the primers were found in the reverse complement. This is documented in the docs:
https://cutadapt.readthedocs.io/en/stable/guide.html#searching-reverse-complements
> The name of a reverse-complemented read is changed by adding a space and rc to it. (Please file an issue if you would like this to be configurable.)

So I would like to be the one that makes that request to add an option to control if the string is added or not. The reason is that I'm using custom files which I filled with some taxonomic information in the header, causing this extra string to be treated like a subspecies in my flow. The workaround is to open the output file just to remove the string, but it would be great if there were an option where the string is not added in the first place.

Best regards and thanks for such a great tool!

**Comment by marcelm** [comment]
Ok, I’ll keep this in mind. I think I can fix this as part of #437, where I try to come up with a way of general read name modifications.

Either you’d have to explicitly describe how you want your read header to look, for example using `--rename "{header}"` to force it not to be modified, or I’ll disable the current behavior and then people can get the `rc` added to the read name with `--rename "{header} {rc}"` (or something similar, this isn’t fully thought out).

**Comment by fjossandon** [comment]
For my case, my interest would go into not making any modifications at all to the header, because its already edited and they are all different, so a blanket rename would not work. To give more context, I'm generating theoretical amplicons using primer pairs from fasta reference sequences, which why I dont want editions in the header that contains the taxonomy. =)

**Comment by fjossandon** [comment]
Oh, I think maybe I did not understand you correctly, so you mean that using `"{heder}"` would preserve the original one intact?? but then maybe the `--rename` argument should be optional in case you want to make such an edition?? or it would be as a way to counter the current edition that `--revcomp` makes??

**Comment by marcelm** [comment]
I understand. The `--rename "{header}"` option would be a way to force "renaming" to the existing name, so effectively not renaming at all.

**Comment by marcelm** [comment]
I have to consider whether I want to preserve backwards compatibility. If I do, then using `--revcomp` would then effectively (without specifying it explicitly) set `--rename "{header} {rc}"`, where the `{header}` is the existing, unchanged read header, and the `{rc}` thing is set to `rc` if the read was reverse complemented (and is an empty string otherwise). Then, to counter that, as you said correctly, one would need to specify `--rename "{header}"` in order *not* to get the extra `rc`.

It’s a bit convoluted, but I also don’t want to add yet another option like `--no-add-rc-to-read-header` (or similar) because there are already many options.

But maybe it makes more sense to just don’t do any renaming at all by default. This would be backwards incompatible, though, so I need to judge whether it’s worth it.

**Comment by marcelm** [comment]
And for completeness, you can use this command to remove the extra ` rc` from a FASTQ file:
```
zcat withrc.fastq.gz | sed '1~4s/ rc$//' | pigz > withoutrc.fastq.gz
```
(Interpretation of the `sed` command: Starting from line 1, and then on every fourth line, replace ` rc` at the end of the line with an empty string.)

**Comment by fjossandon** [comment]
Alright, I will make a workaround until Cutadapt offers a way to do it. Thanks for the command!

**Comment by fjossandon** [comment]
Hello again!
Today I was reading again the documentation and found that you have implemented in version 3.2 that "--rename" option you mentioned before (https://cutadapt.readthedocs.io/en/stable/guide.html#rename-renames-reads), so I was eager to test it... 
```
>example description 1
GTGCCAGCAGCCGCGGTAAACCTGCGGAAGGATCAAGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACAAACTTTCAACAACGGATCTC
>example_reverse_complement description 2
GAGATCCGTTGTTGAAAGTTTGTGAAACCATCGGAGCCAAACAGTTGAGTCAGAACCAGCCTTCATGGGGTTGTCGGAATCTGGATTTAGAACTGTACTCCCTAGCCTCGCGGGCACAGCCTCGTATCCATCTATCAGGAGAACCAGCGTTCCACAGTACCTCTTGATCCTTCCGCAGGTTTACCGCGGCTGCTGGCAC
```
First the regular command without rename to confirm the default behaviour: `cutadapt -a 'ACCTGCGGARGGATCA;min_overlap=15;max_error_rate=0.3...AACTTTYARCAAYGGATCTC;min_overlap=20;max_error_rate=0.3' --times 1 --max-n 5 --revcomp --trimmed-only --cores 0 --output example_trim.fasta example.fasta`
generates:
```
>example description 1
AGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACA
>example_reverse_complement description 2 rc
AGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACA
```
Now using the new rename option using {header}, hoping to avoid the "rc" addition: `cutadapt -a 'ACCTGCGGARGGATCA;min_overlap=15;max_error_rate=0.3...AACTTTYARCAAYGGATCTC;min_overlap=20;max_error_rate=0.3' --times 1 --max-n 5 --revcomp --trimmed-only --cores 0 --rename='{header}' --output example_trim.fasta example.fasta`
generates:
```
>example description 1
AGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACA
>example_reverse_complement description 2 rc
AGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACA
```
So the "rc" still shows up... It appears that "revcomp" is overriding my "rename", by somehow including the "rc" into the {comment} portion of the {header} before the rename applies. If I use `rename='{id} prefix {comment} suffix'` for example, I get:
```
>example_reverse_complement prefix description 2 rc suffix
```
Which confirms that {comment} is not the original value, so I effectively can't get rid of the "rc" part.

**Comment by marcelm** [comment]
Sorry about that, yes, I know that this still does not work (which is why this issue is still open). I didn’t have more time to work on it and just wanted to get the `--rename` option released, which is why 3.2 still adds the `rc`.

**Comment by marcelm** [comment]
The development version will now no longer add the "rc" when `--rename` is used. So that should solve the problem for you.

However, before I release that version, I will also need to add an `{rc}` template or similar that can be used with `--rename` for those people that do want to have the suffix. I’ll wait with closing this issue until I have done so.

**Comment by fjossandon** [comment]
Awesome! I just tested the development version and it works perfectly: `example_reverse_complement prefix description 2 suffix` =)
Thanks for your hard work!

**Comment by marcelm** [comment]
I’ve added the `{rc}` template variable now
