### ISSUE TITLE
Use of `--cores > 1` with gzipped output leads to corrupted results

### ISSUE THREAD

**Issue by vmikk** [marcelm/cutadapt#493]
Hello!

I'm trying to demultiplex PacBio data and noticed a strange behaviour.
Usage of multiple threads (`--cores 2`) with gzipped output produces corrupted results.
Example command:
```
mkdir -p demux2

cutadapt  \
  -e 1 --no-indels  --revcomp \
  -a file:barcodes.fasta \
  -g file:barcodes.fasta \
  --cores 2 \
  -o demux2/{name}.fq.gz   s1.fastq.gz  > demux2/log

zless demux2/unknown.fq.gz
```
The output that cutadapt produces looks corrupted:
![zless](https://user-images.githubusercontent.com/7162120/98974505-a48e4a80-251d-11eb-85aa-a8217260f050.png)

This command (differs only in the number of cores) works fine:
```
mkdir -p demux1

cutadapt  \
  -e 1 --no-indels  --revcomp \
  -a file:barcodes.fasta \
  -g file:barcodes.fasta \
  --cores 1 \
  -o demux1/{name}.fq.gz   s1.fastq.gz  > demux1/log

zless demux1/unknown.fq.gz
```
![zless2](https://user-images.githubusercontent.com/7162120/98975261-8ffe8200-251e-11eb-8345-40fdcd8362b1.png)

Please find the example data in the attachment.
This is PacBio data. Barcodes are not anchored and should be present on both ends of the reads (the same barcode on both sides).

* Cutadapt v.3.0 and Python v.3.7.9 (installed via conda) 

Thank you for your time and efforts, cutadapt is great software!
With kind regards,
Vladimir

[s1.fastq.gz](https://github.com/marcelm/cutadapt/files/5532229/s1.fastq.gz)
[barcodes.fasta.gz](https://github.com/marcelm/cutadapt/files/5532234/barcodes.fasta.gz)
PS. sorry, GitHub does not allow to attach FASTA, I gzipped it.

**Comment by marcelm** [comment]
Hi, thanks a lot for the report. I can confirm that I see the same problem as well. It appears to occur only beyond a certain number of barcodes, which is why I probably missed this in my tests.

I’ll look into this soon.

**Comment by marcelm** [comment]
I believe I fixed this problem (it was in xopen, which is used by cutadapt), but I want to reply in more detail. Let me re-open the issue until I have time for that.

**Comment by marcelm** [comment]
The thing I wanted to mention: It is possible the command you are using will not work the way you want it. Cutadapt by default only trims (at most) a single adapter from each read. So your command would trim one of the barcodes, but ignore the other (which one depends on which occurrence has fewer errors). Perhaps you should try using [linked adapters](https://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters-combined-5-and-3-adapter) instead. So in the `barcodes.fasta`, you would write
```
>s543
ACCGGAGTAGGA...ACCGGAGTAGGA
```
and so on and then either use `-a file:barcodes.fasta` or `-g file:barcodes.fasta` (but not both), depending on whether the barcodes are required or not (see the docs for that).

Demultiplexing this many non-anchored adapters is quite slow currently, but using linked adapters will improve speed somewhat, in case that is relevant.

**Comment by vmikk** [comment]
Thank you so much for the detailed response (I didn't know that it's possible to specify linked adapters in `barcodes.fasta`) and for the fix to `xopen`.
