### ISSUE TITLE
deprecated --format/-f flag removed which causes cutadapt to fail

### ISSUE THREAD

**Issue by sconlan** [marcelm/cutadapt#497]
This is not a bug so much as a note for others, that cutadapt 3.0 has completely removed the --format/-f flag which was deprecated (issue #359). It will now fail as below instead of producing output. I had cutadapt buried in a pipeline and this took a bit to sort out. This isn't documented in the change log.

```
	20:43 cn0863 test$ cutadapt -a CTGTCTCTTATACACATCTGACGCTGCCGACGA -a CTGTCTCTTATACACATCTCCGAGCCCACGAGAC -q 20 -e 0.15 -m 50 -f fastq foo2gn4 > tmp
	This is cutadapt 3.0 with Python 3.8.5
	Command line parameters: -a CTGTCTCTTATACACATCTGACGCTGCCGACGA -a CTGTCTCTTATACACATCTCCGAGCCCACGAGAC -q 20 -e 0.15 -m 50 -f fastq foo2gn4
	Run "cutadapt --help" to see command-line options.
	See https://cutadapt.readthedocs.io/ for full documentation.

	cutadapt: error: unrecognized arguments: -f
```

**Comment by marcelm** [comment]
Thanks, good point! I’ve modified the changelog to include this information, and also added it to the changelog for the upcoming version 3.1 so people will read it who no longer look at the 3.0 changelog.

I considered adding the option back and make it print a more useful error message, but `--format`/`-f` has been deprecated for 1.5 years already, and I would like to move forward. I think this issue will be easy enough to find if people see the above error message.
