### ISSUE TITLE
Feature request: option to include {times} in the read header

### ISSUE THREAD

**Issue by billytcl** [marcelm/cutadapt#498]
I couldn't find this in the docs, but I think it would be really useful to have a {times} tag as an optional read header modification, especially for concatenated reads or for multiple adapters that are found. Is this possible?

**Comment by marcelm** [comment]
Interesting idea. Can you please also add a comment over at #437? Do I understand correctly that this would be the number of adapter matches found in a read?

**Comment by billytcl** [comment]
Actually, now that I read the documentation more clearly for some examples,
I think I have misunderstood what the "times" option actually does for
concatenated reads!

Suppose I have a concatenated sequence Ad1 -- Seq1 -- Ad2 -- Ad1 -- Seq2 --
Ad2 etc, and used -g "adapter=Ad1...Ad2" for a linked adapter, then in the
info file I was hoping it would do something like outputting the Seq1 on
every second line (eg. adapter;2) in the info file. and subsequently spit
out Seq1 and Seq2 into the fastq.

Billy

**Comment by marcelm** [comment]
Yeah, that won’t work directly.

You could let Cutadapt search only for the 5' adapter repeatedly (i.e., using `--times`/`-n`). That would give you multiple rows in the info file, telling you the start coordinates of the matches. Assuming you have `AAAAA` as 5' adapter and `GGGGG` as 3' adapter:
```bash
$ echo -e '>r\nAAAAAgattacaGGGGGcccccAAAAAacattagGGGGG' | \
  cutadapt --quiet -n 2 --info info.txt -g AAAAA -
>r
acattagGGGGG
$ cat info.txt | column -nt
r  0  0   5                      AAAAA  gattacaGGGGGcccccAAAAAacattagGGGGG  1      
r  0  17  22  gattacaGGGGGccccc  AAAAA  acattagGGGGG                        1
```
Then you’d need your own script to extract `gattacaGGGGGccccc` and `acattagGGGGG` and write them to FASTA/FASTQ (some thought required to extract the correct sequence if `--times` is greater than 2), and then you could run Cutadapt a second time to remove the 3' adapters. Not sure whether this is an option for you, but that’s what I can come up with at the moment.

**Comment by billytcl** [comment]
Could I use a linked adapter, -g "Ad1...Ad2" without times, and then
extract the sequence outside of the match into a new fastq, and just run it
a second time/repeat until no more matches?

**Comment by marcelm** [comment]
That should work as well I believe. You may want to set a minimum overlap so that you don’t get partial matches.
