### ISSUE TITLE
Crashes on multicore when conducting "Demultiplexing paired-end reads with combinatorial dual indexes"

### ISSUE THREAD

**Issue by MNM-TB** [marcelm/cutadapt#499]
Thank you for a fantastic tool. It has become essential in my toolbox. I have however run into an issue. The multicore support is a key component for us as we are using it on 1 billion+ reads, the 64 core servers are needed. In most cases, it is working perfectly.

However, I fail to use it In the "Demultiplexing paired-end reads with combinatorial dual indexes" approach

A single threaded run works as expected i.e:

```
cutadapt \
    -j 1 -e 0.15 --no-indels \
    -g file:barcodes_fwd.fasta \
    -G file:barcodes_rev.fasta \
    -o {name1}-{name2}.1.fastq.gz -p {name1}-{name2}.2.fastq.gz \
    input.1.fastq.gz input.2.fastq.gz
```

However as soon as I add a second core i.e., `-j 2` it crashes with the error:

```
ERROR: Traceback (most recent call last):
  File "/opt/anaconda/anaconda3/envs/nbdev/lib/python3.6/site-packages/cutadapt/pipeline.py", line 646, in run
    (n, bp1, bp2) = self._pipeline.process_reads()
  File "/opt/anaconda/anaconda3/envs/nbdev/lib/python3.6/site-packages/cutadapt/pipeline.py", line 456, in process_reads
    if filter_(read1, read2, info1, info2):
  File "/opt/anaconda/anaconda3/envs/nbdev/lib/python3.6/site-packages/cutadapt/filters.py", line 116, in __call__
    self.writer.write(read1, read2)
  File "/home/lcadmin/.local/lib/python3.6/site-packages/dnaio/__init__.py", line 368, in write
    self._writer.write(read1)
  File "/home/lcadmin/.local/lib/python3.6/site-packages/dnaio/writers.py", line 102, in _write
    self._file.write(record.fastq_bytes())
AttributeError: 'NoneType' object has no attribute 'write'
```
I run version 3.1 under python 3.6.10 installed in a conda environment

Thank you again

/Tomas

**Comment by marcelm** [comment]
Hi, thanks for the report. I hope to have time to look into this tomorrow. In the meantime, can you let me know which version of the `dnaio` package you have installed? (`conda list dnaio`)

**Comment by qifei9** [comment]
same issue here. I have cutadapt 3.1, python 3.8 and dnaio 0.4.4

**Comment by marcelm** [comment]
Thanks again, this should be fixed now.

This escaped me because I had forgotten to change the automated tests so that they cover combinatorial demultiplexing.

**Comment by Yyeserin** [comment]
Hi,

I face the same issue, and I did not understand the solution here. My code works well for single core, but it crashes in multicore with the error. I have to use multicore, and other demultiplexing alternatives are bit as flexible as cutadapt. So, I have to have it run.  I run cutadapt on a cluster. The software is already in their list. Please see the error not:

__This is cutadapt 3.1 with Python 3.7.2

_Command line parameters: --action trim -m 40 --no-indels --trim-n -j 0 -e 0.16 -g file:i7_barcodes.fasta -G file:i5_barcodes.fasta -o output/round1-{name1}-{name2}.1.fastq.gz -p output/round1-{name1}-{name2}.2.fastq.gz inpput_R1.fastq.gz input_R2.fastq.gz

Processing reads on 2 cores in paired-end mode ...
ERROR: Traceback (most recent call last):
  File "/sw/bioinfo/cutadapt/3.1/rackham/venv/lib/python3.7/site-packages/cutadapt/pipeline.py", line 646, in run
    (n, bp1, bp2) = self._pipeline.process_reads()
  File "/sw/bioinfo/cutadapt/3.1/rackham/venv/lib/python3.7/site-packages/cutadapt/pipeline.py", line 456, in process_reads
    if filter_(read1, read2, info1, info2):
  File "/sw/bioinfo/cutadapt/3.1/rackham/venv/lib/python3.7/site-packages/cutadapt/filters.py", line 116, in __call__
    self.writer.write(read1, read2)
  File "/sw/bioinfo/cutadapt/3.1/rackham/venv/lib/python3.7/site-packages/dnaio/__init__.py", line 368, in write
    self._writer.write(read1)
  File "/sw/bioinfo/cutadapt/3.1/rackham/venv/lib/python3.7/site-packages/dnaio/writers.py", line 102, in _write
    self._file.write(record.fastq_bytes())
AttributeError: 'NoneType' object has no attribute 'write'___


I cannot modify the .py file in the cluster system. I am trying to install it to my home directory. However cutadapt package doesn't exist. Please see the error note below. What am I supposed to do? I will appreciate your advice.

(base) [yeserin@rackham3 myenv_conda]$ conda create -n cutadaptenv cutadapt

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cutadapt

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by Yyeserin** [comment]
> --action trim -m 40 --no-indels --trim-n -j 0 -e 0.16 -g file:i7_barcodes.fasta -G file:i5_barcodes.fasta -o output/round1-{name1}-{name2}.1.fastq.gz -p output/round1-{name1}-{name2}.2.fastq.gz inpput_R1.fastq.gz input_R2.fastq.gz

I could install the newest cutadapt version with pip installation. Now the software works fine.

**Comment by marcelm** [comment]
Great! I was just about to comment: To install packages from Bioconda, you need to run the three commands [shown in the Bioconda installation instructions](http://bioconda.github.io/user/install.html#set-up-channels). Perhaps helpful for other software.

**Comment by marcelm** [comment]
Oh, I see you are on rackham. I’ll ask support to upgrade the installed Cutadapt version.

**Comment by marcelm** [comment]
Regarding conda: If you are on rackham, you should not install Conda yourself, but use `module load conda`. Then everything is preconfigured (including Bioconda) and you save space in your home directory.

**Comment by Yyeserin** [comment]
> Regarding conda: If you are on rackham, you should not install Conda yourself, but use `module load conda`. Then everything is preconfigured (including Bioconda) and you save space in your home directory.

Ah Ok. Thank you for the tip.

**Comment by marcelm** [comment]
Support was very quick and has already installed Cutadapt 4.0 on the UPPMAX clusters.
