### ISSUE TITLE
error rate and trimmed bases

### ISSUE THREAD

**Issue by wangjiawen2013** [marcelm/cutadapt#502]
Hi,
I used cutadapt (version 2.10) to remove adaptors from my fastq file using this command:
cutadapt -g **_CGAAACACCG_** --discard-untrimmed -o A_trimmed.fastq A.fastq
the default error rate was 0.1, allowing one mismatched base. Then I find that cutadptor only remove nine bases for some reads,such as:
@A00262:572:HM3KKDSXY:3:1101:8142:1595 1:N:0:ATCACGAT+AGATCTC
CTTGTGGAAAGGA **_CGAAACACCA_** CGCCTTCTCCTCACTCGCCGGTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGAAAAAGTTGCACCGAGTCGGTGCTTTTTTGAATTCGCTAGCTAGGTCTTGAAAG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFF:FFFFFFFF::FF:FFF
Because the default error rate was 0.1, so the adaptor sequence **_CGAAACACCG_** can match the target sequence **_CGAAACACCA_** in the above fastq. I intended to remove ten bases (**_CGAAACACCA_**), because this is essentially the adaptor sequence. However, cutadptor only remove exactly matched seqeunce (only nine bases, **_CGAAACACC_**, leaving the extra "A" base in the trimmed fastq).

**Comment by wangjiawen2013** [comment]
The one base difference was more likely caused by senquencing error, so it's reasonable to trim the whole sequence.

**Comment by marcelm** [comment]
This particular problem has been reported recently in #485 and was fixed in Cutadapt 3.0, released not too long ago. See also the [changelog](https://cutadapt.readthedocs.io/en/latest/changes.html#v3-0-2020-11-10).

Using Cutadapt 3.1, there is no more extra `A` in the trimmed sequence.
