### ISSUE TITLE
Trying to install an old version

### ISSUE THREAD

**Issue by aureliendejode** [marcelm/cutadapt#506]
Hello,

I am trying to install an old version of cutadapt to have the same pipeline on different datasets. One I analyzed a while ago...
I am trying to install cutadapt 1.16.

I used the following command:
pip install cutadapt==1.16

I get the following error:

Collecting cutadapt==1.16
  Using cached cutadapt-1.16.tar.gz (320 kB)
Requirement already satisfied: xopen>=0.3.2 in /home/aurelien/.local/lib/python3.7/site-packages (from cutadapt==1.16) (1.0.1)
Building wheels for collected packages: cutadapt
  Building wheel for cutadapt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/aurelien/.local/bin/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n7zqtv8g/cutadapt_0536bfca637342fd8b70c25e9169ea90/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n7zqtv8g/cutadapt_0536bfca637342fd8b70c25e9169ea90/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-c6lggt22
       cwd: /tmp/pip-install-n7zqtv8g/cutadapt_0536bfca637342fd8b70c25e9169ea90/
  Complete output (59 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/align.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/filters.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/qualtrim.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/__main__.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/__init__.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/pipeline.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/compat.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/modifiers.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/seqio.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/colorspace.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/report.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/adapters.py -> build/lib.linux-x86_64-3.7/cutadapt
  copying src/cutadapt/_version.py -> build/lib.linux-x86_64-3.7/cutadapt
  UPDATING build/lib.linux-x86_64-3.7/cutadapt/_version.py
  set build/lib.linux-x86_64-3.7/cutadapt/_version.py to '1.16'
  running build_ext
  building 'cutadapt._align' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  creating build/temp.linux-x86_64-3.7/src/cutadapt
  gcc -pthread -B /home/aurelien/.local/bin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/aurelien/.local/bin/anaconda3/include/python3.7m -c src/cutadapt/_align.c -o build/temp.linux-x86_64-3.7/src/cutadapt/_align.o
  gcc -pthread -shared -B /home/aurelien/.local/bin/anaconda3/compiler_compat -L/home/aurelien/.local/bin/anaconda3/lib -Wl,-rpath=/home/aurelien/.local/bin/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/cutadapt/_align.o -o build/lib.linux-x86_64-3.7/cutadapt/_align.cpython-37m-x86_64-linux-gnu.so
  building 'cutadapt._qualtrim' extension
  gcc -pthread -B /home/aurelien/.local/bin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/aurelien/.local/bin/anaconda3/include/python3.7m -c src/cutadapt/_qualtrim.c -o build/temp.linux-x86_64-3.7/src/cutadapt/_qualtrim.o
  gcc -pthread -shared -B /home/aurelien/.local/bin/anaconda3/compiler_compat -L/home/aurelien/.local/bin/anaconda3/lib -Wl,-rpath=/home/aurelien/.local/bin/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/cutadapt/_qualtrim.o -o build/lib.linux-x86_64-3.7/cutadapt/_qualtrim.cpython-37m-x86_64-linux-gnu.so
  building 'cutadapt._seqio' extension
  gcc -pthread -B /home/aurelien/.local/bin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/aurelien/.local/bin/anaconda3/include/python3.7m -c src/cutadapt/_seqio.c -o build/temp.linux-x86_64-3.7/src/cutadapt/_seqio.o
  src/cutadapt/_seqio.c: In function ‘__Pyx__ExceptionSwap’:
  src/cutadapt/_seqio.c:9589:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
   9589 |     tmp_type = tstate->exc_type;
        |                        ^~~~~~~~
        |                        curexc_type
  src/cutadapt/_seqio.c:9590:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
   9590 |     tmp_value = tstate->exc_value;
        |                         ^~~~~~~~~
        |                         curexc_value
  src/cutadapt/_seqio.c:9591:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
   9591 |     tmp_tb = tstate->exc_traceback;
        |                      ^~~~~~~~~~~~~
        |                      curexc_traceback
  src/cutadapt/_seqio.c:9592:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
   9592 |     tstate->exc_type = *type;
        |             ^~~~~~~~
        |             curexc_type
  src/cutadapt/_seqio.c:9593:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
   9593 |     tstate->exc_value = *value;
        |             ^~~~~~~~~
        |             curexc_value
  src/cutadapt/_seqio.c:9594:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
   9594 |     tstate->exc_traceback = *tb;
        |             ^~~~~~~~~~~~~
        |             curexc_traceback
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cutadapt
  Running setup.py clean for cutadapt
Failed to build cutadapt
Installing collected packages: cutadapt
  Attempting uninstall: cutadapt
    Found existing installation: cutadapt 1.17
    Uninstalling cutadapt-1.17:
      Successfully uninstalled cutadapt-1.17
    Running setup.py install for cutadapt ... error
    ERROR: Command errored out with exit status 1:
     command: /home/aurelien/.local/bin/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n7zqtv8g/cutadapt_0536bfca637342fd8b70c25e9169ea90/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n7zqtv8g/cutadapt_0536bfca637342fd8b70c25e9169ea90/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-a6241g8u/install-record.txt --single-version-externally-managed --compile --install-headers /home/aurelien/.local/bin/anaconda3/include/python3.7m/cutadapt
         cwd: /tmp/pip-install-n7zqtv8g/cutadapt_0536bfca637342fd8b70c25e9169ea90/
    Complete output (59 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/align.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/filters.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/qualtrim.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/__main__.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/__init__.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/pipeline.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/compat.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/modifiers.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/seqio.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/colorspace.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/report.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/adapters.py -> build/lib.linux-x86_64-3.7/cutadapt
    copying src/cutadapt/_version.py -> build/lib.linux-x86_64-3.7/cutadapt
    UPDATING build/lib.linux-x86_64-3.7/cutadapt/_version.py
    set build/lib.linux-x86_64-3.7/cutadapt/_version.py to '1.16'
    running build_ext
    building 'cutadapt._align' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    creating build/temp.linux-x86_64-3.7/src/cutadapt
    gcc -pthread -B /home/aurelien/.local/bin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/aurelien/.local/bin/anaconda3/include/python3.7m -c src/cutadapt/_align.c -o build/temp.linux-x86_64-3.7/src/cutadapt/_align.o
    gcc -pthread -shared -B /home/aurelien/.local/bin/anaconda3/compiler_compat -L/home/aurelien/.local/bin/anaconda3/lib -Wl,-rpath=/home/aurelien/.local/bin/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/cutadapt/_align.o -o build/lib.linux-x86_64-3.7/cutadapt/_align.cpython-37m-x86_64-linux-gnu.so
    building 'cutadapt._qualtrim' extension
    gcc -pthread -B /home/aurelien/.local/bin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/aurelien/.local/bin/anaconda3/include/python3.7m -c src/cutadapt/_qualtrim.c -o build/temp.linux-x86_64-3.7/src/cutadapt/_qualtrim.o
    gcc -pthread -shared -B /home/aurelien/.local/bin/anaconda3/compiler_compat -L/home/aurelien/.local/bin/anaconda3/lib -Wl,-rpath=/home/aurelien/.local/bin/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/cutadapt/_qualtrim.o -o build/lib.linux-x86_64-3.7/cutadapt/_qualtrim.cpython-37m-x86_64-linux-gnu.so
    building 'cutadapt._seqio' extension
    gcc -pthread -B /home/aurelien/.local/bin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/aurelien/.local/bin/anaconda3/include/python3.7m -c src/cutadapt/_seqio.c -o build/temp.linux-x86_64-3.7/src/cutadapt/_seqio.o
    src/cutadapt/_seqio.c: In function ‘__Pyx__ExceptionSwap’:
    src/cutadapt/_seqio.c:9589:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     9589 |     tmp_type = tstate->exc_type;
          |                        ^~~~~~~~
          |                        curexc_type
    src/cutadapt/_seqio.c:9590:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     9590 |     tmp_value = tstate->exc_value;
          |                         ^~~~~~~~~
          |                         curexc_value
    src/cutadapt/_seqio.c:9591:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     9591 |     tmp_tb = tstate->exc_traceback;
          |                      ^~~~~~~~~~~~~
          |                      curexc_traceback
    src/cutadapt/_seqio.c:9592:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     9592 |     tstate->exc_type = *type;
          |             ^~~~~~~~
          |             curexc_type
    src/cutadapt/_seqio.c:9593:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     9593 |     tstate->exc_value = *value;
          |             ^~~~~~~~~
          |             curexc_value
    src/cutadapt/_seqio.c:9594:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     9594 |     tstate->exc_traceback = *tb;
          |             ^~~~~~~~~~~~~
          |             curexc_traceback
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of cutadapt
  Moving to /home/aurelien/.local/bin/cutadapt
   from /tmp/pip-uninstall-v6wtehbl/cutadapt
  Moving to /home/aurelien/.local/lib/python3.7/site-packages/cutadapt-1.17.dist-info/
   from /home/aurelien/.local/lib/python3.7/site-packages/~utadapt-1.17.dist-info
  Moving to /home/aurelien/.local/lib/python3.7/site-packages/cutadapt/
   from /home/aurelien/.local/lib/python3.7/site-packages/~utadapt
ERROR: Command errored out with exit status 1: /home/aurelien/.local/bin/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n7zqtv8g/cutadapt_0536bfca637342fd8b70c25e9169ea90/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n7zqtv8g/cutadapt_0536bfca637342fd8b70c25e9169ea90/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-a6241g8u/install-record.txt --single-version-externally-managed --compile --install-headers /home/aurelien/.local/bin/anaconda3/include/python3.7m/cutadapt Check the logs for full command output.

Python version is 3.7.6

The installation works for version 1.17 with the following command line: pip install cutadapt==1.17. If there is no major change between those two versions I think I could just go with version 1.17.

Let me know what you think.

Thank you

**Comment by marcelm** [comment]
Looking at [the changelog for version 1.17](https://cutadapt.readthedocs.io/en/stable/changes.html#v1-17-2018-08-20), you’ll see that Cutadapt 1.16 was not installable under Python 3.7. So you need to use Python 3.6 to get it to work or just use version 1.17. I am 99% sure that the results will be identical between 1.16 and 1.17 because I try very hard to not make any backwards incompatible changes as long as the major version number does not change.
