### ISSUE TITLE
Removing two internal adapters

### ISSUE THREAD

**Issue by curtisd0886** [marcelm/cutadapt#507]
Hello is it possible to remove two adapters only while keeping everything else (on either side and in between the two adapters)? I have 3 barcodes separated by two constant sequences and I would like to remove the constant sequences while retaining the three barcodes. I have included an example below. 

Before:
GTBBBBBBCGACTCACTACAGGGBBBBBBTCGGTGACACGATCGBBBBBBNNNNNN
After:
GTBBBBBBBBBBBBBBBBBBNNNNNN

**Comment by marcelm** [comment]
This isn’t currently possible, no.

Perhaps you could hack something together using linked adapters and the `--info-file`. Not sure whether that is something within your comfort zone, but here are a couple of commands that could be a starting point:
```
$ cat in.fasta
>seq
GTBBBBBBCGACTCACTACAGGGHHHHHHHTCGGTGACACGATCGYYYYYYYNNNNNN
$ cutadapt --info-file info.txt -g CGACTCACTACAGGG...TCGGTGACACGATCG in.fasta
$ cat info.txt 
seq     0       8       23      GTBBBBBB        CGACTCACTACAGGG HHHHHHHTCGGTGACACGATCGYYYYYYYNNNNNN     3;1
seq     0       7       22      HHHHHHH TCGGTGACACGATCG YYYYYYYNNNNNN   3;2
$ awk -F "\t" '$8 ~ /;1/ { before=$5 } $8 ~ /;2/ { printf(">%s\n%s%s%s\n", $1, before, $5, $7) }' info.txt > barcodesonly.fasta
$ cat barcodesonly.fasta
>seq
GTBBBBBBHHHHHHHYYYYYYYNNNNNN
```
The info file doesn’t contain qualities, so this only gives you FASTA format, though. Re-adding qualities would need some more scripting.

Cutadapt assumes in many places in the code that sequences are never re-joined after having been cut, so it may be hard to add such a feature to the program. I can think about this when I have some time, though.

**Comment by curtisd0886** [comment]
This is great! I was able to get it to work as a Fasta, but the tool I need to use requires a fastq. Any ideas how to re add the qualities as well? Thanks again for your help.

**Comment by marcelm** [comment]
I forgot that the info file actually contains quality values as well. Here’s how to get FASTQ:
```
$ cat in.fastq
@seq
GTBBBBBBCGACTCACTACAGGGHHHHHHHTCGGTGACACGATCGYYYYYYYNNNNNN
+
IHIHIHIH#I#I#I#I#I#I#I#HHHHHHHABABABABABABABACDCDCDCDCDCDC
$ cutadapt --info-file info.txt -o /dev/null -g CGACTCACTACAGGG...TCGGTGACACGATCG in.fastq
$ awk -F "\t" '$8 ~ /;1/ { beforeseq=$5; beforequal=$9 } $8 ~ /;2/ { printf("@%s\n%s%s%s\n+\n%s%s%s\n", $1, beforeseq, $5, $7, beforequal, $9, $11) }' info.txt > out.fastq
$ cat out.fastq
@seq
GTBBBBBBHHHHHHHYYYYYYYNNNNNN
+
IHIHIHIHHHHHHHHCDCDCDCDCDCDC
```

**Comment by marcelm** [comment]
I’ll close this now – please feel free to comment or re-open if you have more questions.

**Comment by wu99271053** [comment]
Hi! i have a similar situation and i am wondering have this been enabled in newer version? my situation is simpler that i got ATGCADAPTORATGC i want to kept ATGCATGC. If not, perhaps i could first do the 5' trimming, and do the 3' trimming again and combine the result?

**Comment by marcelm** [comment]
No, sorry, this isn’t implemented and probably won’t.

If this is single-end data, maybe one trick is to pass the same input file twice (that is, pretend that the data is paired-end where R1 and R2 are identical), then let Cutadapt do some type of trimming for R1 and some other for R2 and let it output paired-end reads. Then you combine the R1 and R2 output files to get the final result. Let me know if you need help with an appropriate command-line invocation.

**Comment by wu99271053** [comment]
> No, sorry, this isn’t implemented and probably won’t.
> 
> If this is single-end data, maybe one trick is to pass the same input file twice (that is, pretend that the data is paired-end where R1 and R2 are identical), then let Cutadapt do some type of trimming for R1 and some other for R2 and let it output paired-end reads. Then you combine the R1 and R2 output files to get the final result. Let me know if you need help with an appropriate command-line invocation.

Thank you for your help! i eventually pair-end trimmed it twice, one on 5' one on 3'. and use seqkit to concat them.
