### ISSUE TITLE
Removing -g adaptor is successful but when trimming with -g and -a the -g adaptor fails

### ISSUE THREAD

**Issue by fjossandon** [marcelm/cutadapt#508]
Cutadapt version 3.2, installed throgh pip3.

I recently have been trying to generate a sequence without the 5' and 3' adaptors using "-g" and "-a". Although both adaptors where clearly there, only the "-a" adaptor was being removed, while the "-g" one was reported as not found. After many tests, I tried specifying only the -g adaptor and it worked!!! Note that I don't wanted to use the "linked" option ("...") to solve this, because this is a single but important case among others where 1 of the adaptors may be missing, and I dont know in advance which sequences will have both to trim and which will only have one to trim.

This is the example sequence:
```
>example
GTGCCAGCAGCCGCGGTAAACCTGCGGAAGGATCAAGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACAAACTTTCAACAACGGATCTC
```
The 5' adaptor in this sequence is located in the 20th position, while the 3' adaptor is at the very end.

Here is the command I'm using to remove both:
`cutadapt -g 'ACCTGCGGARGGATCA;min_overlap=16;max_error_rate=0.3' -a 'AACTTTYARCAAYGGATCTC;min_overlap=20;max_error_rate=0.3' --times 1 --max-n 5 --revcomp --trimmed-only --cores 4 --output example_trim_both.fasta example.fasta`
And only trims 3':
```
=== Adapter 1 ===

Sequence: ACCTGCGGARGGATCA; Type: regular 5'; Length: 16; Trimmed: 0 times; Reverse-complemented: 0 times

=== Adapter 2 ===

Sequence: AACTTTYARCAAYGGATCTC; Type: regular 3'; Length: 20; Trimmed: 1 times; Reverse-complemented: 0 times

No. of allowed errors:
1-2 bp: 0; 3-5 bp: 1; 6-9 bp: 2; 10-12 bp: 3; 13-15 bp: 4; 16-19 bp: 5; 20 bp: 6

Bases preceding removed adapters:
  A: 100.0%
  C: 0.0%
  G: 0.0%
  T: 0.0%
  none/other: 0.0%

Overview of removed sequences
length	count	expect	max.err	error counts
20	1	0.0	6	1
```
The trimmed sequence: GTGCCAGCAGCCGCGGTAAACCTGCGGAAGGATCAAGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACA

Now if I remove the part of the 3' adaptor, it finds without problems the 5' that was missing before:
`cutadapt -g 'ACCTGCGGARGGATCA;min_overlap=16;max_error_rate=0.3' --times 1 --max-n 5 --revcomp --trimmed-only --cores 4 --output example_trim_only_fwd.fasta example.fasta`
```
=== Summary ===

Total reads processed:                       1
Reads with adapters:                         1 (100.0%)
Reverse-complemented:                        0 (0.0%)
Reads with too many N:                       0 (0.0%)
Reads written (passing filters):             1 (100.0%)

Total basepairs processed:           199 bp
Total written (filtered):            164 bp (82.4%)

=== Adapter 1 ===

Sequence: ACCTGCGGARGGATCA; Type: regular 5'; Length: 16; Trimmed: 1 times; Reverse-complemented: 0 times

No. of allowed errors:
1-2 bp: 0; 3-5 bp: 1; 6-9 bp: 2; 10-12 bp: 3; 13-16 bp: 4

Overview of removed sequences
length	count	expect	max.err	error counts
35	1	0.0	4	1
```
The trimmed sequence: AGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACAAACTTTCAACAACGGATCTC

What I was expecting with the first command that included both adaptors was they both were found and trimmed to generate this: AGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACA

Best regads.

**Comment by marcelm** [comment]
Cutadapt by default will only trim *at most one* adapter from each read. So if you specify one adapter with `-a` and one with `-g`, only one of them will be removed from each read. I know this is a bit unfortunate (others have stumbled over this before), but I don’t want to change this because it would be backwards incompatible.

To solve this, you could use `--times 2`. Cutadapt will then do *two* rounds of adapter trimming.

But actually I would recommend to use a linked adapter here, as in `-g 'ACCTGCGGARGGATCA;min_overlap=16;max_error_rate=0.3...AACTTTYARCAAYGGATCTC;min_overlap=20;max_error_rate=0.3'`. If you write it like this, both the 5' and 3' "halves" of the linked adapter are optional, that is, a match will still be found even if the 5' or 3' adapter is missing in a read.

**Comment by fjossandon** [comment]
Hey @marcelm , thanks for your reply.
> To solve this, you could use --times 2. Cutadapt will then do two rounds of adapter trimming

Unfortunately Times 2 is not an option here because in my larger pool of sequences, it trims too much and I lose several thousands of sequences due to not passing my length filter. =/

> But actually I would recommend to use a linked adapter here, as in -g 'ACCTGCGGARGGATCA;min_overlap=16;max_error_rate=0.3...AACTTTYARCAAYGGATCTC;min_overlap=20;max_error_rate=0.3'. If you write it like this, both the 5' and 3' "halves" of the linked adapter are optional, that is, a match will still be found even if the 5' or 3' adapter is missing in a read.

This seems like exactly what I need, but I thought that using a linked adapter "..." made both obligatory (https://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters), maybe I read it wrong... 

Ok, I made another test using the original sequence that have both the 5' and 3' adaptors, another where I removed the 5' adaptor only, and a last one where I removed the 3' adaptor only:
```
>example_full
GTGCCAGCAGCCGCGGTAAACCTGCGGAAGGATCAAGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACAAACTTTCAACAACGGATCTC
>example_no_fwd
AGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACAAACTTTCAACAACGGATCTC
>example_no_rev
GTGCCAGCAGCCGCGGTAAACCTGCGGAAGGATCAAGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACA
```
And applied the linked adaptors strategy: `cutadapt -g 'ACCTGCGGARGGATCA;min_overlap=16;max_error_rate=0.3...AACTTTYARCAAYGGATCTC;min_overlap=20;max_error_rate=0.3' --times 1 --max-n 5 --revcomp --trimmed-only --cores 4 --output example_trimmed.fasta example.fasta`
The results:
```
=== Summary ===

Total reads processed:                       3
Reads with adapters:                         1 (33.3%)
Reverse-complemented:                        0 (0.0%)
Reads with too many N:                       0 (0.0%)
Reads written (passing filters):             1 (33.3%)

Total basepairs processed:           542 bp
Total written (filtered):            144 bp (26.6%)

=== Adapter 3 ===

Sequence: ACCTGCGGARGGATCA...AACTTTYARCAAYGGATCTC; Type: linked; Length: 16+20; 5' trimmed: 1 times; 3' trimmed: 1 times
; Reverse-complemented: 0 times

No. of allowed errors:
1-2 bp: 0; 3-5 bp: 1; 6-9 bp: 2; 10-12 bp: 3; 13-16 bp: 4

No. of allowed errors:
1-2 bp: 0; 3-5 bp: 1; 6-9 bp: 2; 10-12 bp: 3; 13-15 bp: 4; 16-19 bp: 5; 20 bp: 6

Overview of removed sequences at 5' end
length	count	expect	max.err	error counts
35	1	0.0	4	1

Overview of removed sequences at 3' end
length	count	expect	max.err	error counts
20	1	0.0	6	1
```
Only the the sequence with both adaptors passed, so their invididual optionality is being ignored, maybe there is a bug there. =( 
```
>example_full
AGAGGTACTGTGGAACGCTGGTTCTCCTGATAGATGGATACGAGGCTGTGCCCGCGAGGCTAGGGAGTACAGTTCTAAATCCAGATTCCGACAACCCCATGAAGGCTGGTTCTGACTCAACTGTTTGGCTCCGATGGTTTCACA
```

**Comment by marcelm** [comment]
Sorry, I gave you the wrong option: Use the `-a` option to specify the linked adapter. If you use `-g` as I wrote, then indeed both the 5' and 3' components are required. When you use `-a`, then both the 5' and 3' adapters are optional (they would only become required when you anchor them).

**Comment by fjossandon** [comment]
Oh, lots of subtle details!
YES!!! using "-a" made it work!
Also, I just discovered that this works too `-g 'ACCTGCGGARGGATCA;min_overlap=16;max_error_rate=0.3;optional...AACTTTYARCAAYGGATCTC;min_overlap=20;max_error_rate=0.3;optional'`, adding the "optional" parameter, although that is longer, so probably I will stick with "-a".

Thanks for all the help, I will close the issue now that I know how to make it work!
