### ISSUE TITLE
Two linked primers

### ISSUE THREAD

**Issue by termithorbor** [marcelm/cutadapt#510]
Hi,

I have two paired end linked primer pairs because I did multiplex PCR with two different primer pairs (Primer1F +Primer1R and Primer2F + Primer2R).

Would this line of code work to trim them both? 

-a Primer1F ... Primer1R_reverse_complement -a Primer2F ... Primer2R_reverse_complement -A Primer1R ...Primer1F_reverse_complement -A Primer2R ... Primer2F_reverse_complement

So theoretically my sample files should look like this:

R1_sample_file: 
Primer1F-Sequence-Primer1R_reverse_complement
Primer2F-Sequenjce-Primer2R_reverse_complement

R2_sample_file:
Primer1F_reversecomplement-Sequence_reverse_complement-Primer1R
Primer2F_reversecomplement-Sequence_reverse_complement-Primer2R

I hope my example makes sense. Thanks in advace :)

**Comment by marcelm** [comment]
When you write the command, remember that there should be no spaces around the three dots, so it should be like `-a AAAA...TTTT` etc. Other than that, this should work, yes!

You may also possibly want to use the option `-g` instead of `-a`, please see [this section in the documentation](https://cutadapt.readthedocs.io/en/latest/guide.html#changing-which-adapters-are-required) (making the two primers *required*). But probably it doesn’t change much.

**Comment by termithorbor** [comment]
I tried it but it works not as good as I expected it

So after running cutadapt my first primer pair is still found in some places:

Before: 
![image](https://user-images.githubusercontent.com/66436023/106620297-b9eda080-6571-11eb-90cc-0318a634895c.png)

After:
![image](https://user-images.githubusercontent.com/66436023/106620369-ca9e1680-6571-11eb-8b10-ecb982927c0e.png)

And t6he second one as well:

Before:
![image](https://user-images.githubusercontent.com/66436023/106620511-eef9f300-6571-11eb-9db2-75073345937e.png)

Forward = Forward primer; Complement = reverse complement of the Forward primer; Reverse = Reverse primer; RevComp = reverse complement of the Reverse primer

FWD.ForwardReads = Forward read (R1) ; FWD.ReverseReads = reverse complement of forward reads and so on.

Is it probably better to first remove the first primer pair and then run cutadapt again and remove the soncond primer pair? each time I would use -a Primer1F...Primer1R_reverse_complement -A Primer1R..Primer1F_reverse_complement

Thanks in advance.

**Comment by marcelm** [comment]
Hm, are these primers nested? Or does each read have exactly one of the two primer pairs?

Cutadapt removes at most a single adapter from each read (a linked adapter with its two components counts as one) by default. If running Cutadapt twice works better, then I’m guessing that you have some reads that contain both primer pairs. Is that possible?

Try the original command line, but add `--times=2` to it. That should be equivalen to running Cutadapt twice.
