### ISSUE TITLE
cut-adapt can't be installed via conda with python 3.8

### ISSUE THREAD

**Issue by ZheFrenchKitchen** [marcelm/cutadapt#511]
This describes the same issue [TrimGalore Github](https://github.com/FelixKrueger/TrimGalore/issues/99)
I'm using conda 4.9.2 on Ubuntu 18.04;

` conda install -c bioconda trim-galore 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:
Specifications:

  - trim-galore -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*']

  Your python: python=3.8

  If python is on the left-most side of the chain, that's the version you've asked for.
  When python appears to the right, that indicates that the thing on the left is somehow
  not available for the python version you are constrained to. Note that conda will not
  change your python version to a different minor version unless you explicitly specify
  that.
`

**Comment by marcelm** [comment]
This is unfortunately nothing I can help with since it appears to be either a problem with Trim Galore or with how you run Conda, and not an issue with Cutadapt.

Possibly it helps to install into a new Conda environment (add `-n theenvironmentname`). Ensure also you specify `-c conda-forge` (Bioconda requires conda-forge).

**Comment by ZheFrenchKitchen** [comment]
Yeah I created an environnement in python 3.7... it worked but...anyway thanks.

**Comment by adler-sudo** [comment]
@marcelm including -c conda-forge worked for me
