### ISSUE TITLE
Bug in --info-file with --revcomp

### ISSUE THREAD

**Issue by alephreish** [marcelm/cutadapt#517]
$ cutadapt 2>&1 | head -n1
    This is cutadapt 3.3 with Python 3.8.5

It seems that there is a problem with the `--info-file` when the adapter is found in `revcomp`:

    $ cat test.fna 
    >test
    TATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCG
    >test_rv
    CGGTTCCTGGCCTTTTGCTGGCCTTTTGCTCACATGTTCTTTCCTGCGTTATCCCCTGATTCTGTGGATAACCGTATTACCGCCTTTGAGTGAGCTGATA
    $
    $ cutadapt --report=minimal --info-file test.info --revcomp -g TATCAGCTCACT test.fna -o /dev/null
    [8<----------] 00:00:00             2 reads  @    237.0 µs/read;   0.25 M reads/minute
    status	in_reads	in_bp	too_short	too_long	too_many_n	out_reads	w/adapters	qualtrim_bp	out_bp
    OK	2	200	0	0	0	2	2	0	176
    $
    $ cat test.info 
    test		0	0	12		TATCAGCTCACT	CAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCG	1			
    test_rv rc	0	0	12		CGGTTCCTGGCC	TTTTGCTGGCCTTTTGCTCACATGTTCTTTCCTGCGTTATCCCCTGATTCTGTGGATAACCGTATTACCGCCTTTGAGTGAGCTGATA	1	

Above, there are two identical reads differing in orientation. `cutadapt` correctly identifies the adapter in both, but in `info-file` the sequences in columns 5-7 are incorrect for the read with a match in the reverse complement, as they contain substrings extracted from the wrong strand. The coordinates in columns 3-4 are in principle usable as they can be understood by a parser as referring to the opposite strand based on the flag " rc" (although false positives can emerge if input reads for some other reason already have this very string "rc" in the definition, e.g. `>my-read read with rc`), but columns 5-7 are plainly unreliable.

**Comment by marcelm** [comment]
Thanks, you’re right that this is a bug.

I think I’d like to change it so that
- there’s an extra flag column that tells whether the read has been reverse-complemented or not,
- the sequence is shown in its reverse-complemented version if the adapter was found on the reverse complement. This is similar to how reads in SAM/BAM files are all shown as "normalized" in the same orientation as the reference.

Any objections?

**Comment by alephreish** [comment]
Sounds perfect.

**Comment by alephreish** [comment]
@marcelm Thanks a lot!

**Comment by marcelm** [comment]
This should be fixed now. While fixing that, I noticed another problem, for which I added #518. As long as you don’t use 5' quality trimming or prefix removal (`-U`), you should be fine.

**Comment by alephreish** [comment]
I'm personally totally happy. My idea is actually to locate [spliced leader RNA](https://www.pnas.org/content/104/11/4618) which is in a way merely a (potentially truncated) adapter added at 5' to transcripts e.g. in dinoflagellates.
