### ISSUE TITLE
Cutadapt stop running: says I need to intall. 

### ISSUE THREAD

**Issue by lcamVz** [marcelm/cutadapt#521]
After couple of week using cutadapt version 1.18 via conda python 2.7 environment I got a message that goes like this 

`Command 'cutadapt' not found, but can be installed with:`
`sudo apt install cutadapt`

I have there after installed it as a standalone environment and still receive the same message in my forward loop I am running. when I test version it runs smoothly. 
 
the loop is as follows:

`for sample in $(cat samples)
do

    echo "On sample: $sample"
    
    cutadapt -a ^ATGGTCTGGCTWAGACG...TGGACATACAGATGGATGGC \
    -A ^GCCATCCATCTGTATGTCCA...CGTCTWAGCCAGACCAT \
    --discard-untrimmed --match-read-wildcards \
    -o NEWTRIM/${sample}_sub_R1_trimmed.fastq.gz \
    -p NEWTRIM/${sample}_sub_R2_trimmed.fastq.gz FWD/${sample}_R1_001.fastq.gz RVS/${sample}_R2_001.fastq.gz \
    >> cutadapt_primer_trimming_stats2.txt 2>&1

done`

**cutadapt version 3.3** installed outside conda in a WSL2 (ububtu 20.04)
**conda version**( in standalone environment and in python 2.7 environment is)  **1.18**

**Comment by marcelm** [comment]
I don’t quite understand which Cutadapt version you want to use. 1.18 or 3.3? Can you try to just create a new conda environment with the Cutadapt version that you want? Like this: `conda create -n cutadaptenv -c conda-forge -c bioconda cutadapt=3.3` and then `conda activate cutadaptenv`.

`sudo apt install cutadapt` would give you Cutadapt 2.8 as that is the version included with Ubuntu 20.04.

**Comment by lcamVz** [comment]
I have cutadapt version in conda python 2.7 environment and also I have version 3.3 outside of conda. and I can call it and also have created a stand-alone cutadapt environment for cutadapt I get a message that cutadapt appears not to be installed.  When it is clearly installed in both cond and through pip but will try to install it via `sudo apt` and see if that fixes my issue. 

Thank you for the quick reply.

**Comment by marcelm** [comment]
Did you remember to activate the conda environment?

**Comment by lcamVz** [comment]
Yes, I go from base to cutadapt environment and still nothing. Also tested deactivating cutadapt and running it through my other environments where I have it installed. Do you think it might be an issue with the WSL2 linux subsystem?

**Comment by rhpvorderman** [comment]
Try `echo $PATH`. It shows which paths are actually searched for executables.

**Comment by lcamVz** [comment]
So i did echo and I got this.
`echo $PATH
/home/microbiomelab-ndsu/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/bin:/home/microbiomelab-ndsu/.local/bin:/home/microbiomelab-ndsu/miniconda3/bin:/home/microbiomelab-ndsu/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/MEGA-X:/mnt/c/Users/micro/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/micro/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin` 

Seems that I got my miniconda3 path.  also wanted to mention that if I call cutadapt -h I get the help menu but the problem arises when I run the for loop. Looking in the path is there somehting i might be missing?

**Comment by lcamVz** [comment]
this is my full command I use. 

`for sample in $(cat samples)
do

    echo "On sample: $sample"
    
    cutadapt -a ^ATGGTCTGGCTWAGACG...TGGACATACAGATGGATGGC \
    -A ^GCCATCCATCTGTATGTCCA...CGTCTWAGCCAGACCAT \
    --discard-untrimmed --match-read-wildcards \
    -o NEWTRIM/${sample}_sub_R1_trimmed.fastq.gz \
    -p NEWTRIM/${sample}_sub_R2_trimmed.fastq.gz FWD/${sample}_R1_001.fastq.gz RVS/${sample}_R2_001.fastq.gz \
    >> cutadapt_primer_trimming_stats2.txt 2>&1

done`

**Comment by marcelm** [comment]
Did you do the `echo $PATH` after activating the environment? The PATH you show does not contain the `bin/` directory of a Conda environment. After you run `conda activate environmentname`, you should have `/home/path/to/conda/envs/environmentname/bin` in your PATH. In your case, probably `/home/microbiomelab-ndsu/miniconda3/environmentname/bin`.

How do you run the command that you pasted in your most recent comment? Do you have it in a script? Put the `echo $PATH` into that script and see what it outputs.

**Comment by lcamVz** [comment]
Conda environmen for cutadapt
cutadapt --version 1.18

did the echo $PATH 
 bash ../../../../FUNCTIONAL_GENES_DATABASE/cutadaptloop.sh
/home/microbiomelab-ndsu/miniconda3/envs/cutadaptenv/bin:/home/microbiomelab-ndsu/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/bin:/home/microbiomelab-ndsu/.local/bin:/home/microbiomelab-ndsu/miniconda3/bin:/home/microbiomelab-ndsu/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/MEGA-X:/mnt/c/Users/micro/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/micro/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin


the script is as follows now

```
echo $PATH

for sample in $(cat samples)
do

    echo "On sample: $sample"
    
    cutadapt -a ^ATGGTCTGGCTWAGACG...TGGACATACAGATGGATGGC \
    -A ^GCCATCCATCTGTATGTCCA...CGTCTWAGCCAGACCAT \
    --discard-untrimmed --match-read-wildcards \
    -o NEWTRIM/${sample}_sub_R1_trimmed.fastq.gz \
    -p NEWTRIM/${sample}_sub_R2_trimmed.fastq.gz FWD/${sample}_R1_001.fastq.gz RVS/${sample}_R2_001.fastq.gz \
    >> cutadapt_primer_trimming_stats2.txt 2>&1

done
```

Message I get 

Command 'cutadapt' not found, but can be installed with:

sudo apt install cutadapt


I am not sure now what I can do now. is it the format of the script?

**Comment by marcelm** [comment]
Is there a `cutadapt` binary in `/home/microbiomelab-ndsu/miniconda3/envs/cutadaptenv/bin`? Check with
```
ls /home/microbiomelab-ndsu/miniconda3/envs/cutadaptenv/bin/cutadapt
```
If not delete and recreate the environment with
```
conda env remove -n cutadaptenv
conda create -n cutadaptenv cutadapt=1.18
```

And if that does not help, as a last act of desperation, do not call `cutadapt` directly in the script, but give the path directly. So the script would contain this line:
```
/home/microbiomelab-ndsu/miniconda3/envs/cutadaptenv/bin/cutadapt -a ^ATGGTCTGGCTWAGACG...TGGACATACAGATGGATGGC \
```
etc. But if you activate the environment before running the script, this should really not be necessary.

**Comment by lcamVz** [comment]
I'll check all of them and confirm which one works. 

What is weird that I get the same error in the bash script and also a line command for loop.  Because I am able to call cutadapt -h without problems but as I run it in the loop it starts giving problems.

**Comment by marcelm** [comment]
Did you get it to work?

**Comment by lcamVz** [comment]
Yes, I did with the whole path copied in the command.

 I also uninstalled all of the one I had installed and re installed them to make sure. 

Right now I am troubleshooting some problems but they are regarding Dada2. 

Thank you again!

**Comment by marcelm** [comment]
Good news! I’ll close this issue then. You can always post a new issue or comment here and I can re-open it.
