### ISSUE TITLE
Multi-core trimming with info file using all available RAM. 

### ISSUE THREAD

**Issue by J-Burgess** [marcelm/cutadapt#524]
Hi Marcel, I hope that you are well!

Previously, I have used version 1.14 of Cutadapt to trim and generate INFO files which has worked great on a single core. More recently, I have been attempting to implement the multi-core options to improve run times.     

* Versions:  
  + Cutadapt version 3.4. & Python 3.6.13 
* Installation:
  + conda install -c conda-forge mamba 
  + mamba install -c bioconda cutadapt 
* Command line:
  + `cutadapt -g <adapter> -j 10 -o outfile.fastq --info-file=outfile.info -O4 infile.fastq.gz >> outfile.stats`

Everything seems to be processing normally, I can see the output files being generated and the progress bar displaying how many reads have been processed thus far. However, for every core the RAM consumption seems to steadily increase until reaching my machines limit and the progress bar halts but does not exit with an error. This is running on Linux with a 32 core machine and 252Gb of RAM. Monitoring the resource consumption with htop showed that the 10 cores were consuming ~25Gb of RAM each after leaving it to run overnight and checking on the progress in the morning which had frozen. 

The input FASTQ is ~48Gb and the INFO files produced from the single core runs were ~250Gb. I do not remember the single core runs consuming too much RAM but I will check that again. I've performed the same multi-core command line on a subset of 2M reads from the 48Gb file and it worked fine. I'll keep trying to find a solution but in the mean time wanted to post this. Thanks! 

Kind regards,
James

**Comment by marcelm** [comment]
Thanks for the report. I’ll try to reproduce this as soon as I can. I have two questions in the meantime:

- Are you running this on Linux or macOS?
- Cutadapt in some cases runs external processes to handle compression or decompression, such as `pigz`. Is it actually the Python processes that consume the memory, or does that come from a subprocess?

**Comment by marcelm** [comment]
This should be fixed now. The content of the info file was inadvertantly kept in memory.

**Comment by J-Burgess** [comment]
Great, thanks for the rapid response!
