### ISSUE TITLE
Cutadapt still keep running after raising error on improperly paired reads

### ISSUE THREAD

**Issue by az7jh2** [marcelm/cutadapt#525]
Hi there.

I am using Cutadapt 3.4 with Python 3.9.2 on paired reads FASTQ files. However, the reads in the two FASTQ files are  actually not paired because of a mistake in concatenating reads from mutiple FASTQ files.

Cutadapt raise a error as below

```'K00162:286:HTWNNBBXX:8:1101:5477:1209 1:N:0:NTATGTCA' in file 1 does not match 'K00162:286:HTWNNBBXX:6:1101:3569:1173 2:N:0:NTATGTCA' in file 2.```

It's very helpful that Cutadapt can point out this mistake. But Cutadapt keep running and acctually doesn't do any thing like getting frozen. I have to mannually kill the process.

Is that the way Cutadapt dealing with the improperly paired reads?

**Comment by marcelm** [comment]
Which command-line options are you using?

This should not be the way it deals with this, no.

**Comment by az7jh2** [comment]
Here is the command I used

```
cutadapt -A AAGCAGTGGTATCAACGCAGAGTACATGGG..."A{20}" \
        --interleaved \
        -m 30 \
        --max-n 20 \
        --interleaved \
        --pair-filter=both \
        -j 10 \
        -o Sample1_trimmed_R1.fastq.gz \
        -p Sample2_trimmed_R2.fastq.gz \
        Sample1_merged_R1.fastq.gz \
        Sample2_merged_R2.fastq.gz
```

Actually we are trimming the R1 and R2 FASTQ files from 10X single cell RNA sequencing. The R1 FASTQ file store the cell barcode and UMI sequences for each cDNA read in R2, so we treat them as interleaved and only apply trimming on R2 FASTQ file

**Comment by marcelm** [comment]
> we treat them as interleaved

I don’t quite understand: The `--interleaved` option in this case doesn’t actually do anything because you provide both two input files and two output files. (Cutadapt should print a warning in this case, but that’s a different issue.)

In any case, what I mostly wanted to see was whether you are using `-j`, and you do.

**Comment by az7jh2** [comment]
Thanks for pointing out the mis-use of  `--interleaved` option in our script. And Cutadapt worked well on the paired single cell RNA sequencing R1 and R2 FASTQ files after correcting the mistake which caused mismatching of the paired files.

I think you can close this issue now. Thanks again!

**Comment by marcelm** [comment]
Ok, good that fixed it for you!

If you don’t mind, I’d like to leave the issue open for the moment because I assume that the problem that Cutadapt keeps running after an error in a subprocess is still valid.

**Comment by az7jh2** [comment]
Sure. You can keep it open until you fix the issue!

**Comment by marcelm** [comment]
Should be fixed now!

**Comment by marcelm** [comment]
The fix does more harm than good, so I had to revert it for now. I’ll need to work on this when I have more time. I opened #528 for that.
