### ISSUE TITLE
Cutadapt: error: unrecognized arguments

### ISSUE THREAD

**Issue by Sammijiyoung** [marcelm/cutadapt#526]
Cutadapt ver. 3.4 
Installed via conda on MAC terminal 
I used " conda create -n cutadaptenv cutadapt " to install it. 
And it says the file got downloaded to /Users/Sammy/opt/miniconda3/envs/cutadaptenv but when I actually went into the files, there was multiple other files so I had to switch the directory to "/Users/Sammy/opt/miniconda3/envs/cutadaptenv/bin/cutadapt"

I am using Cutadapt on R studio, and 
```
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, 
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], 
                             fnFs.filtN[i], fnRs.filtN[i])) 
}
```
This script gives me this type of error output: 

```
This is cutadapt 3.4 with Python 3.9.2
Command line parameters: -g CCTACGGGNGGCWGCAG -a GGATTAGATACCCBDGTAGTC -G GACTACHVGGGTATCTAATCC -A CTGCWGCCNCCCGTAGG -n 2 -o /Users/Sammy/Desktop/Trial raw sequences//cutadapt/BCH1_S66_L001_R1_001.fastq.gz -p /Users/Sammy/Desktop/Trial raw sequences//cutadapt/BCH1_S66_L001_R2_001.fastq.gz /Users/Sammy/Desktop/Trial raw sequences//filtN/BCH1_S66_L001_R1_001.fastq.gz /Users/Sammy/Desktop/Trial raw sequences//filtN/BCH1_S66_L001_R2_001.fastq.gz
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: unrecognized arguments: raw sequences//cutadapt/BCH1_S66_L001_R2_001.fastq.gz /Users/Sammy/Desktop/Trial raw sequences//filtN/BCH1_S66_L001_R1_001.fastq.gz /Users/Sammy/Desktop/Trial raw sequences//filtN/BCH1_S66_L001_R2_001.fastq.gz
```
I don't know what would be the unrecognized arguments? 

I am following through DADA2 flowchart.. and I don't know the issue, I have those gz files in the right working folders...

https://benjjneb.github.io/dada2/ITS_workflow.html

I am working on R studio right now. My R ver is 4.0.5

Thank you!

**Comment by marcelm** [comment]
The problem is using `system2` combined with spaces in the directory name. A workaround is to rename the "Trial raw sequences" directory such that it does not contain spaces. But you may also want to point out to the creators of the tutorial that using `system2()` isn’t adequate.

**Comment by Sammijiyoung** [comment]
Thank you! It got solved! And now I am trying to run those trimmed sequences in Qiime 2 on Mac terminal to get OTU table. 

And it is keep giving me the error that I cannot tell why...

I am running this on Mac Qiime 2, 

Here is the script that I am running: 
qiime taxa collapse \
  --i-table dada2_trial/table.qza \
  --i-taxonomy 99_otu_classifier_trial.qza \
  --p-level 7 \
  –-o-collapsed-table table_trial.qza \

Here is the error msg: 

 (1/2) Missing option '--o-collapsed-table'.  ("--output-dir" may also be
  used)
 (2/2) Got unexpected extra argument ( )
/var/lib/slurmd/job2224692/slurm_script: line 22: –-o-collapsed-table: command not found

My script includes the Missing option...so I don't understand why it doesn't recognize it????
Can anyone tell??? what's wrong??

**Comment by marcelm** [comment]
Hi, great you got it solved.

I can unfortunately not help with the Qiime 2 question as this is the Cutadapt issue tracker. Perhaps the Qiime 2 developers can help you, but you will need to find contact info for them yourself. Good luck!
