### ISSUE TITLE
Unrecognized arguments error when using loop for paired-end trimming

### ISSUE THREAD

**Issue by awsdd** [marcelm/cutadapt#530]
Hello, just learning to use cutadapt and have trimmed paired-end reads for individual samples successfully. I'm now trying to put together a loop to run through 400 or so paired-end samples based on the advice in #217 which currently looks like this:

```
for r1 in /idempout/R1.fastq.gz_*; do
     r2=${r1/R1.fastq.gz_/R2.fastq.gz_}
     out1=cutadaptoutp/$(basename ${r1})
     out2=cutadaptoutp/${out1/R1.fastq.gz_/R2.fastq.gz_}
     cutadapt GTGYCAGCMGCCGCGGTAA...ATTAGAACCCNGTAGTCC -A GGACTACNVGGGTWTCTAAT...TTACCGCGGCGCTGCAC -o ${out1} -p ${out2} ${r1} ${r2}
done
```

Files are currently in the format 'R1.fastq.gz_001.fastq.gz', 'R2.fastq.gz_001.fastq.gz' etc (yes, I should rename to remove the first extraneous fastq.gz!).

When run, the loop goes through all the samples, however after each sample I get the following

```
This is cutadapt 3.4 with Python 3.9.4
Command line parameters: GTGYCAGCMGCCGCGGTAA...ATTAGAACCCNGTAGTCC -A GGACTACNVGGGTWTCTAAT...TTACCGCGGCGCTGCAC -o cutadaptoutp/R1.fastq.gz_73.fastq.gz -p cutadaptoutp/cutadaptoutp/R1.fastq.gz_73.fastq.gz /idempout/R1.fastq.gz_73.fastq.gz /idempout/R2.fastq.gz_73.fastq.gz
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: unrecognized arguments: /idempout/R1.fastq.gz_001.fastq.gz /idempout/R2.fastq.gz_001.fastq.gz
```
before it moves on to the next pair. I've spent quite a bit of time tweaking and trying to figure it out but the problem persists - is there anything you can suggest? I notice that one of the output files listed after command line parameters repeats the folder name i.e. cutadaptputp/cutadaptoutp/....

Any help most appreciated.

**Comment by marcelm** [comment]
I believe you forgot the `-a` before the first parameter.

**Comment by awsdd** [comment]
Indeed I had. Thanks very much, it has just run through without errors.

Much appreciated!
