### ISSUE TITLE
ModuleNotFoundError: No module named 'cutadapt.__main__'

### ISSUE THREAD

**Issue by Whale-fall** [marcelm/cutadapt#531]
Same problem of [#324 ]

**Comment by marcelm** [comment]
Let’s discuss this here instead of in #324.

Do you remember which command you used to install Cutadapt? Can you try to create a fresh Conda environment and see whether you still get the error? On the compute node, what is the output of `env | grep PYTHON`?

**Comment by Whale-fall** [comment]
Hello, I am sorry to respond so late.I install Cutadapt via conda, the command I use for install is `mamba install Cutadapt`.And I created a new env called cutadapt_test，however it also didn't work on the compute node. The record is below here:
![image](https://user-images.githubusercontent.com/22662209/120127632-7985f280-c1f2-11eb-9c1c-cd445c6cf849.png)
![image](https://user-images.githubusercontent.com/22662209/120127657-89053b80-c1f2-11eb-892c-c8c4455c5985.png)
A wired thing is Python3 is not in Path on the compute node, can you help me fix it?
![image](https://user-images.githubusercontent.com/22662209/120127743-c36ed880-c1f2-11eb-9e48-bbc15c248c7c.png)

**Comment by Whale-fall** [comment]
Actually, the output of the login node is the same as the compute node, and Cutadapt seems to work 
![image](https://user-images.githubusercontent.com/22662209/120128496-b5ba5280-c1f4-11eb-9a00-45c79c0eb7f1.png)

**Comment by Whale-fall** [comment]
sorry for my bad editing

**Comment by marcelm** [comment]
The `PYTHONPATH` on the compute node points to an old version of Cutadapt:
```
/public/software/cutadapt-1.4.1/lib64/python2.6/site-packages
```
Removing this may solve the problem. You also need to find out which of your login scripts sets this. Do you use some kind of module system and have a `module load cutadapt` somewhere?

The `PYTHONPATH` usually does not need to be set at all. It can be used to tell Python where installed packages are, and it seems that your publicly installed software is made available that way, but there are other mechanisms that work much better. It is safest if you have an empty `PYTHONPATH` while you are in an activated Conda environment.

**Comment by Whale-fall** [comment]
Thanks a lot,I set `export PYTHONPATH=`in my PBS script and fixed this problem temporarily.

**Comment by marcelm** [comment]
Great, glad I could help!

**Comment by ryandward** [comment]
`export PYTHONPATH=` seems to work. How can I make this fix more robust?
