### ISSUE TITLE
Meaning of the length feature in Cutadapt output

### ISSUE THREAD

**Issue by VakilT** [marcelm/cutadapt#535]
- Cutadapt and Python version: **cutadapt version 3.4**, **python/3.7.4**
- How you installed the tool: **pip**
- Which command-line parameters you used: **cutadapt -g "GACTGGTTCCAATTGAAAGTGCTCTTCCGATCT;e=0.1;min_overlap=27" --discard-trimmed -o OUTPUT.fastq.gz INPUT.fastq.gz**

The relevant output of Cutadapt:

=== Adapter 1 ===

Sequence: GACTGGTTCCAATTGAAAGTGCTCTTCCGATCT; Type: regular 5'; Length: 33; Trimmed: 43904 times

No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20-29 bp: 2; 30-33 bp: 3

Overview of removed sequences
length  count   expect  max.err error counts
26      9       0.0     2       0 6 3
27      78      0.0     2       69 6 3
28      102     0.0     2       78 19 5
29      120     0.0     2       84 30 6
30      116     0.0     3       90 24 0 2
31      206     0.0     3       180 19 5 2
32      123     0.0     3       97 12 5 9
33      105     0.0     3       68 20 8 9
34      163     0.0     3       126 22 6 9
35      281     0.0     3       119 23 25 114
36      905     0.0     3       183 129 536 57
37      4316    0.0     3       944 3194 162 16
38      35112   0.0     3       33318 1548 205 41
39      2123    0.0     3       1827 238 46 12
40      85      0.0     3       10 11 47 17
...
70      1       0.0     3       1

Hello,

Could you please explain the meaning of the column "length" in this case? In the documentation of Cutadapt, I found that "Note that the “length” column refers to the length of the removed sequence", and this confuses me a bit.

Specifically, let's focus on the length **40**, there are 10 sequences that matched the adapter without an error. Unfortunately, I couldn't understand how it could be possible with the 33-nucleotide-long adapter. There should be 7 insertions to the adapter to match this 40-nucleotide-long sequence.

I though of this potential explanation. Since I asked to discard reads with the adapter, maybe this 40-nucleotide-long sequence is a discarded read that has a 33-nucleotide-long match with the adapter. However, this explanation must be wrong because there are sequences with the length 29, 27, 28 etc. but in the input file reads cannot be shorter than 36 nucleotides.   

Could you please explain the meaning of the length feature?

Many thanks!

Cheers,
Vakil

**Comment by marcelm** [comment]
Providing a 5' adapter sequence with `-g` allows matches anywhere within the read. In particular, if an adapter of length 33 was found at positions 8 to 40, then the removed sequence is 40 bp long.

In other words, you have this situation:
```
SOMENUCLEOTIDESADAPTEROTHERNUCLEOTIDES
```
After trimming, this will be
```
OTHERNUCLEOTIDES
```
And the length of `SOMENUCLEOTIDES` is what is listed in the statistics output.

If you do not want this trimming behavior, you can instead use a [non-internal 5' adapter](https://cutadapt.readthedocs.io/en/stable/guide.html#non-internal) with `-g XADAPTER` or an [anchored 5' adapter](https://cutadapt.readthedocs.io/en/stable/guide.html#anchored-5adapters) with `-g ^ADAPTER`.

**Comment by marcelm** [comment]
I hope my answer was helpful, closing this now.
