### ISSUE TITLE
Enhancement: Sequence Entropy Filter

### ISSUE THREAD

**Issue by DarioS** [marcelm/cutadapt#538]
Although not an adapter, low-complexity sequences are ideally removed. I often see them in my Unmapped.out.mate1 files from STAR, but I don't want them going into microbiome data analysis. Do you think `cutadapt` is a suitable stage to remove them at? If so, might cutadapt offer an entropy-based threshold filter?

**Comment by marcelm** [comment]
That could possibly be within scope for Cutadapt. Do you have experience with another tool that implements such a filter?

Also, do you have a couple of example sequences that should be filtered out?

A couple of notes while researching this (and complexity filtering in general):

* [prinseq](https://chipster.csc.fi/manual/prinseq-complexity-filter.html) uses the entropy of trinucleotide frequencies and also implements a method similar to Dust
* [Dust](https://pubmed.ncbi.nlm.nih.gov/16796549/) is used by BLAST. [sdust](https://github.com/lh3/sdust) is a faster implementation by Heng Li.
* There’s a tool called [komplexity](https://github.com/eclarke/komplexity) that just uses the number of unique *k*-kmers
* Sequencing errors increase complexity. For example, Shannon entropy (using single-character frequencies) of `AAAAAAAAAA` is 0 bits, but with `AAAAAAAAAT`, it jumps to 0.47.
* A long time ago, I worked on a tool that also [implements a low-complexity filter](https://bitbucket.org/svenrahmann/verjinxer/src/15c051c17d14e26e83ebfe81714e568c01d495bc/src/verjinxer/sequenceanalysis/QGramFilter.java#lines-54). It can also ignore the least frequent *k*-mers, which could be a method to alleviate the sequencing error problem

**Comment by DarioS** [comment]
Oh, it seems complicated and is probably best left to dedicated software.

**Comment by marcelm** [comment]
Hm, you’re giving up fast! None of these are hard to implement (I’ve already written a basic Shannon entropy filter actually), and having it directly in Cutadapt would be nice (just as it is nice you don’t need an extra quality trimming tool). So perhaps I’ll add this anyway.

Please let me know which external tool you end up choosing.
