### ISSUE TITLE
Untrimmed reads in output when specifying --untrimmed-output 

### ISSUE THREAD

**Issue by J-Burgess** [marcelm/cutadapt#539]
Hi Marcel, I hope all is well. 

I am running into a situation in which it appears some untrimmed reads are actually being output to the trimmed output. 

The experiment has paired end data but only the R2 contains variation when the gene is in the forwards orientation which we are extracting for alignment. 

Therefore, my inputs are single end (R2) and I wish to extract the variable region between two wild type 'adapters' in the sequence. Initially, I started with a two pass approach and trimmed the first pass with the -g command as shown below (Following second pass with -a on the downstream adapter). However, there appears to be many reads which do not contain this adapter in the first pass output file. 

- Cutadapt and Python version
  + Cutadapt 3.4 and Python 3.9.5 
- How you installed the tool (conda or pip, for example)
  + Conda 
- Which command-line parameters you used
  
Command line parameters: -j 20 -e 0.1 -g GACTGCCATATTTTATATCCACGTTTAATT -o Firstpass_trimmed_R2.fq --action retain --untrimmed-output untrimmed_intermediate_R2.fq Input_R2.fq.gz

An example from the start of the reads in the output -o file is shown below:

GACTGCCATATTTTATATCCACGTTTAATTGAAAGAAGAATGGTAAGATTTTGCTATT....continues until 135bp (Expected trimming result.)

ATTGATTCAATAAACCGGTTGCAATAATTTATTTAAATATATATTTTAGTTTTAAAAAT..... continues until 242bp  (Wild type from the reverse orientation. The -g adapter specified is not present in this wild type sequence. We started with 250bp reads and the real 8bp adapter has already been removed. Therefore, this read is untrimmed.)

A large proportion of these wild type reads are present in the output -o file instead of the --untrimmed-output file. I have since used the linked adapter method which worked great and gave me comparable results to this two pass method but I am curious to find out if this is something I am not interpreting correctly? Interestingly, there are still many untrimmed reads which are sent to the --untrimmed-output and these look as expected so it is not the case that all reads are being directed to the -o file. 

Thanks in advance!

James

**Comment by marcelm** [comment]
Hi, you haven’t said it explicitly, but is it correct that you expect the 5' adapter to appear in full at the 5' end of the read? Then you should use an [anchored 5’ adapter](https://cutadapt.readthedocs.io/en/stable/guide.html#anchored-5adapters), that is, you should prefix the adapter sequence with a `^`.

Without this, a 5’ adapter sequence is allowed to 1) occur partially at the 5' end, and to 2) occur anywhere within the read. The second example sequence you gave starts with `ATT`, while the adapter ends with `ATT`, so this is actually found as a partial occurrence.

You can check whether that is the problem by inspecting the "Overview of removed sequences" table that Cutadapt prints at the end: It will probably show many different lengths. The ones shorter than the actualy adapter sequence are partial matches, whereas the ones longer than the adapter sequence are matches that do not start at the 5' end. You could also run with `--action=lowercase` and see where the adapters were found.

**Comment by J-Burgess** [comment]
Hi, thanks for the rapid response. 

The 5' adapter is expected to be found within the original reads rather than at the beginning. From my understanding this would mean the anchored notation would not work? I shall try with the lowercase action and see if there is an adapter found within the other reads and update you. Thanks!

**Comment by marcelm** [comment]
If an occurrence within the read needs to be allowed, but you want to disallow partial occurrences, you can set the minimum overlap (`-O`) to the adapter length.

**Comment by J-Burgess** [comment]
Hi Marcel, 

Setting -O to adapter length worked perfectly. I will stay with the linked adapter method but its good to know what was happening. Thanks for the responses!

**Comment by marcelm** [comment]
Great, I agree using linked adapters is preferable! Just in case you need it, I’ll mention that you can [set the minimum overlap individually](https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-trimming-parameters) for each linked adapter, using something like `-a TTGGCCAA;o=12...AACCGGTT`.
