### ISSUE TITLE
minimum overlap not working with linked adapters

### ISSUE THREAD

**Issue by asthara10** [marcelm/cutadapt#542]
- Cutadapt and Python version
cutadapt 2.8 with Python 3.8.10
- How you installed the tool
installed with apt

I am trying to trim with linked adapters and using a minimum overlap.
The command works as expected when both adapters are complete or where they 
 are incomplete, but without extra bases at the extremes.
When one of the adapters is incomplete and contains extra bases, it is not detected nor trimmed.

I created an example fasta file for illustration.
```
>complete
AACCACTGACTGTTGG
>complete_extra5
TAACCACTGACTGTTGG
>complete_extra3
AACCACTGACTGTTGGT
>complete_extraboth
TAACCACTGACTGTTGGT
>short3
TAACCACTGACTGTTG
>shot3_extraboth
TAACCACTGACTGTTGA
>short5_extra5
TACCACTGACTGTTGG
```
The commands that I have used tried for trimming are the following:
```
cutadapt -e 0.2 -O 3 --match-read-wildcards --discard-untrimmed -g AACC...TTGG --rc reads2.fasta
cutadapt -e 0.2 --match-read-wildcards --discard-untrimmed -g "AACC;o=3...TTGG;o=3" --rc reads2.fasta
```
The output that I obtain is
```
>complete
ACTGACTG
>complete_extra5
ACTGACTG
>complete_extra3
ACTGACTG
>complete_extraboth
ACTGACTG
>short3
ACTGACTG
```
And I would expect to have the adapters trimmed in all cases
```
>complete
ACTGACTG
>complete_extra5
ACTGACTG
>complete_extra3
ACTGACTG
>complete_extraboth
ACTGACTG
>short3
ACTGACTG
>shot3_extraboth
ACTGACTG
>short5_extra5
ACTGACTG
```

As a summary, I am wondering which parameters should I use to obtain the behavior of trimming `basesPTER1sequenceADAPTEbases` and obtain `sequence`

Thank you very much for you help,

Júlia

**Comment by marcelm** [comment]
Cutadapt only allows partial matches at the beginning or end of the read. The minimum overlap parameter applies only to these cases. So your desired behavior isn’t supported directly. May I ask what the use case is, that is, what is this adapter/primer actually and how can it happen that it occurs only partially, but within the read?

Two workarounds come to mind, perhaps one of them works for you:
- Provide only the last couple of bases for the 5' adapter and only the first couple of bases for the 3' adapter: `cutadapt -g ACC...TTG`
- If the number of bases preceding the 5' adapter is always the same, use `-u` (as in `-u 7`) to remove them. This is done before the adapter trimming, so you could use that option in the same command line (you do not have to run Cutadapt twice). Then the partial occurrence will be at the 5' end and be recognized. Same for the 3' end, but you need to use `-u` with a negative number: `-u -8`.

**Comment by asthara10** [comment]
Thank you very much for your reply @marcelm

I was not aware that this behaviour was not supported. I am trying to use cutadapt to detect nested primers within nanopore reads, which happen in some cases to have indels.
Your second suggestion will help me with this particular problem.

Thanks

**Comment by marcelm** [comment]
If this is about allowing indels, you could also choose an appropriately high error rate. In your example above where you have `AACC` as a 5' adapter sequence, you could use `-e 1` to allow 1 error (insertion, deletion, mismatch) (or even `-e 2` and so on).
