### ISSUE TITLE
Clearer error for I (inosine), or automatically treat it as N?

### ISSUE THREAD

**Issue by peterjc** [marcelm/cutadapt#546]
Attempting to call cutadapt v3.4 with a primer sequence containing "I" fails with:

```
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: Character 'I' in adapter sequence 'GYRGGGACGAAAGTCYYTGCI' is not a valid IUPAC code. Use only characters ABCDGHKMNRSTUVWXY
```

Inosine is found naturally at the wobble position of tRNA, and can match any base. Structurally similar to guanine (G), it preferentially binds cytosine (C). It sometimes used in primer design (Ben-Dov *et al.*, 2006 https://doi.org/10.1128/aem.00849-06 ), where degeneracy N would give similar results.

In my own work I have mapped "I" to "N" when calling cutadapt with such a primer, and wondered if it would make sense to add ``.replace("I", "N")`` to cutadapt, or at least fail with a hint in this special case?, e.g.

```
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: Character 'I' in adapter sequence 'GYRGGGACGAAAGTCYYTGCI' is not a valid IUPAC code. For inosine consider using N instead.
```

**Comment by marcelm** [comment]
Thanks, I learned something! I’ll do something about this when I have time again. I’ll probably go the `.replace()` route.

**Comment by peterjc** [comment]
The "I" to "N" replacement is what I've done before calling cutadapt, based on the Ben-Dov *et al.* (2006) reference. This isn't one of "my" primers but the example "GYRGGGACGAAAGTCYYTGCI" was from a public dataset I was using.

**Comment by peterjc** [comment]
That seems very prudent 👍

**Comment by TatyanaVl** [comment]
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: Character 'I' in adapter sequence 'CTCCTACGGGIGGCAGCAG' is not a valid IUPAC code. For inosine, consider using N instead and please comment on <https://github.com/marcelm/cutadapt/issues/546>.
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: Character 'I' in adapter sequence 'CTCCTACGGGIGGCAGCAG' is not a valid IUPAC code. For inosine, consider using N instead and please comment on <https://github.com/marcelm/cutadapt/issues/546>.

**Comment by peterjc** [comment]
@TatyanaVl is the error message unclear?

Try using 'CTCCTACGGGNGGCAGCAG' with an 'N' instead of 'CTCCTACGGGIGGCAGCAG' with an 'I'.

**Comment by marcelm** [comment]
Ah, good find! So I guess that indeed means that at least one other person wants to use `I` for inosine.
