### ISSUE TITLE
Problems installing cutadapt on ssh server

### ISSUE THREAD

**Issue by eibol1** [marcelm/cutadapt#548]
Hi there, 

I am a beginner in informatics/bioinformatics, so I don't understand too much about installing pckgs, but I want to learn. I have some problems when I try to install Cutadapt on SSH Server (linux, **no root privileges**). 

I have installed Python 3 (3.8.8) and pip (21.2.1) without root privileges and I have them on PATH (.bashrc):
export PATH=$HOME/python3.9/Python-3.9.0/:$PATH
export PATH=$HOME/.local/bin/:$PATH

When I try to install cutadapt running: `pip install cutadapt` I got some errors with PEP517:

 "Building wheel for isal (PEP517) ... (error)"
ERROR: Command errored out with exit status 1:
   command: /home/abel.garcia/anaconda3/bin/python /home/abel.garcia/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpki04_zsp
       cwd: /tmp/pip-install-yxrg7gj_/isal_467a045c40e84e7eb39bb73cfc7cda49
  Complete output (33 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/isal
  copying src/isal/igzip.py -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/__init__.py -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/crc.pxd -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/version.pxd -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/__init__.pxd -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/igzip_lib.pxd -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/isal_zlib.pyx -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/_isal.pyx -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/igzip_lib.pyx -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/_isal.pyi -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/isal_zlib.pyi -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/igzip_lib.pyi -> build/lib.linux-x86_64-3.8/isal
  copying src/isal/py.typed -> build/lib.linux-x86_64-3.8/isal
  creating build/lib.linux-x86_64-3.8/isal/isa-l
  copying src/isal/isa-l/LICENSE -> build/lib.linux-x86_64-3.8/isal/isa-l
  copying src/isal/isa-l/README.md -> build/lib.linux-x86_64-3.8/isal/isa-l
  copying src/isal/isa-l/Release_notes.txt -> build/lib.linux-x86_64-3.8/isal/isa-l
  running build_ext
  cythoning src/isal/isal_zlib.pyx to src/isal/isal_zlib.c
  cythoning src/isal/igzip_lib.pyx to src/isal/igzip_lib.c
  cythoning src/isal/_isal.pyx to src/isal/_isal.c
  configure.ac:4: error: Autoconf version 2.69 or higher is required
  configure.ac:4: the top level
  autom4te: /usr/bin/m4 failed with exit status: 63
  aclocal: autom4te failed with exit status: 63
  autoreconf: aclocal failed with exit status: 63
  error: [Errno 2] No such file or directory: '/tmp/tmpmhhl6a8c/configure'
  ----------------------------------------
  ERROR: Failed building wheel for isal
Failed to build isal
ERROR: Could not build wheels for isal which use PEP 517 and cannot be installed directly

I updated pip and PEP517 with: `pip install --upgrade pip` and `pip install PEP517` but the error persists. 

What I should do? I am stuck with this for some days so if you can help me that would be great, please!!

**Comment by marcelm** [comment]
eibol1 ***@***.***> skrev: (30 juli 2021 13:43:25 CEST)
>Hi there, 
>
>I am a beginner in informatics/bioinformatics, so I don't understand
>too much about installing pckgs, but I want to learn. I have some
>problems when I try to install Cutadapt on SSH Server (linux, **no root
>privileges**). 
>
>I have installed Python 3 (3.8.8) and pip (21.2.1) without root
>privileges and I have them on PATH:
>export PATH=$HOME/python3.9/Python-3.9.0/:$PATH
>export PATH=$HOME/.local/bin/:$PATH
>
>When I try to install cutadapt running: `pip install cutadapt` I got
>some errors with PEP517:
> "Building wheel for isal (PEP517) ... (error)"
>ERROR: Command errored out with exit status 1:
>command: /home/abel.garcia/anaconda3/bin/python
>/home/abel.garcia/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py
>build_wheel /tmp/tmpki04_zsp
>   cwd: /tmp/pip-install-yxrg7gj_/isal_467a045c40e84e7eb39bb73cfc7cda49
>  Complete output (33 lines):
>  running bdist_wheel
>  running build
>  running build_py
>  creating build
>  creating build/lib.linux-x86_64-3.8
>  creating build/lib.linux-x86_64-3.8/isal
>  copying src/isal/igzip.py -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/__init__.py -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/crc.pxd -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/version.pxd -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/__init__.pxd -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/igzip_lib.pxd -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/isal_zlib.pyx -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/_isal.pyx -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/igzip_lib.pyx -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/_isal.pyi -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/isal_zlib.pyi -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/igzip_lib.pyi -> build/lib.linux-x86_64-3.8/isal
>  copying src/isal/py.typed -> build/lib.linux-x86_64-3.8/isal
>  creating build/lib.linux-x86_64-3.8/isal/isa-l
>copying src/isal/isa-l/LICENSE -> build/lib.linux-x86_64-3.8/isal/isa-l
>copying src/isal/isa-l/README.md ->
>build/lib.linux-x86_64-3.8/isal/isa-l
>copying src/isal/isa-l/Release_notes.txt ->
>build/lib.linux-x86_64-3.8/isal/isa-l
>  running build_ext
>  cythoning src/isal/isal_zlib.pyx to src/isal/isal_zlib.c
>  cythoning src/isal/igzip_lib.pyx to src/isal/igzip_lib.c
>  cythoning src/isal/_isal.pyx to src/isal/_isal.c
>  configure.ac:4: error: Autoconf version 2.69 or higher is required
>  configure.ac:4: the top level
>  autom4te: /usr/bin/m4 failed with exit status: 63
>  aclocal: autom4te failed with exit status: 63
>  autoreconf: aclocal failed with exit status: 63
>error: [Errno 2] No such file or directory:
>'/tmp/tmpmhhl6a8c/configure'
>  ----------------------------------------
>  ERROR: Failed building wheel for isal
>Failed to build isal
>ERROR: Could not build wheels for isal which use PEP 517 and cannot be
>installed directly
>
>I updated pip and PEP517 with: `pip install --upgrade pip` and `pip
>install PEP517` but the error persists. 
>
>What I should do? I am stuck with this for some days so if you can help
>me that would be great, please!! 

I'm on vacation, so just briefly: it appears you also use conda, so try "conda install -c bioconda -c conda-forge cutadapt" instead. Don't change the PATH. See also the conda install instructions in the cutadapt documentation

**Comment by eibol1** [comment]
Thanks for your time. I run the command `conda install -c bioconda -c conda-forge cutadapt` and it worked. `cutadapt --version` --> 3.4. So I guess it's now working. Thank you very much marcelm!!!! 😁👍🏼
