### ISSUE TITLE
cutadapt installation issue

### ISSUE THREAD

**Issue by DenisGoryunov** [marcelm/cutadapt#549]
Hi,

I tried to install cutadapt by doing following:

conda create --name Cutadaptenv python=3.7
conda install -n Cutadaptenv -c bioconda -c conda-forge cutadapt

But got error after the command:
cutadapt --version

Traceback (most recent call last):
  File "/home/tkiy/miniconda3/envs/Cutadaptenv/bin/cutadapt", line 7, in <module>
    from cutadapt.__main__ import main_cli
  File "/home/tkiy/miniconda3/envs/Cutadaptenv/lib/python3.7/site-packages/cutadapt/__main__.py", line 69, in <module>
    from cutadapt.modifiers import (SingleEndModifier, LengthTagModifier, SuffixRemover,
  File "/home/tkiy/miniconda3/envs/Cutadaptenv/lib/python3.7/site-packages/cutadapt/modifiers.py", line 12, in <module>
    from dnaio import record_names_match, Sequence as DnaSequence
ImportError: cannot import name 'record_names_match' from 'dnaio' (/home/tkiy/.local/lib/python3.7/site-packages/dnaio/__init__.py)

Could you help me please to fix it?

Regads,
Denis

**Comment by marcelm** [comment]
You have a remnant of a previous cutadapt installation that you did using the command "pip install --user" on your system in /home/tkiy/.local/lib/python3.7/site-packages/... Easiest is too just remove /home/tkiy/.local/lib/python3.7. (This will also remove any other Python packages that you installed using "pip install --user")
Alternatively, run "export PYTHONNOUSERSITE=1" before starting cutadapt, which makes Python ignore the .local directory.

**Comment by DenisGoryunov** [comment]
Hi,
Thanks for your reply. That's weird as i executed "pip3 uninstall cutadapt" command before installation. Will check it out once more.

Regards,
Denis

**Comment by marcelm** [comment]
I simplified: The actual problem is with the still-installed "dnaio", which cutadapt has as a dependency. "pip uninstall cutadapt" won't remove dependencies. You could "pip uninstall cutadapt dnaio xopen" to get rid of everything, but because you as a user shouldn't have to know which the dependencies are, best practice would be to install the program into a virtual environment (virtualenv), either manually (see cutadapt install instructions) or with "pipx". Removing the virtualenv then gets rid of everything without affecting other installations. I'll update the docs at some point.

**Comment by DenisGoryunov** [comment]
Hi,
Thanks for your response, unfortunately command "pip uninstall cutadapt dnaio xopen" doesn't work for me and i got error:
"-bash: /usr/bin/pip: /usr/bin/python3: bad interpreter: No such file or directory"
In the /home/tkiy/.local/lib/python2.7/site-packages there are folders "bz2file-0.98.dist-info"  "cutadapt"  "cutadapt-1.16.dist-info" "xopen-0.3.5.dist-info" and two files "xopen.py" and "xopen.pyc"
In the /home/tkiy/.local/lib/python3.7/site-packages there are folders "dnaio"  "dnaio-0.4.1.dist-info"  "isal"  "isal-0.11.0.dist-info"  "xopen"  "xopen-0.8.4.dist-info"

Could you advise me please which of the mentioned above files and folders are associated with cutadapt and its dependencies and hence may be safely removed? I used conda that time but used pip for cutadapt installation previously.

**Comment by marcelm** [comment]
You should delete both site-packages folders, and it is safe to do so: /home/tkiy/.local/lib/python2.7/site-packages/ and /home/tkiy/.local/lib/python3.7/site-packages/ .
If it exists, you should also remove the file /home/tkiy/.local/bin/cutadapt

**Comment by DenisGoryunov** [comment]
Yes, that solved the issue. I much appreciate your help.
