### ISSUE TITLE
The order of trimming of different adapter types

### ISSUE THREAD

**Issue by DenisGoryunov** [marcelm/cutadapt#552]
Hi Marcel,

I'm dealing with Illumina paired end amplicon data. I usually trim the 5' anchored adapter at first and then remove 3' regular adapters. I'm wondering if my trimming order is correct (i.e. 5’ adapters before 3’ adapters) and if the order of trimming of different adapters types is important for their full removal from the data in general?

Besides i have a few additional questions regarding adapters trimming.

To my understanding i have to remove 3' regular adapters in my data only in cases when the Read Length > Fragment Length. Am i right?

If so i’d expect to observe approximately the same percentage of adapters in forward and reverse reads, but in my analysis it was not the case:

```
Total read pairs processed:            354,210
  Read 1 with adapter:                  16,725 (4.7%)
  Read 2 with adapter:                 167,416 (47.3%)
```
Can that be a reliable indicator of the wrong program settings ?

The observed discrepancies in percentage were mainly because in R2 reads:
```
length  count   expect  max.err error counts
3       141087  5534.5  0       141087
4       10326   1383.6  0       10326
```

Should i adjust --overlap parameter at least to 5?

Manu thanks,
Denis

**Comment by marcelm** [comment]
Hi, I was on vacation and saw this issue only now, sorry for the delay. I’ll answer in the hope that it is still relevant.

> I'm wondering if my trimming order is correct (i.e. 5’ adapters before 3’ adapters) and if the order of trimming of different adapters types is important for their full removal from the data in general?

In this case, the order normally does not matter. The only exception is the situation in which you have a read where the 5' and 3' adapter overlap. For example, if your 5' adapter was `AACCGGTT` and your 3' adapter was `GGTTACGT`, then trimming order would matter for this sequence:
```
AACCGGTTACGT
```
Removing the 5' adapter gives you `ACGT`, and then the 3' adapter wouldn’t be found anymore. Removing the 3' adapter first results in `AACC` and then the 5' adapter wouldn’t be found anymore.

That said, if you always remove a single 5' and single 3' adapter, note that you may want to use [linked adapters](https://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters) instead, which combine the 5' and the 3' adapter. Internally, Cutadapt still searches for the 5' adapter first and then the 3' adapter, but you don’t need to run the tool twice. (And, in case that is relevant, by giving multiple linked adapters, you force Cutadapt to always pair up a certain 5' adapter with a certain 3' adapter.)

> To my understanding i have to remove 3' regular adapters in my data only in cases when the Read Length > Fragment Length. Am i right?

Yes, that is correct.

> If so i’d expect to observe approximately the same percentage of adapters in forward and reverse reads, but in my analysis it was not the case:

To judge the output that you pasted, one would need to know how the library was prepared and which actual command-line options you used. In particular, I’m not so sure whether you are removing Illumina adapters or the PCR primers.

> Should i adjust --overlap parameter at least to 5?

The minimum overlap exists to avoid false positives, but increasing it gives more false negatives (decreases sensitivity). Your R2 statistic is close to 50% occurrences, so I wonder whether these aren’t actually true matches that you would want to trim. However, your R1 occurrences don’t fit that. It’s hard to say without more context.

**Comment by DenisGoryunov** [comment]
Hi Marcel,
Many thanks for such a detailed reply. I'm sorry for the late reply. I'd like to remove PCR primers from the 5' ends of my forward and reverse reads (normally almost all of the reads have to contain these). In addition, in cases if Read Length > Fragment Length i need to remove from the reads another primer as 3' regular adapters and it would be expected to obtain the same percentage of reads with adapter in forward and reverse reads for such cases (as R1 and R2 reads have exactly the same length in each pair). When i've set up  --overlap parameter to 5 i got the following statistic for 3' regular adapters search and it looks more realistic in my opinion:

```
Total read pairs processed:            354,210
  Read 1 with adapter:                  17,008 (4.8%)
  Read 2 with adapter:                  16,749 (4.7%)
```

Will you plan to adjust Cutadapt in future to correctly treat such cases (e.g. use the whole R1 and R2 reads for pairwise alignment as implemented in Trimmomatic)?
Thank you again.

Regards,
Denis

**Comment by marcelm** [comment]
> In addition, in cases if Read Length > Fragment Length i need to remove from the reads another primer as 3' regular adapters

Then you can use a linked adapter. These were added for exactly this use case. When you write `-a ^FWDPRIMER...REVPRIMER`, the `REVPRIMER` is optional. That is, this will work correctly no matter the length of the read vs. the fragment length.

> Will you plan to adjust Cutadapt in future to correctly treat such cases

I would like to implement this, yes, but other things have had higher priority. Now that you got me thinking about this again, perhaps I’ll find some time to implement it, but no promises (#555 and probably #528 need to come first). Please subscribe to issue #332 to see whether I’m making any progress!

Closing this now since I hope I answered your questions, but feel free to ask more.
