### ISSUE TITLE
Adapter sequence incomplete at 5'?

### ISSUE THREAD

**Issue by eibol1** [marcelm/cutadapt#553]
Hi there,

First of all, sorry if I miss something, I am a beginner on this. I have cutadapt 3.4 with python 3.8.8.

I have my fastq files on which I am doing Cutadapt. For example, for Sample1, the UDI (adapter sequence) I used was this: **GTTCGTGA**.  When I get the report  I got this:
=== Summary ===

Total read pairs processed:         38,211,000
  Read 1 with adapter:               3,744,972 (9.8%)
  Read 2 with adapter:               3,744,972 (9.8%)
Pairs written (passing filters):    38,211,000 (100.0%)

Total basepairs processed: 11,539,722,000 bp
  Read 1: 5,769,861,000 bp
  Read 2: 5,769,861,000 bp
Total written (filtered):  11,353,163,709 bp (98.4%)
  Read 1: 5,678,679,224 bp
  Read 2: 5,674,484,485 bp

=== First read: Adapter 1 ===

Sequence: GTTCGTGA; Type: regular 3'; Length: 8; Trimmed: 3744972 times

No. of allowed errors:
1-8 bp: 0

Bases preceding removed adapters:
  A: 0.1%
  C: 99.7%
  G: 0.1%
  T: 0.2%
  none/other: 0.0%
WARNING:
    The adapter is preceded by "C" extremely often.
    The provided adapter sequence could be incomplete at its 5' end.

Overview of removed sequences
length	count	expect	max.err	error counts
3	128976	597046.9	0	128976
4	121120	149261.7	0	121120
5	115677	37315.4	0	115677
6	114053	9328.9	0	114053
7	112058	2332.2	0	112058
8	109895	583.1	0	109895
9	107436	583.1	0	107436
10	106793	583.1	0	106793
11	103429	583.1	0	103429
12	102780	583.1	0	102780
13	100313	583.1	0	100313
14	98339	583.1	0	98339
15	96088	583.1	0	96088
16	95578	583.1	0	95578
17	91747	583.1	0	91747
18	89469	583.1	0	89469
19	88153	583.1	0	88153
20	85351	583.1	0	85351
21	83238	583.1	0	83238
22	81380	583.1	0	81380
23	78833	583.1	0	78833
24	75854	583.1	0	75854
25	74906	583.1	0	74906
26	71721	583.1	0	71721
27	69599	583.1	0	69599
28	67348	583.1	0	67348
29	64953	583.1	0	64953
30	62294	583.1	0	62294
31	59908	583.1	0	59908
32	57247	583.1	0	57247
33	55807	583.1	0	55807
34	53085	583.1	0	53085
35	50628	583.1	0	50628
36	49058	583.1	0	49058
37	47262	583.1	0	47262
38	45131	583.1	0	45131
39	42801	583.1	0	42801
40	40794	583.1	0	40794
41	39075	583.1	0	39075
42	37027	583.1	0	37027
43	35294	583.1	0	35294
44	33654	583.1	0	33654
45	31745	583.1	0	31745
46	30535	583.1	0	30535
47	28884	583.1	0	28884
48	27762	583.1	0	27762
49	26116	583.1	0	26116
50	24446	583.1	0	24446
51	23443	583.1	0	23443
52	22154	583.1	0	22154
53	20777	583.1	0	20777
54	19527	583.1	0	19527
55	18403	583.1	0	18403
56	17544	583.1	0	17544
57	16018	583.1	0	16018
58	15257	583.1	0	15257
59	14157	583.1	0	14157
60	13631	583.1	0	13631
61	13064	583.1	0	13064
62	12125	583.1	0	12125
63	11367	583.1	0	11367
64	10410	583.1	0	10410
65	9680	583.1	0	9680
66	9038	583.1	0	9038
67	8398	583.1	0	8398
68	7840	583.1	0	7840
69	7220	583.1	0	7220
70	6686	583.1	0	6686
71	6229	583.1	0	6229
72	5895	583.1	0	5895
73	5334	583.1	0	5334
74	4583	583.1	0	4583
75	4261	583.1	0	4261
76	3764	583.1	0	3764
77	3312	583.1	0	3312
78	2845	583.1	0	2845
79	2549	583.1	0	2549
80	2136	583.1	0	2136
81	1819	583.1	0	1819
82	1506	583.1	0	1506
83	1266	583.1	0	1266
84	996	583.1	0	996
85	793	583.1	0	793
86	660	583.1	0	660
87	548	583.1	0	548
88	376	583.1	0	376
89	328	583.1	0	328
90	188	583.1	0	188
91	154	583.1	0	154
92	101	583.1	0	101
93	85	583.1	0	85
94	53	583.1	0	53
95	55	583.1	0	55
96	45	583.1	0	45
97	43	583.1	0	43
98	47	583.1	0	47
99	20	583.1	0	20
100	42	583.1	0	42
101	42	583.1	0	42
102	34	583.1	0	34
103	43	583.1	0	43
104	41	583.1	0	41
105	34	583.1	0	34
106	51	583.1	0	51
107	31	583.1	0	31
108	51	583.1	0	51
109	53	583.1	0	53
110	34	583.1	0	34
111	8	583.1	0	8
112	13	583.1	0	13
113	4	583.1	0	4
114	13	583.1	0	13
115	22	583.1	0	22
116	11	583.1	0	11
117	38	583.1	0	38
118	3470	583.1	0	3470
119	151	583.1	0	151
120	13	583.1	0	13
121	24	583.1	0	24
122	17	583.1	0	17
123	23	583.1	0	23
124	8	583.1	0	8
125	8	583.1	0	8
126	14	583.1	0	14
127	6	583.1	0	6
128	23	583.1	0	23
129	8	583.1	0	8
130	10	583.1	0	10
131	8	583.1	0	8
132	5	583.1	0	5
133	14	583.1	0	14
134	11	583.1	0	11
135	5	583.1	0	5
136	24	583.1	0	24
137	19	583.1	0	19
138	16	583.1	0	16
139	11	583.1	0	11
140	17	583.1	0	17
141	19	583.1	0	19
142	11	583.1	0	11
143	11	583.1	0	11
144	19	583.1	0	19
145	11	583.1	0	11
146	16	583.1	0	16
147	5	583.1	0	5
148	7	583.1	0	7
150	18	583.1	0	18
151	15	583.1	0	15

=== Second read: Adapter 2 ===

Sequence: AGTGCTTG; Type: regular 3'; Length: 8; Trimmed: 3744972 times

No. of allowed errors:
1-8 bp: 0

Bases preceding removed adapters:
  A: 0.2%
  C: 0.2%
  G: 0.4%
  T: 99.2%
  none/other: 0.0%
WARNING:
    The adapter is preceded by "T" extremely often.
    The provided adapter sequence could be incomplete at its 5' end.

Overview of removed sequences
length	count	expect	max.err	error counts
3	7695	597046.9	0	7695
4	121266	149261.7	0	121266
5	119487	37315.4	0	119487
6	115626	9328.9	0	115626
7	113701	2332.2	0	113701
8	112081	583.1	0	112081
9	109787	583.1	0	109787
10	107279	583.1	0	107279
11	106643	583.1	0	106643
12	103389	583.1	0	103389
13	102404	583.1	0	102404
14	100332	583.1	0	100332
15	98318	583.1	0	98318
16	95968	583.1	0	95968
17	95358	583.1	0	95358
18	91737	583.1	0	91737
19	89184	583.1	0	89184
20	88163	583.1	0	88163
21	85237	583.1	0	85237
22	83257	583.1	0	83257
23	81144	583.1	0	81144
24	78814	583.1	0	78814
25	75681	583.1	0	75681
26	74876	583.1	0	74876
27	71659	583.1	0	71659
28	69531	583.1	0	69531
29	67378	583.1	0	67378
30	64825	583.1	0	64825
31	62229	583.1	0	62229
32	59895	583.1	0	59895
33	57175	583.1	0	57175
34	55817	583.1	0	55817
35	53049	583.1	0	53049
36	50572	583.1	0	50572
37	48935	583.1	0	48935
38	47320	583.1	0	47320
39	45087	583.1	0	45087
40	42789	583.1	0	42789
41	40769	583.1	0	40769
42	39076	583.1	0	39076
43	36993	583.1	0	36993
44	35262	583.1	0	35262
45	33595	583.1	0	33595
46	31786	583.1	0	31786
47	30505	583.1	0	30505
48	28874	583.1	0	28874
49	27771	583.1	0	27771
50	26057	583.1	0	26057
51	24434	583.1	0	24434
52	23497	583.1	0	23497
53	22138	583.1	0	22138
54	20777	583.1	0	20777
55	19506	583.1	0	19506
56	18419	583.1	0	18419
57	17607	583.1	0	17607
58	15993	583.1	0	15993
59	15312	583.1	0	15312
60	14186	583.1	0	14186
61	13614	583.1	0	13614
62	13089	583.1	0	13089
63	12171	583.1	0	12171
64	11378	583.1	0	11378
65	10438	583.1	0	10438
66	9678	583.1	0	9678
67	9037	583.1	0	9037
68	8444	583.1	0	8444
69	7906	583.1	0	7906
70	7176	583.1	0	7176
71	6765	583.1	0	6765
72	6285	583.1	0	6285
73	5926	583.1	0	5926
74	5365	583.1	0	5365
75	4612	583.1	0	4612
76	4329	583.1	0	4329
77	3822	583.1	0	3822
78	3348	583.1	0	3348
79	2904	583.1	0	2904
80	2607	583.1	0	2607
81	2194	583.1	0	2194
82	1868	583.1	0	1868
83	1546	583.1	0	1546
84	1306	583.1	0	1306
85	1051	583.1	0	1051
86	840	583.1	0	840
87	693	583.1	0	693
88	607	583.1	0	607
89	435	583.1	0	435
90	422	583.1	0	422
91	245	583.1	0	245
92	185	583.1	0	185
93	146	583.1	0	146
94	127	583.1	0	127
95	94	583.1	0	94
96	100	583.1	0	100
97	116	583.1	0	116
98	96	583.1	0	96
99	80	583.1	0	80
100	74	583.1	0	74
101	89	583.1	0	89
102	77	583.1	0	77
103	85	583.1	0	85
104	63	583.1	0	63
105	95	583.1	0	95
106	88	583.1	0	88
107	109	583.1	0	109
108	99	583.1	0	99
109	90	583.1	0	90
110	93	583.1	0	93
111	88	583.1	0	88
112	64	583.1	0	64
113	84	583.1	0	84
114	64	583.1	0	64
115	63	583.1	0	63
116	69	583.1	0	69
117	73	583.1	0	73
118	92	583.1	0	92
119	3545	583.1	0	3545
120	223	583.1	0	223
121	81	583.1	0	81
122	82	583.1	0	82
123	82	583.1	0	82
124	76	583.1	0	76
125	54	583.1	0	54
126	88	583.1	0	88
127	65	583.1	0	65
128	65	583.1	0	65
129	65	583.1	0	65
130	99	583.1	0	99
131	81	583.1	0	81
132	87	583.1	0	87
133	99	583.1	0	99
134	86	583.1	0	86
135	62	583.1	0	62
136	76	583.1	0	76
137	67	583.1	0	67
138	89	583.1	0	89
139	50	583.1	0	50
140	61	583.1	0	61
141	82	583.1	0	82
142	72	583.1	0	72
143	87	583.1	0	87
144	103	583.1	0	103
145	74	583.1	0	74
146	74	583.1	0	74
147	86	583.1	0	86
148	78	583.1	0	78
149	69	583.1	0	69
150	55	583.1	0	55
151	60	583.1	0	60

WARNING:
    One or more of your adapter sequences may be incomplete.
    Please see the detailed output above.

I don't know if there is something wrong, but when I see the QC report, the % of adapter don't decrease. I mean I think adapters weren't remove. I expected a higher % of adapter trimmed but it isn't. I saw that there is a warning in the summary that the adapter is too short. Do you know if there is something wrong here?

Thank you !!!! Need help pls.

**Comment by eibol1** [comment]
Edit: Adapters in 5' were removed (Demultiplexing), what I want to remove is 3' adapters

**Comment by marcelm** [comment]
Hi, and sorry for the delay. I was on vacation and am only now catching up with Cutadapt issues.

Is this still relevant? If so, can you please provide the full command that you used? Also, what type of data is this? Amplicons, shotgun sequencing, etc.?

Not sure if that is relevant, but note that there is a [section concerning UDIs in the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#paired-adapters-dual-indices).

I’m a bit surprised that the adapter that you remove from read 1 (R1) is `GTTCGTGA`, whereas the adapter that you remove from read 2 (R2) is the reversed sequence `AGTGCTTG`. I’m not sure how your sequencing library is structured, so this could be totally fine, but I just wanted to point it out in case you actually wanted these sequences to be reverse complements of each other. Also, the adapters are quite short

> I saw that there is a warning in the summary that the adapter is too short.

If the library contains amplicons, then you can ignore the warning.

**Comment by eibol1** [comment]
Hi marcelm, 

I solve the problem, so it is now working well!

**Comment by marcelm** [comment]
> I solve the problem, so it is now working well!

Great!

You re-opened the issue. Was that by mistake? Can it be closed?

**Comment by marcelm** [comment]
Closing now, feel free to re-open if necessary.
