### ISSUE TITLE
Trim multiple unique dual indexes using --paired-adapter

### ISSUE THREAD

**Issue by AstroBioBen** [marcelm/cutadapt#560]
Hi Marcel, 

I'm using cutadapt version 3.4 in a Unix terminal with python 3.9.4 which was installed using conda. 

I'm attempting to trim demultiplexed pair-end reads which have unique dual indexes barcodes and primers using the --paired_adapaters function. The reads are in the following format...

*R1- ^barcodeTGTAprimerSEQUENCE
*R2- ^barcodeATCTACprimerSEQUENCE

For some reason, some of the barcodes for R1 can also be found in R2 and vice versa which means I need the paired_adapter function to search for both the forward and reverse barcodes. When I run this from the command line everything works well. My command line is...

"cutadapt --pair-adapters -g R1_barcode -g R2_barcode -G R2_barcode -G R1_barcode -o ./null -p ./null ./PATHTO/*_R1.fq.gz ./PATHTO/*_R2.fq.gz -j 6"

However, I have quite a few sequencing files which has led me to try and automate the process by writing the attached script
[cutadaptscript.txt](https://github.com/marcelm/cutadapt/files/7106601/cutadaptscript.txt) I was wondering if there is a way I can provide the "-g" and "-G" arguments with a .fasta tat contains multiple barcodes and primers in the format as described by "*R1 & *R2" above?

When I run it at the moment as "cutadapt --pair-adapters -g file:R1_barcodes.fasta -g file:R2_barcodes.fasta -G file:R2_barcodes.fasta -G file:R1_barcodes.fasta -o ./null -p ./null ./PATHTO/*_R1.fq.gz ./PATHTO/*_R2.fq.gz -j 6" none of the reads are being trimmed. 

Thank you in advance! 
Ben

**Comment by marcelm** [comment]
Assuming the first command does what you want it do for a single barcode pair, the second command you gave should also work, so I’m unsure what’s going on. The important thing when using `--pair-adapters` is that the order of R1 adapters (lowercase options) and R2 adapters (uppercase options) is relevant, and you seem to have gotten that right.

So just to confirm: As you would expect, when you write `-g file:one.fasta -g file:two.fasta`, the final list of adapters/sequences is all sequences from `one.fasta` (in the order in which they occur in the file), followed by all sequences from `two.fasta` (again, in the order in which they occur in the file).

It’s of course possible that there’s a bug, though.

You can try a couple of things to help find the problem:
- Use a different `R1_barcodes.fasta` and `R2_barcodes.fasta` file that contains only one barcode each. Does it work the same way as the first example?
- Now add one barcode to each of these files: Does that work?
- Run the original command, but leave out `--pair-adapter` and look at the statistics? Is anything trimmed?
- Can you get a result when you ignore that half of your reads have R1 and R2 swapped, that is, when you only provide `-g file:R1_barcodes.fasta -G file:R2_barcodes.fasta`?

I’ll need to add something to Cutadapt that allows to print out which barcode pairs it uses. That would make it apparent immediately if something is amiss.

By the way, I am planning to make the `--revcomp` option work for paired-end data as well. I assume that this is what is going on here: 50% of the DNA fragments are sequenced one way and 50% are sequenced the other way. When `--revcomp` is used, Cutadapt would try to trim R1/R2 as usual first and then swap R1/R2 and attempt the same (and keep the best result). With that, you could just provide `-g file:R1_barcodes.fasta -G file:R2_barcodes.fasta` and it would work correctly.

**Comment by AstroBioBen** [comment]
Hi Marcel, 

I have tested out your troubleshooting advice and the results are as follows.

1. I created a .fasta file that only contained one barcode which worked well. 
2. I added a second barcode and it ran into some issues. It worked perfectly on read one but appeared to not be able to detect adapter 1 on the second read (I should have mentioned prior the adapter for forward reads is the same for all samples). However, it did detect the reverse adapter in my forward reads which led it to remove the forward adapter from the reverse reads. I think despite what I was advised by the sequencing company I used these aren't UDI adapters... 
3.  I removed --paired adapters and It seemed to run perfectly for my barcodes but wasn't as good at removing the full-length barcodes and adapters in one go (95% - 100% of reads). Perhaps this confirms my last point.

Thank you for your quick response and help.

P.s. On a slight side note, I'm struggling to generate a report of the read trimming with the 2> argument. Am I correct in thinking this argument is meant to capturing the summary in a .txt file?

**Comment by marcelm** [comment]
I’ll have to think through your reply a bit, but can answer regarding this point:

> On a slight side note, I'm struggling to generate a report of the read trimming with the 2> argument. Am I correct in thinking this argument is meant to capturing the summary in a .txt file?

The report in your case is actually sent to stdout, so you need to use `>` instead of `2>` to redirect it to a file.

**Comment by marcelm** [comment]
Hi and sorry for the delay. This issue is still open, but I wonder whether I may have already given the answers you need. Do you think this can be closed or is there an open question?

**Comment by AstroBioBen** [comment]
Hi Marcel, Yes I think the issue is now solved and this can be closed. 

Thank you for all your help!

**Comment by marcelm** [comment]
Great, closing now :-)
