### ISSUE TITLE
Trimming NovaSeq PE data 

### ISSUE THREAD

**Issue by madzayasodara** [marcelm/cutadapt#563]
Hi, I have data with these adapters to trim
Sequences of adaptor

  5' Adapter:

  5'-AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT-3'

  3' Adapter(The underlined 6bp bases is Index):

  5'-GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG-3'

I tried to understand from the guide but am still quite confused about how to input adapter sequences.
I'm guessing the correct here would be:

Sequences of adapter
-a GATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG
-g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT

Thank you

**Comment by marcelm** [comment]
You can just follow these instructions: https://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq . That section also contains a link to "Illumina TruSeq Adapters De-Mystified", which talks about exactly those adapter sequences. I can recommend reading it in case you want to understand a bit more.

Illumina also [has something](https://emea.support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html).
