### ISSUE TITLE
de-multiplexing problem with pair-adapters

### ISSUE THREAD

**Issue by rezenman** [marcelm/cutadapt#570]
Hey all,
I am using cutadapt 2.6 with python 3.7.10 and I encounter a weird problem.
So I currently dealing with deep-sequencing data of 16S amplicons from multiple variable regions on the 16S gene.
I used different sets of primers to amplify different regions and then sequenced them all together,
I am trying to de-multiplex based on those primers using cutadapt and the following code:

    cutadapt \
        --pair-adapters \
        --no-indels \
        -g file:primers_16S_V1-9_qiagen_for.fasta \
        -G file:primers_16S_V1-9_qiagen_rev.fasta \
        -o {name1}_{name2}.1.fastq.gz -p {name1}_{name2}.2.fastq.gz \
        1_S1_L001_R1_001.fastq.gz 1_S1_L001_R2_001.fastq.gz

where my primer files look like that:

primers_16S_V1-9_qiagen_for.fasta:

    >V1V2_f
    AGRGTTTGATYMTGGCTC
    >V2V3_f
    GGCGNACGGGTGAGTAA
    >V3V4_f
    CCTACGGGNGGCWGCAG
    >V4V5_f
    GTGYCAGCMGCCGCGGTAA
    >V5V7_f
    GGATTAGATACCCBRGTAGTC
    >V7V9_f
    YAACGAGCGMRACCC

primers_16S_V1-9_qiagen_rev.fasta:

    >V1V2_r
    CTGCTGCCTYCCGTA
    >V2V3_r
    WTTACCGCGGCTGCTGG
    >V3V4_r
    GACTACHVGGGTATCTAATCC
    >V4V5_r
    CCGYCAATTYMTTTRAGTTT
    >V5V7_r
    ACGTCRTCCCCDCCTTCCTC
    >V7V9_r
    GCTGCGTTCTTCATCGATGC

My primers are not necessarily anchored so they can appear at any place in the reads.
When I demultiplex I almost don't get any matches to the V3V4f and V3V4r combination which is weird since I know it is a major part of my reads.

So I tried running the following code on the unknown reads only with the V3V4f and V3V4r combination:

    cutadapt \
        --pair-adapters \
        --no-indels \
        --action=none \
        -g CCTACGGGNGGCWGCAG \
        -G GACTACHVGGGTATCTAATCC \
        -o {name1}_{name2}.1.fastq.gz -p {name1}_{name2}.2.fastq.gz \
        unknown-unknown.1.fastq.gz unknown-unknown.2.fastq.gz

and lo and behold I get tens of thousands of reads matching the primer combination.

Does anybody have any idea what is happening here? I am sure I am missing something.
Why are those matches not found in my first run of cutadapt ?

Sorry for the long post and thank u for any suggestions

Cheers

**Comment by rezenman** [comment]
Hey, thanks for the quick reply,
Yes, I guess this is the case, unfortunately, I can't just do the same as I did cause I don't know which other amplicons are missing or misassigned.
So for now I'll just loop over each combination separately, this will solve the problem.
Another option for me is to only look for the primers in the first ~50bp cause that's where they suppose to be, is there any option of doing that directly with cutadapt? 
Anyhow a fix to the limitation will be amazing,
Thanks again :)

**Comment by marcelm** [comment]
I believe I have fixed the problem. Do you think you could [test the development version of Cutadapt](https://cutadapt.readthedocs.io/en/stable/installation.html#installing-the-development-version) and see whether the problem still occurs?

(For the record: To look for primers in the first 50 bp only, you could use a "non-internal 5' adapter" and prefix your primer with lots of `N` bases, something like this: `-g XN{33}CCTACGGGNGGCWGCAG`, but this is actually not terribly efficient.)

**Comment by rezenman** [comment]
Hey,
I tried the developer version, it does seem to fix the problem so now I am getting the lost reads, 
however the pair adapters option does not seem to work well since I get all optional combinations of the primers and not only the paired ones.
Attaching the command and the output here:

```
~/cutadapt-venv/bin/cutadapt \
         --pair-adapters \
        --no-indels \
         -g file:../../primers_16S_V1-9_qiagen_for.fasta \
         -G file:../../primers_16S_V1-9_qiagen_rev.fasta \
         -o {name1}_{name2}.1.fastq.gz -p {name1}_{name2}.2.fastq.gz \
        1_S1_L001_R1_001.fastq.gz 1_S1_L001_R2_001.fastq.gz
```
Output:
This is cutadapt 3.5.dev143+ge119a66 with Python 3.7.4
Command line parameters: --pair-adapters --no-indels -g file:../../primers_16S_V1-9_qiagen_for.fasta -G file:../../primers_16S_V1-9_qiagen_rev.fasta -o {name1}_{name2}.1.fastq.gz -p {name1}_{name2}.2.fastq.gz 1_S1_L001_R1_001.fastq.gz 1_S1_L001_R2_001.fastq.gz
Processing reads on 1 core in paired-end mode ...
Done           00:00:40       535,197 reads @  75.9 µs/read;   0.79 M reads/minute
Finished in 40.75 s (76 µs/read; 0.79 M reads/minute).

=== Summary ===

Total read pairs processed:            535,197
  Read 1 with adapter:                 451,274 (84.3%)
  Read 2 with adapter:                 451,274 (84.3%)
Pairs written (passing filters):       535,197 (100.0%)

Total basepairs processed:   295,428,744 bp
  Read 1:   147,714,372 bp
  Read 2:   147,714,372 bp
Total written (filtered):    274,948,399 bp (93.1%)
  Read 1:   137,317,196 bp
  Read 2:   137,631,203 bp

=== First read: Adapter V1V2_f ===

Sequence: AGRGTTTGATYMTGGCTC; Type: regular 5'; Length: 18; Trimmed: 136266 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-18 bp: 1

Overview of removed sequences
length  count   expect  max.err error counts
3       42      8362.5  0       42
4       22      2090.6  0       22
17      8       0.0     1       5 3
18      8535    0.0     1       8436 99
19      10407   0.0     1       10306 101
20      12200   0.0     1       12094 106
21      13186   0.0     1       13075 111
22      11837   0.0     1       11731 106
23      14459   0.0     1       14368 91
24      8328    0.0     1       8263 65
25      11304   0.0     1       11213 91
26      13025   0.0     1       12915 110
27      14082   0.0     1       13956 126
28      8596    0.0     1       8513 83
29      10212   0.0     1       10115 97
30      21      0.0     1       16 5
49      1       0.0     1       1
56      1       0.0     1       1


=== First read: Adapter V2V3_f ===

Sequence: GGCGNACGGGTGAGTAA; Type: regular 5'; Length: 17; Trimmed: 53906 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-16 bp: 1

Overview of removed sequences
length  count   expect  max.err error counts
3       1       8362.5  0       1
4       1       2090.6  0       1
13      1       0.0     1       1
16      24      0.0     1       23 1
17      4324    0.0     1       4242 82
18      3754    0.0     1       3707 47
19      5502    0.0     1       5428 74
20      4953    0.0     1       4885 68
21      5195    0.0     1       5138 57
22      4718    0.0     1       4663 55
23      4793    0.0     1       4747 46
24      4899    0.0     1       4842 57
25      4723    0.0     1       4684 39
26      3607    0.0     1       3551 56
27      4057    0.0     1       4011 46
28      3294    0.0     1       3261 33
29      4       0.0     1       4
36      1       0.0     1       1
95      2       0.0     1       1 1
96      4       0.0     1       3 1
97      1       0.0     1       1
99      1       0.0     1       1
100     1       0.0     1       1
101     1       0.0     1       1
102     4       0.0     1       2 2
103     5       0.0     1       5
104     3       0.0     1       3
105     4       0.0     1       3 1
106     3       0.0     1       2 1
107     2       0.0     1       1 1
108     2       0.0     1       2
110     1       0.0     1       1
112     2       0.0     1       2
113     4       0.0     1       4
114     3       0.0     1       2 1
115     1       0.0     1       1
116     2       0.0     1       2
118     3       0.0     1       3
119     1       0.0     1       1
120     1       0.0     1       1
122     1       0.0     1       1
123     2       0.0     1       2
124     1       0.0     1       1


=== First read: Adapter V3V4_f ===

Sequence: CCTACGGGNGGCWGCAG; Type: regular 5'; Length: 17; Trimmed: 62306 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-16 bp: 1

Overview of removed sequences
length  count   expect  max.err error counts
3       5       8362.5  0       5
4       5       2090.6  0       5
5       1       522.7   0       1
11      1       0.1     1       0 1
12      2       0.0     1       1 1
14      2       0.0     1       0 2
15      1       0.0     1       0 1
16      104     0.0     1       71 33
17      62130   0.0     1       61224 906
18      10      0.0     1       8 2
39      1       0.0     1       1
48      1       0.0     1       1
52      1       0.0     1       1
53      1       0.0     1       1
54      1       0.0     1       1
56      1       0.0     1       1
61      3       0.0     1       3
209     1       0.0     1       0 1
241     1       0.0     1       1
242     3       0.0     1       2 1
243     4       0.0     1       2 2
244     2       0.0     1       2
246     2       0.0     1       1 1
247     1       0.0     1       0 1
248     3       0.0     1       1 2
249     3       0.0     1       1 2
251     2       0.0     1       2
256     3       0.0     1       3
257     1       0.0     1       1
259     1       0.0     1       1
260     1       0.0     1       1
262     1       0.0     1       0 1
264     2       0.0     1       2
267     2       0.0     1       2
268     1       0.0     1       0 1
269     1       0.0     1       1
272     1       0.0     1       0 1


=== First read: Adapter V4V5_f ===

Sequence: GTGYCAGCMGCCGCGGTAA; Type: regular 5'; Length: 19; Trimmed: 110002 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1

Overview of removed sequences
length  count   expect  max.err error counts
3       1       8362.5  0       1
13      1       0.0     1       1
16      2       0.0     1       1 1
17      2       0.0     1       2
18      23      0.0     1       18 5
19      9954    0.0     1       9809 145
20      9582    0.0     1       9475 107
21      12956   0.0     1       12832 124
22      13533   0.0     1       13396 137
23      12917   0.0     1       12799 118
24      11045   0.0     1       10955 90
25      9652    0.0     1       9550 102
26      9587    0.0     1       9476 111
27      11698   0.0     1       11592 106
28      8973    0.0     1       8887 86
29      7       0.0     1       6 1
32      1       0.0     1       1
168     13      0.0     1       13
169     3       0.0     1       3
170     15      0.0     1       15
173     8       0.0     1       8
175     2       0.0     1       2
182     3       0.0     1       3
183     1       0.0     1       1
185     3       0.0     1       3
192     3       0.0     1       3
193     17      0.0     1       17


=== First read: Adapter V5V7_f ===

Sequence: GGATTAGATACCCBRGTAGTC; Type: regular 5'; Length: 21; Trimmed: 88789 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20-21 bp: 2

Overview of removed sequences
length  count   expect  max.err error counts
3       2       8362.5  0       2
19      1       0.0     1       0 1
20      23      0.0     2       14 5 4
21      5805    0.0     2       5717 76 12
22      8285    0.0     2       8188 83 14
23      7310    0.0     2       7212 72 26
24      9255    0.0     2       9135 104 16
25      8903    0.0     2       8800 88 15
26      8372    0.0     2       8287 73 12
27      6694    0.0     2       6607 71 16
28      7353    0.0     2       7268 69 16
29      7524    0.0     2       7434 80 10
30      7275    0.0     2       7186 76 13
31      5701    0.0     2       5625 65 11
32      6281    0.0     2       6209 64 8
33      4       0.0     2       4
52      1       0.0     2       1


=== First read: Adapter V7V9_f ===

Sequence: YAACGAGCGMRACCC; Type: regular 5'; Length: 15; Trimmed: 5 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-15 bp: 1

Overview of removed sequences
length  count   expect  max.err error counts
15      1       0.0     1       1
18      1       0.0     1       1
23      2       0.0     1       2
26      1       0.0     1       1


=== Second read: Adapter V1V2_r ===

Sequence: CTGCTGCCTYCCGTA; Type: regular 5'; Length: 15; Trimmed: 136266 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-15 bp: 1

Overview of removed sequences
length  count   expect  max.err error counts
3       11      8362.5  0       11
4       4       2090.6  0       4
6       4       130.7   0       4
13      1       0.0     1       0 1
14      20      0.0     1       17 3
15      14548   0.0     1       12077 2471
16      14282   0.0     1       12775 1507
17      11397   0.0     1       11250 147
18      12234   0.0     1       12111 123
19      16536   0.0     1       16361 175
20      16728   0.0     1       16508 220
21      16820   0.0     1       16652 168
22      9421    0.0     1       9315 106
23      11401   0.0     1       11247 154
24      12779   0.0     1       12660 119
25      20      0.0     1       18 2
29      2       0.0     1       2
38      1       0.0     1       1
47      1       0.0     1       1
49      1       0.0     1       1
50      1       0.0     1       1
57      1       0.0     1       1
68      1       0.0     1       0 1
74      2       0.0     1       0 2
75      1       0.0     1       0 1
76      3       0.0     1       1 2
77      5       0.0     1       1 4
79      5       0.0     1       3 2
80      1       0.0     1       0 1
81      1       0.0     1       0 1
82      4       0.0     1       0 4
83      2       0.0     1       0 2
84      1       0.0     1       0 1
85      2       0.0     1       0 2
167     1       0.0     1       1
168     2       0.0     1       2
169     2       0.0     1       1 1
170     3       0.0     1       3
171     2       0.0     1       2
172     1       0.0     1       1
173     2       0.0     1       2
174     1       0.0     1       1
187     1       0.0     1       1
192     2       0.0     1       2
195     1       0.0     1       1
196     1       0.0     1       1
197     4       0.0     1       4
198     1       0.0     1       1
200     1       0.0     1       1


=== Second read: Adapter V2V3_r ===

Sequence: WTTACCGCGGCTGCTGG; Type: regular 5'; Length: 17; Trimmed: 53906 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-17 bp: 1

Overview of removed sequences
length  count   expect  max.err error counts
3       2       8362.5  0       2
4       8       2090.6  0       8
7       2       32.7    0       2
9       3       2.0     0       3
13      1       0.0     1       1
16      9       0.0     1       5 4
17      7248    0.0     1       7168 80
18      8140    0.0     1       8002 138
19      5064    0.0     1       4943 121
20      5503    0.0     1       5393 110
21      8520    0.0     1       8380 140
22      8505    0.0     1       8364 141
23      5223    0.0     1       4851 372
24      5656    0.0     1       5397 259
25      15      0.0     1       14 1
26      1       0.0     1       1
74      1       0.0     1       0 1
77      1       0.0     1       0 1
78      2       0.0     1       0 2
79      1       0.0     1       0 1
82      1       0.0     1       0 1


=== Second read: Adapter V3V4_r ===

Sequence: GACTACHVGGGTATCTAATCC; Type: regular 5'; Length: 21; Trimmed: 62306 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20-21 bp: 2

Overview of removed sequences
length  count   expect  max.err error counts
3       12      8362.5  0       12
14      1       0.0     1       0 1
16      1       0.0     1       1
17      1       0.0     1       0 1
18      7       0.0     1       3 4
19      2       0.0     1       1 1
20      88      0.0     2       28 24 36
21      62137   0.0     2       60905 1059 173
22      15      0.0     2       9 2 4
31      1       0.0     2       1
51      1       0.0     2       1
63      2       0.0     2       2
71      1       0.0     2       1
78      1       0.0     2       1
79      1       0.0     2       0 0 1
80      1       0.0     2       0 1
81      2       0.0     2       0 0 2
82      1       0.0     2       0 1
143     1       0.0     2       1
145     2       0.0     2       2
146     3       0.0     2       2 1
147     1       0.0     2       1
148     3       0.0     2       3
149     2       0.0     2       2
150     3       0.0     2       3
151     5       0.0     2       5
152     2       0.0     2       1 0 1
153     1       0.0     2       0 0 1
156     1       0.0     2       1
206     1       0.0     2       1
208     2       0.0     2       2
209     3       0.0     2       3
211     1       0.0     2       1


=== Second read: Adapter V4V5_r ===

Sequence: CCGYCAATTYMTTTRAGTTT; Type: regular 5'; Length: 20; Trimmed: 110002 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20 bp: 2

Overview of removed sequences
length  count   expect  max.err error counts
3       156     8362.5  0       156
4       2       2090.6  0       2
5       1       522.7   0       1
18      2       0.0     1       2
19      14      0.0     1       11 3
20      5761    0.0     2       4643 1053 65
21      5306    0.0     2       5043 248 15
22      8711    0.0     2       8465 208 38
23      8958    0.0     2       8249 677 32
24      10478   0.0     2       9359 996 123
25      8637    0.0     2       8157 446 34
26      9809    0.0     2       9625 165 19
27      8284    0.0     2       8068 190 26
28      12336   0.0     2       9631 2622 83
29      10502   0.0     2       7367 2868 267
30      11200   0.0     2       9911 1242 47
31      9783    0.0     2       9607 152 24
32      26      0.0     2       23 2 1
33      2       0.0     2       2
34      1       0.0     2       1
35      1       0.0     2       0 1
38      1       0.0     2       1
48      1       0.0     2       1
49      1       0.0     2       1
78      1       0.0     2       0 0 1
79      1       0.0     2       0 0 1
80      3       0.0     2       0 0 3
81      2       0.0     2       0 0 2
82      2       0.0     2       0 1 1
83      3       0.0     2       0 1 2
84      3       0.0     2       0 0 3
85      5       0.0     2       0 0 5
86      2       0.0     2       0 0 2
87      1       0.0     2       0 0 1
88      1       0.0     2       0 0 1
89      4       0.0     2       0 2 2
90      1       0.0     2       0 1


=== Second read: Adapter V5V7_r ===

Sequence: ACGTCRTCCCCDCCTTCCTC; Type: regular 5'; Length: 20; Trimmed: 88789 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20 bp: 2

Overview of removed sequences
length  count   expect  max.err error counts
3       10      8362.5  0       10
4       2       2090.6  0       2
18      1       0.0     1       1
19      8       0.0     1       3 5
20      8619    0.0     2       8340 249 30
21      10446   0.0     2       10234 183 29
22      9454    0.0     2       9199 218 37
23      8655    0.0     2       8211 414 30
24      9390    0.0     2       8894 456 40
25      10071   0.0     2       9777 265 29
26      8793    0.0     2       8613 153 27
27      7545    0.0     2       7352 171 22
28      8202    0.0     2       7913 248 41
29      7547    0.0     2       6765 743 39
30      7       0.0     2       6 1
50      1       0.0     2       1
75      1       0.0     2       0 0 1
78      1       0.0     2       0 0 1
79      3       0.0     2       0 0 3
80      5       0.0     2       0 2 3
81      4       0.0     2       0 1 3
82      6       0.0     2       0 1 5
83      6       0.0     2       0 1 5
84      1       0.0     2       0 0 1
85      4       0.0     2       0 2 2
86      1       0.0     2       1
87      5       0.0     2       0 1 4
88      1       0.0     2       0 1


=== Second read: Adapter V7V9_r ===

Sequence: GCTGCGTTCTTCATCGATGC; Type: regular 5'; Length: 20; Trimmed: 5 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20 bp: 2

Overview of removed sequences
length  count   expect  max.err error counts
3       5       8362.5  0       5

**Comment by marcelm** [comment]
> the pair adapters option does not seem to work well since I get all optional combinations of the primers and not only the paired ones.

Can you explain? What do you mean by optional? It seems that at least primers have been removed in pairs because the number of removed adapters is the same for R1 and R2.

**Comment by rezenman** [comment]
Oh, sorry you're right, 
I thought so since it still creates files for all different combinations but they are empty, so I think that's the only issue.
Other than that all good,
Thanks a lot!

**Comment by marcelm** [comment]
Ah, well that’s another bug to fix then!

**Comment by marcelm** [comment]
Actually, thinking about it, you should just switch to using `{name}` in your output file name template, not `{name1}` and `{name2}`.

Then the bug is not that so many files are created, but that Cutadapt allows you to use `{name1}` and `{name2}` in the file name template when `--pair-adapters` is specified. I’ll open a separate issue for that and close this one now. I’ll release Cutadapt 3.5 soon with the fixed `--pair-adapters` behavior.
