### ISSUE TITLE
Paired end linked adapter removing more length than expected

### ISSUE THREAD

**Issue by ursulahneumann** [marcelm/cutadapt#573]
- Cutadapt and Python version
     - This is cutadapt 3.5 with Python 3.9.5
- How you installed the tool (conda or pip, for example)
     - conda
- Which command-line parameters you used
```    
cutadapt -a "CCTACGGGNGGCWGCAG;min_overlap=5...GGATTAGATACCCBDGTAGTC;min_overlap=5" \
    -A "GACTACHVGGGTATCTAATCC;min_overlap=5...CTGCWGCCNCCCGTAGG;min_overlap=5" \
    --discard-untrimmed \
    -o cut_${id}_L001_R1_001.fastq.gz \
    -p cut_${id}_L001_R2_001.fastq.gz ${id}_L001_R1_001.fastq.gz ${id}_L001_R2_001.fastq.gz
```

**Questions**
==========================================================================

1) My data is the V3V4 region (~460 bp amplicon) of the 16S rRNA gene with a 17 bp forward primer and 21 bp reverse primer; 2 x 300 bp reads.  I used the recipe _"Trimming (amplicon-) primers from both ends of paired-end reads"_, the cutadapt output is below.  I was expecting the maximum length removed to be 18 for the forward primer and 23 for the reverse primer given the allowed errors, but there are instances of 61 to 282 bp being removed.  It is only a few reads so it's not that concerning, I'm just wondering what could be causing this since it goes against my understanding of what I thought would happen.  Would the primer be found internally causing more to be trimmed? 

2) Minor question, the output says _=== First read: Adapter 3 ===_ and _=== Second read: Adapter 6 ===_, what to the 3 and the 6 represent?

Thank you!

**Example output for one file:**
==========================================================================
This is cutadapt 3.5 with Python 3.9.5
Command line parameters: -a CCTACGGGNGGCWGCAG;min_overlap=5...GGATTAGATACCCBDGTAGTC;min_overlap=5 -A GACTACHVGGGTATCTAATCC;min_overlap=5...CTGCWGCCNCCCGTAGG;min_overlap=5 --discard-untrimmed -o cut_Li21690_S41_L001_R1_001.fastq.gz -p cut_Li21690_S41_L001_R2_001.fastq.gz Li21690_S41_L001_R1_001.fastq.gz Li21690_S41_L001_R2_001.fastq.gz
Processing reads on 1 core in paired-end mode ...
Finished in 1.37 s (49 µs/read; 1.23 M reads/minute).

=== Summary ===

Total read pairs processed:             28,193
  Read 1 with adapter:                  28,032 (99.4%)
  Read 2 with adapter:                  27,988 (99.3%)

== Read fate breakdown ==
Pairs discarded as untrimmed:              360 (1.3%)
Pairs written (passing filters):        27,833 (98.7%)

Total basepairs processed:    16,901,284 bp
  Read 1:     8,462,817 bp
  Read 2:     8,438,467 bp
Total written (filtered):     15,626,997 bp (92.5%)
  Read 1:     7,880,723 bp
  Read 2:     7,746,274 bp

=== First read: Adapter 3 ===

Sequence: CCTACGGGNGGCWGCAG...GGATTAGATACCCBDGTAGTC; Type: linked; Length: 17+21; 5' trimmed: 27956 times; 3' trimmed: 136 times

Minimum overlap: 5+5
No. of allowed errors:
1-9 bp: 0; 10-16 bp: 1

No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20-21 bp: 2

Overview of removed sequences at 5' end
length	count	expect	max.err	error counts
15	2	0.0	1	1 1
16	406	0.0	1	13 393
17	27431	0.0	1	26404 1017 10
18	117	0.0	1	7 110

Overview of removed sequences at 3' end
length	count	expect	max.err	error counts
20	5	0.0	2	0 3 2
21	122	0.0	2	57 56 9
22	3	0.0	2	1 2
23	1	0.0	2	0 0 1
64	1	0.0	2	0 0 1
156	1	0.0	2	1
240	1	0.0	2	0 1
281	1	0.0	2	0 0 1
282	1	0.0	2	1

=== Second read: Adapter 6 ===

Sequence: GACTACHVGGGTATCTAATCC...CTGCWGCCNCCCGTAGG; Type: linked; Length: 21+17; 5' trimmed: 27980 times; 3' trimmed: 68 times

Minimum overlap: 5+5
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20-21 bp: 2

No. of allowed errors:
1-9 bp: 0; 10-16 bp: 1

Overview of removed sequences at 5' end
length	count	expect	max.err	error counts
19	12	0.0	1	1 1 10
20	617	0.0	2	12 486 119
21	27071	0.0	2	26204 718 147 2
22	275	0.0	2	6 219 49 1
23	5	0.0	2	0 0 3 2

Overview of removed sequences at 3' end
length	count	expect	max.err	error counts
11	1	0.0	1	0 1
16	4	0.0	1	0 2 1 1
17	60	0.0	1	6 46 4 4
61	1	0.0	1	1
132	1	0.0	1	0 1
275	1	0.0	1	1

**Comment by ursulahneumann** [comment]
Thank you for your help! When I run the command below I get an error _"cutadapt: error: Allowed placement restrictions for a 3' adapter are ADAPTERX and ADAPTER$"._ Should the ```-A``` be changed to a ```-G```?

``` 
cutadapt -g '^CCTACGGGNGGCWGCAG' -A '^GACTACHVGGGTATCTAATCC' \
    --discard-untrimmed \
    -o cut_${id}_L001_R1_001.fastq.gz \
    -p cut_${id}_L001_R2_001.fastq.gz ${id}_L001_R1_001.fastq.gz ${id}_L001_R2_001.fastq.gz
```

**Comment by marcelm** [comment]
Just cleaning up old issues: It appears this one can be closed.
