### ISSUE TITLE
Reporting multiple adaptors

### ISSUE THREAD

**Issue by igoronzy** [marcelm/cutadapt#577]
Is there a simple hack to figure out all the adaptors that were found during a round of search, not just the first in the fasta file?

**Comment by marcelm** [comment]
Can you clarify: What is one round of search for you? Which FASTA file? Perhaps it’s easiest to show the command-line arguments that you are using.

I’m asking because Cutadapt by default only removes at most one adapter from each read (counting linked adapters as "one"). Are you using `--times` to increase the number of rounds?

**Comment by igoronzy** [comment]
I wanted to use cutadapt to identify multiple adapters present in a single read. My fasta file contains 96 possible adapters and 6 should be present in each read. The order of these 6 is not known in advance. 
When I use --times, the adapter listed earliest in the fasta is trimmed, but this is not necessarily the rightmost adapter in the sequence. Part of the sequence that contains unreported adapters can be trimmed away.
I was wondering if there was a simple hack to report all equal matches (ie. all 6 possible matches) instead of just one?

**Comment by marcelm** [comment]
I don’t think this is possible using the command-line `cutadapt`. Are you comfortable with Python? I am trying to see whether I can make parts of Cutadapt available as an API, so to see how well your use case would be covered, I wrote a little script that I think can do what you asked. It uses Cutadapt’s alignment algorithm to search for each of the adapters one by one (not very efficient, sorry). (Writing this, I see that the FLAGS thing is confusing and I need to change that.)
```
#!/usr/bin/env python3

import sys
import random
from cutadapt.align import Aligner, START_WITHIN_SEQ2, STOP_WITHIN_SEQ2
import dnaio

# Adapter occurrence is allowed to start anywhere within the
# read (seq2) and end anywhere within the read
FLAGS = START_WITHIN_SEQ2 | STOP_WITHIN_SEQ2


def make_aligners(fasta):
    with dnaio.open(fasta) as f:
        aligners = {
            record.name: Aligner(record.sequence.upper(), max_error_rate=0.1, flags=FLAGS)
            for record in f
        }
    return aligners


def find_adapters_in_record(aligners, record):
    found = 0
    for adapter_name, aligner in aligners.items():
        result = aligner.locate(record.sequence.upper())
        if result is None:
            continue
        adapter_start, adapter_stop, read_start, read_stop, matches, errors = result
        print(f"On read {record.name}, adapter {adapter_name} found at {read_start}..{read_stop}")
        # or in TSV format:
        # print(read_start, adapter_name, read_stop, errors, sep="\t")
        found += 1
        if found == 6:
            # Stop when we found six occurrences to save a little bit of time
            break


def main():
    aligners = make_aligners(sys.argv[1])
    with dnaio.open(sys.argv[2]) as f:
        for record in f:
            find_adapters_in_record(aligners, record)


if __name__ == "__main__":
    main()
```

**Comment by igoronzy** [comment]
Thanks! 
Yes, I'm comfortable with python. I downloaded the source code and was trying to write a work-around to make match_to() from the MultipleAdapters Class print all adapters found. This is a much cleaner solution.
