### ISSUE TITLE
q2-cutadapt in a very specific case: advice?

### ISSUE THREAD

**Issue by marwa38** [marcelm/cutadapt#579]
Hello 

I am using the qiime2 2021.11 to run again on a different dataset while I need to use deblur and to do so, I need to pre-use cutadapt (`q2-cutadapt`) to trim/truncate what deblur can't truncate (like in case dada2).
Could you please help with choosing if my dada2 code is as following

    qiime dada2 denoise-paired \
      --i-demultiplexed-seqs paired-end-demux.qza \
      --p-trunc-len-f 250 \
      --p-trunc-len-r 200 \
      --o-table dada2-table.qza \
      --p-n-threads 0 \
      --o-representative-sequences dada2-rep-seqs.qza \
      --o-denoising-stats dada2-denoising-stats.qza \
      --verbose
 
so what I can do in cutadapt to have the same result that come out from dada2 
So that I can merge both forward and reverse reads to be used to Deblur 

My sequences are already trimmed using trimGalore outside qiime2 which I tried before and worked fine for my results when compared to using Rstudio (was doing some trials)
In our group, we use trimGalore followed up by dada2 to get rid of the unneeded sequences 

Thanks very much

**Comment by marcelm** [comment]
Hi, I am very sorry, but I don’t think I can help with that question as I am not familiar with qiime nor q2-cutadapt. Perhaps you can try asking at https://github.com/qiime2/q2-cutadapt, where the QIIME 2 Cutadapt plugin is maintained? Or ask the dada2 maintainers.
