### ISSUE TITLE
cutadapt: error: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by adarshdas1995** [marcelm/cutadapt#580]
Cutadapt: 2.8
Python: 3.7
I am trying to get `cutadapt` running on a fairly large dataset (each fastq.gz file is about 3-4 gigs). We are using `cromwell` along with `slurm` in the backend. I am constantly running into the above-mentioned error. I have about 3-4 TB of free drive space and about 10 GB or free space in my `/tmp` directory. I tried running the code with `--debug` flag but there was no new information in the output. I am attaching the screenshots of the input params and the final output.
Any ideas? 

Params
---
![Parameters](https://user-images.githubusercontent.com/42201757/143579616-692bea4e-0d18-4679-81e8-f9946f78954c.png)
---
Error log
---
![Error-Log](https://user-images.githubusercontent.com/42201757/143579609-c02cfc38-cedf-41ff-99ba-ec3480cefc80.png)

**Comment by marcelm** [comment]
Perhaps you have run out of inodes (I think the error messages are identical). Try `df -i` to check

**Comment by adarshdas1995** [comment]
So I went ahead and ran `df -i` and we have a very high limit for inodes on our server setup. And we are nowhere close to hitting them. I am attaching a screenshot of it. Any other ideas about what could cause it?
---
example
---
![Screenshot 2021-11-29 at 12 35 42 PM](https://user-images.githubusercontent.com/42201757/143823120-61008015-7122-4478-b72b-e7016c97ce26.png)

**Comment by rhpvorderman** [comment]
I see you are using BioWDL, which I happen to be one of the maintainers of. Your jobs will run in a container by default.
I believe cromwell mounts the execution directory. Can you perform a `df -h` on the cromwell executions folder where the job is running?

**Comment by adarshdas1995** [comment]
The issue was resolved by using another node in the slurm backend. Not really 100% sure what the issue was as we have a shared file system for all the nodes.

**Comment by rhpvorderman** [comment]
@adarshdas1995 It usually has to do with /tmp being full on a particular node. That has bitten us as well in the past.
