### ISSUE TITLE
clarification of minimum overlap?

### ISSUE THREAD

**Issue by matt-sexton** [marcelm/cutadapt#584]
I was surprised to see cutadapt trim 5 bases from the end of a read when the minimum overlap for the 3' adapter was specified as 6.  My guess is that this is the alignment cutadapt found:

```
READ:    ATAGCAAGA_CG
ADAPTER:       AGATCGGAAGAGCACACGTCT
```
and that cutadapt is really measuring the span of the portion of the adapter that was aligned, which may included deleted bases.  Is that the case?  Are substitutions also included in the count?  (Note that I have shortened the read for clarity.  The behavior is the same with the full read.)

Based on the description in the documentation, I had thought the overlap measured the number of matching bases.  For instance:

> the alignment algorithm requires that, by default, at least three bases match between adapter and read

would seem to imply that the overlap is just counting matching bases.

Thank you for any clarification you can provide.

This was the input:

```
>120570-BC04-0000000127
ATAGCAAGACG
```

And the output:

```
>120570-BC04-0000000127
ATAGCA
```

And the run of cutadapt, version 3.5.

```
This is cutadapt 3.5 with Python 3.8.10
Command line parameters: -a AGATCGGAAGAGCACACGTCT -e 0.2 -O 6 127.fa -o 127-trimmed.fa
Processing reads on 1 core in single-end mode ...
Done           00:00:00             1 reads @ 6721.7 µs/read;   0.01 M reads/minute
Finished in 0.01 s (14301 µs/read; 0.00 M reads/minute).

=== Summary ===

Total reads processed:                       1
Reads with adapters:                         1 (100.0%)
Reads written (passing filters):             1 (100.0%)

Total basepairs processed:            11 bp
Total written (filtered):              6 bp (54.5%)

=== Adapter 1 ===

Sequence: AGATCGGAAGAGCACACGTCT; Type: regular 3'; Length: 21; Trimmed: 1 times

Minimum overlap: 6
No. of allowed errors:
1-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3; 20-21 bp: 4

Bases preceding removed adapters:
  A: 100.0%
  C: 0.0%
  G: 0.0%
  T: 0.0%
  none/other: 0.0%

Overview of removed sequences
length	count	expect	max.err	error counts
5	1	0.0	1	0 1
```

**Comment by marcelm** [comment]
> cutadapt is really measuring the span of the portion of the adapter that was aligned, which may included deleted bases.

Yes, that is the case. The overlap length is the number of bases in the adapter that got aligned to the read.

>>  the alignment algorithm requires that, by default, at least three bases match between adapter and read

> would seem to imply that the overlap is just counting matching bases.

I see how this can be understood the wrong way, you’re right. I’ll reword that sentence in the documentation.

I don’t remember, but the reason I wrote it this way may have been that I was thinking about the default settings (10% maximum error rate, minimum overlap length 3), for which there cannot be any mismatches or indels in the overlap, only matches.

**Comment by matt-sexton** [comment]
Thank you for the clarification.
