### ISSUE TITLE
Adapter sequence

### ISSUE THREAD

**Issue by cdanmaigona** [marcelm/cutadapt#587]
How do I specify these adapters sequences in the cutadapt command? 

![Normalase UDI](https://user-images.githubusercontent.com/57462926/146839445-8a4e534e-4660-4ca7-b208-38cc0b7a8fa7.png)

index 1 (i7) Adapters
5' - GATCGGAAGAGCACACGTCTGAACTCCAGTCAXXXXXXXXXXATCTCGTATGCCGTCTTCTGCTTG -3'

Index 2 (i5) Adapters
5' - AATGATACGGCGACCACCGAGATCTACAYYYYYYYYYYACACTCTTTCCCTACACGACGCTCTTCCGATCT -3'

**Comment by marcelm** [comment]
These look like standard Illumina adapters. If you want to remove them, follow the [Illumina TruSeq instructions in the documentation](https://cutadapt.readthedocs.io/en/latest/guide.html#illumina-truseq).

* `-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA` is the part before the XXXXX section in the index 1 adapter plus an extra A in the beginning. When found, the sequence after it (the P7 adapter) will also be removed, so it’s not a problem to specify only the first part). 
* `-A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT` is the reverse complement of the sequence after the YYYYYY section in the index 2 adapter.

**Comment by cdanmaigona** [comment]
Thank you!
