### ISSUE TITLE
Forward reads on FWD.Reverse and REV.Forward

### ISSUE THREAD

**Issue by emdida** [marcelm/cutadapt#588]
Hi, so when counting the primers I got the following output:
Forward Complement Reverse RevComp
FWD.ForwardReads 26848 0 0 0
FWD.ReverseReads 2 0 0 30
REV.ForwardReads 3 0 0 39
REV.ReverseReads 26088 0 0 0

Then I used cutadapt to remove primers:
cutadapt <- "/Users/didaskalouea/miniconda3/envs/cutadaptenv/bin/cutadapt" # CHANGE ME to the cutadapt path on your machine
system2(cutadapt, args = "--version") # Run shell commands from R

path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))

FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)

Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC)

Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC)

Run Cutadapt
for(i in seq_along(fnFs)) {
system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
"-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
fnFs.filtN[i], fnRs.filtN[i])) # input files
}

But I still have some forward reads on FWD.ReverseReads and REV.ForwardReads:
Forward Complement Reverse RevComp
FWD.ForwardReads 0 0 0 0
FWD.ReverseReads 2 0 0 0
REV.ForwardReads 3 0 0 0
REV.ReverseReads 0 0 0 0

What can I do to remove these primers?

**Comment by marcelm** [comment]
You can ignore these 5 remaining primer occurrences. They refer to occurrences in the wrong orientation and/or on the wrong read. Getting a few of these is totally normal.

(By the way, it is helpful to give a bit more context when reporting errors. It appears you are following [this tutorial](https://benjjneb.github.io/dada2/ITS_workflow.html), and I had to google this in order to understand what you are actually trying to do.)

**Comment by emdida** [comment]
Thanks a lot!! Yes, you're right. I should have been more clear with that, will keep it in mind for next time.

**Comment by marcelm** [comment]
Great, closing this then.
