### ISSUE TITLE
No pre-compiled wheels for Windows

### ISSUE THREAD

**Issue by peterjc** [marcelm/cutadapt#589]
Currently https://pypi.org/project/cutadapt/#files has Linux wheels for Python 3.6, 3.7, 3.8, 3.9 and 3.10 - plus a ``.tar.gz`` archive of the source code. This means ``pip install cutadapt`` on Windows attempts to compile things:

```
$ pip install cutadapt
Collecting cutadapt
  Using cached cutadapt-3.5.tar.gz (303 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting dnaio~=0.5
  Using cached dnaio-0.6.0.tar.gz (131 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting xopen~=1.1
  Using cached xopen-1.2.1-py3-none-any.whl (12 kB)
Collecting isal>=0.9.0
  Using cached isal-0.11.1-cp310-cp310-win_amd64.whl (274 kB)
Using legacy 'setup.py install' for dnaio, since package 'wheel' is not installed.
Building wheels for collected packages: cutadapt
  Building wheel for cutadapt (pyproject.toml): started
  Building wheel for cutadapt (pyproject.toml): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\xxx\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe' 'C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\xxx\AppData\Local\Temp\tmp0a8lowdp'
       cwd: C:\Users\xxx\AppData\Local\Temp\pip-install-n29oeudt\cutadapt_10e512be8b9643199f3079ff9d38e975
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\adapters.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\align.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\filters.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\json.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\log.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\modifiers.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\parser.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\pipeline.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\report.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\statistics.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\steps.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\tokenizer.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\utils.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\_version.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\__init__.py -> build\lib.win-amd64-3.10\cutadapt
  copying src\cutadapt\__main__.py -> build\lib.win-amd64-3.10\cutadapt
  running build_ext
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for cutadapt
Failed to build cutadapt
ERROR: Could not build wheels for cutadapt, which is required to install pyproject.toml-based projects

```

https://cutadapt.readthedocs.io/en/stable/installation.html#installation-on-windows highlights that the GitHub releases page often has a ``.exe`` file for Windows. Would it be easy for you to make a Windows wheel as well / instead of the EXE?

**Comment by rhpvorderman** [comment]
I just successfully build wheels for fastq-filter for all major platforms using CIbuildwheel. This is my github actions yaml: https://github.com/LUMC/fastq-filter/blob/develop/.github/workflows/ci.yml#L100

In the above example I had problems with pp38 wheels on Windows, so I just disabled PyPy builds alltogether. PyPy does not work well with C-extensions. In fact, it is incredibly slow when calling them. So it is not a problem.

It is quite doable. I also do it for python-isal, but that setup is more involved since it also has to statically link the ISA-L library. So above example is easier to start from.

**Comment by peterjc** [comment]
PyPy *can* work well with C-extensions, but I agree that skipping building PyPy wheels is pragmatic.

Having the wheels built via continuous integration sounds like a good idea 👍

**Comment by marcelm** [comment]
I already use cibuildwheel, so it wasn’t that much work. Can you test the Windows wheels I just uploaded to TestPyPI? Use `pip install -i https://test.pypi.org/simple/ cutadapt==3.6.dev2` to install. If they work, I’ll publish wheels to regular PyPI as well.

Since Cutadapt is an application, not a library, I don’t see the benefit of supporting both PyPy and CPython. I’ll think about macOS builds when someone requests that.

**Comment by rhpvorderman** [comment]
>  Use `pip install -i https://test.pypi.org/simple/ cutadapt==3.6.dev2`

That can give an error due to the xopen, dnaio and python-isal dependencies.  `pip install -i https://test.pypi.org/simple/  --extra-index-url https://pypi.org/simplecutadapt==3.6.dev2` will find the dependencies which are not on test pypi.

**Comment by peterjc** [comment]
I tried that under Python 3.10 on Windows 10, but it got stuck trying to compile dnaio v0.6.0

(Sadly I'm not able to install MSVC on the machine in question)

**Comment by marcelm** [comment]
> Sadly I'm not able to install MSVC on the machine in question

Thanks. I’ll need to make Windows wheels for dnaio as well.

> That can give an error due to the xopen, dnaio and python-isal dependencies

Good point, I forgot (and just copied what TestPyPI writes on top of the page.)

**Comment by peterjc** [comment]
I'd be happy to retest if you can make Windows wheels for dnaio too (sorry, I hadn't appreciated those had compiled code too - obvious in hindsight).

**Comment by marcelm** [comment]
Thanks, I’ll be back at work next week and will look into this (I’ve started work on dnaio already, shouldn’t be too hard to finish it).

**Comment by marcelm** [comment]
Short update: The last remaining pieces to get this working are the PRs at
* https://github.com/pycompression/xopen/pull/83 and
* https://github.com/marcelm/dnaio/pull/28

**Comment by marcelm** [comment]
Both dependencies have been updated: xopen 1.4.0 and dnaio 0.7.0 should run under Windows. @peterjc It would be great if you could re-test! (Using the command @rhpvorderman gave.)

**Comment by peterjc** [comment]
Good news: This just worked on Python 3.10 on Windows (without MSVC or admin rights), it downloaded the wheel and all the dependencies worked too:

``pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple cutadapt==3.6.dev2``

**Comment by peterjc** [comment]
This turned out to be a bigger request than I expected, but it looks to have prompted several small fixes for Windows - so that's good. Thank you everyone.

**Comment by marcelm** [comment]
Oh great, thanks for testing it! Some of the changes benefitted all platforms, so it was good to do this even for users not on Windows.

**Comment by peterjc** [comment]
Note for anyone seeing no Windows Wheels on PyPI, that currently only has cutadapt 3.5, and I believe we have to wait until cutadapt 3.6 is released which will benefit from this work.

(This isn't a problem for me personally - just trying to pre-empt a likely question)
