### ISSUE TITLE
Trimming in paired-end sequencing

### ISSUE THREAD

**Issue by luchaoqi** [marcelm/cutadapt#597]
Hello, I am new to Cutadapt and sorry if this question is very basic:

I would like to know in paired-end sequencing I have R1 e.g. `ATGC...` and correponding R2 e.g. `...GCAT`. So, to remove adapter `ATGC`, am I supposed to run `cutadapt -g ^ATGC -A GCAT$ -o output.R1 -p output.R2 input.R1 input.R2` in this case?

If that's the case: if I have an adapter in the form of `^N{8}ATGC`, then I should run `cutadapt -g ^N{8}ATGC -A GCATN{8}$`, right?

I searched for the documentation [here](https://cutadapt.readthedocs.io/en/stable/guide.html#regular-3-adapters) and the example there is still a bit confusing for me.

**Comment by marcelm** [comment]
So is it correct that your adapter (or primer) is directly at the beginning of R1? Then `-g ^ATGC` is correct, but in the other direction, it’s unlikely that you see the adapter right at the end of the read, so you should use `-a GCAT` (that is, no anchoring).

It looks roughly like this:
```
R1-sequencing-primer -- 5' adapter -- fragment-of-interest -- revcomp-of-R2-sequencing-primer
                        ------------R1------------->          
                               <---------------R2---------
```
So while R1 starts with your 5' adapter, for R2 anything is possible depending on the length of the fragment of interest and the read length: You could see the reverse complement of the 5' adapter not at all, partially or within the read (followed by the reverse complement of the R1 sequencing primer).

**Comment by luchaoqi** [comment]
Thank you for the quick reply! Yes, the reason for no anchoring makes sense. 

BTW, is it `-a GCAT` or `-A GCAT`? Since I find the documentation [here](https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads) says lowercase options are only applied for R1 and uppercase for R2?

**Comment by marcelm** [comment]
Sorry about the typo, it should of course be uppercase for R2 (`-A`)!

**Comment by luchaoqi** [comment]
Thanks for the answer! One more question, what if I wanted to control the error rate for R1 and R2 separately?

**Comment by marcelm** [comment]
No, the above will just set the maximum errors for both adapters to 2. You can use [adapter-trimming parameters](https://cutadapt.readthedocs.io/en/latest/guide.html#adapter-trimming-parameters) instead:
```
cutadapt -a 'ATGC;max_errors=1' -A 'GCAT;max_errors=2' ...
```
The minimum overlap can also be set, see the linked section in the documentation.

**Comment by luchaoqi** [comment]
Great! Thanks so much for your help.

To clarify, settings in fasta file will overwrite the global settings?

e.g. `-e 2 -g file:file.fasta -A file:file_with_error_settings.fasta` will trim R1 with `e=2` and R2 with `e=3`, separately?

```
# file_with_error_settings.fasta
>myadapter
ACGT;max_errors=3
```

**Comment by marcelm** [comment]
> settings in fasta file will overwrite the global settings?

Yes! The example you gave is correct.

**Comment by luchaoqi** [comment]
Thanks for your help earlier, cutadapt is an awesome tool!
I believe I have set up parameters correctly, however, I got the following unexpected output from cutadapt using settings:

```
file1 = ../raw_data/tmp.R1.fastq.gz
file2 = ../raw_data/tmp.R2.fastq.gz

# ligation trimming
ligation.R1.fastq.gz ligation.R2.fastq.gz : $(file1) $(file2)
	cutadapt -e 1 -m 25 --nextseq-trim=20 \
	--pair-filter=first \
	--cores=96 --info-file=info_ligation.tsv --report=minimal --trim-n \
	-g file:fasta/anchored_ligation.fasta \
	--untrimmed-output=untrimmed_ligation.R1.fastq.gz --untrimmed-paired-output=untrimmed_ligation.R2.fastq.gz \
	-o ligation.R1.fastq.gz -p ligation.R2.fastq.gz \
	$(file1) $(file2) > report_ligation.txt

final_trimming : ligation.R1.fastq.gz ligation.R2.fastq.gz
	cutadapt -e 10 -m 1 \ # technically -e should be 1, but I do it to reproduce the following output
	--pair-filter=first \
	--cores=96 --info-file=info_linker_umi_RT.tsv --report=minimal --trim-n \
	-g file:fasta/N14_RT.fasta -A file:fasta/RT_rc.fasta \
	--untrimmed-output=untrimmed_linker_umi_RT.R1.fastq.gz --untrimmed-paired-output=untrimmed_linker_umi_RT.R2.fastq.gz \
	-o 3.R1.fastq.gz -p 3.R2.fastq.gz \
	ligation.R1.fastq.gz ligation.R2.fastq.gz > report_linker_umi_RT.txt
```
What data looks like:
```
# tmp.R1.fastq
@A01010:86:HCYKKDSXY:1:2301:27868:5885 1:N:0:TCGCCGCCGG+GGCCGTCAAC
GGTTGGCATCAGAGCACCTTGCCCCAGTCCTTTCCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGTGGTTCATAGCAACAATTATCTTTGAACTTTTGAATTTCAAAAACTATTTATCTGGCTGGGATTACAGGCGTGAGC
+
,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF::FF:FF,:F:FFF:FFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFFF:FF:F:F:F:FF:FF

# tmp.R2.fastq
@A01010:86:HCYKKDSXY:1:2301:27868:5885 2:N:0:TCGCCGCCGG+GGCCGTCAAC
GGTATATATTTCCAGGAAAAGTGCCCTTTAGGTATAAAATCTACAGATAAATAGGTTTTTTTCTGTTGTTGTTGTTTTTTTTGTTTGGTTTGGTCTTTGAGATGGAGTCTTGCTCTGTCACCCAGTGCAGTGGAATGATCTCGGCTCACTG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF:FFFF:F:FFFFF:F:FFFFFFF,FFFFFFFF
```

The result:
```
% cat info_ligation.tsv
A01010:86:HCYKKDSXY:1:2301:27868:5885 1:N:0:TCGCCGCCGG+GGCCGTCAAC       0       0       9              GGTTGGCAT        CAGAGCACCTTGCCCCAGTCCTTTCCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGTGGTTCATAGCAACAATTATCTTTGAACTTTTGAATTTCAAAAACTATTTATCTGGCTGGGATTACAGGCGTGAGC  anchored_ligation_barcode315            ,FFFFFFFF       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF::FF:FF,:F:FFF:FFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFFF:FF:F:F:F:FF:FF
```
```
% cat info_linker_umi_RT.tsv
A01010:86:HCYKKDSXY:1:2301:27868:5885 1:N:0:TCGCCGCCGG+GGCCGTCAAC       3       0       27             CAGAGCACCTTGCCCCAGTCCTTTCCT      GAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGTGGTTCATAGCAACAATTATCTTTGAACTTTTGAATTTCAAAAACTATTTATCTGGCTGGGATTACAGGCGTGAGC     RT_barcode182           FFFFFFFFFFFFFFFFFFFFFFFFFFF    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF::FF:FF,:F:FFF:FFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFFF:FF:F:F:F:FF:FF
```

My read structure regarding barcodes: ligation (9/10bp) + linker (6bp) + UMI (8bp) + RT (10bp) + cDNA.
The linker is always `CAGAGC`. And my `N14_RT.fasta` contains the following line:
```
>RT_barcode182
^N{14}CCAGTCCTCT
```
other files if needed to check:
[anchored_ligation.fasta.txt](https://github.com/marcelm/cutadapt/files/8182300/anchored_ligation.fasta.txt)
[linker.fasta.txt](https://github.com/marcelm/cutadapt/files/8182301/linker.fasta.txt)
[N14_RT.fasta.txt](https://github.com/marcelm/cutadapt/files/8182286/N14_RT.fasta.txt)


So, why does the above `info_linker_umi_RT.tsv` gives me 3 errors with 27 bp of sequence that should be trimmed off?
Isn't the result should be:

```
A01010:86:HCYKKDSXY:1:2301:27868:5885 1:N:0:TCGCCGCCGG+GGCCGTCAAC       1       0       24             CAGAGC(linker)ACCTTGCC(UMI)CCAGTCCTTT(RT with 1 error)      CCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGTGGTTCATAGCAACAATTATCTTTGAACTTTTGAATTTCAAAAACTATTTATCTGGCTGGGATTACAGGCGTGAGC     RT_barcode182           FFFFFFFFFFFFFFFFFFFFFFFFFFF    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF::FF:FF,:F:FFF:FFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFFF:FF:F:F:F:FF:FF
```

If you ever need anything else from me to help reproduce the problem, or, if you have any suggestions regarding any cutadapt settings e.g. anchored/regex/error rate, etc. please let me know.
Thank you so much for your time in advance!

**Comment by marcelm** [comment]
Hi, that’s a lot to go through. Can you make the example a bit simpler? That is, remove as many options as you can but still show the problem: You can probably remove `--untrimmed-output`, `--cores` and a couple more.

**Comment by luchaoqi** [comment]
Sure, to simplify it (step1):
```
cutadapt -e 1 -m 25 --nextseq-trim=20 --pair-filter=first --info-file=info_ligation.tsv --trim-n -g file:fasta/anchored_ligation.fasta --discard-untrimmed -o ligation.R1.fastq.gz -p ligation.R2.fastq.gz tmp.R1.fastq.gz tmp.R2.fastq.gz
```
Then trim other barcodes from previous output (step2):
```
cutadapt -e 10 -m 1 --pair-filter=first --info-file=info_linker_umi_RT.tsv --trim-n -g ^N{14}CCAGTCCTCT --discard-untrimmed -o 3.R1.fastq.gz -p 3.R2.fastq.gz ligation.R1.fastq.gz ligation.R2.fastq.gz
```
Results:
```
% cat info_linker_umi_RT.tsv
A01010:86:HCYKKDSXY:1:2301:27868:5885 1:N:0:TCGCCGCCGG+GGCCGTCAAC       3       0       27              CAGAGCACCTTGCCCCAGTCCTTTCCT     GAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGTGGTTCATAGCAACAATTATCTTTGAACTTTTGAATTTCAAAAACTATTTATCTGGCTGGGATTACAGGCGTGAGC      1               FFFFFFFFFFFFFFFFFFFFFFFFFFF     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF::FF:FF,:F:FFF:FFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFFF:FF:F:F:F:FF:FF
```

Some annotations to help understand the problem:
```
GGTTGGCAT (ligation trimmed in step1) CAGAGC (linker inclued in N{14}) ACCTTGCC (UMI included in N{14}) CCAGTCCTTT (RT barcode that should be matching CCAGTCCTCT with 1 error in theory) CCT (end coordinate of the adapter match from cutadapt in practice) GAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGTGGTTCATAGCAACAATTATCTTTGAACTTTTGAATTTCAAAAACTATTTATCTGGCTGGGATTACAGGCGTGAGC
```

**Comment by marcelm** [comment]
Are `--nextseq-trim`, `--pair-filter=first`, `--trim-n`, `--discard-untrimmed` necessary to see the problem?

**Comment by luchaoqi** [comment]
I reran code without these parameters (updated already). They provide the same results so it is not necessary here.

**Comment by marcelm** [comment]
Thank you, that was a bit clearer. It seems that step 1 is irrelevant to show the problem, though, and it’s not really necessary to work with paired-end data, right?

If I understand correctly, this shows the problem:
```
echo -e '>r\nCAGAGCACCTTGCCCCAGTCCTTTCCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGT' | cutadapt -e 10 -g ^N{14}CCAGTCCTCT -
```
(The sequence is a version of the one in `ligation.R1.fastq.gz`, but shortened at the 3' end because we only need to look at the 5' end.)
The above outputs this in the report:
```
=== Adapter 1 ===

Sequence: NNNNNNNNNNNNNNCCAGTCCTCT; Type: anchored 5'; Length: 24; Trimmed: 1 times

No. of allowed errors: 4

Overview of removed sequences
length  count   expect  max.err error counts
27      1       0.0     4       0 0 0 1
```
That is, the adapter was found and a sequence of length 27 was removed from the read.

First, note that you set the total number of errors to 10 with `-e 10`, but there is apparently a bug in Cutadapt that reduces this to 4 ("No. of allowed errors: 4"). I will need to fix this.

Finally, the answer to your question as I understand it is that Cutadapt removes a stretch of 27 bases because 1) you allow indels and 2) Cutadapt tries to find an alignment with as many matches as possible. This is probably the alignment that it finds:
```
CAGAGCACCTTGCC CCAGTCCTTT CCTGAGAGT
NNNNNNNNNNNNNN CCAGTCCT-- -CT
```
In this way, the number of matches is maximal.

I will think about changing the alignment algorithm a bit, but in the meantime, you should just use `--no-indels` to avoid this problem.

**Comment by luchaoqi** [comment]
A point might be helpful for you when I run it with `-O`:
```
echo -e '>r\nCAGAGCACCTTGCCCCAGTCCTTTCCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGT' | cutadapt -O 23 -g ^N{14}CCAGTCCTCT --info-file=info.tmp.tsv -
```
It gets the expected results:
```
=== Adapter 1 ===

Sequence: NNNNNNNNNNNNNNCCAGTCCTCT; Type: anchored 5'; Length: 24; Trimmed: 1 times

No. of allowed errors: 1

Overview of removed sequences
length  count   expect  max.err error counts
24      1       0.0     1       0 1
>r
CCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGT
```
```
% cat info.tmp.tsv
r       1       0       24              CAGAGCACCTTGCCCCAGTCCTTT        CCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGT     1
```

But when I read over the manual [here](https://cutadapt.readthedocs.io/en/stable/guide.html#minimum-overlap-reducing-random-matches):
> This minimum overlap length can be changed globally (for all adapters) with the parameter --overlap (or its short version -O). The option is ignored for anchored adapters since these do not allow partial matches.

**Comment by marcelm** [comment]
The manual is correct: `-O` indeed doesn’t have any effect here. The different result arises only because you allow only 1 error, which makes the "weird" alignment with three deletions impossible.

**Comment by luchaoqi** [comment]
> The different result arises only because you allow only 1 error

When you mean 1 error, is this because of `-e` default to 0.1, then the length of non-N RT barcode (10bp) * 0.1 == 1 error like shown [here](https://cutadapt.readthedocs.io/en/stable/guide.html#n-wildcard-characters)?

So, to get my expected results (removes a stretch of 24 bases instead of 27 bases), should I just run Cutadapt with:
```
# This trims expected 24 bases
echo -e '>r\nCAGAGCACCTTGCCCCAGTCCTTTCCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGT' | cutadapt -g ^N{14}CCAGTCCTCT --info-file=info.tmp.tsv -
```
instead of tuning `-e`:
```
# This doesn't trim adapters with -1 (non-match)
echo -e '>r\nCAGAGCACCTTGCCCCAGTCCTTTCCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGT' | cutadapt -e 1 -g ^N{14}CCAGTCCTCT --info-file=info.tmp.tsv -
```
BTW, I am also curious why `-e 3` gives expected results and `-e 2` gives non-match when it shows `1 (number of errors in column 2)` in the info file with `-e 3`.

**Comment by marcelm** [comment]
> When you mean 1 error, is this because of `-e` default to 0.1, then the length of non-N RT barcode (10bp) * 0.1 == 1 error like shown [here](https://cutadapt.readthedocs.io/en/stable/guide.html#n-wildcard-characters)?

I a mainly meant 1 error in my message because that was what is shown in the log output, but yes, the way it is computed is as described in that section.

> So, to get my expected results (removes a stretch of 24 bases instead of 27 bases and also allow indels for other reads not in this case), should I just run Cutadapt with:
> 
> ```
> # This trims expected 24 bases
> echo -e '>r\nCAGAGCACCTTGCCCCAGTCCTTTCCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGT' | cutadapt -g ^N{14}CCAGTCCTCT --info-file=info.tmp.tsv -
> ```

If you want to keep allowing indels, then yes, that is one way to do it.

> instead of tuning `-e`:
> 
> ```
> # This doesn't trim adapters with -1 (non-match)
> echo -e '>r\nCAGAGCACCTTGCCCCAGTCCTTTCCTGAGAGTCTCAAGCTTGTCTCCAAAGAGTTTCCTCAAGAGT' | cutadapt -e 1 -g ^N{14}CCAGTCCTCT --info-file=info.tmp.tsv -
> ```
> 
> BTW, I am also curious why without `-e` and `-e 3` gives expected results (removes a stretch of 24 bases) and `1 (number of errors in column 2)` in the info file while `-e 1` and `-e 2` gives non-match.

* `-e 0.1` is the default and allows 1 error in this case according to the computation above.
* To allow two errors, you could use `-e 0.2`. This will work.
* Specifying an *absolute number* of errors as `-e 1` or `-e 2` and so on is currently broken. The reason is that this is actually converted back to an error rate internally by taking the length of the sequence and dividing it by the given number of errors. However, the bug is that this uses the full length of the sequence while it should use only the non-N characters. So in this case, when you specify `-e 2` and `-g ^N{14}CCAGTCCTCT`, this is converted back to an error rate of 2/24=0.08. Then the actual matching algorithm sees an error rate of 0.08, but this time it knows that it should ignore the N bases and allows only 0.08 * 10 = 0 (rounded down) errors. But as I said, this is a bug and will be fixed shortly, see #603.

**Comment by luchaoqi** [comment]
Thanks so much for your informative answer!
I have another question regarding the [quality trimming algorithm](https://cutadapt.readthedocs.io/en/stable/algorithms.html#quality-trimming-algorithm). Let's say I want to trim a read with:

```
echo -e '>r\nCAGAGCAGTTGGCGGGCAGACGGCTTTGTTTTTTTTTTTTTTTTTTGGGTTTTTTTTTGGGGGTGTGTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTGTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGGGGGGGGGTG' | cutadapt -e 0.1 -g ^N{14}GGCAGACGCC -
```

This does exactly what I want:

```
This is cutadapt 3.5 with Python 3.8.12
Command line parameters: -e 0.1 -g ^N{14}GGCAGACGCC -
Processing reads on 1 core in single-end mode ...
Done           00:00:00             1 reads @ 1162.5 µs/read;   0.05 M reads/minute
Finished in 0.00 s (4038 µs/read; 0.01 M reads/minute).

=== Summary ===

Total reads processed:                       1
Reads with adapters:                         1 (100.0%)
Reads written (passing filters):             1 (100.0%)

Total basepairs processed:           142 bp
Total written (filtered):            118 bp (83.1%)

=== Adapter 1 ===

Sequence: NNNNNNNNNNNNNNGGCAGACGCC; Type: anchored 5'; Length: 24; Trimmed: 1 times

No. of allowed errors: 1

Overview of removed sequences
length  count   expect  max.err error counts
24      1       0.0     1       0 1
>r
TTTGTTTTTTTTTTTTTTTTTTGGGTTTTTTTTTGGGGGTGTGTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTGTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGGGGGGGGGTG
```

However, after adding quality scores (fastq format), I get the following results:

```
zcat tmp2.R1.fastq.gz | cutadapt -q 0 -e 0.1 -g ^N{14}GGCAGACGCC -
```
```
This is cutadapt 3.5 with Python 3.8.12
Command line parameters: -e 0.1 -g ^N{14}GGCAGACGCC -
Processing reads on 1 core in single-end mode ...
Done           00:00:00             1 reads @ 1081.7 µs/read;   0.06 M reads/minute
Finished in 0.00 s (3800 µs/read; 0.02 M reads/minute).

=== Summary ===

Total reads processed:                       1
Reads with adapters:                         0 (0.0%)
Reads written (passing filters):             1 (100.0%)

Total basepairs processed:           151 bp
Total written (filtered):            151 bp (100.0%)

=== Adapter 1 ===

Sequence: NNNNNNNNNNNNNNGGCAGACGCC; Type: anchored 5'; Length: 24; Trimmed: 0 times
@A01010:86:HCYKKDSXY:2:2203:18891:26130 1:N:0:TCGCCGCCGG+GGCCGTCAAC
CGAGATGCTCAGAGCAGTTGGCGGGCAGACGGCTTTGTTTTTTTTTTTTTTTTTTGGGTTTTTTTTTGGGGGTGTGTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGTGTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGGGGGGGGGTG
+
:FFFFFFFFFFFFFFFFF:,,,FFF:,F,,F,:,,,,:,,:F,F:,F,,,:,,,,,F:,,,,,,,,,,,:,F,,,F,,,,F,FF::F,FF:F,FF,,F:,,F::,:,,,,,:FF,FF,,,:,,:::,F,F::,,:,,:,,,,,,,,,,,,,
```

I believe `-q 0` should disable quality trimming of R1. So why does Cutadapt output the above results? Thank you!

**Comment by marcelm** [comment]
I have now merged PR #608 which changes the alignment algorithm a little bit. I have added some explanations to the documentation: https://cutadapt.readthedocs.io/en/latest/algorithms.html#algorithm-indel-scores

Do you think you could test this? You would need to [install the development version](https://cutadapt.readthedocs.io/en/latest/installation.html#installing-the-development-version) of Cutadapt.

**Comment by marcelm** [comment]
Hi and thanks. I have seen your question only now because you added it afterwards through an edit. Are you asking for how to pipe paired-end data? There is a [section about this in the documentation](https://cutadapt.readthedocs.io/en/stable/recipes.html#piping-paired-end-data).

**Comment by luchaoqi** [comment]
Ummm, close, it's more like redirecting reports from the previous step as well as piping the previous trimmed data into the next step:
```
cutadapt [options] --interleaved in.1.fastq.gz in.2.fastq.gz 
(I wanted to extract the report information from here as well as make the pipeline happy) | \
  cutadapt [options] --interleaved -o out.1.fastq.gz -p out.2.fastq.gz -
```
The reason is that I wanted to know about trimming statistics from step_1 but avoid writing data into disk and read the same data for step_2.
BTW, thanks for your helpful response to the email!

**Comment by marcelm** [comment]
Redirect the first report with `2>` and the second with `>`:
```
cutadapt [options] --interleaved in.1.fastq.gz in.2.fastq.gz 2> first-report.log | \
  cutadapt [options] --interleaved -o out.1.fastq.gz -p out.2.fastq.gz - > second.report.log
```
If the data is sent to stdout (that is, when no `-o`/`-p` is given), Cutadapt sends the report to stderr, which is why you need to redirect the first report with `2>`. If `-o`/`-p` is used, then the report is sent to stdout, which is why `>` is needed for the second `cutadapt` invocation.

**Comment by marcelm** [comment]
This appears to have been solved, so closing now. Fine to re-open if necessary.
