### ISSUE TITLE
KeyError: 'match_sequence' when renaming paired-end reads

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#600]
Cutadapt version: 3.6

When trying to rename paired-end reads using `--rename` with the `{match_sequence}` placeholder, Cutadapt crashes and prints a traceback followed by the error message:
```
KeyError: 'match_sequence'
```

**Comment by chucknordy** [comment]
Hi -- sorry if this isn't the best place to note this -- but FYI, the v3.7 **documentation** of this newly-added `{match_sequence}` option has the formatting kinda messed up...

**Comment by marcelm** [comment]
Thanks! That indeed looked completely broken, not sure what went wrong. Should be fixed now.

**Comment by marcelm** [comment]
To be clear: I cannet change the stable v3.7 docs at https://cutadapt.readthedocs.io/en/stable/guide.html#rename-renames-reads, so it’s only fixed in the "latest" docs at https://cutadapt.readthedocs.io/en/latest/guide.html#rename-renames-reads
