### ISSUE TITLE
Redirect stdout when trimming paired-end reads (`-o` option)

### ISSUE THREAD

**Issue by jgarces02** [marcelm/cutadapt#601]
- Cutadapt and Python version -> cutadapt 1.18, with Python 2.7.15
- How you installed the tool (conda or pip, for example) -> I guess with conda, but I'm not the admin of my work cluster 😅 
- Which command-line parameters you used ->
```
cutadapt -e 0 \
	--nextseq-trim=20 \
	--minimum-length 20:20 \
	-a "A{10}" -a "T{10}" -a "G{10}" \
	-A "A{10}" -A "T{10}" -A "G{10}" \
	-a file:~/adapters/nextera_transposase.fa \
	-A file:~/adapters/nextera_transposase.fa \
	-o 61516_BM_0m_S5_R1_001.cutadapt.fastq.gz -p 61516_BM_0m_S5_R2_001.cutadapt.fastq.gz \
	61516_BM_0m_S5_R1_001.fastq.gz 61516_BM_0m_S5_R2_001.fastq.gz 2> 61516_BM_0m_S5.cutadapt.log
```
Because adding the `-o` option, the _stdout_ is not sent to _61516_BM_0m_S5.cutadapt.log_. Is there any way of trimming paired-end reads and redirect the _stdout_ to another file using `2>`? 

Thanks in advance.

**Comment by marcelm** [comment]
When you use `-o`, the report is sent to stdout, so you need to use `>` instead of `2>` to redirect the log output.

> Cutadapt and Python version -> cutadapt 1.18, with Python 2.7.15

Tell your cluster admin they should update their software once in a while! ...

**Comment by jgarces02** [comment]
> Tell your cluster admin they should update their software once in a while! ...

ABSOLUTELY!

Thanks for your very quick help with this (silly) problem!

**Comment by marcelm** [comment]
No worries, glad I could help :-)
