### ISSUE TITLE
Using Cutadapt to separate data based on primer sequence

### ISSUE THREAD

**Issue by LaurCC** [marcelm/cutadapt#602]
Hello,

I am using cutadapt 2.4 through R in a conda environment and intending to use the DADA2 pipeline for analysis. I have used illumina amplicon sequencing to amplify two different hypervariable regions of the 16S rRNA gene (V1-V2 and V4) as a result I have received the data from the sequencing facility as demultiplexed paired end data but with reads from both primers contained in the same fastq files. I would like to assess the two hypervariable regions as two independent datasets. Would I be able to use cutadapt to separate the data based on primer sequences? 

Thank you for any help!

Best wishes, 
Laura

**Comment by marcelm** [comment]
Yes, that should be possible. First you may want to read this section in the documentation: https://cutadapt.readthedocs.io/en/stable/recipes.html#trimming-amplicon-primers-from-paired-end-reads

To actually separate the data based on the primer sequence, you need to modify the commands given there to do [demultiplexing](https://cutadapt.readthedocs.io/en/stable/guide.html#demultiplexing). That is, you need to give each adapter a name (something like `-a my_name=ACGTACGT`) and insert the placeholder `{name}` into the output file names: `-o out.{name}.1.fastq.gz -p out.{name}.2.fastq.gz`.

If you do not want to do any trimming, but only split the data by primer, use also `--action=none`.

This should get you started, please let me know if you need more help.

**Comment by LaurCC** [comment]
Thank you so much for getting back to me! Following from my previous post I have separated them by trimming and discarding untrimmed reads for each primer set independently (before reading your reply). This seems to have been successful so I hope this is an acceptable way of achieving this!

Thanks again for your guidance!
