### ISSUE TITLE
Can cutadapt handle degenerate sequences?

### ISSUE THREAD

**Issue by iquasere** [marcelm/cutadapt#605]
Hi there!

Can cutadapt trim degenerate sequences? If I supply it a primer such as ```GGATTAGAKACCCYACTATGC```, will it recognize the ```K``` and ```Y``` bases as degenerate and appropriately consider the corresponding nucleotide bases?

**Comment by marcelm** [comment]
Yes: https://cutadapt.readthedocs.io/en/stable/guide.html#wildcards

I have now updated the documentation so that you will find the correct section when you search for the word "degenerate".
