### ISSUE TITLE
Customising Cutadapt to split chimeric reads

### ISSUE THREAD

**Issue by MortenEneberg** [marcelm/cutadapt#620]
Thanks for a great tool!

We work with Nanopore sequencing, where it is common to ligate sequencing adapters to your DNA. This is preceeded by a PCR that introduces barcodes. After PCR our constructs (in theory) looks like this (SEQ: Sequence of interest):
![image](https://user-images.githubusercontent.com/81558602/165738184-6515109e-54fa-4388-9296-585819a8ef56.png)
And following ligation of Nanopore sequencing adapters:
![image](https://user-images.githubusercontent.com/81558602/165738288-a7d997fb-98cd-42d6-a362-969e667ccc96.png)

The ligation of Nanopore sequencing adapter was done on PCR-products from multiple samples at once, which is common pratice. However, we have found that a substantial fraction of PCR-products is not only ligated to Nanopore sequencing adapters, but also to PCR-products from other samples, which causes major issues in demultiplexing and adapter trimming. This gives us constructs like:
![image](https://user-images.githubusercontent.com/81558602/165738449-9cfb3a78-20e2-4811-a5a0-83be101289d0.png)

Our demultiplexing workflow consists of 2 cutadapt steps:
1) Find a set of barcodes (e.g. barcode7) and demultiplex the read based on this. Settings are: cutadapt -g file:barcodes.fasta -e 0.04 etc.
Barcodes are listed in an adjacent fasta-file like this: AAGAAAGTTGTCGGTGTCTTTGTG;min_overlap=22...AAGAAAGTTGTCGGTGTCTTTGTG;min_overlap=22

2) Trim read from remaning primer sequence. Settings are: cutadapt -g file:adapters.fasta -e 0.08 etc. 
Adapters/primers are listed in a fasta-file like this:
ACACTCTTTCCCTACACGACGCTCTTCCGATCT;min_overlap=23...AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC;min_overlap=23

What we have found is, that this can happen at demultiplexing (the same read as presented above, only demultiplexed):
![image](https://user-images.githubusercontent.com/81558602/165739551-29289412-3edf-430c-ad9e-50990c0fa2ef.png)

And this at primer/adapter trim:
![image](https://user-images.githubusercontent.com/81558602/165739665-4932731c-0668-48ca-98db-999d4cbdad15.png)

The end result is, that we are left with a sequence that "belongs to" a different barcode than the one it was demultiplexed to.

What we want to do to avoid this is to split a read into more reads, if we find two different barcodes close to each other, which would split sequences of the different PCR-products. Does cutadapt support this in any way?

Kind regards

**Comment by MortenEneberg** [comment]
Thanks for the elaborate answer!

I did think of throwing away reads still containing a barcode, but wasnt aware of the --discard-trimmed parameter - that makes it a lot easier. I will go with that for now and see how much data I end up throwing away. Thanks for the other suggestions - not sure it is within my level of expertise to customise Cutadapt, but I will look into what you have suggested if it proofs necessary.

Yes, it is very possible that some protocol changes will lower the frequency of these occurences. Thanks again!

**Comment by marcelm** [comment]
The other suggestion(s) were more meant as ideas for myself (or for anyone who’s willing to implement them). I’ll open a separate issue so I don’t forget.

**Comment by Meghana9854** [comment]
Hi, 

I have nanopore data as well that would be similar to Morten's in the sense that the structure should be:
ONT adapters + For_barcode + primer + Seq + primer + Rev_barcode + ONT adapters
My forward and reverse barcodes are are unique, meaning their sequences differ to each other and are only used once for a samples (i.e. for_barcode01 and rev_barcode01 - for sample 01
                                                      for_barcode02 and rev_barcode02 - for sample 02 and so on)
I want to  demultiplex my samples based on the barcodes. I've tried using --pair-adapters -g file:F_barcodes.fasta -G file:R_rev_compl_barcodes.fasta in paired-end mode. As I have a single input file, and not as R1 and R2 unlike Illumina data, do I give the same input file twice as input.R1 and input.R2? Is there better way of doing this, to bin reads based on the presence of both barcodes (say, for_barcode01 and rev_barcode01 - for sample 01) from the same reads on a files. Essentially meaning I only want those reads in my barcode01 folder that have the for_barcode01 in the front and rev_barcode01 at the rare of the sequence. 

Thanks

**Comment by marcelm** [comment]
@Meghana9854 Sorry for the late reply (comments on a closed issue are easy to forget, I recommend just opening a new issue for a new question and referring to the closed issue). It is probably no longer relevant, but for completeness sake and in case anyone else ends up here, you could use [linked adapters](https://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters).
