### ISSUE TITLE
Running Cutadapt 4.0 in Apptainer container

### ISSUE THREAD

**Issue by marcelglueck** [marcelm/cutadapt#622]
I have containerized Cutadapt 4.0 in Apptainer 1.0.1 with Python 3.8.10. using pip. 
The installation of Cutadapt within the container was successful (the cutadapt --version) command shows the installed version.

However, when I now try to process my reads trough the containerized Cutadapt 4.0, I get the following error message:

cutadapt: error: [Errno 2] No such file or directory
This is cutadapt 4.0 with Python 3.8.10
Command line parameters: -j 0 -u 3 -U 2 -o ../20220419_ok/results/sl9/sl9_1.fq.gz -p ../20220419_ok/results/sl9/sl9_2.fq.gz ../20220419_ok/data/sl9/sl9_EKDL220002878-1a-AK39033-AK48527_HG7Y2DSX3_L4_1.fq.gz ../20220419_ok/data/sl9/sl9_EKDL220002878-1a-AK39033-AK48527_HG7Y2DSX3_L4_2.fq.gz
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

I am pretty certain that the containerized software sees my files, as file names are obtained using grep.
If I run this script using a locally installed version of Cutadapt, the script performs as intended.

Unfortunately, the error message is not really informative. 
May you please help in solving this issue? Thank you.

**Comment by marcelm** [comment]
I don’t use Apptainer and this doesn’t appear to be an issue in Cutadapt, so I can just give a little bit of generic advice. Try to make the command as small as possible while still reproducing the error. In particular, leave out `-j 0` to make sure that the problem doesn’t have anything to do with multithreading. Leave out `-p` and provide only one input file (pretending the data is single-end). You can also use `-o /dev/null` and if you still get the message, you know that it’s probably about opening the input file and not the output.

Also try adding the `--debug` option to the command.

What is a bit strange is that the error message appears to be printed *before* the "This is cutadapt ..." message, and also that it does not show the name of the "file or directory" that cannot be opened.

Try to replace the `cutadapt` command with just `ls`. That is, just try to list the file. If you get an error even from `ls`, that’s helpful as well.

**Comment by marcelglueck** [comment]
Thank you very much. Leaving out the `-j 0` did the job for me. I can imagine that the minimal Ubuntu build in the container does not support the type of multithreading Cutadapt requires. Stacks, seems to run smootly with multithreading enabled in the container though.

**Comment by marcelglueck** [comment]
Are there any specific libraries you use for multithreading? If so, I could try to integrate them in my container to allow for faster data processing.

**Comment by marcelm** [comment]
Cutadapt just uses the `multiprocessing` module, which is part of Python’s standard library. I’m guessing that the `No such file or directory` refers to some device file like `/dev/shm` or something in `/proc`or similar which may not be available in the container. I think in order to get this working, you need to find out which file the error message refers to. Try with `--debug` and if you know how, use `strace`.

I noticed now that Apptainer is the new name for Singularity, which I have used before. Do you know that there’s a Biocontainer for Cutadapt? This is somewhat documented at http://bioconda.github.io/recipes/cutadapt/README.html. For Docker, the command to get it would be `docker pull quay.io/biocontainers/cutadapt:4.0` and I guess it’s `apptainer pull docker:quay.iosimilar for Apptainer.

**Comment by marcelglueck** [comment]
Thank you for your help. The command to pull version 4.0 was: `apptainer pull docker://quay.io/biocontainers/cutadapt:4.0--py37h8902056_0`. Unfortunately, the issue still persists. If I leave out the -j 0 flag, everything works fine. However, upon enabling multithreading, the issue described above appears again. Using the --debug flag does not result in more verbose output, but the output error message is the one described above.

**Comment by marcelm** [comment]
I completely forget that this issue has been reported before in #583. Please have a look over there. The short answer is that adding `-B /run/shm:/run/shm` to the Singularity options helped; perhaps it does so for `apptainer` as well.

**Comment by marcelm** [comment]
I installed apptainer 1.0.1 on my laptop (Ubuntu 21.10) and ran `echo -e '>r\nACGT' | apptainer exec docker://quay.io/biocontainers/cutadapt:4.0--py37h8902056_0 cutadapt -j0 -o /dev/null -`, which finished successfully. Any idea what is different about your setup?

**Comment by rhpvorderman** [comment]
@marcelglueck Always run singularity or "apptainer" as they call it now with the `--containall` (`-C`) option. 

Unfortunately apptainer uses the shittiest defaults imaginable for reproducibiltiy:
- Mounts your home dir (with all the settings files, just to make it only reproducible across your computer and no one elses)
- Imports the users environment (same as above and even worse)

It also mounts the PID and IPC namespaces of the current computer. I don't know what that entails exactly (but IPC stands for interprocess communication). Which happens to interfere with python's multiprocessing module.

Running with `--containall` does not mount any directories unless explicitly asked, does not import environment variables unless explicitly set, and also does not mount the IPC and PID namespace, which results in cutadapt running fine.

See also: https://github.com/apptainer/apptainer/issues/64 . 

And that they didn't choose to fix it even when going trough a major refactoring (by changing the name) shows to me that this whole projec gets by on false advertising. Unfortunately this is the best available to us on HPC. I recommend docker for all other use cases.

**Comment by marcelm** [comment]
I’ll assume this is no longer a problem and will close the issue. Please comment if it is not solved, yet.
