### ISSUE TITLE
cutadapt: error: name must be a valid ASCII-string.

### ISSUE THREAD

**Issue by M-gowda** [marcelm/cutadapt#628]
I am using Cutadapt 3.4 with Python 3.8.6
CogentAP pipeline uses Cutadapt for trimming. I did not install Cutadapt explicitly since it is already installed in the HPC. I just load the module to use it. Whenever I run the CogentAP pipeline, it runs into failed trimming and I am getting the following error from Cutadapt.

**cutadapt: error: name must be a valid ASCII-string.**

I tried running the Cutadapt at the terminal with the same parameters and files as used by CogentAP. I am getting the same error. I think this error is specific to Cutadapt. I was told by the takara bioinformatics support that using "_" in the sample name might be causing this. So, I switched to "-", but no use.

following are the command and error

```
cutadapt -j 1 -m 15 --trim-n --max-n 0.7 -q 20 \
> -o /scratch/mcm3ha/RNA_seq/DNMT-KO_mPFC_PN_RNASeq/Reads/analyze/work/TTACAGGAGCTTGTCA/trimmed_R1.fastq.gz \
> -a file:/sfs/lustre/bahamut/scratch/mcm3ha/RNA_seq/CogentAP/lib/../config/adapters.fasta \
> -p /scratch/mcm3ha/RNA_seq/DNMT-KO_mPFC_PN_RNASeq/Reads/analyze/work/TTACAGGAGCTTGTCA/trimmed_R2.fastq.gz \
> -A file:/sfs/lustre/bahamut/scratch/mcm3ha/RNA_seq/CogentAP/lib/../config/adapters.fasta \
> /scratch/mcm3ha/RNA_seq/DNMT_KO_mPFC_PN_RNASeq/bcl2fq/demux/demux_TTACAGGAGCTTGTCA_KO-2-S5_R1.fastq.gz \
> /scratch/mcm3ha/RNA_seq/DNMT_KO_mPFC_PN_RNASeq/bcl2fq/demux/demux_TTACAGGAGCTTGTCA_KO-2-S5_R2.fastq.gz


This is cutadapt 3.4 with Python 3.8.8
Command line parameters: -j 1 -m 15 --trim-n --max-n 0.7 -q 20 -o /scratch/mcm3ha/RNA_seq/DNMT-KO_mPFC_PN_RNASeq/Reads/analyze/work/TTACAGGAGCTTGTCA/trimmed_R1.fastq.gz -a file:/sfs/lustre/bahamut/scratch/mcm3ha/RNA_seq/CogentAP/lib/../config/adapters.fasta -p /scratch/mcm3ha/RNA_seq/DNMT-KO_mPFC_PN_RNASeq/Reads/analyze/work/TTACAGGAGCTTGTCA/trimmed_R2.fastq.gz -A file:/sfs/lustre/bahamut/scratch/mcm3ha/RNA_seq/CogentAP/lib/../config/adapters.fasta /scratch/mcm3ha/RNA_seq/DNMT_KO_mPFC_PN_RNASeq/bcl2fq/demux/demux_TTACAGGAGCTTGTCA_KO-2-S5_R1.fastq.gz /scratch/mcm3ha/RNA_seq/DNMT_KO_mPFC_PN_RNASeq/bcl2fq/demux/demux_TTACAGGAGCTTGTCA_KO-2-S5_R2.fastq.gz
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: name must be a valid ASCII-string.

```
I don't see any non-ASCII string in the names. Looks like this is not faced by anyone earlier and also I could not find relavent information in the documentation.

Can someone please help?

Thanks,
Mohan

**Comment by marcelm** [comment]
This error message refers to the sequence IDs in a FASTA or FASTQ file. The FASTQ finnes are probably fine, so please check your adapters.fasta file, are there any non-ASCII characters in the FASTA headers?

If this was the problem, please leave the issue open for now because I need to improve the error message.

**Comment by M-gowda** [comment]
Thanks for the response!
I am not sure about what are all non-ASCII characters. If it is possible please point me to a right document/description regarding this. However, comparing the text to ASCII table, I think the hyphen here "Illumina–TruSeq" is unusually long (-). And, guess what, after changing to "IlluminaTruSeq" the pipeline is running fine!   
I am pasting the adapters.fasta here. If you want to check. 
```
>polyA
AAAAAAAA
>polyT
TTTTTTTT
>Illumina_sequencing_primer
AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT
>Illumina_sequencing_primer_revcomp
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
>polyG
GGGGGGGG
>SINGV6
ACACTCTTTCCCTACACGACGC
>SINGV6_revcomp
GCGTCGTGTAGGGAAAGAGTGT
>SMART
AAGCAGTGGTATCAACGCAGAGTAC
>SMART_revcomp
GTACTCTGCGTTGATACCACTGCTT
>IDT_for_Illumina–TruSeq_DNA_and_RNA_UD_Indexes_Adapter_Trimming_Read1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
>IDT_for_Illumina–TruSeq_DNA_and_RNA_UD_Indexes_Adapter_Trimming_Read1_revcomp
TGACTGGAGTTCAGACGTGTGCTCTTCCGATCT
>IDT_for_Illumina–TruSeq_DNA_and_RNA_UD_Indexes_Adapter_Trimming_Read2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
>IDT_for_Illumina–TruSeq_DNA_and_RNA_UD_Indexes_Adapter_Trimming_Read2_revcomp
ACACTCTTTCCCTACACGACGCTCTTCCGATCT
>Nextera
CTGTCTCTTATACACATCT
>Nextera_revcomp
AGATGTGTATAAGAGACAG

```

**Comment by marcelm** [comment]
Great you found the problem yourself. I have now improved the error message slightly. It’ll look like this in the next version:
```
cutadapt: error: Error in FASTA file at line 5: 'name' in sequence file must be ASCII encoded, but found '–' at position 17
```
