### ISSUE TITLE
cutadapt installation not working

### ISSUE THREAD

**Issue by jwkkang** [marcelm/cutadapt#629]
I have tried conda, pip, and all suggested installation method but gives me error. Python version is 3.9.12.

Please help!

**Comment by rhpvorderman** [comment]
Most of these errors are usually related to python-isal. Which is why I chip in (as python-isal maintainer)

Can you please try to install cutadapt in a new virtual environment?

```
python3 -m virtualenv cutadapt_venv
source cutadapt_venv/bin/activate
pip install --upgrade pip setuptools
pip install cutadapt
```

If that does not work, pip will give a long list of messages. Can you post the whole list here?

**Comment by jwkkang** [comment]
Hello,

This is the whole terminal run that I tried. Still giving me an error after trying in a new virtual environment.
I copied the whole process below.

Thank you!

--

(base) DOM12677:~ jwkang$ python3 -m virtualenv cutadapt_venv
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3: No module named virtualenv
(base) DOM12677:~ jwkang$ source cutadapt_venv/bin/activate
bash: cutadapt_venv/bin/activate: No such file or directory
(base) DOM12677:~ jwkang$ pip install --upgrade pip setuptools
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (22.1.2)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (58.1.0)
Collecting setuptools
 Using cached setuptools-63.1.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
 Attempting uninstall: setuptools
 Found existing installation: setuptools 58.1.0
 Uninstalling setuptools-58.1.0:
 Successfully uninstalled setuptools-58.1.0
Successfully installed setuptools-63.1.0
(base) DOM12677:~ jwkang$ pip install cutadapt
Collecting cutadapt
 Using cached cutadapt-4.1-cp310-cp310-macosx_10_9_universal2.whl
Collecting xopen>=1.1
 Using cached xopen-1.5.0-py3-none-any.whl (14 kB)
Collecting dnaio>=0.7.1
 Using cached dnaio-0.9.0.tar.gz (41 kB)
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Preparing metadata (pyproject.toml) ... done
Collecting isal>=0.9.0
 Using cached isal-0.11.1-cp310-cp310-macosx_10_9_x86_64.whl (330 kB)
Building wheels for collected packages: dnaio
 Building wheel for dnaio (pyproject.toml) ... error
 error: subprocess-exited-with-error

 × Building wheel for dnaio (pyproject.toml) did not run successfully.
 │ exit code: 1
 ╰─> [93 lines of output]
 running bdist_wheel
 running build
 running build_py
 creating build
 creating build/lib.macosx-10.9-universal2-cpython-310
 creating build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/interfaces.py -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/readers.py -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/_version.py -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/singleend.py -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/writers.py -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/_util.py -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/pairedend.py -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/exceptions.py -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/chunks.py -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/py.typed -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/_version.pyi -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/_core.pyi -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/ascii_check.h -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/_conversions.h -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 copying src/dnaio/ascii_check_sse2.h -> build/lib.macosx-10.9-universal2-cpython-310/dnaio
 running build_ext
 cythoning src/dnaio/_core.pyx to src/dnaio/_core.c
 building 'dnaio._core' extension
 creating build/temp.macosx-10.9-universal2-cpython-310
 creating build/temp.macosx-10.9-universal2-cpython-310/src
 creating build/temp.macosx-10.9-universal2-cpython-310/src/dnaio
 clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DUSE_SSE2 -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/dnaio/_core.c -o build/temp.macosx-10.9-universal2-cpython-310/src/dnaio/_core.o
 In file included from src/dnaio/_core.c:700:
 In file included from src/dnaio/ascii_check_sse2.h:27:
 In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/emmintrin.h:13:
 In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/xmmintrin.h:13:
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:50:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:129:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:159:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:189:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:216:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:239:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:260:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:287:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:310:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:331:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:352:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:373:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:394:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:416:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:439:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_paddsw((__v4hi)__m1, (__v4hi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:461:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_paddusb((__v8qi)__m1, (__v8qi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:483:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_paddusw((__v4hi)__m1, (__v4hi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:504:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_psubb((__v8qi)__m1, (__v8qi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:525:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
 return (__m64)__builtin_ia32_psubw((__v4hi)__m1, (__v4hi)__m2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 fatal error: too many errors emitted, stopping now [-ferror-limit=]
 20 errors generated.
 error: command '/usr/bin/clang' failed with exit code 1
 [end of output]

 note: This error originates from a subprocess, and is likely not a problem with pip.
 ERROR: Failed building wheel for dnaio
Failed to build dnaio
ERROR: Could not build wheels for dnaio, which is required to install pyproject.toml-based projects

**Comment by lumc-sasc** [comment]
Can you `pip install virtualenv` first? It looks like that is not installed.

Also there seems to be an error while the dnaio dependency. I see that wheels are not provided for dnaio for macos. I will have a look.

**Comment by rhpvorderman** [comment]
Hi it seems this has to do with dnaio. Wheels are not provided by default for Mac OS. In the next release of dnaio this will be fixed. In the meantime I have attached the dnaio wheels.
You can check your version of python with `python --version` and download the correct wheel. From what I can see you need `dnaio-0.9.1.dev15+g28ca4ca-cp310-cp310-macosx_10_9_x86_64.whl`. [wheels.zip](https://github.com/marcelm/cutadapt/files/9118936/wheels.zip)

The install procedure is as follows
```
pip install virtualenv
python3 -m virtualenv cutadapt_venv
source cutadapt_venv/bin/activate
pip install --upgrade pip setuptools
pip install --nodeps cutadapt
pip install xopen
pip install <path to the wheel package you downloaded>
```

**Comment by jwkkang** [comment]
Hello,
Thank you for your solution. With your solution, I was able to successfully install cutadapt with the following procedure!

```
pip install virtualenv
python3 -m virtualenv cutadapt_venv
source cutadapt_venv/bin/activate
pip install --upgrade pip setuptools
pip install --no-deps cutadapt
pip install <path to the wheel package you downloaded> (e.g., pip install ./bin/wheels/dnaio-0.9.1.dev15+g28ca4ca-cp310-cp310-macosx_10_9_x86_64.whl)
```

**Comment by marcelm** [comment]
Thanks for handling this while I was away. I’m adding some tests to reduce the chance that this particular problem appears again in the future.

**Comment by marcelm** [comment]
dnaio 0.9.1 wheels are now available.

**Comment by ssyberg** [comment]
FWIW this is still happening for me, latest pip installed, ventura 13.0.1 on a 2nd gen M1

**Comment by marcelm** [comment]
@ssyberg Can you please post the command that you used and the exact error message?

**Comment by ssyberg** [comment]
Sure! Just a normal install: `pip install cutadapt`

```
seth@MacBook-Pro-2 ~ % pip install cutadapt
Collecting cutadapt
  Using cached cutadapt-4.1.tar.gz (231 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dnaio>=0.7.1
  Using cached dnaio-0.9.1.tar.gz (41 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting xopen>=1.1
  Using cached xopen-1.7.0-py3-none-any.whl (15 kB)
Building wheels for collected packages: cutadapt, dnaio
  Building wheel for cutadapt (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cutadapt (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AssertionError:
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-cpython-310
      creating build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/steps.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/align.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/_version.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/log.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/__init__.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/parser.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/tokenizer.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/utils.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/pipeline.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/modifiers.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/statistics.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/json.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/__main__.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/report.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/filters.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/adapters.py -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/_align.pyi -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      copying src/cutadapt/qualtrim.pyi -> build/lib.macosx-12-arm64-cpython-310/cutadapt
      running build_ext
      building 'cutadapt._align' extension
      creating build/temp.macosx-12-arm64-cpython-310
      creating build/temp.macosx-12-arm64-cpython-310/src
      creating build/temp.macosx-12-arm64-cpython-310/src/cutadapt
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/cutadapt/_align.c -o build/temp.macosx-12-arm64-cpython-310/src/cutadapt/_align.o
      clang: error: no such file or directory: 'src/cutadapt/_align.c'
      clang: error: no input files
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cutadapt
  Building wheel for dnaio (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for dnaio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AssertionError:
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-cpython-310
      creating build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/interfaces.py -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/readers.py -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/_version.py -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/__init__.py -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/singleend.py -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/writers.py -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/_util.py -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/pairedend.py -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/exceptions.py -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/chunks.py -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/py.typed -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/_version.pyi -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/_core.pyi -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/ascii_check.h -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/_conversions.h -> build/lib.macosx-12-arm64-cpython-310/dnaio
      copying src/dnaio/ascii_check_sse2.h -> build/lib.macosx-12-arm64-cpython-310/dnaio
      running build_ext
      building 'dnaio._core' extension
      creating build/temp.macosx-12-arm64-cpython-310
      creating build/temp.macosx-12-arm64-cpython-310/src
      creating build/temp.macosx-12-arm64-cpython-310/src/dnaio
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/dnaio/_core.c -o build/temp.macosx-12-arm64-cpython-310/src/dnaio/_core.o
      clang: error: no such file or directory: 'src/dnaio/_core.c'
      clang: error: no input files
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dnaio
Failed to build cutadapt dnaio
ERROR: Could not build wheels for cutadapt, dnaio, which is required to install pyproject.toml-based projects
```

**Comment by ssyberg** [comment]
And if it's helpful:
```
seth@MacBook-Pro-2 ~ % python --version
Python 3.10.8
seth@MacBook-Pro-2 ~ % pip --version
pip 22.3.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
seth@MacBook-Pro-2 ~ %
```

**Comment by marcelm** [comment]
Can you do me a favor and copy and paste the above into a new issue?

**Comment by ssyberg** [comment]
> Can you do me a favor and copy and paste the above into a new issue?

Is it not related to this one?

**Comment by marcelm** [comment]
No, it’s a different error message. Also, you’re on an M1 Mac which may have something to do with it.

**Comment by marcelm** [comment]
I opened #658.
