### ISSUE TITLE
Remove reads with polyA/T/G/C

### ISSUE THREAD

**Issue by bounlu** [marcelm/cutadapt#637]
I know how to trim polyA/T/G/C from the reads, but is it possible to remove the entire read if it contains polyA/T/G/C?

**Comment by marcelm** [comment]
You can use the `--discard-trimmed` option.

**Comment by marcelm** [comment]
The command you show in #638 uses `--discard-untrimmed`. Does that work the way you want it?

**Comment by bounlu** [comment]
As I want to remove reads that do not contain 3' adapter as well as contains poly A/T/G/C, I need to use `--discard-untrimmed`. I think your answer to my other posts will help to achieve this. Thanks.
