### ISSUE TITLE
Segmentation fault when disk space is low

### ISSUE THREAD

**Issue by pinin4fjords** [marcelm/cutadapt#640]
Hi! 

When running cudadapt 3.4 on Python 3.9.6 via trim_galore 0.6.7 in a Docker container on AWS batch via the nf-core RNA-seq Nextflow workflow as follows:

```
trim_galore \
    --fastqc \
    --cores 4 \
    --paired \
    --gzip \
     \
     \
     \
     \
    SRX8042381_1.fastq.gz \
    SRX8042381_2.fastq.gz
```

... which reported Cutadapt command line parameters like:

```
-j 1 -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC SRX8042381_1.fastq.gz
```

... I encountered an error like: 

```
 Writing final adapter and quality trimmed output to SRX8042381_1_trimmed.fq.gz
    >>> Now performing quality (cutoff '-q 20') and adapter trimming in a single pass for the adapter sequence: 'AGATCGGAAGAGC' from file SRX8042381_1.fastq.gz <<<
  sh: line 1:   296 Segmentation fault      (core dumped) pigz -p 4 -c - > SRX8042381_1_trimmed.fq.gz
```

This turned out to be down to a lack of space available to the batch job, since using a single core in the above command produced an error like:

```
...
10000000 sequences processed
20000000 sequences processed
30000000 sequences processed
gzip: write error: No space left on device
```

If this has been addressed in more up-to-date versions of Cudadapt than used in that workflow then great- please disregard. But at least this issue is here to explain the error to others Googling around.

If this is still something that would happen, could there maybe be some mechanism to catch the problem and provide a more intelligible error message than the seg fault?

Thank you!

**Comment by marcelm** [comment]
Thanks for the report. I haven’t been able to reproduce a segmentation fault with pigz when the disk is full. Using only Cutadapt, I get a proper error message:
```
$ cutadapt -j 2 -o full/disk/output.fastq.gz input.fastq.gz
...
ERROR: cutadapt: error: Output pigz process terminated with exit code 28
```

In fact, I think that this message:
```
sh: line 1:   296 Segmentation fault     (core dumped) pigz -p 4 -c - > SRX8042381_1_trimmed.fq.gz
```
does not come from Cutadapt, but from the tool that is wrapping it. The text `sh: line 1` indicates to me that a shell is involved, but Cutadapt always calls `pigz` directly for compression, not via a shell. Perhaps Trim Galore runs its own compression step? You may want to report this issue to them instead.

Anyway, I have taken the opportunity to improve the error message (see pycompression/xoen#111), and it should in the future look like this (with the "Possible cause" part added):
```
ERROR: cutadapt: error: Output process 'pigz --no-name' terminated with exit code 28.
Possible cause: No space left on device
```
