### ISSUE TITLE
weird distribution in the overview of removed sequences log (length)

### ISSUE THREAD

**Issue by soluna1** [marcelm/cutadapt#645]
Hello:

I'm using Cutadapt to remove primers from pair-end sequences of 400 bp (base pair) 18s (MiSeq PE300 flow cell (Illumina)) with this parameters:

```
This is cutadapt 3.4 with Python 3.8.5
Command line parameters: -g CCAGCASCYGCGGTAATTCC -G ACTTTCGTTCTTGATYRR -e 0.1 -O 3 --discard-untrimmed -m 200
```

Although the output summary seems to be fine:
```
Total read pairs processed:             70,134
  Read 1 with adapter:                  69,989 (99.8%)
  Read 2 with adapter:                  69,683 (99.4%)
Pairs that were too short:                  39 (0.1%)
Pairs written (passing filters):        69,532 (99.1%)

Total basepairs processed:    42,213,563 bp
  Read 1:    21,110,334 bp
  Read 2:    21,103,229 bp
Total written (filtered):     39,216,521 bp (92.9%)
  Read 1:    19,538,658 bp
  Read 2:    19,677,863 bp
```
For many samples the distribution in the "overview of removed sequences" shows some very long reads, only in the forward pair (the last three rows, for instance):

```
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20 bp: 2

Overview of removed sequences
length	count	expect	max.err	error counts
16	1	0.0	1	0 1
17	5	0.0	1	1 4
18	13	0.0	1	6 0 7
19	232	0.0	1	61 171
20	69635	0.0	2	68856 750 29
21	90	0.0	2	25 63 2
22	5	0.0	2	0 1 4
23	1	0.0	2	0 1
28	1	0.0	2	1
172	3	0.0	2	0 0 3
177	2	0.0	2	0 0 2
180	1	0.0	2	0 0 1
```
there is a way to avoid this output?

Thanks a lot!!

**Comment by marcelm** [comment]
These numbers come from 5' adapters that are located in the middle of a read. If you want Cutadapt to find an adapter sequence only when it occurs  exactly at the 5' end, specify it as an anchored adapter by preceding it with the `^` character (see also the docs).

**Comment by soluna1** [comment]
Ok, I thought in that option, but I don't want to be so strict in anchoring the primer, perhaps there is a way to give some range of bases close to the 5'. I'll have a look to the docs.

Thanks a lot!

**Comment by marcelm** [comment]
You can add a couple of `N` bases in the beginning (as in `-g ^NNNNNACGT`). Also `X` is less strict than `^` (in one direction)

**Comment by soluna1** [comment]
Perfect!! Thanks!!
