### ISSUE TITLE
Demultiplexing pulling out non-barcoded sequences despite anchoring

### ISSUE THREAD

**Issue by R-Huerlimann** [marcelm/cutadapt#646]
I'm using cutadapt 4.1 with Python 3.10.6 through conda.

I'm trying to demultiplex a dual indexed library with inline barcodes where the first 8 bp of each read are a unique barcode. 

My command looks like the one below, were I create three arrays from a sample table containing sample names and forward/reverse barcodes. (I tried it with a barcode list first, but that crates 20,405 combinations, which are too many for the system to handle, hence me trying the array.)
`cutadapt -j 10 -e 0.15 --no-indels -g ^${fwdA[${SLURM_ARRAY_TASK_ID}]} -G ^${revA[${SLURM_ARRAY_TASK_ID}]} -o ${nameA[${SLURM_ARRAY_TASK_ID}]}_R1.fastq.gz -p ${nameA[${SLURM_ARRAY_TASK_ID}]}_R2.fastq.gz ${inDir}/*R1.fastq.gz ${inDir}/*R2.fastq.gz
`

However, the output files I'm getting are much bigger than expected, and upon further inspection, it doesn't look like it has been demultiplexed by barcode. Doing a grep with the barcode sequence, I can see that all reads contain the barcode, but it's not anchored to the start of the sequence, but all over the sequence.
![image](https://user-images.githubusercontent.com/7220856/196569723-c5a39536-225f-4ab7-96e8-d0d891bcda2e.png)

I thought the ^ should anchor my sequence to the start, so I don't know what I'm missing here.

Since I wasn't sure if the problem lies with my array, I also ran this which gave me the same result:
`cutadapt -j 10 -e 0.15 --no-indels -g ^aaacaata -G ^gacatcct -o test_R1.fastq.gz -p test_R2.fastq.gz ${inDir}/*R1.fastq.gz ${inDir}/*R2.fastq.gz
`

Although now I'm wondering if the lower case barcodes are an issue?

Edit: I should probably add that the barcodes are not removed. The read length is 250 before and after the demultiplexing, and I do find reads starting with the barcode in the demultiplexed file.

**Comment by marcelm** [comment]
It appears you’re not actually using Cutadapt’s demultiplexing capability. Is that on purpose? See the [section about demultiplexing in the manual](https://cutadapt.readthedocs.io/en/stable/guide.html#demultiplexing).

Also, if these are Illumina unique dual indices, then see [the section in the manual about UDIs](https://cutadapt.readthedocs.io/en/stable/guide.html#paired-adapters-dual-indices).

In short, I’d use this command:
```
cutadapt -j 10 -e 1 --no-indels --pair-adapters -g file:r1indices.fasta -G file:r2indices.fasta -o 'demultiplexed-{name}_R1.fastq.gz' -p 'demultiplexed-{name}_R2.fastq.gz' input.R1.fastq.gz input.R2.fastq.gz
```
where the file `r1indices.fasta` contains your R1 barcodes like this:
```
>barcode1
^aaacaata
...
```
and `r2indices.fasta` contains the R2 barcodes.

I replaced `-e 0.15` with `-e 1` just for readability. (Cutadapt nowadays understands an absolute number of errors instead of an error rate.)

Uppercase vs lowercase does not matter.

**Comment by R-Huerlimann** [comment]
Aah, I see. I need the {name} to trigger the function. I assumed -g and -G are not enough.

And the pair-adapters parameter makes it a lot easier. Thank you this is perfect.

**Comment by marcelm** [comment]
Let me know in case you have a suggestion for improving the documentation.

**Comment by R-Huerlimann** [comment]
Thank you! Reading it again, I think it's pretty clear. It's just a complex topic and the information is in multiple places, but I'm not sure if there is an easier way of doing it. That being said, maybe add a short section just below "Demultiplexing paired-end reads with combinatorial dual indexes" that repeats some of the information of "Paired adapters (dual indices)" with the command you gave above might work.

**Comment by marcelm** [comment]
Thanks, I have added such a section. https://cutadapt.readthedocs.io/en/latest/guide.html#unique-dual-indices
