### ISSUE TITLE
using cutadapt in r (running in unix)?

### ISSUE THREAD

**Issue by marwa38** [marcelm/cutadapt#650]
Hi guys 

Anyway to use cutadapt in rstudio that I am using in UNIX?
I installed via bioconda in unix but couldn't use in r when I tried `library()`. 
Any way to compile the source code in unix and then use in R? give me more details please so that I could try 
I tried to use .exe but got the error: `sh: 1: ./cutadapt.exe: Exec format error` in r and in bash: `./cutadapt.exe: cannot execute binary file: Exec format error` in UNIX which makes sense I know I can't use this .exe in UNIX 

thank you 
M

**Comment by marcelm** [comment]
Cutadapt is not an R library, so using `library()` does not work. Cutadapt is meant to be used as a command-line program in your terminal. If you need to run it from within an R script, you can run it like any other command-line program. I believe R has the `system()` function for this.

**Comment by marwa38** [comment]
thanks @marcelm 
yeah I used system() and as I informed you I found this error sh: 1: ./cutadapt.exe: Exec format error

**Comment by marcelm** [comment]
As you said, `cutadapt.exe` is not for Unix. It is a Windows binary.

Please try [one of the installation methods described in the documentation](https://cutadapt.readthedocs.io/en/stable/installation.html). I recommend Conda/Bioconda. It works on Linux.

**Comment by marwa38** [comment]
Thank you for the clarification. 
I had done that step in bioconda as I said earlier, but I couldn't import it to use within R environment like other software after bioconda installation. 
Cheers
M
