### ISSUE TITLE
Add quality metrics, just like fastp

### ISSUE THREAD

**Issue by rhpvorderman** [marcelm/cutadapt#651]
Hi,

A common workflow is to run FastQC and cutadapt simultaneously, then run FastQC again on the result. This has of course quite some overhead because the  continuous compression/decompression of FASTQ files. A program called [fastp](https://github.com/opengene/fastp) jumps into this gap. It basically does all FASTQ processing in a single program. As a result it is very popular.

Unfortunately, it is not very good in my opinion. Quality scores are averaged naively not aware of the logarithmic phred score. This is by design as this gives "better results". (There is an issue where this is stated). In my experience however, averaging naively means that a lot of crappy reads are not thrown away. For example the half of the read is quality 0, the other half is quality 40, this means that on average 1 in 2 bases is wrong. With naive averaging however, the quality comes at 20 average (1 in 100 bases is wrong) and will pass. A naive filter will hardly ever filter anything. 
Also, fastp does not have many tests, there are many many open issues etc. 

I prefer cutadapt, but that does not mean that fastp doens not have a very good idea. I think it should be relatively easy (although quite some work) to add some QC modules to cutadapt. This would make the whole FASTQ processing a lot faster. I have been playing in my head with the idea of creating a FasterQC program which uses dnaio, I think it would be better to add this to cutadapt instead.  

What do you think?

**Comment by marcelm** [comment]
I’m quite open to this. An idea I’ve had for a while is to turn Cutadapt into a general FASTQ processing tool, and adding one or more QC modules would fit quite well into that.

It would be great to only have to iterate over the input file once and do all the preprocessing within one tool. Cutadapt would need to be more flexible and extensible for that, and adding QC modules is a good test for where the flexibility is needed.

My favorite way of adding modules would actually be to make Cutadapt extensible along the way so it is easier to add them even without integrating them directly into Cutadapt. So if there’s some stuff that’s very specialized, it would be great if someone could develop that as a plugin and just distribute it separately on PyPI.

However, don’t let that deter you. Just adding a `--qc` (or whatever) command-line option is also fine as a first step.

If you need to make architectural changes, please open an issue to discuss them first.

**Comment by rhpvorderman** [comment]
Hi @marcelm, this issue just got more urgency. I just discovered that fastp **and FastQC** horror of horrors: **average Phred scores naively**.

This is horribly wrong. When half of my bases is quality 40 and the other half is quality 0. I am quite sure that half of my bases is incorrect. So the phred score should be -10 * log10(0.5) = 3. While averaging naively delivers a phred score of 20: which means 1 in 100 bases incorrect. This means that averaging naively has a tendency to overestimate actual quality of the reads. I started working on a QC module that does it correctly and fastp and FastQC report quality scores that are 5 higher on a certain file. That is quite a big difference in terms of actual probability.

It is quite distressing that the go to tool that everyone has been using for years, FastQC has such an egregious error and nobody has reported it. (Also my personal failure, I have been working in this field for 6 years now...). 

Anyway. The cutadapt QC module should be quite good. I deduced that the fastest way to generate stats is to make a big three-dimensional matrix of sequence position, phred score and nucleotide. Only A,C,G,T, N are considered (using a lookup  table to map every non-ACGT to N) and there are 94 possible phreds (0-93). 
Simply incrementing the count in the table for every nucleotide generates a table from which all other data can be generated: sequence lengths, gc scores, average quality etc. This can be done at the very end. I am quite happy by how it is working out. I will make a PR once I got the report nailed.

In other news, I have been looking at plotting libraries. Especially ones that have little dependencies, as I don't want to ruin cutadapt's flat dependency tree by adding a monster library that imports the world. Unfortunately all python plotting libraries seem to fall in this category. Then I found this https://www.pygal.org/en/stable/. Pygal writes svg (:heart:) which of course can be easily embedded into html. It also has **0** dependencies !!! The install size is under 200 kb. This is really awesome. I am going to try this out. This looks exactly right for a cutadapt QC report and I don't mind adding this is a dependency to cutadapt if it turns out to work okay. Then I also can use it to generate the dnaio plots for the paper.

**Comment by rhpvorderman** [comment]
Pygal it is. 129 kb install size. This is the code:
```python
    def quality_plot(self) -> str:
        plot = pygal.Line(
            title="Quality per position",
            dots_size=1,
            x_labels = list(range(1, self.max_length + 1)),
            x_labels_major=list(range(0, self.max_length, 10)),
            show_minor_x_labels=False,
            truncate_label=-1,
        )
        plot.add("mean", self.mean_qualities)
        plot.add("A", self.per_base_qualities[A])
        plot.add("G", self.per_base_qualities[G])
        plot.add("C", self.per_base_qualities[C])
        plot.add("T", self.per_base_qualities[T])

        return plot.render().decode("UTF-8")
```
And this is the result: 

![here is the result.](https://user-images.githubusercontent.com/26142226/211832672-63fb0263-8267-4fd1-9e10-415a521cfca8.svg)

Below is the fastp result for the same file. It is a pretty big difference in terms of quality values. (It is a non-interactive png, but in the actual report it is interactive.):

![fastp_result](https://user-images.githubusercontent.com/26142226/211833733-9113180c-6828-4908-aa08-ff897ccab1c3.png)
