### ISSUE TITLE
H nucleotides and wildcards in cutadapt?

### ISSUE THREAD

**Issue by marwa38** [marcelm/cutadapt#653]
Hi 

I hope I didn’t missed any post about V3_V4, but I couldn’t find an answer:

Here is the V3-V4 forward and reverse primers:
Forward CCTACGGG**N**GGCWGCAG
Reverse GACTAC**H**VGGGTATCTAATCC
I know that "N" is used as a wild card for all nucleotides in cutadapt.
It is a quick technical question, do you think that trimming primers which have "H" nucleotides should work? 

Thank you
Marwa

**Comment by marcelm** [comment]
Yes, Cutadapt understands the H wildcard.

**Comment by marwa38** [comment]
thank you so so much :)
