### ISSUE TITLE
Unexpected behavior when cutting non-internal 5’ adapter with wildcards

### ISSUE THREAD

**Issue by simondrue** [marcelm/cutadapt#654]
Hi,

I want to cut an adapter from the 5' end of my reads (ONT long-reads), but only want to search the first n bases of the read, to avoid random matches in the middle of the reads, which can be solved using the the non-internal adapter functionality. However the adapter might not be in the end of the adapter, ie. I want to assume the beginning of the adapter sequence is random. This should be solved by padding my adapter with N wildcards, leaving me with `-g "XN{n}ADAPTER `. However this only seem to work if the adapter is a perfect match when there is less than n random bases, and I want to allow some errors. The errors are allowed when there are exactly n random bases. 

I've come up with the following reproducible example:

Say we have the input file `my_seqs.fasta`:

```
>read_1
CCCTTT
>read_2
ACCCTTT
>read_2_match
ACGCTTT
>read_3
AACCCTTT
>read_4
AAACCCTTT
>read_5
AAAACCCTTT
>read_6
AAAAACCCTTT
>read_7
AAAAAACCCTTT
>read_8
AAAAAAACCCTTT
```

Running the command:
```
cutadapt -g XN{3}CGC -o test.fasta my_seqs.fasta -e 0.34 --debug
```
then yields the following output:
```
>read_1
CCCTTT
>read_2
ACCCTTT
>read_2_match
TTT
>read_3
AACCCTTT
>read_4
TTT
>read_5
AAAACCCTTT
>read_6
AAAAACCCTTT
>read_7
AAAAAACCCTTT
>read_8
AAAAAAACCCTTT
```

From my understanding from the documentation, I would assume that all reads 1-4 would have been trimmed equally, as when i run the command without X and N's. However, then reads 5-8 get trimmed, which is what I would like to avoid. 

The report generated by the command:
```
This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g XN{3}CGC -o test.fasta my_seqs.fasta -e 0.34 --debug
DEBUG: Python executable: /home/simond/miniconda3/envs/porechop/bin/python
DEBUG: dnaio version: 0.9.1
DEBUG: xopen version: 1.7.0
DEBUG: Adapters (1):
DEBUG: - <NonInternalFrontAdapter(name='1', sequence='NNNCGC', max_error_rate=0.34, min_overlap=3, read_wildcards=False, adapter_wildcards=True, indels=True)>
DEBUG: Opening 'test.fasta', mode 'wb' with xopen resulted in <_io.BufferedWriter name='test.fasta'>
DEBUG: Opening 'my_seqs.fasta', mode 'rb' with xopen resulted in <_io.BufferedReader name='my_seqs.fasta'>
DEBUG: Pipeline step 1: NoFilter(FastaWriter('test.fasta'))
Processing single-end reads on 1 core ...
Finished in 0.12 s (13790 µs/read; 0.00 M reads/minute).

=== Summary ===

Total reads processed:                       9
Reads with adapters:                         2 (22.2%)
Reads written (passing filters):             9 (100.0%)

Total basepairs processed:            83 bp
Total written (filtered):             73 bp (88.0%)

=== Adapter 1 ===

Sequence: NNNCGC; Type: non-internal 5'; Length: 6; Trimmed: 2 times

Minimum overlap: 3
No. of allowed errors:
1-1 bp: 0; 2-3 bp: 1

Overview of removed sequences
length	count	expect	max.err	error counts
4	1	0.0	1	1
6	1	0.0	1	0 1
````

Looking forward to hear if the problem can be solved easily - and maybe even quickly 🚀 

Thanks for a great tool! 👌 

Kind regards,
Simon

**Comment by marcelm** [comment]
Thanks for the reproducer! This used to work in Cutadapt 1.18, but stopped working in 2.0. The offending commit is b95c5882c724aa3b27bc1ad9fd5a2e772465b14b. Please give me a couple of days to look into this.

**Comment by marcelm** [comment]
I’ve fixed this in the development version just now. Please see the [commit message](https://github.com/marcelm/cutadapt/commit/f120d7f7b3500d85898f0f48c008d2edda73a10a) for an explanation of what the error was.

I plan to release Cutadapt 4.2 (with the fix) within the next week or so.

Thanks again for reporting! I’ve added some test cases so this won’t re-appear.
