### ISSUE TITLE
Conda installs a very old version

### ISSUE THREAD

**Issue by Davood-Norouzi** [marcelm/cutadapt#659]
Hi, 

Thanks for the great tool! 

- I would like to install Cutadapt 4.1, with Python version: 3.7.15
- I use: >> conda install -c bioconda cutadapt; conda update --all

I would like to install cutadapt 4.1. But when I use conda, it installs version 1.18. What am I doing wrong? I have installed many bioconda packages. Never encountered such thing.

Thanks again!
-Davood

**Comment by marcelm** [comment]
Hi, I think this could be one of two problems:
1. Using `-c bioconda` is usually not enough to use Bioconda packages. You also need `conda-forge` in your channels list and both must be in the correct order. The easiest way to solve this would be to follow the [Bioconda setup instructions](http://bioconda.github.io/#usage). If you insist on not adding the bioconda channel permanently, click on the arrow next to "What if I don't want to modify my condarc?" to see which options to add to the command line and in which order.
2. If you are installing into an existing environment, there could be some conflicts with the already existing packages in that environment that force Conda to choose that old version of Cutadapt. Also, it is recommended to never install things into the base environment (apart from Conda itself and related tools), so I would use `conda create -n cutadapt cutadapt` followed by `conda activate cutadapt` to install Cutadapt. That creates a fresh environment with only Cutadapt in it.

**Comment by marcelm** [comment]
I assume this has been solved.
