### ISSUE TITLE
partially match for 5' adapter (-g) won't work when `rightmost` is specified.

### ISSUE THREAD

**Issue by y9c** [marcelm/cutadapt#665]
input data:

```diff
>test
TACAGTCCGACGATCAGTCCAGGGCGTGCTACGGGTGGATGGTGCACCACGGCACGCGCTACCGCGACGCCGA
```

command:

```bash
cutadapt -g "AGTTCTACAGTCCGACGATC;o=5;e=0.2;rightmost"
```

common part is **TACAGTCCGACGATC**, so expected output is:

```
>test
AGTCCAGGGCGTGCTACGGGTGGATGGTGCACCACGGCACGCGCTACCGCGACGCCGA
```

real output:

```
>test
TACAGTCCGACGATCAGTCCAGGGCGTGCTACGGGTGGATGGTGCACCACGGCACGCGCTACCGCGACGCCGA
```

But run cutadapt without `rightmost` won't have this problem. I think this is a bug rather than a feature?

**Comment by marcelm** [comment]
Thanks, this is indeed a bug! I have now fixed this in the development version.

**Comment by y9c** [comment]
Thank you very much for your help.
