### ISSUE TITLE
Has there been any Sliding Window option?

### ISSUE THREAD

**Issue by AtheerAS** [marcelm/cutadapt#667]
Hi,

I follow a pipeline that uses cutadapt (v2.6) to filter sequencing reads. They filtered reads with average Phred quality values < 20 **over a 25 bp sliding window**. 
I couldn't find any option in cutadapt that support quality filtering within a sliding window. Is there? Or has been any?

Thank you

**Comment by marcelm** [comment]
Hi, no, such an option has never existed in any version.

**Comment by AtheerAS** [comment]
Thank you

**Comment by marcelm** [comment]
Let me know if there’s anything else, closing this issue for now.
