### ISSUE TITLE
question: insert <tab> char with --rename?

### ISSUE THREAD

**Issue by eboyden** [marcelm/cutadapt#669]
Hi - is there a means to use `--rename` to insert a `tab` character?  I tried `\t` and `"\t"`, to no avail.  This would be useful, for example, when extracting multiple pieces of information with Cutadapt and putting them all into separate SAM tags in the fastq comment, then using a compatible aligner to move the entire comment into the bam file.  (The space after the read ID is fine, but every subsequent separator needs to be a `tab`.)  If there's a convenient way to do this inside of Cutadapt then please let me know, if not it would be great to add this feature (e.g. `{tab}`).  Thanks!

**Comment by y9c** [comment]
You can insert tab into the command line, rather `\t`, and the output will contain tab. 

In linux shell, use `Ctrl+V TAB` to insert a tab.

**Comment by marcelm** [comment]
Sorry for not responding earlier, this issue got lost among other notifications. @y9c is correct, but I agree it would be nicer with direct support for this in Cutadapt. I have therefore just added support for writing `\t` within the `--rename` template string. That should also be more readable in scripts than having a literal tab character in the file. Thank you for the suggestion!

This will be in Cutadapt 4.3.

**Comment by eboyden** [comment]
Excellent, thanks!  And yeah I know you can insert a literal TAB on the command line with Ctrl+V, and that does indeed work, but I agree that more explicit support is cleaner.  TABs aren't always interpreted properly by text parsers, and if someone copy-pasted code and wasn't careful about it, it could become a string of spaces that would break things.
