### ISSUE TITLE
Cutadapt 4.2 Installation issue.

### ISSUE THREAD

**Issue by jz431** [marcelm/cutadapt#670]
Hi all,

I am having an issue installing cutadapt version 4.2. My Python version is 3.10.8, and I am trying to install Cutadapt 4.2. I am trying to install it via bioconda using the following command: conda install -c bioconda cutadapt. However, it only installs version 1.18. Trying to update cutadapt by conda update cutadapt does not work either. Does anyone know a fix?

**Comment by rhpvorderman** [comment]
Try `conda install -c conda-forge -c bioconda -c defaults cutadapt`

See also proper bioconda usage: http://bioconda.github.io/#usage .

**Comment by marcelm** [comment]
Are you using a Mac with Apple Silicon (M1 processor)? Then please try this: https://github.com/marcelm/cutadapt/issues/672#issuecomment-1398183020

**Comment by RPINerd** [comment]
I just tried it out myself, I had to add conda-forge for some dependency resolutions, but cutadapt 4.2 was installed correctly

**Comment by marcelm** [comment]
Thanks for the feedback! I’ll close this issue as the installation instructions should now cover this.
