### ISSUE TITLE
Cutadapt not being downloaded from Bioconda 

### ISSUE THREAD

**Issue by HrishikeshHard** [marcelm/cutadapt#672]
I am unable to install cut adapt v 4.2 from Conda. 
I am using MacBook Air M1 16 GB, on MacOS Ventura 13.0.1
conda version = 22.11.1
python version  = 3.10.8
Bioconda, Conda-forge and defaults channels are added.

the command I'm using is: 
`conda install -c bioconda cutadapt`

I get the following error:
`Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cutadapt
`

I have check on the bioconda website online, and cutadapt is present there. However, I am unable to download. 
I have downloaded cutadapt using `brew install cutadapt`, but it only installs cutadapt 3.4

Attaching screenshot of the error

<img width="731" alt="Screenshot 2023-01-20 at 10 25 54 am" src="https://user-images.githubusercontent.com/63086391/213620268-93bb4f41-ab66-45df-96d8-3d82afed355c.png">

**Comment by rhpvorderman** [comment]
Bioconda does not build packages for the M1 chip (yet). I doubt you will be able to install anything through bioconda that is pre-compiled.

Try using a python installation instead.
```bash 
virtualenv my_virtual_env 
source my_virtual_env/bin/activate
pip install cutadapt
```
That should compile cutadapt and its dependencies for your platform.

**Comment by marcelm** [comment]
I recently learned that macOS on M1 1) can run x86-64 binaries and 2) you can [force Conda to use the x86-64 binaries](https://conda-forge.org/docs/user/tipsandtricks.html#installing-apple-intel-packages-on-apple-silicon). 
First, ensure you correctly [set up the Bioconda channel](http://bioconda.github.io/#usage). Just adding `-c bioconda` to the command-line options is usually not enough!

Then try this:
```
CONDA_SUBDIR=osx-64 conda create -n cutadapt cutadapt
```

**Comment by HrishikeshHard** [comment]
@marcelm I tried your solution. Cutadapt was downloaded, however, it is not running. It says that the type is x86, you need arm64. 
I have switched my terminal to the rosetta 2 mode. I still cannot use cutadapt. Attaching screenshot. 

<img width="864" alt="image" src="https://user-images.githubusercontent.com/63086391/213842596-35273b7d-0155-4b07-9c1c-b68a6c51ac10.png">

**Comment by marcelm** [comment]
I believe you need to create a new Conda environment in order to ensure that all the packages in it use the `CONDA_SUBDIR` setting. So don’t use `conda install`, but the `conda create` command I wrote above (followed by `conda activate cutadapt`).

I’ve seen other people use this method sucessfully in a different project (https://github.com/NBISweden/IgDiscover/issues/120), so I think you should be able to get it to work.

**Comment by HrishikeshHard** [comment]
> I believe you need to create a new Conda environment in order to ensure that all the packages in it use the `CONDA_SUBDIR` setting. So don’t use `conda install`, but the `conda create` command I wrote above (followed by `conda activate cutadapt`).
> 
> I’ve seen other people use this method sucessfully in a different project ([NBISweden/IgDiscover#120](https://github.com/NBISweden/IgDiscover/issues/120)), so I think you should be able to get it to work.

@marcelm Thank you for the guidance. I would like to conclude by giving a few more suggestions to people (who are absolute beginners like me). These suggestions for M1 Mac/MacOS Ventura users. 

1. Do not play with the type of the terminal. The solution suggested by Marcel works perfectly fine without enabling Rosetta. I did that, and somehow my OpenSSL crashed. Things got quite ugly, ultimately I had to uninstall Anaconda and Miniconda completely and reinstall them. 
2. Assuming you have a fresh Anaconda environment, do what Marcel has suggested. Activate the 3 conda channels. 
3. Do create a new environment for cutadapt. I tried installing cutadapt on my base environment, it somehow doesn't work. Cutadapt will work fine if you follow Marcel's instructions. 
4. If you absolutely want to install Cutadapt outside of all environments, try `brew install cutadapt`. This will install version 3.4 of Cutadapt. Sadly, the latest version of Cutadapt is not there on Homebrew. I request @marcelm to release  it on brew as well!

Thanks to Marcel for the support. Now it works!

**Comment by marcelm** [comment]
Sorry for the trouble you had to go through and thanks so much for this detailed write-up! I have added a sentence to the documentation pointing people to this issue.

**Comment by marcelm** [comment]
Regarding  `brew install`: It is a good suggestion, but as I don’t have a Mac myself, I wouldn’t be the right person to work on that.

**Comment by rhpvorderman** [comment]
@HrishikeshHard I still wonder what would happen if you would try the `pip install` method as [suggested above](https://github.com/marcelm/cutadapt/issues/672#issuecomment-1397966446). 

I did install cutadapt successfully on my phone that way. (Using termux on android). No wheels are provided for ARM64 with android libc, nevertheless my phone managed to install cutadapt, xopen and dnaio just fine. It had to do some compilation, but this was no issue. I therefore think it should also work for your M1 macbook.

**Comment by HrishikeshHard** [comment]
@rhpvorderman I tried the `virtualenv my_virtualenv` command, but it says 'command not found'
So I proceeded on to directly use `pip install cutadapt` on my base environment without creating another environment for it. 
It was successfully downloaded, and is working! 
thanks for your suggestion.

**Comment by rhpvorderman** [comment]
>  I tried the virtualenv my_virtualenv command, but it says 'command not found'

You can do `pip install virtualenv` to remedy that. Using virtualenvs is recommended as it allows you to install separate packages without creating conflicting dependencies. Having said that, cutadapt should be fine as it  has very little dependencies.

**Comment by ryandkuster** [comment]
For anyone on M1/M2 having issues with this command from the docs:
```
CONDA_SUBDIR=osx-64 conda create -n cutadapt cutadapt
```
you may need to try adding the channel:
```
CONDA_SUBDIR=osx-64 conda create -n cutadapt -c bioconda cutadapt
```

**Comment by laurabogar** [comment]
Many, many thanks to @marcelm for solving this issue, and to @HrishikeshHard for summarizing the process so nicely! I have been stuck with this same problem all morning, and am so relieved to learn how I can keep using Bioconda packages on my M1 computer. Thanks!

**Comment by soluna1** [comment]
Excellent solution for M1 Mac users! Thanks @ryandkuster !
Running the `CONDA_SUBDIR=osx-64 conda create -n cutadapt -c bioconda cutadapt` command cutadapt 2.6 version was installed, it seems that there is cutadapt 4.7 version, is there any update option in conda?

Thanks!!

**Comment by rhpvorderman** [comment]
You are not using the conda-forge channel. Please use the channels as listed in the documentation: http://bioconda.github.io/#usage

**Comment by DinaZangwill** [comment]
> You are not using the conda-forge channel. Please use the channels as listed in the documentation: http://bioconda.github.io/#usage

Hello, what is a conda-forge channel? I am getting the same error that this question thread was started for. 
I am on windows 10. 

when i say i dont know what a conda-forge channel is, i mean i dont know what a channel is, what it does, how to use them at all. I have tried googling "what is a conda channel" and "what is a channel in python" with no answers. this seems like a basic concept that everyone knows how to use and thus is not explained in any documentation.

**Comment by marcelm** [comment]
Hi @DinaZangwill, don’t despair. You seem to have done everything correct to get Conda working, but unfortunately, Cutadapt is just not available for Windows when using Conda.

As a brief explanation: Anyone who wants to make software available for use with Conda can create their own channel. It’s like a YouTube channel, but instead of videos, the channel owner uploads software packages. For the Bioconda channel, there’s not a single person, but a large team behind it uploading packages of bioinformatics software. Unfortunately, Bioconda does not provide Windows-compatible packages (only macOS and Linux). One reason for this may be that the developers of bioinformatics tools often don’t use Windows, so the software does not run on Windows at all or it takes extra work to get it to run.

To be clear: Conda itself supports Windows (which is why you could install it), but not the Bioconda channel.

For Cutadapt, you can [download a Windows .exe file](https://github.com/marcelm/cutadapt/actions/runs/7631879722).

**Comment by DinaZangwill** [comment]
Interesting! And thank you for such a prompt reply! I am always amazed at how fast and supportive the informatics community is. Thanks again.

**Comment by DinaZangwill** [comment]
> Hi @DinaZangwill, don’t despair. You seem to have done everything correct to get Conda working, but unfortunately, Cutadapt is just not available for Windows when using Conda.
> 
> As a brief explanation: Anyone who wants to make software available for use with Conda can create their own channel. It’s like a YouTube channel, but instead of videos, the channel owner uploads software packages. For the Bioconda channel, there’s not a single person, but a large team behind it uploading packages of bioinformatics software. Unfortunately, Bioconda does not provide Windows-compatible packages (only macOS and Linux). One reason for this may be that the developers of bioinformatics tools often don’t use Windows, so the software does not run on Windows at all or it takes extra work to get it to run.
> 
> To be clear: Conda itself supports Windows (which is why you could install it), but not the Bioconda channel.
> 
> For Cutadapt, you can [download a Windows .exe file](https://github.com/marcelm/cutadapt/actions/runs/7631879722).

Interesting! And thank you for such a prompt reply! I am always amazed at how fast and supportive the informatics community is. Thanks again.
