### ISSUE TITLE
Reverse Complements of Adapter Classes

### ISSUE THREAD

**Issue by CCranney** [marcelm/cutadapt#673]
Cutadapt: 4.1
Python: 3.10.6

This may be more of an enhancement request. I've made an issue before asking about using cutadapt in python scripts (see [here](https://github.com/marcelm/cutadapt/issues/568)). I've done that relatively successfully, which has been great. Part of my project requires making linked adapters in addition to the reverse complement equivalent of each linked adapter. I've just been making a linked adapter and it's reverse complement separately, but was wondering if there was a method baked in to cutadapt for this kind of use case.

For example, let's say I make the following linked adapter:

```
adapterSequence1 = "AAACCC"
adapterSequence2 = "ATCGATCG"
adapter1 = FrontAdapter(adapterSequence1)
adapter2 = BackAdapter(adapterSequence2)
linkedAdapter = LinkedAdapter(
    adapter1,
    adapter2,
    name="alinkedadapter",
    front_required=True,
    back_required=True,
)
```

I now have a linked adapter. However, sometimes I need to use this same linked adapter on a reverse complement strand. So I make a second linked adapter like so that represents the reverse complement:

```
adapterSequence1_reverseComplement = "GGGTTT"
adapterSequence2_reverseComplement = "CGATCGAT"
adapter1 = FrontAdapter(adapterSequence1_reverseComplement)
adapter2 = BackAdapter(adapterSequence2_reverseComplement)
linkedAdapter_reverseComplement = LinkedAdapter(
    adapter2, 
    adapter1,
    name="alinkedadapter_reverseComplement",
    front_required=True,
    back_required=True,
)
```

So now I have two linked adapters, `linkedAdapter` and `linkedAdapter_reverseComplement`, which are effectively the same linked adapter.

Is there any baked-in usability for generating or referencing the reverse complement of the `linkedAdapter` without replicating it as I have above? I've been reviewing the code, but I'm not seeing anything. Again, I can keep replicating it, so my program can work just fine. I was just wondering if there was a more straightforward method in existence, and if not, if that may be a future enhancement idea.

**Comment by marcelm** [comment]
Hi Caleb, this functionality doesn’t exist, but could be added. For example, one could add a `reverse_complemented()` method to `LinkedAdapter`. Hm, what would happen to the `front_required` and `back_required` options when they have different values, do you have an opinion on that?

**Comment by CCranney** [comment]
Good to know! And that's an excellent question - At present my program will set `front_required` and `back_required` both to `True`, but I could see the reverse complement bit getting hairy if that's not the case. Off the top of my head one could just switch the settings, where the reverse complement `front_required` value would be set to whatever `back_required` was in the original adapter and vice versa.

**Comment by CCranney** [comment]
I wound up changing my code so this wouldn't be necessary - possibly something to revisit in the future, but I'll close this for now. Thank you for the package!

**Comment by marcelm** [comment]
Sorry about not being more responsive - I have too many other things going on at the moment. I’ll leave this closed but add an API tag so that I’ll find it in case I decide to work more in that direction.
