### ISSUE TITLE
cutadapt bash for loop error

### ISSUE THREAD

**Issue by singhdharmesh** [marcelm/cutadapt#675]
Hi Marcel,

This is cutadapt 4.1 with Python 3.7.4
I am trying to run cutadapt on a windows 10 Hyper V Manager virtual machine (screenshot attached - cutadapt error) and the following error message comes (attached log file).
Input files are demultiplexed Fastq.gz file (screenshot attached - output folder).

![cutadapt error](https://user-images.githubusercontent.com/81809472/222114640-0af5f953-76f2-40da-9a70-ca475ab9e5f2.JPG)
![output folder](https://user-images.githubusercontent.com/81809472/222114963-eeb7e7aa-0f74-46ab-bb1a-5a4991c68bac.JPG)
[cutadapt_log.10.txt](https://github.com/marcelm/cutadapt/files/10860003/cutadapt_log.10.txt)
How could I possibly resolve this?

Thanks and best,
Dharmesh

**Comment by marcelm** [comment]
The log message is this:
```
This is cutadapt 4.1 with Python 3.7.4
Command line parameters: --no-indels --max-n 0 --minimum-length 200 --cores=0 -a CCTACGGGNGGCWGCAG...GGATTAGATACCCBDGTAGTC -A GACTACHVGGGTATCTAATCC...CTGCWGCCNCCCGTAGG -o /home/mih/hpvac/cutadapt/_R1_001.fastq.gz -p /home/mih/hpvac/cutadapt/_R2_001.fastq.gz _R1_001.fastq.gz _R2_001.fastq.gz
Processing paired-end reads on 12 cores ...
ERROR: Traceback (most recent call last):
  File "/home/mih/.local/lib/python3.7/site-packages/cutadapt/pipeline.py", line 684, in run
    dnaio.read_paired_chunks(f, f2, self.buffer_size)
  File "/home/mih/.local/lib/python3.7/site-packages/dnaio/chunks.py", line 161, in read_paired_chunks
    start1 = f.readinto(memoryview(buf1)[0:1])  # type: ignore
  File "/home/mih/anaconda3/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/home/mih/anaconda3/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/mih/.local/lib/python3.7/site-packages/isal/igzip.py", line 293, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

I believe your `${SAMPLE}` environment variable is empty because the input file name does not contain a sample name as they are just `_R1_001.fastq.gz` and `_R1_001.fastq.gz`. According to your screenshot, these two files exist, but they are very small, so they may be some leftovers from earlier errors.

The error message just tells you that the input file is shorter than expected.

**Comment by marcelm** [comment]
Closing as I assume this has been solved.
