### ISSUE TITLE
Output fastq.gz files still contain primers after using cutadapt.

### ISSUE THREAD

**Issue by chrissy005** [marcelm/cutadapt#679]
I am using cutadapt in R (on a Windows system) to trim away primers from a NovaSeq 6000 -paired-end 250bp amplicon sequencing run. The 16S V4 region was targeted using the 515F-"GTGCCAGCMGCCGCGGTAA" and 806R- "GGACTACHVGGGTWTCTAAT" . 

The Cutadapt and Python version used : cutadapt 4.2 with Python 3.11.2

Prior to running cutadapt, primer detection resulted in: 
#                  Forward Complement Reverse RevComp
#FWD.ForwardReads   15693          0       0      83
#FWD.ReverseReads     122          0       0     335
#REV.ForwardReads      19          0       0    9003
#REV.ReverseReads    2540          0       0      88

After running cutadapt, primer detection resulted in:
#                Forward Complement Reverse RevComp
#FWD.ForwardReads     706          0       0      82
#FWD.ReverseReads     108          0       0      15
#REV.ForwardReads      18          0       0     160
#REV.ReverseReads      18          0       0      73

This clearly shows that the primers remain untrimmed in many reads as the output should all be 0.

I am not sure how to proceed from here and would appreciate help to process these reads using cutadapt
[A1_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896741/A1_2.fq.gz)

Command-line parameters used:

The following is the R-code that I have used from filtering the demultiplexed and compressed forward and reverse reads to primer removal with cutadapt:(references for codes: https://benjjneb.github.io/dada2/ITS_workflow.html and https://github.com/ErnakovichLab/dada2_ernakovichlab)

#Pre-processing data for dada2 - remove sequences with Ns, cutadapt####

# Get full paths for all files and save for downstream analyses
fnFs <- sort(list.files(SBW.TG.fq.r1.r2.fp, pattern="_1.fq.gz", full.names = TRUE))
fnRs <- sort(list.files(SBW.TG.fq.r1.r2.fp, pattern="_2.fq.gz", full.names = TRUE))

# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)

#Pre-filter to remove sequence reads with Ns
# Name the N-filtered files to put them in filtN
fnFs.filtN <- file.path(preprocess.fp, "filtN", basename(fnFs))
fnRs.filtN <- file.path(preprocess.fp, "filtN", basename(fnRs))

# Filter Ns from reads and put them into the filtN directory.
filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = FALSE) 
# CHANGE multithread to FALSE on Windows (here and elsewhere in the program)

# Set up the primer sequences to pass along to cutadapt
FWD <- "GTGCCAGCMGCCGCGGTAA"  ## CHANGE ME # this is 515f
REV <- "GGACTACHVGGGTWTCTAAT"  ## CHANGE ME # this is 806r

# Write a function that creates a list of all orientations of the primers
allOrients <- function(primer) {
  # Create all orientations of the input sequence
  require(Biostrings)
  dna <- DNAString(primer)  # The Biostrings works w/ DNAString objects rather than character vectors
  orients <- c(Forward = dna, Complement = complement(dna), Reverse = reverse(dna), 
               RevComp = reverseComplement(dna))
  return(sapply(orients, toString))  # Convert back to character vector
}

# Save the primer orientations to pass to cutadapt
FWD.orients <- allOrients(FWD)
REV.orients <- allOrients(REV)

# Write a function that counts how many time primers appear in a sequence
primerHits <- function(primer, fn) {
  # Counts number of reads in which the primer is found
  nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
  return(sum(nhits > 0))
}

#Before running cutadapt, look at primer detection in all samples. There may be some primers here, we will remove them below using cutadapt.
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN), 
    FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN), 
    REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN), 
    REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN))

##Result copied from console for checking in all reads:
#                  Forward Complement Reverse RevComp
#FWD.ForwardReads   15693          0       0      83
#FWD.ReverseReads     122          0       0     335
#REV.ForwardReads      19          0       0    9003
#REV.ReverseReads    2540          0       0      88

#to check for primer presence in just the first sample
#rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]), 
    #FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]), 
    #REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]), 
    #REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))

# Create directory to hold the output from cutadapt. 
#prep files for cutadapt
fnFs.cut <- file.path(trimmed.fp, basename(fnFs))
fnRs.cut <- file.path(trimmed.fp, basename(fnRs))

## Save the reverse complements of the primers to variables
FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)

##  Create the cutadapt flags ##
# Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC, "--minimum-length 50") 

# Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC, "--minimum-length 50") 

# Run Cutadapt
for (i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}

# As a sanity check,check for primers in the first cutadapt-ed sample:

rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut))

#Results
#                Forward Complement Reverse RevComp
#FWD.ForwardReads     706          0       0      82
#FWD.ReverseReads     108          0       0      15
#REV.ForwardReads      18          0       0     160
#REV.ReverseReads      18          0       0      73

The output of cutadapt during primer trimming was as follows:

This is cutadapt 4.2 with Python 3.11.2
Command line parameters: -g GTGCCAGCMGCCGCGGTAA -a ATTAGAWACCCBDGTAGTCC --minimum-length 50 -G GGACTACHVGGGTWTCTAAT -A TTACCGCGGCKGCTGGCAC --minimum-length 50 -n 2 -o processed/01_preprocess/trimmed.cutadapt/D5_1.fq.gz -p processed/01_preprocess/trimmed.cutadapt/D5_2.fq.gz processed/01_preprocess/filtN/D5_1.fq.gz processed/01_preprocess/filtN/D5_2.fq.gz
Processing paired-end reads on 1 core ...
Finished in 4.988 s (27.903 µs/read; 2.15 M reads/minute).

=== Summary ===

Total read pairs processed:            178,762
  Read 1 with adapter:                     260 (0.1%)
  Read 2 with adapter:                     646 (0.4%)

== Read fate breakdown ==
Pairs that were too short:                 329 (0.2%)
Pairs written (passing filters):       178,433 (99.8%)

Total basepairs processed:    71,446,981 bp
  Read 1:    35,723,153 bp
  Read 2:    35,723,828 bp
Total written (filtered):     71,357,954 bp (99.9%)
  Read 1:    35,679,766 bp
  Read 2:    35,678,188 bp

=== First read: Adapter 1 ===

Sequence: GTGCCAGCMGCCGCGGTAA; Type: regular 5'; Length: 19; Trimmed: 172 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1

Overview of removed sequences
length	count	expect	max.err	error counts
3	9	2793.2	0	9
18	72	0.0	1	0 72
20	73	0.0	1	0 73
47	2	0.0	1	2
51	3	0.0	1	3
52	3	0.0	1	3
53	5	0.0	1	5
54	3	0.0	1	3
55	1	0.0	1	1
173	1	0.0	1	1

=== First read: Adapter 2 ===

Sequence: ATTAGAWACCCBDGTAGTCC; Type: regular 3'; Length: 20; Trimmed: 91 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20 bp: 2

Bases preceding removed adapters:
  A: 7.7%
  C: 1.1%
  G: 90.1%
  T: 0.0%
  none/other: 1.1%
WARNING:
    The adapter is preceded by 'G' extremely often.
    The provided adapter sequence could be incomplete at its 5' end.
    Ignore this warning when trimming primers.

Overview of removed sequences
length	count	expect	max.err	error counts
3	21	2793.2	0	21
5	3	174.6	0	3
6	4	43.6	0	4
10	6	0.2	1	6
12	14	0.0	1	10 4
14	11	0.0	1	11
19	1	0.0	1	1
26	14	0.0	2	13 1
27	2	0.0	2	2
28	4	0.0	2	4
29	1	0.0	2	1
30	4	0.0	2	4
35	1	0.0	2	0 1
37	1	0.0	2	1
93	1	0.0	2	1
113	2	0.0	2	1 0 1
122	1	0.0	2	1

=== Second read: Adapter 3 ===

Sequence: GGACTACHVGGGTWTCTAAT; Type: regular 5'; Length: 20; Trimmed: 168 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20 bp: 2

Overview of removed sequences
length	count	expect	max.err	error counts
18	5	0.0	1	0 0 5
19	78	0.0	1	0 76 2
21	83	0.0	2	0 81 2
51	1	0.0	2	1
55	1	0.0	2	0 1

=== Second read: Adapter 4 ===

Sequence: TTACCGCGGCKGCTGGCAC; Type: regular 3'; Length: 19; Trimmed: 486 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1

Bases preceding removed adapters:
  A: 1.0%
  C: 4.3%
  G: 0.0%
  T: 94.0%
  none/other: 0.6%
WARNING:
    The adapter is preceded by 'T' extremely often.
    The provided adapter sequence could be incomplete at its 5' end.
    Ignore this warning when trimming primers.

Overview of removed sequences
length	count	expect	max.err	error counts
3	151	2793.2	0	151
4	3	698.3	0	3
5	303	174.6	0	303
6	2	43.6	0	2
9	3	0.7	0	0 3
10	11	0.2	1	0 11
12	3	0.0	1	3
14	1	0.0	1	0 1
28	1	0.0	1	0 1
43	1	0.0	1	0 1
47	2	0.0	1	0 2
73	1	0.0	1	0 1
113	1	0.0	1	0 1
122	1	0.0	1	0 1
153	1	0.0	1	1
200	1	0.0	1	0 1

WARNING:
    One or more of your adapter sequences may be incomplete.
    Please see the detailed output above.

Some of the raw fastq.gz forward and reverse files are attached:
[A1_1.fq.gz](https://github.com/marcelm/cutadapt/files/10897000/A1_1.fq.gz)
[A1_2.fq.gz](https://github.com/marcelm/cutadapt/files/10897001/A1_2.fq.gz)
[D3_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896713/D3_2.fq.gz)
[D4_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896717/D4_1.fq.gz)
[D4_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896718/D4_2.fq.gz)
[D5_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896723/D5_1.fq.gz)
[A2_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896747/A2_1.fq.gz)
[A2_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896752/A2_2.fq.gz)
[D5_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896728/D5_2.fq.gz)
[A1_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896737/A1_1.fq.gz)
[A3_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896757/A3_1.fq.gz)
[A3_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896764/A3_2.fq.gz)
[A4_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896772/A4_1.fq.gz)
[A4_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896779/A4_2.fq.gz)
[A5_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896788/A5_1.fq.gz)
[A5_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896796/A5_2.fq.gz)
[B1_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896806/B1_1.fq.gz)
[B1_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896815/B1_2.fq.gz)
[B2_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896820/B2_1.fq.gz)
[B2_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896835/B2_2.fq.gz)
[B3_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896841/B3_1.fq.gz)
[B3_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896843/B3_2.fq.gz)
[B4_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896845/B4_1.fq.gz)
[B4_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896851/B4_2.fq.gz)
[B5_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896858/B5_1.fq.gz)
[B5_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896866/B5_2.fq.gz)
[C1_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896874/C1_1.fq.gz)
[C1_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896886/C1_2.fq.gz)
[C3_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896895/C3_1.fq.gz)
[C3_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896898/C3_2.fq.gz)
[C4_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896901/C4_1.fq.gz)
[C4_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896904/C4_2.fq.gz)
[C5_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896917/C5_1.fq.gz)
[C5_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896920/C5_2.fq.gz)
[D1_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896934/D1_1.fq.gz)
[D1_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896938/D1_2.fq.gz)
[D2_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896946/D2_1.fq.gz)
[D2_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896951/D2_2.fq.gz)
[D3_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896961/D3_1.fq.gz)

Some of the primer trimmed files are as follows:
[A2_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896981/A2_1.fq.gz)
[A2_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896984/A2_2.fq.gz)
[B1_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896985/B1_1.fq.gz)
[B1_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896986/B1_2.fq.gz)
[B2_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896987/B2_1.fq.gz)
[B2_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896988/B2_2.fq.gz)
[C1_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896989/C1_1.fq.gz)
[C1_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896990/C1_2.fq.gz)
[C3_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896992/C3_1.fq.gz)
[C3_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896994/C3_2.fq.gz)
[D1_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896995/D1_1.fq.gz)
[D1_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896996/D1_2.fq.gz)
[D2_1.fq.gz](https://github.com/marcelm/cutadapt/files/10896998/D2_1.fq.gz)
[D2_2.fq.gz](https://github.com/marcelm/cutadapt/files/10896999/D2_2.fq.gz)

**Comment by marcelm** [comment]
Hi, I haven’t used DADA2 myself, so I don’t quite know how to interpret the output. Maybe a better option would be to ask the DADA2 developers about this?

That said, I can try to make a guess what is going on. Your "primer detection" table has 16 entries, and Cutadapt is run with four adapters, so whatever Cutadapt does, it can only reduce the numbers in four entries. (Plus some changes in the other entries because removing an adapter can always lead to another sequence not being detected as well.)

I don’t know how the numbers in the table are computed, that is, how the primer sequences are detected. (And to be honest, I wonder why whichever routine detects the primers doesn’t just remove them itself without involving Cutadapt ...). Assuming the routine detects primers in a different way from Cutadapt, I think it is normal to see that the numbers aren’t reduced to zero entirely. Going from 15693 to 706 doesn’t look that bad. I wouldn’t expect Cutadapt to miss 5% of adapter occurrences, though.

Looking at the pasted log, it appears that the error rates are relatively high. At least for `GTGCCAGCMGCCGCGGTAA`, there’s this line in the "Overview of removed sequences":
```
18 72 0.0 1 0 72
```
So 72 sequences of length 18 were removed. The last two numbers give a breakdown of many many errors were found when matching the adapter against the sequence: In 0 cases, no errors, and in 72 cases, there was one error. This is very unusual because you would expect there to be more cases with zero errors. So perhaps you have a typo in the primer sequence(s)?

As an experiment, you could try to reduce the maximum allowed error rate to 0 (option `-e 0` in Cutadapt; I don’t know how to do it in DADA2). If the primer sequences are correct, then you should see some reduction in primer content because most primer occurrences should be error-free. If nearly nothing is trimmed, then something else is wrong, such as the primer sequences (or perhaps a very high sequencing error rate).

**Comment by chrissy005** [comment]
Thank you for your explanation. I am certain the primer sequences are correct.

The 16 entries used for primer detection aims to identify both the forward and reverse primers in both forward and reverse sequences in all possible orientations such as forward, reverse, complement and reverse complement. I now see your point on how only 4 of these orientations are provided as flags for cutadapt.

As you mentioned, I should write into the DADA2 developers to get more clarification on their pipeline with cutadapt.

**Comment by chrissy005** [comment]
As I was certain that the primer sequences used were correct, I experimented as you suggested which was to reduce the maximum error rate ("-e",0). I did see quite a considerable reduction in primer content for some sequences but there was no change in the rest. 

Along with some suggestions from Hannah (https://github.com/ErnakovichLab/dada2_ernakovichlab/issues/13) to increase the number of times primer as adapters are identified and removed, the R code I used for cutadapt is : 
for (i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 5, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             "--minimum-length", 150, #reads below 100 base pairs are removed
                             "-e", 0, # reduce maximum allowed error rate to 0 instead of default 0.1%
                             fnFs.filtN[i], fnRs.filtN[i])) #
}

The final count of primers in the filtered reads are:
#                 Forward Complement Reverse RevComp
#FWD.ForwardReads       0          0       0      81
#FWD.ReverseReads     102          0       0       0
#REV.ForwardReads      16          0       0       0
#REV.ReverseReads       0          0       0      67

From the looks of this and by manually inspecting the filtered reads, it appears that the sequences in the forward and reverse files may be of mixed orientation and many primers were detected either in the middle or a quarter into the read. Not sure how to work around this.

But I think I have considerable progress compared to:
#                Forward Complement Reverse RevComp
#FWD.ForwardReads     706          0       0      82
#FWD.ReverseReads     108          0       0      15
#REV.ForwardReads      18          0       0     160
#REV.ReverseReads      18          0       0      73

**Comment by marcelm** [comment]
> many primers were detected either in the middle or a quarter into the read. Not sure how to work around this.

Do  need to work around this at all? It depends on what the next tool in the pipeline expects.

I have also seen stricter setups where anything that doesn’t match expectations (single, full-length 5' primer in the beginning etc.) is discarded because one can argue that anything that looks weird (partial primer, primer in unexpected places or unexpecetd orientation) is a sign that something is wrong with the read and it shouldn’t be trusted anyway.

Anyway, it appears your numbers look ok now. Would you be fine with closing this issue?

**Comment by chrissy005** [comment]
Thank you for your help. I am considering the stricter setup options too.
Will close the issues now.
