### ISSUE TITLE
Adapter Sequence Character Error

### ISSUE THREAD

**Issue by mmccorkindale** [marcelm/cutadapt#682]
Hi,

I have a quick question - on Illumina's site for adapter sequences, they give the DNA PCR-Free Prep sequence for trimming as:

CTGTCTCTTATACACATCT+ATGTGTATAAGAGACA

But when providing this as -a and -A options, I get this error:

cutadapt: error: Character '+' in adapter sequence 'CTGTCTCTTATACACATCT+ATGTGTATAAGAGACA' is not a valid IUPAC code. Use only characters 'ABCDGHKMNRSTUVWXY'.

Should I just provide the two sequences separately, i.e.

cutadapt \
-a CTGTCTCTTATACACATCT \
-a ATGTGTATAAGAGACA \
-A CTGTCTCTTATACACATCT \
-A ATGTGTATAAGAGACA \
-j 4 \
-o R1_trimmed.fastq.gz \
-p R2_trimmed.fastq.gz \
R1.fastq.gz \
R2.fastq.gz

Thanks,

Michael

**Comment by marcelm** [comment]
I honestly don’t know. The Illumina document that I found (and where you possibly have that sequence from) says this:
> llumina DNA PCR-Free Prep, Tagmentation Adapter Trimming
> The following sequence includes two adapter sequences joined by a plus sign. When performing
> adapter trimming, the software independently assesses each adapter for trimming.
> CTGTCTCTTATACACATCT+ATGTGTATAAGAGACA

I have no idea what "independently assesses each adapter" means here.

Try the above command that you wrote and also try to provide it as a single sequence (by just omitting the `+`). Then look at the statistics and try to get an impression what works.
