### ISSUE TITLE
Cannot download cutadapt on windows 10, error in building isal

### ISSUE THREAD

**Issue by kitkat5671** [marcelm/cutadapt#683]
**Hello! I am very new to this and am currently trying to download cutadapt on my windows laptop by following the instructions from this site: https://cutadapt.readthedocs.io/en/stable/installation.html#installation-on-windows

I am using pip. I followed their instructions but am stuck on this command: py -m pip install cutadapt

When running, I get the following error message:** 
C:\Users\kat>py -m pip install cutadapt
Requirement already satisfied: cutadapt in c:\users\kat\appdata\local\programs\python\python311-32\lib\site-packages (4.2)
Collecting dnaio>=0.9.1
  Using cached dnaio-0.10.0-cp311-cp311-win32.whl
Collecting xopen>=1.6.0
  Using cached xopen-1.7.0-py3-none-any.whl (15 kB)
Collecting isal>=1.0.0
  Using cached isal-1.1.0.tar.gz (682 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: isal
  Building wheel for isal (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for isal (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      C:\Users\kat\AppData\Local\Temp\pip-build-env-9anq_z07\overlay\Lib\site-packages\setuptools\config\setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-311
      creating build\lib.win32-cpython-311\isal
      copying src\isal\igzip.py -> build\lib.win32-cpython-311\isal
      copying src\isal\__init__.py -> build\lib.win32-cpython-311\isal
      copying src\isal\igzip_lib.pyi -> build\lib.win32-cpython-311\isal
      copying src\isal\isal_zlib.pyi -> build\lib.win32-cpython-311\isal
      copying src\isal\_isal.pyi -> build\lib.win32-cpython-311\isal
      copying src\isal\py.typed -> build\lib.win32-cpython-311\isal
      creating build\lib.win32-cpython-311\isal\isa-l
      copying src\isal\isa-l\LICENSE -> build\lib.win32-cpython-311\isal\isa-l
      copying src\isal\isa-l\README.md -> build\lib.win32-cpython-311\isal\isa-l
      copying src\isal\isa-l\Release_notes.txt -> build\lib.win32-cpython-311\isal\isa-l
      running build_ext
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for isal
Failed to build isal
ERROR: Could not build wheels for isal, which is required to install pyproject.toml-based projects

**I then attempted to download isal separately with this command: py -m pip install isal
However, I now get this error message:** 
C:\Users\kat>py -m pip install isal
Collecting isal
  Using cached isal-1.1.0.tar.gz (682 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: isal
  Building wheel for isal (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for isal (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      C:\Users\kat\AppData\Local\Temp\pip-build-env-18tx98g6\overlay\Lib\site-packages\setuptools\config\setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-311
      creating build\lib.win32-cpython-311\isal
      copying src\isal\igzip.py -> build\lib.win32-cpython-311\isal
      copying src\isal\__init__.py -> build\lib.win32-cpython-311\isal
      copying src\isal\igzip_lib.pyi -> build\lib.win32-cpython-311\isal
      copying src\isal\isal_zlib.pyi -> build\lib.win32-cpython-311\isal
      copying src\isal\_isal.pyi -> build\lib.win32-cpython-311\isal
      copying src\isal\py.typed -> build\lib.win32-cpython-311\isal
      creating build\lib.win32-cpython-311\isal\isa-l
      copying src\isal\isa-l\LICENSE -> build\lib.win32-cpython-311\isal\isa-l
      copying src\isal\isa-l\README.md -> build\lib.win32-cpython-311\isal\isa-l
      copying src\isal\isa-l\Release_notes.txt -> build\lib.win32-cpython-311\isal\isa-l
      running build_ext
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for isal
Failed to build isal
ERROR: Could not build wheels for isal, which is required to install pyproject.toml-based projects

**I'm just very lost on what to do now... If anyone has any advice, that would be amazing! Thank you!**

**Comment by rhpvorderman** [comment]
Hi, python-isal maintainer here. Windows should be a supported platform, and we have modified xopen in such a way that it shouldn't download isal on unsupported platforms. Only 64-bit windows, linux and macos x86/64 platforms are supported as well as aarch64 platforms on linux.

So it should run on windows, but then I saw this in your logs: `cached dnaio-0.10.0-cp311-cp311-win32.whl`. For some reason it is downloading the 32-bit binaries for dnaio, but apparantly your platform identifies as `amd64`. You have probably the 32-bit version of python installed. The best solution is to remove this and install the 64-bit version. Then everything should work.

If you do not have the privileges to install 64-bit python you can apply the following solution.
```bash
pip install --no-deps cutadapt
pip install --no-deps dnaio
pip install --no-deps xopen
```

Alternatively, [you can install bioconda](http://bioconda.github.io/), and install cutadapt with 
```bash
conda create -n cutadapt cutadapt  # Installs cutadapt in a new conda environment
conda activate cutadapt  # activates the environment so you can use cutadapt.
```

**Comment by kitkat5671** [comment]
You were right! I installed the 64-bit and it worked thank you so much!!!

**Comment by rhpvorderman** [comment]
You're welcome. The 64-bit version should give a lot less problems as x86 32-bit has gotten quite obscure now in 2023. (I believe the last chips produced were an intel atom series that got produced until 2008ish or so).
