### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mycotonia3** [marcelm/cutadapt#697]
<Hello, I have a mac M1 and i am having issues installing cutadapt.  I looked at an old issue (#629) and i think it may have something to do with not having the proper dnaoi file. I have Python 3.10.0

I followed these instructions:
pip install virtualenv
python3 -m virtualenv cutadapt_venv
source cutadapt_venv/bin/activate
pip install --upgrade pip setuptools
pip install --nodeps cutadapt
pip install xopen

pip install /Users/toniadebellis/Downloads/dnaio-0.10.0-cp311-cp311-macosx_10_9_x86_64.whl
ERROR: dnaio-0.10.0-cp311-cp311-macosx_10_9_x86_64.whl is not a supported wheel on this platform.
tried this one too:
 pip install /Users/toniadebellis/Downloads/dnaio-0.10.0-cp310-cp310-macosx_10_9_x86_64.whl
ERROR: dnaio-0.10.0-cp310-cp310-macosx_10_9_x86_64.whl is not a supported wheel on this platform.

would you know what is going wrong from this info?

here is the part prior to the error:
toniadebellis@Tonias-MacBook-Pro ~ % pip install virtualenv
Requirement already satisfied: virtualenv in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (20.21.0)
Requirement already satisfied: distlib<1,>=0.3.6 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from virtualenv) (0.3.6)
Requirement already satisfied: filelock<4,>=3.4.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from virtualenv) (3.11.0)
Requirement already satisfied: platformdirs<4,>=2.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from virtualenv) (2.4.0)
toniadebellis@Tonias-MacBook-Pro ~ % python3 -m virtualenv cutadapt_venv
created virtual environment CPython3.10.0.final.0-64 in 277ms
  creator CPython3Posix(dest=/Users/toniadebellis/cutadapt_venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/toniadebellis/Library/Application Support/virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
toniadebellis@Tonias-MacBook-Pro ~ % source cutadapt_venv/bin/activate
(cutadapt_venv) toniadebellis@Tonias-MacBook-Pro ~ % pip install --upgrade pip setuptools
Requirement already satisfied: pip in ./cutadapt_venv/lib/python3.10/site-packages (23.0.1)
Requirement already satisfied: setuptools in ./cutadapt_venv/lib/python3.10/site-packages (67.4.0)
Collecting setuptools
  Using cached setuptools-67.6.1-py3-none-any.whl (1.1 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 67.4.0
    Uninstalling setuptools-67.4.0:
      Successfully uninstalled setuptools-67.4.0
Successfully installed setuptools-67.6.1
(cutadapt_venv) toniadebellis@Tonias-MacBook-Pro ~ % pip install --nodeps cutadapt

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --nodeps
(cutadapt_venv) toniadebellis@Tonias-MacBook-Pro ~ % pip install xopen
Collecting xopen
  Using cached xopen-1.7.0-py3-none-any.whl (15 kB)
Installing collected packages: xopen
Successfully installed xopen-1.7.0

thank you!

**Comment by rhpvorderman** [comment]
Since you were able to install cutadapt, obviously your C compiler works. Can you try `pip install --no-deps dnaio`? That should get the latest source and compile it.

**Comment by marcelm** [comment]
Closing this for now. In time, I’ll try to make appropriate pre-compiled versions of dnaio and Cutadapt available, but not at the moment.
