### ISSUE TITLE
Installation of cutadapt in apple M2 pro 2023 fails. 

### ISSUE THREAD

**Issue by Kiulianm** [marcelm/cutadapt#702]
this is the error I am getting.

"Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cutadapt

Current channels:

  - https://conda.anaconda.org/bioconda/label/cf201901/osx-arm64
  - https://conda.anaconda.org/bioconda/label/cf201901/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org
"

**Comment by marcelm** [comment]
Hi, Bioconda does not provide native packages for arm64 macOS. Have you tried the instructions at https://cutadapt.readthedocs.io/en/latest/installation.html#installation-with-conda? In particular, this line:
```
CONDA_SUBDIR=osx-64 conda create -n cutadaptenv cutadapt
```
This will install the x86 version of Cutadapt and then it should be runnable through the emulation layer in macOS.

**Comment by Kiulianm** [comment]
Yes, I tried that but still Is not installed. I get this error

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cutadapt

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by marcelm** [comment]
I think I can see from the error message that you haven't set up the conda-forge and bioconda channels. There's a link in the Cutadapt installation instructions a bit reseller on the page.

**Comment by Kiulianm** [comment]
Thank you Marcelm, I finally installed it.

**Comment by marcelm** [comment]
Perfect!
