### ISSUE TITLE
How use cutadapt in jupyter?

### ISSUE THREAD

**Issue by junjunlab** [marcelm/cutadapt#703]
Hi, thanks for this great package. Can I use the cutadapt in jupyter nootbook? Can you give some examples? Thanks.

**Comment by rhpvorderman** [comment]
Cutadapt does not have a clearly defined API for use by other python programs. It focuses on its command line application. Luckily Jupyter can also run arbitrary shell commands: https://jupyter-tutorial.readthedocs.io/en/stable/workspace/ipython/shell.html. You could use that to run cutadapt. Does that help you?
