### ISSUE TITLE
cutadapt.exe run with error

### ISSUE THREAD

**Issue by junjunlab** [marcelm/cutadapt#704]
Hi, I download the cutadapt.exe binary and run on fastq files. But I got error like this:

![1683531499517](https://user-images.githubusercontent.com/64965509/236764858-c1deb1dd-7954-4904-ab6d-b979c6ead767.png)

The fastq file seems good. Thanks.

**Comment by marcelm** [comment]
Hi, sorry for a late reply, I was away.

I believe the error occurs when Cutadapt wants to print a report in the end, which contains the `µ` character. It appears that your terminal is configured to use the `gbk` encoding, which cannot handle that character. I don’t really know how to fix this, maybe you can find a way to change your terminal to UTF-8?

**Comment by marcelm** [comment]
This should be fixed now. If the your terminal cannot display the `µ` character, it will print a `u` instead.
