### ISSUE TITLE
Why did CutAdapt not remove all my N's?

### ISSUE THREAD

**Issue by amy-houseman** [marcelm/cutadapt#712]
- Cutadapt v3.5 and Python version
- Container 

- Command:

singularity exec $CONTAINER cutadapt -q 30 -m 35 -a TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG -A GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG -o $OUTPUTFASTQFORWARD -p $OUTPUTFASTQREVERSE $INPUTFASTQFORWARD $INPUTFASTQREVERSE > $TXTREPORT"

If you report unexpected trimming behavior, this would also be helpful:

I have ran this similar command through a few different samples using their corresponding adapter sequences, according to FastQC and multiQC for some of my samples there are still N's being called (now I know that the orange peak is from 12 forward reads which were all sequenced on the same day, same lane, same sequencing company, same exome capture kit). But I am also concerned about the other peaks that remain.

Picture before and after cutadapt across 102 individuals forward and reverse fastq files.

![Picture 1](https://github.com/marcelm/cutadapt/assets/110385188/689a3e09-ff40-41d2-86c6-aca886698480)

Thanks!
Amy

**Comment by amy-houseman** [comment]
Thank you lots for your reply!

My only problem is I didn't spot this before so carried on with downstream processing - I used BWA-mem for aligning - do you think the the data above would prove problematic despite only those in the peak at 59 being above 5%? 

Thank you lots!
Amy

**Comment by marcelm** [comment]
I think you’re probably fine. The `N`s in the middle are unproblematic IMO. BWA-MEM will still be able to align the read and any well-behaved tool you use afterwards will see that an `N` was aligned and will not give you a spurious variant call or so. The untrimmed 5' ends should not be a problem either because BWA-MEM soft-clips ends with too many mismatches.

**Comment by amy-houseman** [comment]
Thank you lots, especially for your fast reply! You have put my mind at ease. BW, Amy
