### ISSUE TITLE
MNot a valid IUPAC code

### ISSUE THREAD

**Issue by scxu-pl** [marcelm/cutadapt#713]
Hello,

I am experiencing an issue when I used cutadapt to sort my sequences based on barcodes.
The version of cutadapt I am using is 4.4 which has been installed through pip, python version is 3.11.2

The parameters I used are as below:
-j 10 -g ^file:DB.fasta -o GN64_S2A_8--S2-{}.CA.fasta input.S2--4.minCluster2.fa --discard-untrimmed -action=none

and it ended up with error:
ERROR: Character 'O' in adapter sequence 'NONE' is not a valid IUPAC code. Use only characters 'ABCDGHIKMNRSTUVWXY'.

However I checked my barcode database and did not find anything that could trigger this issue.

**Comment by marcelm** [comment]
You have a typo (missing dash `-`) in your command: Instead of `-action=none`, it should be `--action=none`.

`-action=none` is interpreted the same as `-a ction=none`, which would mean "search for an adapter named *ction* with the sequence *none*"

**Comment by scxu-pl** [comment]
> You have a typo (missing dash `-`) in your command: Instead of `-action=none`, it should be `--action=none`.
> 
> `-action=none` is interpreted the same as `-a ction=none`, which would mean "search for an adapter named _ction_ with the sequence _none_"

Thank you, you're right. it solved perfectly my problem.

**Comment by marcelm** [comment]
Great!
