### ISSUE TITLE
cutadapt: error: Character 'F'

### ISSUE THREAD

**Issue by Muhyees** [marcelm/cutadapt#717]
Hi, 
i am using cutadapt 3.5 with Python 3.10.6 for demultiplexing and trimming of my sequences.
I have made a barcode file for the demultilexing, my barcode lenghth for each is more tham 8 bases long.

i used the code below:
cutadapt -e 1 -g ^file:BAR_60.fasta -o trimmed-{name}.1.fastq -p trimmed-{name}.2.fastq ~/LINES/File_1.fq.gz ~/LINES/File_2.fq.gz

I keep receiving the error below.

cutadapt: error: Character 'F' in adapter sequence 'FILE:BAR_60.FASTA' is not a valid IUPAC code. Use only characters 'ABCDGHKMNRSTUVWXY'

**Comment by marcelm** [comment]
Hi, Cutadapt 3.5 does not support using `^` together with `file:`. You need to update to at least Cutadapt 4.1 to be able to do so.

**Comment by Muhyees** [comment]
Thank you for your swift reply. I updated to 4.4 and it worked.

**Comment by marcelm** [comment]
Great!
