### ISSUE TITLE
Unable to install cutadapt on Windows 11

### ISSUE THREAD

**Issue by ImperialBV** [marcelm/cutadapt#720]
Hi - I have read through all the issues lists and although some have been helpful, I can't get to the bottom on installing cutadapt for Rstudio (ITS primers trimming).

**1.** I normally use **miniconda3 platform** for cutadapt on my Mac without a problem. I tried this with Windows 11 but a version is not recognised in R and I have read this can not be used for windows anyway. It is recognised on the command prompt but when looking at the file path: C:/Users/Processing PC1/miniconda3/Lib/site-packages  AND C:/Users/Processing PC1/miniconda3/ens/cutadaptenv there is no cutadapt in the folder.

****2.** I used the command prompt to  download virtualenv using pip:**

PS C:\Users\Processing PC1> pip install virtualenv

I get this message:
Requirement already satisfied: virtualenv in c:\users\processing pc1\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (20.24.0)
Requirement already satisfied: distlib<1,>=0.3.6 in c:\users\processing pc1\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from virtualenv) (0.3.7)
Requirement already satisfied: filelock<4,>=3.12 in c:\users\processing pc1\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from virtualenv) (3.12.2)
Requirement already satisfied: platformdirs<4,>=3.5.1 in c:\users\processing pc1\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from virtualenv) (3.9.1)
PS C:\Users\Processing PC1>

When installing cutadapt with the command:
PS C:\Users\Processing PC1> virtualenv cutadapt-venv

I get:
virtualenv : The term 'virtualenv' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ virtualenv cutadapt-venv
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (virtualenv:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I can't seem to activate the virtualenv using the guides online.

3. I then tried to install cutadapt on python 3.11 directly and included the path on the script - but the version is not recognised.

4. I also tried to download cutadapt.exe using the command "py -m pip install cutadapt" - in return I get the following: 'py' is not recognized as an internal or external command,
operable program or batch file.

Would be grateful for your advice.

**Comment by marcelm** [comment]
(I’m on vacation, so just a short reply.) If Cutadapt 4.0 is good enough for your needs, you could try the .exe available from https://github.com/marcelm/cutadapt/releases.

**Comment by ImperialBV** [comment]
Thank you. I have tried downloaded from the cutadapt release successfully, and it is recognised, but I also get the following message that it is not recognised.
![Screenshot 2023-07-20 183634](https://github.com/marcelm/cutadapt/assets/137567532/996cfb7c-4481-46a0-88fc-bbf95e52c7a3)

**Comment by marcelm** [comment]
You are trying two different installation methods: The `pip install` method seems to have worked, but the problem is that the command cannot be found. I don’t know enough about Python on Windows, but maybe it works to run `pip install --user cutadapt` instead.

The other method is to use the downloaded `cutadapt.exe`. To make that work, try typing out the full path to the downloaded `.exe` file. So if the `cutadapt.exe` file is in the `Downloads` folder, try typing in this:
```
"c:\Users\Processing PC1\Downloads\cutadapt.exe"
```
(Include the quote marks. They are needed because the path contains a space.)

Optionally, you can make it work without typing in the full path by changing your PATH environment variable appropriately, but I’m not quite sure how this is done on Windows. (Perhaps https://stackoverflow.com/questions/4822400/ helps.)

**Comment by ImperialBV** [comment]
Thank you very much. The second option worked successfully. 

> cutadapt <- "C:/Users/Processing PC3/Downloads/cutadapt.exe"
> system2(cutadapt, args = "--version")
4.0
