### ISSUE TITLE
Could not build wheels for cutadapt for mac 12.7.1 monterey

### ISSUE THREAD

**Issue by Wardah0q** [marcelm/cutadapt#738]
my version of python is Python 3.11.6 and when I try to install this: sudo python3 -m pip install cutadapt >I get this error message: ERROR: Failed building wheel for cutadapt
Failed to build cutadapt
ERROR: Could not build wheels for cutadapt, which is required to install pyproject.toml-based projects

This is the entire message:
Collecting cutadapt
  Downloading cutadapt-4.5.tar.gz (248 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.4/248.4 kB 631.2 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dnaio>=0.10.0 (from cutadapt)
  Obtaining dependency information for dnaio>=0.10.0 from https://files.pythonhosted.org/packages/47/ce/0a05197fce4e57c4f27fd9060b2cf278fc7f62c0d56e67432c56ce4c36a0/dnaio-1.0.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Downloading dnaio-1.0.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata (3.0 kB)
Collecting xopen>=1.6.0 (from cutadapt)
  Obtaining dependency information for xopen>=1.6.0 from https://files.pythonhosted.org/packages/48/dc/de5c8e5d11b252f321045460ceedc3e6d07c7b6de2983a33c2a1e597c7fa/xopen-1.8.0-py3-none-any.whl.metadata
  Downloading xopen-1.8.0-py3-none-any.whl.metadata (10 kB)
Collecting isal>=1.4.1 (from xopen>=1.6.0->cutadapt)
  Obtaining dependency information for isal>=1.4.1 from https://files.pythonhosted.org/packages/7e/29/b9080fbe343dd8039ed3afc99ada03091f6486a9a38deb611888532cb7e8/isal-1.5.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Downloading isal-1.5.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata (9.9 kB)
Downloading dnaio-1.0.1-cp311-cp311-macosx_10_9_x86_64.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 125.4 kB/s eta 0:00:00
Downloading xopen-1.8.0-py3-none-any.whl (16 kB)
Downloading isal-1.5.1-cp311-cp311-macosx_10_9_x86_64.whl (246 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.0/246.0 kB 318.9 kB/s eta 0:00:00
Building wheels for collected packages: cutadapt
  Building wheel for cutadapt (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cutadapt (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-x86_64-cpython-311
      creating build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/steps.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/files.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/predicates.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/align.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/_version.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/log.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/__init__.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/parser.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/_match_tables.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/tokenizer.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/cli.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/utils.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/pipeline.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/kmer_heuristic.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/runners.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/modifiers.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/statistics.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/json.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/__main__.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/report.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/adapters.py -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      running egg_info
      writing src/cutadapt.egg-info/PKG-INFO
      writing dependency_links to src/cutadapt.egg-info/dependency_links.txt
      writing entry points to src/cutadapt.egg-info/entry_points.txt
      writing requirements to src/cutadapt.egg-info/requires.txt
      writing top-level names to src/cutadapt.egg-info/top_level.txt
      ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
      reading manifest file 'src/cutadapt.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'src/cutadapt/*.c'
      adding license file 'LICENSE'
      writing manifest file 'src/cutadapt.egg-info/SOURCES.txt'
      copying src/cutadapt/_align.pyi -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/_kmer_finder.pyi -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/expected_errors.h -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/info.pyi -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      copying src/cutadapt/qualtrim.pyi -> build/lib.macosx-12-x86_64-cpython-311/cutadapt
      running build_ext
      Compiling src/cutadapt/_align.pyx because it changed.
      [1/1] Cythonizing src/cutadapt/_align.pyx
      building 'cutadapt._align' extension
      creating build/temp.macosx-12-x86_64-cpython-311
      creating build/temp.macosx-12-x86_64-cpython-311/src
      creating build/temp.macosx-12-x86_64-cpython-311/src/cutadapt
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/cutadapt/_align.c -o build/temp.macosx-12-x86_64-cpython-311/src/cutadapt/_align.o
      clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=12'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cutadapt
Failed to build cutadapt
ERROR: Could not build wheels for cutadapt, which is required to install pyproject.toml-based projects

> I've tried to fix this so many ways but I keep getting the message that cutadapt cannot build wheels - can anyone help with this issue

**Comment by marcelm** [comment]
Hi, I just made the necessary changes for providing precompiled wheels for Cutadapt. This means that you won’t have to compile the wheel yourself.

The wheels will be available for the next Cutadapt release (likely version 4.6). In the meantime, they are available for testing here: https://test.pypi.org/project/cutadapt/4.6a0/#files

I believe you can install the wheel relevant for you like this:
```
pip install https://test-files.pythonhosted.org/packages/44/22/a61565ab59d22d0a03b544e2ea2c73b2a2ca8fd62e877418eddba6470830/cutadapt-4.6a0-cp311-cp311-macosx_10_9_x86_64.whl
```
The version number will be 4.6a0 (alpha 0), but it is essentially identical to 4.5.
