### ISSUE TITLE
How to handle reads with alternative adapters or primer sequences

### ISSUE THREAD

**Issue by fxfish** [marcelm/cutadapt#744]
Hi,
It's a powerful  tools for data analysis.
I have a question when trimming primers from paired-end reads of amplicon. The sequencing data (e.g. forward_reads) likes: AAATTTaaaaaaaaCCCGGG and GGGCCCtttttttttTTTAAA (mixed), I want all output data likes: aaaaaaaa, which means recognizing ‘GGGCCC...TTTAAA’ and reversing complementary sequence.
I must do three steps to achive this, one using -g ^AAATTT -G ^CCCGGG, and another using -g ^CCCGGG -G ^AAATTT, at last combining 1st R1.fq and 2st R2.fq into the last R1.fq.
Can I just use one step commond? -g -g or -g XXX|XXX
Thanks.

**Comment by marcelm** [comment]
I have implemented this now. Please update to Cutadapt 4.6. Then you can use `--revcomp` with paired-end reads.

(The release will be available on Bioconda in probably one or two hours.)

**Comment by fxfish** [comment]
wow, nice, I will update it on conda, thanks.
