### ISSUE TITLE
paired fasta input with multiple cores

### ISSUE THREAD

**Issue by bernt-matthias** [marcelm/cutadapt#746]
I recently looked at the Galaxy tool wrapper for cutadapt and found that it fails the tests for fasta input. This is because we recently enabled multiple cores for our tests. This triggered this exception:

```
Processing paired-end reads on 2 cores ...
ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cutadapt/runners.py", line 87, in run
    for index, chunks in enumerate(self._read_chunks(*files)):
  File "/usr/local/lib/python3.10/site-packages/cutadapt/runners.py", line 101, in _read_chunks
    for chunks in dnaio.read_paired_chunks(
  File "/usr/local/lib/python3.10/site-packages/dnaio/chunks.py", line 164, in read_paired_chunks
    raise FileFormatError(
dnaio.exceptions.FileFormatError: Error in sequence file at unknown line: Paired-end data must be in FASTQ format when using multiple cores
```

https://github.com/marcelm/dnaio/blob/a3147ccc2a33517e51edac0794e12dafdcc03ad5/src/dnaio/chunks.py#L165

I wondered if there is an easy way to allow paired fasta input in cutadapt also with multiple cores enabled? Maybe only use a single core for fasta IO?

Found this for cutadapt 4.5.

**Comment by bernt-matthias** [comment]
Still a good idea to mention the versions:

```
Package    Version
---------- -------
cffi       1.16.0
cutadapt   4.5
dnaio      1.0.1
isal       1.3.0
pip        23.2.1
pycparser  2.21
setuptools 68.2.2
wheel      0.41.2
xopen      1.7.0
zstandard  0.21.0
```

We are using the following docker container: `quay.io/biocontainers/cutadapt:4.5--py310h4b81fae_0`

**Comment by marcelm** [comment]
As an explanation for the error, Cutadapt splits the input data up into chunks containing about 4 MB of data when it runs on multiple cores. The chunks are then processed in parallel. For paired-end data, there will be two of these chunks that both need to have the same number of reads. Doing this correctly and efficiently is only implemented for FASTQ because it’s easier due to FASTQ records having a constant number of lines.

I’m working on FASTA support.

**Comment by bernt-matthias** [comment]
Excellent. Just as a side note I just discovered (since we mirror some of the tests implemented here in the galaxy tool tests) that you may already have a test for this https://github.com/marcelm/cutadapt/blob/e04cc32e392e1cbe0c518b4e0637cdf03533d440/tests/test_paired.py#L768 ..if you enable the cores parameter there.

**Comment by marcelm** [comment]
> Excellent. Just as a side note I just discovered (since we mirror some of the tests implemented here in the galaxy tool tests) that you may already have a test for this
> 
> https://github.com/marcelm/cutadapt/blob/e04cc32e392e1cbe0c518b4e0637cdf03533d440/tests/test_paired.py#L768
> ..if you enable the cores parameter there.

Ah, good find! I have tested changing this locally and it works with the dnaio PR I just opened. I’ll need to make a new dnaio release first and then bump the dependency in Cutadapt before I can make that change permanent.

**Comment by marcelm** [comment]
This should now work. Please update dnaio to 1.2.0 to get the fix.

**Comment by bernt-matthias** [comment]
Thanks a lot. 

For the Galaxy tool I would need a new biocontainer. So I suggest to update the pin in the bioconda recipe https://github.com/bioconda/bioconda-recipes/pull/44763
