### ISSUE TITLE
Installation instructions need conda channel

### ISSUE THREAD

**Issue by susheelbhanu** [marcelm/cutadapt#752]
Hi, 

The current installation instructions list the following on the readthedocs page: `conda create -n cutadaptenv cutadapt`. 

Please note that this is throwing a 'channel' missing error, and so should be updated as follows:
`conda create -n cutadaptenv -c bioconda cutadapt`

Thanks!

**Comment by rhpvorderman** [comment]
These are the installation instructions on readthedocs:

> Cutadapt is available as a Conda package from the [Bioconda channel](https://bioconda.github.io/). [Install miniconda](http://conda.pydata.org/miniconda.html) if you don’t have Conda. Then follow the [Bioconda installation instructions](https://bioconda.github.io/user/install.html) (in particular, make sure you have both bioconda and conda-forge in your channels list).

> To then install Cutadapt into a new Conda environment, use this command:

> `conda create -n cutadaptenv cutadapt`

**Comment by marcelm** [comment]
I’ve updated the installation instructions to make it clearer that the Bioconda channel needs to be configured before running the `conda create` command.

For completeness: If you [do not want to permanently add the Bioconda and/or conda-forge channels to your channel list](https://bioconda.github.io/#do-not-modify-condarc), the correct command would be this:
```
conda create -c conda-forge -c bioconda --strict-channel-priority -n cutadapt cutadapt
```
