### ISSUE TITLE
Make Cutadapt portable on macOS

### ISSUE THREAD

**Issue by DmitriiSukhomlinov** [marcelm/cutadapt#756]
Hello,
 I am trying to make a Python 3.12.1 portable package with Cutadapt 4.6 included (on macOS, installed by pip). The module installation works perfect and Cutadapt itself works without any problem on the computer it's been installed.

But, when I move this Python3 package to another macOS computer and try to run the simple command:

`./python3 -m cutadapt --version`

I recieve the following message:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/developer/dsukhomlinov/python3/lib/python3.12/site-packages/cutadapt/__main__.py", line 2, in <module>
    from cutadapt.cli import main_cli
  File "/Users/developer/dsukhomlinov/python3/lib/python3.12/site-packages/cutadapt/cli.py", line 67, in <module>
    import dnaio
  File "/Users/developer/dsukhomlinov/python3/lib/python3.12/site-packages/dnaio/__init__.py", line 40, in <module>
    from ._core import (
ModuleNotFoundError: No module named 'dnaio._core'
```

It is obvious, that there is some kind of problem in a [dnaio](https://github.com/marcelm/dnaio/) library (which is, as Cutadapt, your creation), but I cannot get, what kind of problem and how I can resolve it on one computer so this problem does not appear on another one.

Reinstallation of `dnaio` on the machine I'm trying to run Cutadapt helps, but the point is, I do not want the user who gets the Python+Cutadapt package need to to any reinstallation stuf.

When `dnaio` is reinstalled, I've got pretty similar problem again, but with cutadapt itself:

```
Traceback (most recent call last):
  File "/Users/dsukhomlinov/ext_tools_mac_64-bit/python3/bin/./cutadapt", line 5, in <module>
    from cutadapt.cli import main_cli
  File "/Users/dsukhomlinov/ext_tools_mac_64-bit/python3/lib/python3.12/site-packages/cutadapt/cli.py", line 71, in <module>
    from cutadapt.adapters import warn_duplicate_adapters, Adapter, InvalidCharacter
  File "/Users/dsukhomlinov/ext_tools_mac_64-bit/python3/lib/python3.12/site-packages/cutadapt/adapters.py", line 14, in <module>
    from ._kmer_finder import KmerFinder
ModuleNotFoundError: No module named 'cutadapt._kmer_finder'
```

And again, the module reinstallation helps, but I do not want the user would required to do that.

I understand, that these problems in some way connected to `_core` from `dnaio` and `_kmer_finder` from `cutadapt` parts respectively, but I am not sure, how to resolve this proble. Maybe you have any ideas about that?

**Comment by rhpvorderman** [comment]
Mac OS X comes into an arm64 variant and an x86_64 variant. You cannot create a portable package that works on both versions, unless you include compiled modules for both versions. 

The arm64 variant is really hard to release software for, as there is no easily available mac os arm64 hardware for continuous integration testing and release. Practically this means you will have to compile all the open-source software on ARM64 Mac OS unless it was provided in the apple store. I don't know if the brew installer solves this problem.

**Comment by DmitriiSukhomlinov** [comment]
> Mac OS X comes into an arm64 variant and an x86_64 variant. You cannot create a portable package that works on both versions, unless you include compiled modules for both versions.
> 
> The arm64 variant is really hard to release software for, as there is no easily available mac os arm64 hardware for continuous integration testing and release. Practically this means you will have to compile all the open-source software on ARM64 Mac OS unless it was provided in the apple store. I don't know if the brew installer solves this problem.

Thanks a lot, but the question is - you are talking now about Cutadapt only or about the whole idea of portable Python?

**Comment by marcelm** [comment]
Dmitrii Sukhomlinov ***@***.***> skrev: (15 januari 2024 14:53:19 CET)
>> Mac OS X comes into an arm64 variant and an x86_64 variant. You cannot create a portable package that works on both versions, unless you include compiled modules for both versions.
>> 
>> The arm64 variant is really hard to release software for, as there is no easily available mac os arm64 hardware for continuous integration testing and release. Practically this means you will have to compile all the open-source software on ARM64 Mac OS unless it was provided in the apple store. I don't know if the brew installer solves this problem.
>
>Thanks a lot, but the question is - you are talking now about Cutadapt only or about the whole idea of portable Python?
>

Can you please describe what you mean by this:
> I am trying to make a Python 3.12.1 portable package

How?

**Comment by rhpvorderman** [comment]
> Thanks a lot, but the question is - you are talking now about Cutadapt only or about the whole idea of portable Python?

I am talking about any cross-architecture piece of software in general. This only works for languages that compile to intermediate byte code and execute that on a VM, such as Java and python. But for C extension modules this does not work, as they are compiled for native architectures. Most Python bioinformatics tools use C-extension modules. 

Have you heard of conda and bioconda? Wouldn't that fulfill your requirements? To what goal are you trying to create a portable package?

**Comment by DmitriiSukhomlinov** [comment]
> Dmitrii Sukhomlinov ***@***.***> skrev: (15 januari 2024 14:53:19 CET)
> > Mac OS X comes into an arm64 variant and an x86_64 variant. You cannot create a portable package that works on both versions, unless you include compiled modules for both versions. > > The arm64 variant is really hard to release software for, as there is no easily available mac os arm64 hardware for continuous integration testing and release. Practically this means you will have to compile all the open-source software on ARM64 Mac OS unless it was provided in the apple store. I don't know if the brew installer solves this problem. Thanks a lot, but the question is - you are talking now about Cutadapt only or about the whole idea of portable Python?
> Can you please describe what you mean by this:
> I am trying to make a Python 3.12.1 portable package
> How?

Using [this](https://github.com/indygreg/python-build-standalone) tool

**Comment by DmitriiSukhomlinov** [comment]
> > Thanks a lot, but the question is - you are talking now about Cutadapt only or about the whole idea of portable Python?
> 
> I am talking about any cross-architecture piece of software in general. This only works for languages that compile to intermediate byte code and execute that on a VM, such as Java and python. But for C extension modules this does not work, as they are compiled for native architectures. Most Python bioinformatics tools use C-extension modules.
> 
> Have you heard of conda and bioconda? Wouldn't that fulfill your requirements? To what goal are you trying to create a portable package?

OK, let's start from the beginning. I develop a bioinformatic tool, which includes some other tools - Cutadapt is one of them (we do not violate anything, you have the MIT license). The point is that this tool should provide everything from the box, because this tool is aimed for biologists, for whom conda (which is, of course, a brilliant way to install packages like that) is nothing more than some snake from the Amazon river.

Untill this time we've been using Python 2.7+Cutadapt 1.7 (which wasn't a Python module, but just a python script in this version). As far as Python 2.7 is **a little bit** obsolete, we decided to switch it to some modern Python version (3.12.1) - which requires, of course, switching all related tools. So, now I'm figuring out, how could I make the new Cutadapt (version 4.6, which is a Python module) works everywhere as it was with version 1.7. 

> Mac OS X comes into an arm64 variant and an x86_64 variant.

I am not really into this processor-architecture stuf, but, as far as I know, macOS uses arm64 on new M1 processors and x86_64 on old Intel processors. But, also, it uses [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)#Rosetta_2) to support x86_64 apps on arm64, which means, that if we compile some C-code for x86_64 it will work everythere, am I right?

**Comment by rhpvorderman** [comment]
So why not simply create a conda x86_64 MacOS environment with all tools and redistribute that to Mac users?

**Comment by DmitriiSukhomlinov** [comment]
> So why not simply create a conda x86_64 MacOS environment with all tools and redistribute that to Mac users?

This would require a large changes in our app, e.g. it cannot work with conda environments. I was thinking about simple way - just upgrade python+cutadapt in a native way, without any additional steps

**Comment by marcelm** [comment]
Hi again (and I’m glad you decided to leave Python 2 behind).

I don’t use a Mac myself, so I can only give some vague advice/guesses.

I think Rosetta needs to be installed first, so make sure you did that.

Second, the portable Python that you run on the arm64 machine *also* needs to be the x86_64 variant. The arm64 Python will very likely not be able to load x86_64 modules even when Rosetta is available.

If you did use the same portable Python on both machines, can you please run this on both:
```
./python3 -m sysconfig|grep EXT_SUFFIX
```
This gives the file name extension that Python wants for compiled Python modules. For me, this outputs
```
EXT_SUFFIX = ".cpython-312-x86_64-linux-gnu.so"
```
which tells me that, when Python wants to import the `dnaio._core` module, it tries to use the file `.../site-packages/dnaio/_core.cpython-312-x86_64-linux-gnu.so`. I am guessing that there is a discrepancy between what file is expected and which file actually exists.

**Comment by DmitriiSukhomlinov** [comment]
> Hi again (and I’m glad you decided to leave Python 2 behind).
> 
> I don’t use a Mac myself, so I can only give some vague advice/guesses.
> 
> I think Rosetta needs to be installed first, so make sure you did that.
> 
> Second, the portable Python that you run on the arm64 machine _also_ needs to be the x86_64 variant. The arm64 Python will very likely not be able to load x86_64 modules even when Rosetta is available.
> 
> If you did use the same portable Python on both machines, can you please run this on both:
> 
> ```
> ./python3 -m sysconfig|grep EXT_SUFFIX
> ```
> 
> This gives the file name extension that Python wants for compiled Python modules. For me, this outputs
> 
> ```
> EXT_SUFFIX = ".cpython-312-x86_64-linux-gnu.so"
> ```
> 
> which tells me that, when Python wants to import the `dnaio._core` module, it tries to use the file `.../site-packages/dnaio/_core.cpython-312-x86_64-linux-gnu.so`. I am guessing that there is a discrepancy between what file is expected and which file actually exists.

Thank you very much for you help, you implicitly helped me to find the problem. When I checked `site-packages/dnaio/_core.cpython-312-x86_64-linux-gnu.so` I found out, that this file (and some other `.so`files) were ignored by SVN repository (yes, we store all tools like this in the SVN repo), because it has some kind of default ignore rules, which make it ignores binaries. These files were not commited, but still existed on the first compter. 

Thanks a lot! Closing the issue.

**Comment by marcelm** [comment]
Great! Glad I could help you solve it (at least somehow).
