### ISSUE TITLE
Questions about trimming when both -g and -a options are present

### ISSUE THREAD

**Issue by dbrg77** [marcelm/cutadapt#766]
Hello there,

This is my first issue in this git repo.

I want to thank you for developing this wonderful tool and I used it all the time.

I recently come across some data where only sequences in the middle are of interest. I need to trim both 5' and 3' adapters. I pass both `-g` and `-a` at the same time, but it seems only the 5' adapter got trimmed and the 3' adapter is not.

To provide an example, this is a read `test.fastq`:

```
@read1
ACGTTGTGCGATCAGTGTCA
+
FFFFFFFFFFFFFFFFFFFF
```

I run `cutadapt` in the following way:

`cutadapt -g '^ACGT' -a 'GTCA$' test.fastq -o /dev/stdout`

I would expect to see `TGTGCGATCAGT` to come out, but instead I saw `TGTGCGATCAGTGTCA`.

The full output is:

```
This is cutadapt 4.5 with Python 3.11.6
Command line parameters: -g ^ACGT -a GTCA$ test.fastq -o /dev/stdout
Processing single-end reads on 1 core ...
Done           00:00:00             1 reads @ 20346.2 µs/read;   0.00 M reads/minute
@read1
TGTGCGATCAGTGTCA
+
FFFFFFFFFFFFFFFF
Finished in 0.024 s (23589.134 µs/read; 0.00 M reads/minute).

=== Summary ===

Total reads processed:                       1
Reads with adapters:                         1 (100.0%)
Reads written (passing filters):             1 (100.0%)

Total basepairs processed:            20 bp
Total written (filtered):             16 bp (80.0%)

=== Adapter 1 ===

Sequence: ACGT; Type: anchored 5'; Length: 4; Trimmed: 1 times

No. of allowed errors: 0

Overview of removed sequences
length	count	expect	max.err	error counts
4	1	0.0	0	1


=== Adapter 2 ===

Sequence: GTCA; Type: anchored 3'; Length: 4; Trimmed: 0 times
```

Any comments?

Thank you!

Regards,
Xi

**Comment by marcelm** [comment]
Hi Xi,

by default, Cutadapt trims at most one adapter from each read. See the [section about trimming more than one adapter in the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#more-than-one). In particular, you probably want to use a [linked adapter](https://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters) to trim that example above:
```
cutadapt -a ^ACGT...GTCA$ test.fastq
```

By the way, you do not need to specify `-o /dev/stdout` because that is the default behavior when you don’t use the `-o` option at all.

**Comment by dbrg77** [comment]
Oh!!!!! I see. I missed that section.

Apparently, I should read the documentation more carefully!

Anyway, thank you very much for the tip.

Closing now!

Regards,
Xi

**Comment by marcelm** [comment]
No worries, no worries, glad I could help!
