### ISSUE TITLE
FYI: Macos-14 runners available for M1 macs.

### ISSUE THREAD

**Issue by rhpvorderman** [marcelm/cutadapt#770]
https://github.com/orgs/community/discussions/102846

Also supported by CIBuildWheel: https://cibuildwheel.pypa.io/en/stable/#usage

I thought this might be of interest to you, to get native builds out. 

As for the downstream dependencies: dnaio should be possible as well. Xopen is pure python, python-isal will not be able to build as ISA-L does not support it yet, and zlib-ng should handle it fine without issue. So that will require some twiddling in the xopen requirements (if I now the proper platform.architecture flag for macos arm64).

**Comment by marcelm** [comment]
Yeah, I saw that, but it is quite low on my to-do list. I’ll try to get this done for the next release.

**Comment by marcelm** [comment]
dnaio PR: https://github.com/marcelm/dnaio/pull/134
