### ISSUE TITLE
Error: BiocParallel errors

### ISSUE THREAD

**Issue by ThibauldMichel** [marcelm/cutadapt#779]
Python 3.11.8
Cutadapt 4.6

Cutadapt installed in conda (Bioconda) environment.

Script used: within the R script of the DADA2 pipeline, cutadapt is used as follow.

```
cutadapt <- "cutadapt" # Path to the executable
for(i in seq_along(fas_Fs_raw)) {
  cat("Processing", "-----------", i, "/", length(fas_Fs_raw), "-----------\n")
  system2(cutadapt, args = c(R1_flags, R2_flags,
                             "--discard-untrimmed",
                             "--max-n 0",
                             # Optional strong constraint on expected length
                             #paste0("-m ", 250-nchar(FWD)[1], ":", 250-nchar(REV)[1]), 
                             #paste0("-M ", 250-nchar(FWD)[1], ":", 250-nchar(REV)[1]), 
                             "-o", fas_Fs_cut[i], "-p", fas_Rs_cut[i],
                             fas_Fs_raw[i], fas_Rs_raw[i]))
```

Error during processing, we were expecting the creation of an output folder with trimmed reads, but no folder or files are created and there is an error message in the report slurm file (attached).

```
 WARNING:
    One or more of your adapter sequences may be incomplete.
    Please see the detailed output above.
Stop worker failed with the error: wrong args for environment subassignment
Error: BiocParallel errors
  0 remote errors, element index: 
  154 unevaluated and other errors
  first remote error:
Execution halted
```

[slurm-19692390.txt](https://github.com/marcelm/cutadapt/files/15073343/slurm-19692390.txt)

**Comment by marcelm** [comment]
Hi, sorry, but the error in this case is not with Cutadapt itself, so I cannot help. You should probably talk to the BiocParallel or DADA2 developers.

I can only say that you can ignore the 'WARNING: One or more of your adapter sequences may be incomplete' message. This is normal when trimming primers.

**Comment by ThibauldMichel** [comment]
Apologizes, I have miss-used "Nevertheless", I did not want to suggest that cutadapt is causing the problem or asking for any undue fix.
I agree that the problem is probably coming from the rest of the pipeline. It might be as well from the data set, as the same code has work on other similar sets before.
Much thanks for your help.

**Comment by marcelm** [comment]
Great, then I’ll close the issue. Feel free to comment or open a new issue in case there is something I can do.
