### ISSUE TITLE
cutadapt does something unexpected when i provide a 5' and a 3' adapter sequence

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#78]
_From [b...@langhorst.com](https://code.google.com/u/114161282201777937968/) on October 02, 2013 00:19:46_

When I specify 

cutadapt --format=fastq --front='ATGCGTGCTGGTCTCTCGT' --adapter='CATTCCGATGAGCGTTCTACAANNNN' input.fastq > both_ends_trimmed.fastq

I expected both ends of my sequence to be cut, but I see mostly the 3' end being cut and very little 5' (even though the sequence is obviously present in my reads)

When i do cutadapt sequentially, i see the expected output.

cutadapt   --format=fastq --front='ATGCGTGCTGGTCTCTCGT' ' input.fastq > step1.fastq
cutadapt   --format=fastq--adapter='CATTCCGATGAGCGTTCTACAANNNN'  step1.fastq > both_ends_trimmed.fastq
         
Am I doing something wrong? Or is the expected behavior?

Brad

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=68_

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on February 09, 2014 14:09:08_

Oh, sorry I've overlooked this for so long. Maybe you've figured it out already, but cutadapt trims only one adapter per read in its default settings. If you want it to remove two adapters, try to add the parameter --times=2 .

**Comment by marcelm** [comment]
_From [b...@langhorst.com](https://code.google.com/u/114161282201777937968/) on February 19, 2014 06:02:26_

Thanks for the explanation - it makes sense to me know and seems to work fine.

I read the documentation on --times to mean - how many times *each* adapter would be trimmed.
At least two of my colleagues here were stymied by the same misinterpretation.

Perhaps a doc update would help others to avoid the same confusion.

**Comment by pengchy** [comment]
-n COUNT, --times=COUNT
                        Try to remove adapters at most COUNT times. Useful
                        when an adapter gets appended multiple times (default:
                        1).

This information is helpful. From the help message of cutadapt,  "-n" parameter seems to do trimming iteratively from both ends.

**Comment by marcelm** [comment]
The help text has been changed to "Remove up to COUNT adapters from each read." a while ago. I’m not sure whether that is clearer. However, [the documentation has a section about this](http://cutadapt.readthedocs.org/en/stable/guide.html#more-than-one) where it is made clear what is happening, so I consider this issue solved.
