### ISSUE TITLE
Help to get accurate counts of demultiplexed amplicons using cutadapt

### ISSUE THREAD

**Issue by bgpalmer** [marcelm/cutadapt#789]
cutadapt 4.4
python 3.10
pip 22.0.2

I am using Cutadapt to demultiplex my amplicon sequencing data, and I am reporting the number of amplicons detected under adapters_read1 in the JSON report, after filtering based on length (greater than 100 bp). I now realize that the count of amplicons might be inflated because reads that were too short but still contained the primer are included in the total. I am wondering if there is a way to get an accurate count of the number of amplicons after filtration.

**Comment by marcelm** [comment]
Hm, no; it appears what you would need is the number of reads written per output file, but this does not exist unfortunately. You can of course count the reads in each output file some other way after running Cutadapt.

**Comment by bgpalmer** [comment]
Not a problem, just wanted to be sure I was not missing something. Thanks!
