### ISSUE TITLE
Issue importing fasta files to Cutadapt virtual environment

### ISSUE THREAD

**Issue by elkst00** [marcelm/cutadapt#795]
I am following along with the documentation, attempting to demultiplex combinatorial dual indexed sequences. I am unsure how to read the barcode fasta file into the Cutadapt virtual environment. This is my code:

cutadapt \
    -e 0.15 --no-indels \
    -g ^file:barcodes_fwd.fasta \
    -G ^file:barcodes_rev.fasta \
    -o {ACACTCTTTCCCTACACGACGCTCTTCCGATCT }-{GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT }.1.fastq.gz -p \ 
    {ACACTCTTTCCCTACACGACGCTCTTCCGATCT }-{GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT }.2.fastq.gz \
    input.1.fastq.gz input.2.fastq.gz

This is the error message I receive: 

[Errno 2] No such file or directory: 'barcodes_fwd.fasta'

I am running Cutadapt V4.9 on Python V 3.12.4, installed with Miniconda. Mac OS with Ventura.

**Comment by marcelm** [comment]
You need to create the `barcodes_fwd.fasta` and `barcodes_rev.fasta` files. Read also the [general section about demultiplexing in the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#demultiplexing), which describes how such a `barcodes.fasta` file needs to look.
