### ISSUE TITLE
Update bioconda-recipe to support osx-arm64

### ISSUE THREAD

**Issue by isaacovercast** [marcelm/cutadapt#802]
Hello and thanks so much for cutadapt, it is a very useful tool!

The bioconda folks [recently rolled out support for osx-arm64 builds](https://github.com/bioconda/bioconda-recipes/issues/33333#issuecomment-2221176852) (Mac M1/M2). Enabling the build for this platform is currently 'opt-in' so you have to add a flag to the meta.yaml (documented at the link). I have updated my own package following this direction and it works fine.

The bioconda folks said that I could update recipes for packages that I don't maintain, and I'm happy to do that, but it makes me a bit nervous to mess with other people's stuff without permission, so wanted to check here if you are interested to do the update, or if you mind if I do it, or if there's a reason it wouldn't be a good idea to do.

Thanks again for cutadapt!

**Comment by marcelm** [comment]
Good idea! I opened https://github.com/bioconda/bioconda-recipes/pull/50207 for dnaio, which is a Cutadapt dependency. I don’t have a Mac, can you test

Let’s keep this issue open until the Conda packages are available; I’ll then add an item to the Cutadapt changelog.

**Comment by isaacovercast** [comment]
Awesome, thanks! I have a Mac M2, I'm happy to test dnaio and cutadapt osx-arm64 builds when they're ready. I'll keep an eye on the bioconda recipe PR progress.

Thanks for your quick response!
