### ISSUE TITLE
cutadapt multi core

### ISSUE THREAD

**Issue by zhangqc723** [marcelm/cutadapt#814]
Dear,
  I am currently running Cutadapt using the following command to generate the info file:
_cutadapt -b xxx --times 1 -e 0.2 -O 12 -j 8 -o /dev/null --info-file xxx_info.tsv xxx.gz_
  However, the process is running quite slowly and seems to be using only one CPU, even though I specified -j 8 to use multiple threads. Could you help me understand why this is happening?

**Comment by marcelm** [comment]
Are you running this on your laptop or perhaps on a cluster node where only one CPU core is available to you job? Are other multi-threaded programs able to use more than one core?

Also, the report template asks for the Cutadapt version and how you installed the program. Please also mention which operating system you are on.

**Comment by zhangqc723** [comment]
I runing this code on a cluster node with 52 CPU core and other multi-threaded programs could run with multi-core.
**Version:**cutadapt 4.3 with Python 3.7.16; **OS:** CentOS Linux release 7.9.2009

**Comment by marcelm** [comment]
I don’t know what is going on.

- How do you tell that the CPU usage is one core only? Is it at exactly 100%?
- Try leaving out `--info-file` as a test. Does that change CPU usage?
- If it is easy, you could also try a more recent Cutadapt version and a more recent Python (3.7 is very old), perhaps using Conda/Bioconda.

**Comment by rhpvorderman** [comment]
@marcelm Would it be prudent to yank 4.3 from PyPI?

**Comment by marcelm** [comment]
Awesome!

> @marcelm Would it be prudent to yank 4.3 from PyPI?

I don’t think that’s necessary. `pip install cutadapt` won’t pick it and if 4.3 has made its way into a distribution, yanking won’t help anyway.

**Comment by rhpvorderman** [comment]
Just checked. Debian stable is on 4.2 and ubuntu 24.04 is on 4.4. So this bug should only resurface in rare cases, fortunately!

**Comment by marcelm** [comment]
We dodged that one!
