### ISSUE TITLE
how to remove the PolyG adapter content using cutadapt?

### ISSUE THREAD

**Issue by sayeraselvan** [marcelm/cutadapt#815]
Hi, I am using Cutadapt 4.9 in a Conda environment 

this is the paired end reads sequencing by Novogene Illumina TruSeq Dual Index, I followed the command line

` cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o trimmed-R1.fq.gz -p trimmed-R2.fq.gz R1.fq.gz R2.fq.gz--cores=12 --quality-cutoff 13 --minimum-length 35 --no-indels --pair-filter=any --action=trim > cutadapt.output 2> cutadapt.error `

after trimming the adapters, I have polyG contents, 

<img width="1155" alt="image" src="https://github.com/user-attachments/assets/fcccb4d0-4f58-45e9-a666-eb613ce371be">

when I used sequali on the trimmed paired end (great software :))

<img width="977" alt="image" src="https://github.com/user-attachments/assets/898fa0cf-96e6-4804-bb0f-073ad25c35d2">

I want to know what is the right command to remove the polyG tails from the data using cutadapt.

**Comment by sayeraselvan** [comment]
Thank you so much, for novagene paired end reads, is it neccessary to perform polyA trimming for the genomic data? this is the muttiqc of the samples. 

<img width="1142" alt="image" src="https://github.com/user-attachments/assets/b15702ff-2b4f-4f0b-9b81-a2b6fc994cd2">

**Comment by marcelm** [comment]
Poly-A trimming is for RNA-sequencing. If you have genomic reads, I don’t see why it would be necessary.

**Comment by sayeraselvan** [comment]
Thank you for the clarification. I just have some few confusions regarding the minimum overlap concept.

I have been so far using the default value of minimum overlap of the adapters, should I increase it to increase the stringency. for a alignment for a below case where the adapter content in the genome was 4 percent by fastqc.

`This is cutadapt 4.9 with Python 3.8.19 Command line parameters: -a AGATCGGAAGAGCAC -a GATCGGAAGAGCACA -o trimmed.fq.gz  input.fq.gz -cores=12 --quality-cutoff 13 --minimum-length 35 --no-indels --action=trim`


[cutadaptoutput.txt](https://github.com/user-attachments/files/17402069/cutadaptoutput.txt)

**Comment by marcelm** [comment]
It’s a tradeoff: If you increase the minimum overlap length, you will also miss more real, very short adapter occurrences at the 3' ends. But sure, you could increase it to maybe 4 or 5 to reduce the number of chance matches.

And by the way: Depending a bit on what your data actually, you may get away without any adapter trimming at all if you use a read mapper that soft-clips ends that don’t match the genome. Just a thought.

**Comment by sayeraselvan** [comment]
thank you for clarifying all my questions. thank you for time and support! so far i have planned to use the bwa-mem2. i will close this issue :)

**Comment by marcelm** [comment]
You’re welcome!

And here the ad section: strobealign is a very fast and accurate read mapper that I’m contributing to, see https://github.com/ksahlin/strobealign/

**Comment by rhpvorderman** [comment]
FYI: GATK has updated their best practices for illumina variant calling when you don't have access to Illumina DRAGEN: https://gatk.broadinstitute.org/hc/en-us/articles/4407897446939--How-to-Run-germline-single-sample-short-variant-discovery-in-DRAGEN-mode

That requires you to align using DRAGMAP. This is has a tool that causes a segmentation fault in version 1.3.0 on conda, for everyone. 1.2.1 works fine. DRAGMAP requires a literal ton of resources. It was only able to finish my WGS samples using more than 120 GB of memory. So it is not very well-made from a technical perspective. (In my not so humble opinion, I really resent tools that act like resources don't cost money and that everyone has 128GB sitting around in their laptop.)

Bwa-mem2 does run faster than BWA-MEM, but requires more memory. BWA-MEM requires less than 8 GB. Bwa-mem2 in the order of 19 or so. Worse, it requires more than 80 GB for indexing a reference if you can't get a prebuilt index. On our nodes, bwa-mem2 is typically 2 times faster than BWA-MEM. 
Given the way resource scheduling works on our cluster, this is not necessarily an upgrade. Lots of jobs hoard a lot of memory. So low-memory lots of cores jobs get scheduled quicker and more often. As a result BWA-MEM is better (in our case). Also indexing on BWA-MEM does not require so much memory, so it is much more flexible. 

Technically you could also give minimap2 a try. It should also work very well for illumina reads. And I second Marcel's recommendation on strobealign. I haven't tried it yet, but it solves some innate problems with mapping in a very elegant manner.

Sorry for the information dump, but it might save you some work knowing this stuff now.
