### ISSUE TITLE
ZeroDivisionError when output to named pipe.

### ISSUE THREAD

**Issue by huxs001** [marcelm/cutadapt#820]
When reporting an issue, please include this information:

- Cutadapt and Python version: 4.9
- How you installed the tool (conda or pip, for example): conda
- Which command-line parameters you used

```bash
mkfifo t.pipe.fq
samtools fastq --threads 4 -T'*' tmp.ubam |cutadapt --interleaved --cores 15 -Z -q 16 -Q 16 --max-n 0.04 --pair-filter=both -m 20:20 --max-aer 0.0252 -o t.pipe.fq - &
samtools import -s t.pipe.fq -T'*' -O BAM --threads 4 -o t.clean.ubam
```

Output:

```
This is cutadapt 4.9 with Python 3.11.10
Command line parameters: --interleaved --cores 15 -Z -q 16 -Q 16 --max-n 0.04 --pair-filter=both -m 20:20 --max-aer 0.0252 -o t.clean.ubam.pipe.fq -
Processing paired-end reads on 15 cores ...
Traceback (most recent call last):
  File "/home/galaxy/micromamba/envs/atac1114/bin/cutadapt", line 10, in <module>
    sys.exit(main_cli())
             ^^^^^^^^^^
  File "/home/galaxy/micromamba/envs/atac1114/lib/python3.11/site-packages/cutadapt/cli.py", line 1149, in main_cli
    main(sys.argv[1:])
  File "/home/galaxy/micromamba/envs/atac1114/lib/python3.11/site-packages/cutadapt/cli.py", line 1243, in main
    stats = runner.run(pipeline, progress, outfiles)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galaxy/micromamba/envs/atac1114/lib/python3.11/site-packages/cutadapt/runners.py", line 362, in run
    chunk_index: int = self._try_receive(connection)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galaxy/micromamba/envs/atac1114/lib/python3.11/site-packages/cutadapt/runners.py", line 398, in _try_receive
    raise e
ZeroDivisionError: float division by zero
samtools import: truncated file. Aborting
```

**Comment by marcelm** [comment]
Do you get the same error when you send output to a regular file instead?

I’m wondering whether you have reads in the BAM file that are not paired. Cutadapt can currently not work with mixed single-end/paired-end input data.

**Comment by rhpvorderman** [comment]
Looks to me that the maximun average error rate filter divides by length. If a length of `0` is encountered it should give this error. I think I did not take into account that edge case when writing the filter. Already posted a fix.

**Comment by huxs001** [comment]
> Do you get the same error when you send output to a regular file instead?
> 
> I’m wondering whether you have reads in the BAM file that are not paired. Cutadapt can currently not work with mixed single-end/paired-end input data.

I tried and find same error raised. So it is not about pipe.

After apply #821 , it runs.
