### ISSUE TITLE
discard sub adapter match result

### ISSUE THREAD

**Issue by suyanan** [marcelm/cutadapt#822]
Hi, 
I use cutadapt 4.8 and Python 3.10.11, with command: 
```cutadapt -g ATGGTG -e 0.01 -j 16 --info-file test.info.tsv --rest-file test.rest.tsv --rc -o test.fastq.gz raw.fastq```
I get the test.info.tsv:
![info](https://github.com/user-attachments/assets/b38a9e28-a339-454a-91d5-ae1da0ee0887)
there are some results just **removing sub adapter**(TGGTG, also GGTG, GTG exist), not total ATGGTG. I set error_rate 0.01 with no fault-tolerant for 6 adapter bases, no fault-tolerant also include no gap.
Is there one parameter or solution to **discard these results** ? I will test error_rate=0.2 with 1 base fault-tolerate, I hope solution will also be useful.

Thanks

**Comment by suyanan** [comment]
--overlap

**Comment by marcelm** [comment]
Setting the minimum overlap works, but if the intention is to find the full adapter in the 5' end of reads, you should use an anchored 5' adapter, https://cutadapt.readthedocs.io/en/stable/guide.html#anchored-5adapters. That is, use `-g ^ATGGTG`.
