### ISSUE TITLE
info-file: untrimmed reads do not show

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#95]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on October 31, 2014 12:16:45_

The info file includes only trimmed reads.

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=85_

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on November 05, 2014 04:26:18_

**Summary:** info-file: untrimmed reads do not show  \<span class="oldvalue"> (was: info-file: untrimmed reads not show) \</span>

**Comment by dkoppstein** [comment]
I just ran into this issue. I was surprised that the reads weren't there, since the documentation states: 

```
If no adapter was found, the format is as follows:

Read name
The value -1
The read sequence
```

**Comment by marcelm** [comment]
You are absolutely right ... I’m just astonished no one else has complained so far! Fixed in Git master.

**Comment by dkoppstein** [comment]
Thank you! I really like the --info-file feature, thank you for implementing it.
